(** Formal Sail Code Generators for Multi-VCPU Architecture Specifications *)

let render_visa_sail
    ~(isa_name : string)
    ~(tier : int)
    ~(op_vadd_vv : int)
    ~(op_vsub_vv : int)
    ~(op_vmul_vv : int)
    ~(op_vxor_vv : int)
    ~(op_vand_vv : int)
    ~(op_vor_vv : int)
    ~(op_vsll_vv : int)
    ~(op_vsrl_vv : int)
    ~(op_vli_vi : int)
    ~(op_vmv_vv : int)
    ~(op_vle8_v : int)
    ~(op_vret_v : int)
    ~(op_vbge_vv : int)
    ~(op_vj : int) : string =
  Format.sprintf {|/* ==============================================================================
 * Sail Architecture Specification: %s (Tier %d)
 * Generated by OcaSorry Native DDD vISA Synthesizer
 * ============================================================================== */

default Order dec
$include <prelude.sail>

type regidx = bits(5)
type imm14  = bits(14)
type imm7   = bits(7)

/* 16 Virtual 32-bit Vector Registers */
register R : vector(16, dec, bits(32))
register PC : bits(32)

/* AST Node Union for Synthesized %s */
union ast = {
    VADD_VV : (regidx, regidx, regidx),
    VSUB_VV : (regidx, regidx, regidx),
    VMUL_VV : (regidx, regidx, regidx),
    VXOR_VV : (regidx, regidx, regidx),
    VAND_VV : (regidx, regidx, regidx),
    VOR_VV  : (regidx, regidx, regidx),
    VSLL_VV : (regidx, regidx, regidx),
    VSRL_VV : (regidx, regidx, regidx),
    VLI_VI  : (regidx, bits(14)),
    VMV_VV  : (regidx, regidx),
    VLE8_V  : (regidx, regidx),
    VSE8_V  : (regidx, regidx, regidx),
    VRET_V  : (regidx),
    VBGE_VV : (regidx, regidx),
    VJ      : (bits(32))
}

/* Dynamic Instruction Decoder */
val decode : bits(32) -> option(ast)
function decode(inst) = {
    let funct6 : bits(6) = inst[31..26];
    let vm     : bits(1) = inst[25..25];
    let vs2    : bits(5) = inst[24..20];
    let vs1    : bits(5) = inst[19..15];
    let funct3 : bits(3) = inst[14..12];
    let vd     : bits(5) = inst[11..7];
    let opcode : bits(7) = inst[6..0];

    let imm14 : bits(14) = vm @ funct3 @ vs1 @ vs2;

    match funct6 {
        %d => Some(VADD_VV(vd, vs1, vs2)),
        %d => Some(VSUB_VV(vd, vs1, vs2)),
        %d => Some(VMUL_VV(vd, vs1, vs2)),
        %d => Some(VXOR_VV(vd, vs1, vs2)),
        %d => Some(VAND_VV(vd, vs1, vs2)),
        %d => Some(VOR_VV(vd, vs1, vs2)),
        %d => Some(VSLL_VV(vd, vs1, vs2)),
        %d => Some(VSRL_VV(vd, vs1, vs2)),
        %d => Some(VLI_VI(vd, imm14)),
        %d => Some(VMV_VV(vd, vs1)),
        %d => Some(VLE8_V(vd, vs2)),
        %d => Some(VRET_V(vd)),
        %d => Some(VBGE_VV(vs1, vs2)),
        %d => Some(VJ(inst)),
        _ => None()
    }
}

/* Execution Semantics */
function execute(instruction : ast) -> unit = {
    match instruction {
        VADD_VV(vd, vs1, vs2) => R[vd] = R[vs1] + R[vs2],
        VSUB_VV(vd, vs1, vs2) => R[vd] = R[vs1] - R[vs2],
        VMUL_VV(vd, vs1, vs2) => R[vd] = R[vs1] * R[vs2],
        VXOR_VV(vd, vs1, vs2) => R[vd] = R[vs1] ^ R[vs2],
        VAND_VV(vd, vs1, vs2) => R[vd] = R[vs1] & R[vs2],
        VOR_VV(vd, vs1, vs2)  => R[vd] = R[vs1] | R[vs2],
        VSLL_VV(vd, vs1, vs2) => R[vd] = R[vs1] << unsigned(R[vs2]),
        VSRL_VV(vd, vs1, vs2) => R[vd] = R[vs1] >> unsigned(R[vs2]),
        VLI_VI(vd, imm)       => R[vd] = EXTZ(imm),
        VMV_VV(vd, vs1)       => R[vd] = R[vs1],
        VLE8_V(vd, vs2)       => (),
        VSE8_V(vd, vs1, vs2)  => (),
        VRET_V(vd)            => (),
        VBGE_VV(vs1, vs2)     => (),
        VJ(target)            => ()
    }
}
|} isa_name tier isa_name
      op_vadd_vv op_vsub_vv op_vmul_vv op_vxor_vv op_vand_vv op_vor_vv
      op_vsll_vv op_vsrl_vv op_vli_vi op_vmv_vv op_vle8_v op_vret_v
      op_vbge_vv op_vj

let render_nested_vm_sail ~(vm_name : string) : string =
  Format.sprintf {|/* ==============================================================================
 * Sail Architecture Specification: %s (2-Tier Nested VM)
 * Generated by OcaSorry Native DDD Nested VM Synthesizer
 * ============================================================================== */

default Order dec
$include <prelude.sail>

type byte = bits(8)
type regidx = bits(3)

/* Inner Worker Registers */
register Inner_R : vector(8, dec, bits(32))
register Outer_PC : bits(32)
register Inner_PC : bits(32)

union outer_ast = {
    OUT_SETUP      : (unit),
    OUT_DISPATCH   : (unit),
    OUT_MUTATE_KEY : (byte),
    OUT_HALT       : (unit)
}

union inner_ast = {
    IN_LOAD_ARG   : (regidx),
    IN_LOAD_CONST : (regidx, byte),
    IN_ADD        : (regidx, regidx, regidx),
    IN_SUB        : (regidx, regidx, regidx),
    IN_XOR        : (regidx, regidx, regidx),
    IN_MUL        : (regidx, regidx, regidx),
    IN_RET        : (regidx)
}

function execute_outer(op : outer_ast) -> unit = {
    match op {
        OUT_SETUP      => { Inner_PC = EXTZ(0x00) },
        OUT_DISPATCH   => { () },
        OUT_MUTATE_KEY(k) => { () },
        OUT_HALT       => { () }
    }
}

function execute_inner(op : inner_ast) -> unit = {
    match op {
        IN_LOAD_ARG(rd)         => Inner_R[rd] = EXTZ(0x00),
        IN_LOAD_CONST(rd, imm)  => Inner_R[rd] = EXTZ(imm),
        IN_ADD(rd, rs1, rs2)    => Inner_R[rd] = Inner_R[rs1] + Inner_R[rs2],
        IN_SUB(rd, rs1, rs2)    => Inner_R[rd] = Inner_R[rs1] - Inner_R[rs2],
        IN_XOR(rd, rs1, rs2)    => Inner_R[rd] = Inner_R[rs1] ^ Inner_R[rs2],
        IN_MUL(rd, rs1, rs2)    => Inner_R[rd] = Inner_R[rs1] * Inner_R[rs2],
        IN_RET(rs)              => ()
    }
}
|} vm_name

let render_rolling_vkey_sail
    ~(vm_name : string)
    ~(tier : int)
    ~(lcg_mult : int)
    ~(lcg_delta : int64) : string =
  Format.sprintf {|/* ==============================================================================
 * Sail Architecture Specification: %s (Rolling Key VM Tier %d)
 * Generated by OcaSorry Native DDD Stateful Keychain Synthesizer
 * ============================================================================== */

default Order dec
$include <prelude.sail>

register VKey : bits(32)
register State_Regs : vector(4, dec, bits(32))

union rolling_ast = {
    R_ADD_IMM : (bits(2), bits(32)),
    R_XOR_IMM : (bits(2), bits(32)),
    R_MUL_IMM : (bits(2), bits(32)),
    R_HALT    : (unit)
}

function evolve_key(decrypted_word : bits(32)) -> unit = {
    VKey = (VKey * %d) ^ (decrypted_word + 0x%LX);
}

function execute_rolling(op : rolling_ast) -> unit = {
    match op {
        R_ADD_IMM(rd, imm) => State_Regs[rd] = State_Regs[rd] + imm,
        R_XOR_IMM(rd, imm) => State_Regs[rd] = State_Regs[rd] ^ imm,
        R_MUL_IMM(rd, imm) => State_Regs[rd] = State_Regs[rd] * imm,
        R_HALT             => ()
    }
}
|} vm_name tier lcg_mult lcg_delta

let render_ephemeral_jit_sail
    ~(vm_name : string)
    ~(tier : int) : string =
  Format.sprintf {|/* ==============================================================================
 * Sail Architecture Specification: %s (Ephemeral JIT Tier %d)
 * Generated by OcaSorry Native DDD In-Memory JIT Wiper Synthesizer
 * ============================================================================== */

default Order dec
$include <prelude.sail>

register Page_Allocated : bool
register Page_Zeroed    : bool
register Ephemeral_Result : bits(32)

union ephemeral_ast = {
    EPH_ALLOC_MMAP : (bits(32)),
    EPH_DECRYPT    : (bits(8)),
    EPH_EXECUTE    : (bits(32)),
    EPH_FREE_ZERO  : (unit)
}

function execute_ephemeral(op : ephemeral_ast) -> unit = {
    match op {
        EPH_ALLOC_MMAP(sz) => { Page_Allocated = true; Page_Zeroed = false },
        EPH_DECRYPT(key)   => { () },
        EPH_EXECUTE(input) => { Ephemeral_Result = if input != 0 then EXTZ(0x01) else EXTZ(0x00) },
        EPH_FREE_ZERO()    => { Page_Zeroed = true; Page_Allocated = false }
    }
}
|} vm_name tier
