open GoblintCil.Cil

(** Domain Service: Specification-Driven random_vISA Virtualization Engine
    Ingests synthesized Sail / JSON architecture definitions generated by Python/Sail tools,
    provides dynamic opcode encoding/decoding, and compiles arbitrary CIL AST expressions
    and statements into packed & encrypted 32-bit Vector Instruction Bytecode (.vbc) with
    a custom C11 VCPU emulator tailored to the active ISA specification.
*)
module VisaSpec = C_visa_spec

module Make (Entropy : Entropy_port.S) = struct
  module Spec = C_visa_spec
  module DecoyGen = C_visa_decoy_generator.Make (Entropy)

  let vcpu_counter = ref 0

  let generate_visa_runtime (file : file) : unit =
    let already_injected =
      List.exists
        (function
          | GVarDecl (v, _) when v.vname = "__visa_engine_ready" -> true
          | _ -> false)
        file.globals
    in
    if not already_injected then (
      let flag_var = makeGlobalVar "__visa_engine_ready" intType in
      flag_var.vstorage <- Static;
      file.globals <- (GVarDecl (flag_var, locUnknown)) :: file.globals
    )

  let should_transform (fd : fundec) : bool =
    if fd.svar.vname = "main" || String.starts_with ~prefix:"__" fd.svar.vname then false
    else if C_annotation_service.AnnotationHelper.should_skip_all fd then false
    else if C_annotation_service.AnnotationHelper.has_annotation fd "visa"
            || C_annotation_service.AnnotationHelper.has_annotation fd "vector_vm"
            || C_annotation_service.AnnotationHelper.has_annotation fd "virtualize" then true
    else not (C_annotation_service.AnnotationHelper.has_any_vm_annotation fd)
         && not (C_annotation_service.AnnotationHelper.has_custom_annotations fd)

  let virtualize_function (file : file) (fd : fundec) : unit =
    if not (should_transform fd) then ()
    else (
      incr vcpu_counter;
      generate_visa_runtime file;

      let spec = Spec.get_active_spec () in
      let op = spec.opcodes in
      let lay = spec.layout in

      let vbc_name = Printf.sprintf "__visa_program_%s_%d" fd.svar.vname !vcpu_counter in
      let ptr_formals = List.filter (fun p -> isPointerType p.vtype) fd.sformals in
      let has_ptr_param = ptr_formals <> [] in

      (* Vector 5: Variable to register mapping mapped to polymorphic in_regs *)
      let var_map = Hashtbl.create 32 in
      let in_regs = spec.abi.in_regs in
      let get_in_reg idx =
        if idx < List.length in_regs then List.nth in_regs idx else idx
      in
      List.iteri (fun idx p -> Hashtbl.add var_map p.vname (get_in_reg idx)) fd.sformals;
      let max_in_reg = List.fold_left (fun acc p -> max acc (Hashtbl.find var_map p.vname)) 0 fd.sformals in
      let next_vreg = ref (max (max_in_reg + 1) (List.length fd.sformals)) in
      List.iter
        (fun v ->
          if not (Hashtbl.mem var_map v.vname) then (
            Hashtbl.add var_map v.vname !next_vreg;
            incr next_vreg
          ))
        fd.slocals;

      let get_vreg name =
        if Hashtbl.mem var_map name then Hashtbl.find var_map name
        else (
          let r = !next_vreg in
          incr next_vreg;
          Hashtbl.add var_map name r;
          r
        )
      in

      let instrs = ref [] in
      let emit inst = instrs := inst :: !instrs in

      let encode_jump target_pc =
        let l = spec.layout in
        let word =
          (((op.vj land l.funct6_mask) lsl l.funct6_shift) lor
           ((target_pc land 0x7FFFF) lsl 7) lor
           (l.opcode_val land 0x7F)) land 0xFFFFFFFF
        in
        Int32.of_int word
      in

      let encode_branch_ge vs1 vs2 target_pc =
        let l = spec.layout in
        let word =
          (((op.vbge_vv land l.funct6_mask) lsl l.funct6_shift) lor
           (1 lsl l.vm_shift) lor
           ((vs2 land 0x1F) lsl l.vs2_shift) lor
           ((vs1 land 0x1F) lsl l.vs1_shift) lor
           ((target_pc land 0x1F) lsl 7) lor
           (l.opcode_val land 0x7F)) land 0xFFFFFFFF
        in
        Int32.of_int word
      in

      let rec extract_ptr_var = function
        | Lval (Var v, NoOffset) -> Some v
        | CastE (_, _, e) -> extract_ptr_var e
        | _ -> None
      in

      let rec compile_exp (e : exp) (dst : int) (free_reg : int) : unit =
        match e with
        | Const (CInt (i, _, _)) ->
            let imm = Z.to_int i land 0x3FFF in
            let vm = (imm lsr 13) land 0x01 in
            let f3 = (imm lsr 10) land 0x07 in
            let vs1 = (imm lsr 5) land 0x1F in
            let vs2 = imm land 0x1F in
            emit (Spec.encode_inst spec ~funct6:op.vli_vi ~vm ~vs2 ~vs1_or_imm:vs1 ~funct3:f3 ~vd:(dst land 0x1F))
        | Lval (Var v, NoOffset) ->
            let src = get_vreg v.vname in
            if src <> dst then
              emit (Spec.encode_inst spec ~funct6:op.vmv_vv ~vm:1 ~vs2:0 ~vs1_or_imm:(src land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | Lval (Var ptr_v, Index (idx_e, NoOffset)) ->
            compile_exp idx_e free_reg (free_reg + 1);
            emit (Spec.encode_inst spec ~funct6:op.vle8_v ~vm:1 ~vs2:(free_reg land 0x1F) ~vs1_or_imm:((get_vreg ptr_v.vname) land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | Lval (Mem (BinOp ((PlusPI | PlusA | IndexPI), ptr_e, idx_e, _)), NoOffset) ->
            (match extract_ptr_var ptr_e with
             | Some ptr_v ->
                 compile_exp idx_e free_reg (free_reg + 1);
                 emit (Spec.encode_inst spec ~funct6:op.vle8_v ~vm:1 ~vs2:(free_reg land 0x1F) ~vs1_or_imm:((get_vreg ptr_v.vname) land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
             | None ->
                 (match extract_ptr_var idx_e with
                  | Some ptr_v ->
                      compile_exp ptr_e free_reg (free_reg + 1);
                      emit (Spec.encode_inst spec ~funct6:op.vle8_v ~vm:1 ~vs2:(free_reg land 0x1F) ~vs1_or_imm:((get_vreg ptr_v.vname) land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
                  | None -> ()))
        | Lval (Mem (Lval (Var ptr_v, NoOffset)), NoOffset) ->
            emit (Spec.encode_inst spec ~funct6:op.vli_vi ~vm:0 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:(free_reg land 0x1F));
            emit (Spec.encode_inst spec ~funct6:op.vle8_v ~vm:1 ~vs2:(free_reg land 0x1F) ~vs1_or_imm:((get_vreg ptr_v.vname) land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | UnOp (Neg, e1, _) ->
            compile_exp e1 dst free_reg;
            let sub_op = [| op.vsub_vv; op.vsub_alt1; op.vsub_alt2 |].(Entropy.next_int ~max:3) in
            emit (Spec.encode_inst spec ~funct6:sub_op ~vm:1 ~vs2:(dst land 0x1F) ~vs1_or_imm:0 ~funct3:0 ~vd:(dst land 0x1F))
        | UnOp (BNot, e1, _) ->
            compile_exp e1 dst free_reg;
            let xor_op = [| op.vxor_vv; op.vxor_alt1; op.vxor_alt2 |].(Entropy.next_int ~max:3) in
            emit (Spec.encode_inst spec ~funct6:xor_op ~vm:1 ~vs2:0x1F ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | BinOp (bin_op, e1, e2, _) ->
            compile_exp e1 dst free_reg;
            let t_reg = free_reg in
            compile_exp e2 t_reg (free_reg + 1);
            let pick_add () = [| op.vadd_vv; op.vadd_alt1; op.vadd_alt2 |].(Entropy.next_int ~max:3) in
            let pick_sub () = [| op.vsub_vv; op.vsub_alt1; op.vsub_alt2 |].(Entropy.next_int ~max:3) in
            let pick_xor () = [| op.vxor_vv; op.vxor_alt1; op.vxor_alt2 |].(Entropy.next_int ~max:3) in
            let pick_and () = [| op.vand_vv; op.vand_alt1 |].(Entropy.next_int ~max:2) in
            let pick_or ()  = [| op.vor_vv;  op.vor_alt1  |].(Entropy.next_int ~max:2) in
            let pick_mul () = [| op.vmul_vv; op.vmul_alt1 |].(Entropy.next_int ~max:2) in
            (match bin_op with
             | PlusA ->
                 (* Vector 1 & 9: Micro-Op RISC MBA with Polymorphic Aliasing *)
                 let choice = Entropy.next_int ~max:3 in
                 if choice = 0 then emit (Spec.encode_inst spec ~funct6:(pick_add ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
                 else if choice = 1 then (
                   let t1, t2 = free_reg + 1, free_reg + 2 in
                   emit (Spec.encode_inst spec ~funct6:(pick_and ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(t1 land 0x1F));
                   emit (Spec.encode_inst spec ~funct6:(pick_xor ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F));
                   emit (Spec.encode_inst spec ~funct6:op.vli_vi ~vm:0 ~vs2:1 ~vs1_or_imm:0 ~funct3:0 ~vd:(t2 land 0x1F));
                   emit (Spec.encode_inst spec ~funct6:op.vsll_vv ~vm:1 ~vs2:(t2 land 0x1F) ~vs1_or_imm:(t1 land 0x1F) ~funct3:0 ~vd:(t1 land 0x1F));
                   emit (Spec.encode_inst spec ~funct6:(pick_add ()) ~vm:1 ~vs2:(t1 land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
                 ) else (
                   let t1 = free_reg + 1 in
                   emit (Spec.encode_inst spec ~funct6:(pick_and ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(t1 land 0x1F));
                   emit (Spec.encode_inst spec ~funct6:(pick_or ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F));
                   emit (Spec.encode_inst spec ~funct6:(pick_add ()) ~vm:1 ~vs2:(t1 land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
                 )
             | BXor ->
                 let choice = Entropy.next_int ~max:2 in
                 if choice = 0 then emit (Spec.encode_inst spec ~funct6:(pick_xor ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
                 else (
                   let t1 = free_reg + 1 in
                   emit (Spec.encode_inst spec ~funct6:(pick_and ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(t1 land 0x1F));
                   emit (Spec.encode_inst spec ~funct6:(pick_or ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F));
                   emit (Spec.encode_inst spec ~funct6:(pick_sub ()) ~vm:1 ~vs2:(t1 land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
                 )
             | MinusA -> emit (Spec.encode_inst spec ~funct6:(pick_sub ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
             | Mult -> emit (Spec.encode_inst spec ~funct6:(pick_mul ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
             | BAnd -> emit (Spec.encode_inst spec ~funct6:(pick_and ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
             | BOr -> emit (Spec.encode_inst spec ~funct6:(pick_or ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
             | Shiftlt -> emit (Spec.encode_inst spec ~funct6:op.vsll_vv ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
             | Shiftrt -> emit (Spec.encode_inst spec ~funct6:op.vsrl_vv ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
             | _ -> emit (Spec.encode_inst spec ~funct6:(pick_add ()) ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
            )
        | CastE (_, _, e1) ->
            compile_exp e1 dst free_reg
        | _ -> ()
      in

      let maybe_inject_decoy () =
        if Entropy.next_int ~max:10 < 4 then (
          let count = 2 + Entropy.next_int ~max:4 in
          DecoyGen.emit_opaque_decoy_cluster spec instrs ~count
        )
      in

      let rec compile_stmt (s : stmt) : unit =
        maybe_inject_decoy ();
        match s.skind with
        | Instr inst_list ->
            List.iter
              (function
                | Set ((Var v, NoOffset), exp, _, _) ->
                    let dst = get_vreg v.vname in
                    compile_exp exp dst (!next_vreg)
                | Set ((Mem (BinOp (PlusPI, ptr_e, idx_e, _)), NoOffset), exp, _, _) ->
                    (match extract_ptr_var ptr_e with
                     | Some ptr_v ->
                         let t1 = !next_vreg in
                         let t2 = !next_vreg + 1 in
                         compile_exp idx_e t1 (!next_vreg + 2);
                         compile_exp exp t2 (!next_vreg + 2);
                         emit (Spec.encode_inst spec ~funct6:op.vse8_v ~vm:1 ~vs2:(t1 land 0x1F) ~vs1_or_imm:(t2 land 0x1F) ~funct3:0 ~vd:((get_vreg ptr_v.vname) land 0x1F))
                     | None -> ())
                | _ -> ())
              inst_list
        | Return (Some exp, _, _) ->
            compile_exp exp spec.abi.out_reg (!next_vreg);
            emit (Spec.encode_inst spec ~funct6:op.vret_v ~vm:1 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:(spec.abi.out_reg land 0x1F))
        | Return (None, _, _) ->
            emit (Spec.encode_inst spec ~funct6:op.vret_v ~vm:1 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:(spec.abi.out_reg land 0x1F))
        | Block blk ->
            List.iter compile_stmt blk.bstmts
        | Loop (blk, _, _, _, _) ->
            let loop_start_idx = List.length !instrs in
            List.iter compile_stmt blk.bstmts;
            emit (encode_jump loop_start_idx)
        | If (cond, tb, fb, _, _) ->
            (match cond with
             | BinOp (Lt, e1, e2, _)
             | UnOp (LNot, BinOp (Lt, e1, e2, _), _)
             | BinOp (Ge, e1, e2, _) ->
                 let t1 = !next_vreg in
                 let t2 = !next_vreg + 1 in
                 compile_exp e1 t1 (!next_vreg + 2);
                 compile_exp e2 t2 (!next_vreg + 2);
                 emit (encode_branch_ge (t1 land 0x1F) (t2 land 0x1F) 0)
             | _ -> ());
            List.iter compile_stmt tb.bstmts;
            List.iter compile_stmt fb.bstmts
        | _ -> ()
      in

      List.iter compile_stmt fd.sbody.bstmts;

      if !instrs = [] then (
        emit (Spec.encode_inst spec ~funct6:op.vli_vi ~vm:0 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:(spec.abi.out_reg land 0x1F));
        emit (Spec.encode_inst spec ~funct6:op.vret_v ~vm:1 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:(spec.abi.out_reg land 0x1F))
      );

      let vbc_words = List.rev !instrs in
      let n_words = List.length vbc_words in

      (* Vector 6: Non-Linear Bytecode Mapping & Affine VPC Indexing (Anti-Pushan) *)
      let rec gcd a b = if b = 0 then a else gcd b (a mod b) in
      let affine_p =
        let primes = [3; 5; 7; 11; 13; 17; 19; 23; 29; 31] in
        match List.find_opt (fun p -> gcd p n_words = 1) primes with
        | Some p -> p
        | None -> 1
      in
      let affine_s = if n_words > 1 then 1 + (Entropy.next_int ~max:(n_words - 1)) else 0 in
      let pack_key_32 = Int64.to_int32 spec.pack_key in
      let delta_key_32 = Int64.to_int32 spec.delta_key in
      let permuted_arr = Array.make n_words 0l in
      List.iteri
        (fun idx w ->
          let delta = Int32.mul (Int32.of_int idx) delta_key_32 in
          let key = Int32.logxor pack_key_32 delta in
          let enc = Int32.logxor w key in
          let slot = if n_words > 0 then (idx * affine_p + affine_s) mod n_words else 0 in
          permuted_arr.(slot) <- enc)
        vbc_words;
      let packed_words = Array.to_list permuted_arr in

      let uint_ty = uintType in
      let array_type = TArray (uint_ty, Some (integer (List.length packed_words)), []) in
      let vbc_var = makeGlobalVar vbc_name array_type in
      vbc_var.vstorage <- Static;

      let init_entries =
        List.mapi
          (fun idx w ->
            let u64 = Int64.logand (Int64.of_int32 w) 0xFFFFFFFFL in
            let init_val = SingleInit (Const (CInt (Z.of_int64 u64, IUInt, None))) in
            (Index (integer idx, NoOffset), init_val))
          packed_words
      in
      file.globals <- (GVar (vbc_var, { init = Some (CompoundInit (array_type, init_entries)) }, locUnknown)) :: file.globals;

      (* Build clean C11 Vector VCPU execution function body matching the active Spec *)
      let ptr_arg =
        if has_ptr_param then (List.hd ptr_formals).vname else "0"
      in

      let vreg_total = max 64 (!next_vreg + 32) in

      let type_to_str = function
        | TInt (IULongLong, _) | TInt (ILongLong, _) -> "unsigned long long"
        | TInt (IULong, _) | TInt (ILong, _) -> "unsigned long"
        | TInt (IUInt, _) -> "unsigned int"
        | TPtr (TInt ((IChar | ISChar), _), _) -> "const char *"
        | TPtr (TInt (IUChar, _), _) -> "const unsigned char *"
        | TPtr _ -> "void *"
        | _ -> "int"
      in
      let ret_type_str = match fd.svar.vtype with TFun (t, _, _, _) -> type_to_str t | _ -> "int" in

      (* Vector 3: Entangled Register Affine Key Parameters *)
      let reg_mask_base = Int64.logand (Int64.abs (Entropy.next_int64 ())) 0xFFFFFFFFFFFFL in
      let reg_mask_step = [| 0x9E3779B97F4A7C15L; 0x517CC1B727220A95L; 0x6C62272E07BB0142L |].(Entropy.next_int ~max:3) in

      let arg_inits =
        List.mapi
          (fun idx p ->
            let target_reg = get_in_reg idx in
            if isIntegralType p.vtype then Printf.sprintf "    __VREG_SET(%d, (unsigned long long)%s);" target_reg p.vname
            else if isPointerType p.vtype then Printf.sprintf "    __VREG_SET(%d, (unsigned long long)(uintptr_t)%s);" target_reg p.vname
            else Printf.sprintf "    __VREG_SET(%d, 0);" target_reg)
          fd.sformals
        |> String.concat "\n"
      in

      let fn_params =
        List.map (fun p -> Printf.sprintf "%s %s" (type_to_str p.vtype) p.vname) fd.sformals
        |> String.concat ", "
      in

      let vreg_rot_seed = Entropy.next_int ~max:64 in

      let fn_body_impl =
        C_visa_c_emitter.emit_function_body
          ~ret_type_str
          ~fn_name:fd.svar.vname
          ~fn_params
          ~vreg_total
          ~vreg_rot_seed
          ~reg_mask_base
          ~reg_mask_step
          ~arg_inits
          ~ptr_arg
          ~op
          ~out_reg:spec.abi.out_reg
          ~affine_p
          ~affine_s
          ~word_count:(List.length packed_words)
          ~vbc_name
          ~pack_key:spec.pack_key
          ~delta_key:spec.delta_key
          ~lay
      in

      let new_globals = ref [] in
      List.iter
        (fun g ->
          match g with
          | GFun (f_dec, _) when f_dec.svar.vname = fd.svar.vname ->
              new_globals := GText fn_body_impl :: !new_globals
          | other -> new_globals := other :: !new_globals)
        file.globals;
      file.globals <- List.rev !new_globals
    )

  let transform_file (f : file) : file =
    let funcs =
      List.filter_map
        (function
          | GFun (fd, _) -> Some fd
          | _ -> None)
        f.globals
    in
    List.iter (virtualize_function f) funcs;
    f
end
