open GoblintCil.Cil
open Yojson.Basic.Util

(** Domain Service: Specification-Driven random_vISA Virtualization Engine
    Ingests synthesized Sail / JSON architecture definitions generated by Python/Sail tools,
    provides dynamic opcode encoding/decoding, and compiles arbitrary CIL AST expressions
    and statements into packed & encrypted 32-bit Vector Instruction Bytecode (.vbc) with
    a custom C11 VCPU emulator tailored to the active ISA specification.
*)
module VisaSpec = struct
  type visa_field_layout = {
    funct6_shift : int;
    funct6_mask : int;
    vm_shift : int;
    vs2_shift : int;
    vs1_shift : int;
    funct3_shift : int;
    vd_shift : int;
    opcode_val : int;
  }

  type visa_opcodes = {
    vadd_vv : int;
    vsub_vv : int;
    vmul_vv : int;
    vxor_vv : int;
    vand_vv : int;
    vor_vv  : int;
    vsll_vv : int;
    vsrl_vv : int;
    vli_vi  : int;
    vmv_vv  : int;
    vle8_v  : int;
    vse8_v  : int;
    vret_v  : int;
    vbge_vv : int;
    vj      : int;
  }

  type visa_spec = {
    isa_name : string;
    isa_version : string;
    word_bits : int;
    reg_count : int;
    pack_key : int64;
    delta_key : int64;
    layout : visa_field_layout;
    opcodes : visa_opcodes;
  }

  let default_spec : visa_spec = {
    isa_name = "vISA_Standard_RISCV_Vector";
    isa_version = "1.0";
    word_bits = 32;
    reg_count = 16;
    pack_key = 0x5A5AA5A5L;
    delta_key = 0x1000193L;
    layout = {
      funct6_shift = 26;
      funct6_mask = 0x3F;
      vm_shift = 25;
      vs2_shift = 20;
      vs1_shift = 15;
      funct3_shift = 12;
      vd_shift = 7;
      opcode_val = 0x57;
    };
    opcodes = {
      vadd_vv = 0x00;
      vsub_vv = 0x01;
      vmul_vv = 0x02;
      vxor_vv = 0x03;
      vand_vv = 0x04;
      vor_vv  = 0x05;
      vsll_vv = 0x06;
      vsrl_vv = 0x07;
      vli_vi  = 0x08;
      vmv_vv  = 0x0D;
      vle8_v  = 0x0E;
      vse8_v  = 0x15;
      vret_v  = 0x0F;
      vbge_vv = 0x13;
      vj      = 0x14;
    };
  }

  let active_spec = ref default_spec

  let set_active_spec (spec : visa_spec) : unit =
    active_spec := spec

  let get_active_spec () : visa_spec =
    !active_spec

  let to_str_def def = function
    | `String s -> s
    | _ -> def

  let to_int_def def = function
    | `Int i -> i
    | _ -> def

  let from_json_string (json_str : string) : visa_spec =
    let json = Yojson.Basic.from_string json_str in
    let isa_name = json |> member "isa_name" |> to_str_def "vISA_Custom" in
    let isa_version = json |> member "isa_version" |> to_str_def "1.0" in
    let word_bits = json |> member "word_bits" |> to_int_def 32 in
    let reg_count = json |> member "reg_count" |> to_int_def 16 in
    let pack_key =
      match json |> member "pack_key" with
      | `Int i -> Int64.of_int i
      | `String s -> Int64.of_string s
      | _ -> 0x5A5AA5A5L
    in
    let delta_key =
      match json |> member "delta_key" with
      | `Int i -> Int64.of_int i
      | `String s -> Int64.of_string s
      | _ -> 0x1000193L
    in
    let lay = json |> member "layout" in
    let layout = {
      funct6_shift = lay |> member "funct6_shift" |> to_int_def 26;
      funct6_mask  = lay |> member "funct6_mask" |> to_int_def 0x3F;
      vm_shift     = lay |> member "vm_shift" |> to_int_def 25;
      vs2_shift    = lay |> member "vs2_shift" |> to_int_def 20;
      vs1_shift    = lay |> member "vs1_shift" |> to_int_def 15;
      funct3_shift = lay |> member "funct3_shift" |> to_int_def 12;
      vd_shift     = lay |> member "vd_shift" |> to_int_def 7;
      opcode_val   = lay |> member "opcode_val" |> to_int_def 0x57;
    } in
    let op = json |> member "opcodes" in
    let opcodes = {
      vadd_vv = op |> member "vadd_vv" |> to_int_def 0x00;
      vsub_vv = op |> member "vsub_vv" |> to_int_def 0x01;
      vmul_vv = op |> member "vmul_vv" |> to_int_def 0x02;
      vxor_vv = op |> member "vxor_vv" |> to_int_def 0x03;
      vand_vv = op |> member "vand_vv" |> to_int_def 0x04;
      vor_vv  = op |> member "vor_vv"  |> to_int_def 0x05;
      vsll_vv = op |> member "vsll_vv" |> to_int_def 0x06;
      vsrl_vv = op |> member "vsrl_vv" |> to_int_def 0x07;
      vli_vi  = op |> member "vli_vi"  |> to_int_def 0x08;
      vmv_vv  = op |> member "vmv_vv"  |> to_int_def 0x0D;
      vle8_v  = op |> member "vle8_v"  |> to_int_def 0x0E;
      vse8_v  = op |> member "vse8_v"  |> to_int_def 0x15;
      vret_v  = op |> member "vret_v"  |> to_int_def 0x0F;
      vbge_vv = op |> member "vbge_vv" |> to_int_def 0x13;
      vj      = op |> member "vj"      |> to_int_def 0x14;
    } in
    {
      isa_name;
      isa_version;
      word_bits;
      reg_count;
      pack_key;
      delta_key;
      layout;
      opcodes;
    }

  let load_from_file (file_path : string) : visa_spec =
    let ic = open_in file_path in
    let n = in_channel_length ic in
    let s = really_input_string ic n in
    close_in ic;
    let spec = from_json_string s in
    active_spec := spec;
    spec

  let encode_inst (spec : visa_spec) ~funct6 ~vm ~vs2 ~vs1_or_imm ~funct3 ~vd =
    let l = spec.layout in
    let word =
      (((funct6 land l.funct6_mask) lsl l.funct6_shift) lor
       ((vm land 0x01) lsl l.vm_shift) lor
       ((vs2 land 0x1F) lsl l.vs2_shift) lor
       ((vs1_or_imm land 0x1F) lsl l.vs1_shift) lor
       ((funct3 land 0x07) lsl l.funct3_shift) lor
       ((vd land 0x1F) lsl l.vd_shift) lor
       (l.opcode_val land 0x7F)) land 0xFFFFFFFF
    in
    Int32.of_int word
end

module Make (Entropy : Entropy_port.S) = struct
  module Spec = VisaSpec

  let vcpu_counter = ref 0

  let generate_visa_runtime (file : file) : unit =
    let already_injected =
      List.exists
        (function
          | GVarDecl (v, _) when v.vname = "__visa_engine_ready" -> true
          | _ -> false)
        file.globals
    in
    if not already_injected then (
      let flag_var = makeGlobalVar "__visa_engine_ready" intType in
      flag_var.vstorage <- Static;
      file.globals <- (GVarDecl (flag_var, locUnknown)) :: file.globals
    )

  let should_transform (fd : fundec) : bool =
    if fd.svar.vname = "main" || String.starts_with ~prefix:"__" fd.svar.vname then false
    else if C_annotation_service.AnnotationHelper.should_skip_all fd then false
    else if C_annotation_service.AnnotationHelper.has_annotation fd "visa"
            || C_annotation_service.AnnotationHelper.has_annotation fd "vector_vm"
            || C_annotation_service.AnnotationHelper.has_annotation fd "virtualize" then true
    else not (C_annotation_service.AnnotationHelper.has_any_vm_annotation fd)
         && not (C_annotation_service.AnnotationHelper.has_custom_annotations fd)

  let virtualize_function (file : file) (fd : fundec) : unit =
    if not (should_transform fd) then ()
    else (
      incr vcpu_counter;
      generate_visa_runtime file;

      let spec = Spec.get_active_spec () in
      let op = spec.opcodes in
      let lay = spec.layout in

      let vbc_name = Printf.sprintf "__visa_program_%s_%d" fd.svar.vname !vcpu_counter in
      let ptr_formals = List.filter (fun p -> isPointerType p.vtype) fd.sformals in
      let has_ptr_param = ptr_formals <> [] in

      (* Variable to register mapping: v0..vN *)
      let var_map = Hashtbl.create 32 in
      List.iteri (fun idx p -> Hashtbl.add var_map p.vname idx) fd.sformals;
      let next_vreg = ref (List.length fd.sformals) in
      List.iter
        (fun v ->
          if not (Hashtbl.mem var_map v.vname) then (
            Hashtbl.add var_map v.vname !next_vreg;
            incr next_vreg
          ))
        fd.slocals;

      let get_vreg name =
        if Hashtbl.mem var_map name then Hashtbl.find var_map name
        else (
          let r = !next_vreg in
          incr next_vreg;
          Hashtbl.add var_map name r;
          r
        )
      in

      let instrs = ref [] in
      let emit inst = instrs := inst :: !instrs in

      let encode_jump target_pc =
        let l = spec.layout in
        let word =
          (((op.vj land l.funct6_mask) lsl l.funct6_shift) lor
           ((target_pc land 0x7FFFF) lsl 7) lor
           (l.opcode_val land 0x7F)) land 0xFFFFFFFF
        in
        Int32.of_int word
      in

      let encode_branch_ge vs1 vs2 target_pc =
        let l = spec.layout in
        let word =
          (((op.vbge_vv land l.funct6_mask) lsl l.funct6_shift) lor
           (1 lsl l.vm_shift) lor
           ((vs2 land 0x1F) lsl l.vs2_shift) lor
           ((vs1 land 0x1F) lsl l.vs1_shift) lor
           ((target_pc land 0x1F) lsl 7) lor
           (l.opcode_val land 0x7F)) land 0xFFFFFFFF
        in
        Int32.of_int word
      in

      let rec extract_ptr_var = function
        | Lval (Var v, NoOffset) -> Some v
        | CastE (_, e) -> extract_ptr_var e
        | _ -> None
      in

      let rec compile_exp (e : exp) (dst : int) (free_reg : int) : unit =
        match e with
        | Const (CInt (i, _, _)) ->
            let imm = Z.to_int i land 0x3FFF in
            let vm = (imm lsr 13) land 0x01 in
            let f3 = (imm lsr 10) land 0x07 in
            let vs1 = (imm lsr 5) land 0x1F in
            let vs2 = imm land 0x1F in
            emit (Spec.encode_inst spec ~funct6:op.vli_vi ~vm ~vs2 ~vs1_or_imm:vs1 ~funct3:f3 ~vd:(dst land 0x1F))
        | Lval (Var v, NoOffset) ->
            let src = get_vreg v.vname in
            if src <> dst then
              emit (Spec.encode_inst spec ~funct6:op.vmv_vv ~vm:1 ~vs2:0 ~vs1_or_imm:(src land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | Lval (Var ptr_v, Index (idx_e, NoOffset)) ->
            compile_exp idx_e free_reg (free_reg + 1);
            emit (Spec.encode_inst spec ~funct6:op.vle8_v ~vm:1 ~vs2:(free_reg land 0x1F) ~vs1_or_imm:((get_vreg ptr_v.vname) land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | Lval (Mem (BinOp ((PlusPI | PlusA | IndexPI), ptr_e, idx_e, _)), NoOffset) ->
            (match extract_ptr_var ptr_e with
             | Some ptr_v ->
                 compile_exp idx_e free_reg (free_reg + 1);
                 emit (Spec.encode_inst spec ~funct6:op.vle8_v ~vm:1 ~vs2:(free_reg land 0x1F) ~vs1_or_imm:((get_vreg ptr_v.vname) land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
             | None ->
                 (match extract_ptr_var idx_e with
                  | Some ptr_v ->
                      compile_exp ptr_e free_reg (free_reg + 1);
                      emit (Spec.encode_inst spec ~funct6:op.vle8_v ~vm:1 ~vs2:(free_reg land 0x1F) ~vs1_or_imm:((get_vreg ptr_v.vname) land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
                  | None -> ()))
        | Lval (Mem (Lval (Var ptr_v, NoOffset)), NoOffset) ->
            emit (Spec.encode_inst spec ~funct6:op.vli_vi ~vm:0 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:(free_reg land 0x1F));
            emit (Spec.encode_inst spec ~funct6:op.vle8_v ~vm:1 ~vs2:(free_reg land 0x1F) ~vs1_or_imm:((get_vreg ptr_v.vname) land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | UnOp (Neg, e1, _) ->
            compile_exp e1 dst free_reg;
            emit (Spec.encode_inst spec ~funct6:op.vsub_vv ~vm:1 ~vs2:(dst land 0x1F) ~vs1_or_imm:0 ~funct3:0 ~vd:(dst land 0x1F))
        | UnOp (BNot, e1, _) ->
            compile_exp e1 dst free_reg;
            emit (Spec.encode_inst spec ~funct6:op.vxor_vv ~vm:1 ~vs2:0x1F ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | BinOp (bin_op, e1, e2, _) ->
            compile_exp e1 dst free_reg;
            let t_reg = free_reg in
            compile_exp e2 t_reg (free_reg + 1);
            let funct6 =
              match bin_op with
              | PlusA -> op.vadd_vv
              | MinusA -> op.vsub_vv
              | Mult -> op.vmul_vv
              | BXor -> op.vxor_vv
              | BAnd -> op.vand_vv
              | BOr -> op.vor_vv
              | Shiftlt -> op.vsll_vv
              | Shiftrt -> op.vsrl_vv
              | _ -> op.vadd_vv
            in
            emit (Spec.encode_inst spec ~funct6 ~vm:1 ~vs2:(t_reg land 0x1F) ~vs1_or_imm:(dst land 0x1F) ~funct3:0 ~vd:(dst land 0x1F))
        | CastE (_, e1) ->
            compile_exp e1 dst free_reg
        | _ -> ()
      in

      let rec compile_stmt (s : stmt) : unit =
        match s.skind with
        | Instr inst_list ->
            List.iter
              (function
                | Set ((Var v, NoOffset), exp, _, _) ->
                    let dst = get_vreg v.vname in
                    compile_exp exp dst (!next_vreg)
                | Set ((Mem (BinOp (PlusPI, ptr_e, idx_e, _)), NoOffset), exp, _, _) ->
                    (match extract_ptr_var ptr_e with
                     | Some ptr_v ->
                         let t1 = !next_vreg in
                         let t2 = !next_vreg + 1 in
                         compile_exp idx_e t1 (!next_vreg + 2);
                         compile_exp exp t2 (!next_vreg + 2);
                         emit (Spec.encode_inst spec ~funct6:op.vse8_v ~vm:1 ~vs2:(t1 land 0x1F) ~vs1_or_imm:(t2 land 0x1F) ~funct3:0 ~vd:((get_vreg ptr_v.vname) land 0x1F))
                     | None -> ())
                | _ -> ())
              inst_list
        | Return (Some exp, _, _) ->
            compile_exp exp 0 (!next_vreg);
            emit (Spec.encode_inst spec ~funct6:op.vret_v ~vm:1 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:0)
        | Return (None, _, _) ->
            emit (Spec.encode_inst spec ~funct6:op.vret_v ~vm:1 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:0)
        | Block blk ->
            List.iter compile_stmt blk.bstmts
        | Loop (blk, _, _, _, _) ->
            let loop_start_idx = List.length !instrs in
            List.iter compile_stmt blk.bstmts;
            emit (encode_jump loop_start_idx)
        | If (cond, tb, fb, _, _) ->
            (match cond with
             | BinOp (Lt, e1, e2, _)
             | UnOp (LNot, BinOp (Lt, e1, e2, _), _)
             | BinOp (Ge, e1, e2, _) ->
                 let t1 = !next_vreg in
                 let t2 = !next_vreg + 1 in
                 compile_exp e1 t1 (!next_vreg + 2);
                 compile_exp e2 t2 (!next_vreg + 2);
                 emit (encode_branch_ge (t1 land 0x1F) (t2 land 0x1F) 0)
             | _ -> ());
            List.iter compile_stmt tb.bstmts;
            List.iter compile_stmt fb.bstmts
        | _ -> ()
      in

      List.iter compile_stmt fd.sbody.bstmts;

      if !instrs = [] then (
        emit (Spec.encode_inst spec ~funct6:op.vli_vi ~vm:0 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:0);
        emit (Spec.encode_inst spec ~funct6:op.vret_v ~vm:1 ~vs2:0 ~vs1_or_imm:0 ~funct3:0 ~vd:0)
      );

      let vbc_words = List.rev !instrs in

      (* Packing 32-bit Vector Instruction Words with Active Rolling XOR Key Mask *)
      let pack_key_32 = Int64.to_int32 spec.pack_key in
      let delta_key_32 = Int64.to_int32 spec.delta_key in
      let packed_words =
        List.mapi
          (fun idx w ->
            let delta = Int32.mul (Int32.of_int idx) delta_key_32 in
            let key = Int32.logxor pack_key_32 delta in
            Int32.logxor w key)
          vbc_words
      in

      let uint_ty = uintType in
      let array_type = TArray (uint_ty, Some (integer (List.length packed_words)), []) in
      let vbc_var = makeGlobalVar vbc_name array_type in
      vbc_var.vstorage <- Static;

      let init_entries =
        List.mapi
          (fun idx w ->
            let u64 = Int64.logand (Int64.of_int32 w) 0xFFFFFFFFL in
            let init_val = SingleInit (Const (CInt (Z.of_int64 u64, IUInt, None))) in
            (Index (integer idx, NoOffset), init_val))
          packed_words
      in
      file.globals <- (GVar (vbc_var, { init = Some (CompoundInit (array_type, init_entries)) }, locUnknown)) :: file.globals;

      (* Build clean C11 Vector VCPU execution function body matching the active Spec *)
      let ptr_arg =
        if has_ptr_param then (List.hd ptr_formals).vname else "0"
      in

      let vreg_total = max 64 (!next_vreg + 32) in

      let arg_inits =
        List.mapi
          (fun idx p ->
            if isIntegralType p.vtype then Printf.sprintf "    __vregs[%d] = (int)%s;" idx p.vname
            else Printf.sprintf "    __vregs[%d] = 0;" idx)
          fd.sformals
        |> String.concat "\n"
      in

      let fn_params =
        List.map
          (fun p ->
            let ty_str = match p.vtype with
              | TPtr (TInt (IChar, _), _) | TPtr (TInt (ISChar, _), _) -> "const char *"
              | TPtr (TInt (IUChar, _), _) -> "const unsigned char *"
              | TPtr _ -> "void *"
              | _ -> "int"
            in
            Printf.sprintf "%s %s" ty_str p.vname)
          fd.sformals
        |> String.concat ", "
      in

      let fn_body_impl = Format.sprintf {|
int %s(%s) {
    int __vregs[%d] = {0};
%s
    const char *__ptr_ctx = (const char *)%s;
    unsigned int __pc = 0;
    int __running = 1;

    while (__running && __pc < %d) {
        unsigned int __raw = %s[__pc];
        unsigned int __key = 0x%LxU ^ (__pc * 0x%LxU);
        unsigned int __inst = __raw ^ __key;

        unsigned char __funct6 = (unsigned char)((__inst >> %d) & 0x%X);
        unsigned char __vm     = (unsigned char)((__inst >> %d) & 0x01);
        unsigned char __vs2    = (unsigned char)((__inst >> %d) & 0x1F);
        unsigned char __vs1    = (unsigned char)((__inst >> %d) & 0x1F);
        unsigned char __funct3 = (unsigned char)((__inst >> %d) & 0x07);
        unsigned char __vd     = (unsigned char)((__inst >> %d)  & 0x1F);

        switch (__funct6) {
            case 0x%X: /* vadd.vv */
                __vregs[__vd] = __vregs[__vs1] + __vregs[__vs2];
                break;
            case 0x%X: /* vsub.vv */
                __vregs[__vd] = __vregs[__vs1] - __vregs[__vs2];
                break;
            case 0x%X: /* vmul.vv */
                __vregs[__vd] = __vregs[__vs1] * __vregs[__vs2];
                break;
            case 0x%X: /* vxor.vv */
                __vregs[__vd] = __vregs[__vs1] ^ __vregs[__vs2];
                break;
            case 0x%X: /* vand.vv */
                __vregs[__vd] = __vregs[__vs1] & __vregs[__vs2];
                break;
            case 0x%X: /* vor.vv */
                __vregs[__vd] = __vregs[__vs1] | __vregs[__vs2];
                break;
            case 0x%X: /* vsll.vv */
                __vregs[__vd] = __vregs[__vs1] << __vregs[__vs2];
                break;
            case 0x%X: /* vsrl.vv */
                __vregs[__vd] = (int)((unsigned int)__vregs[__vs1] >> __vregs[__vs2]);
                break;
            case 0x%X: /* vli.vi (14-bit immediate) */
                __vregs[__vd] = (int)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2);
                break;
            case 0x%X: /* vmv.vv */
                __vregs[__vd] = __vregs[__vs1];
                break;
            case 0x%X: /* vle8.v load byte */
                if (__ptr_ctx) {
                    __vregs[__vd] = (int)((unsigned char)__ptr_ctx[__vregs[__vs2]]);
                }
                break;
            case 0x%X: /* vret.v */
                __running = 0;
                break;
            case 0x%X: /* vbge.vv */
                if (__vregs[__vs1] >= __vregs[__vs2]) {
                    /* Break loop: jump past loop back-edge */
                    __pc = (%d) - 1;
                }
                break;
            case 0x%X: /* vj */
                __pc = ((__inst >> 7) & 0x7FFFF) - 1;
                break;
            default:
                break;
        }
        __pc++;
    }
    return __vregs[0];
}
|}
        fd.svar.vname
        fn_params
        vreg_total
        arg_inits
        ptr_arg
        (List.length packed_words)
        vbc_name
        spec.pack_key
        spec.delta_key
        lay.funct6_shift lay.funct6_mask
        lay.vm_shift
        lay.vs2_shift
        lay.vs1_shift
        lay.funct3_shift
        lay.vd_shift
        op.vadd_vv
        op.vsub_vv
        op.vmul_vv
        op.vxor_vv
        op.vand_vv
        op.vor_vv
        op.vsll_vv
        op.vsrl_vv
        op.vli_vi
        op.vmv_vv
        op.vle8_v
        op.vret_v
        op.vbge_vv
        (List.length packed_words - 2)
        op.vj
      in

      let new_globals = ref [] in
      List.iter
        (fun g ->
          match g with
          | GFun (f_dec, _) when f_dec.svar.vname = fd.svar.vname ->
              new_globals := GText fn_body_impl :: !new_globals
          | other -> new_globals := other :: !new_globals)
        file.globals;
      file.globals <- List.rev !new_globals
    )

  let transform_file (f : file) : file =
    let funcs =
      List.filter_map
        (function
          | GFun (fd, _) -> Some fd
          | _ -> None)
        f.globals
    in
    List.iter (virtualize_function f) funcs;
    f
end
