(** Polymorphic Sail Code Generators for Multi-VCPU ISA Specifications.
    Each VCPU gets a structurally distinct ISA: unique register widths,
    mnemonic names, instruction formats, decode schemes and semantics.
    No two generated .sail files share the same structural shape. *)

(* ============================================================================
   Unique mnemonic namer: generates opaque 3-6 char uppercase identifiers
   ============================================================================ *)

let syllables_ =
  [| "VR"; "KX"; "MZ"; "QN"; "PL"; "BF"; "WT"; "GH";
     "CY"; "DS"; "JR"; "FN"; "TK"; "XB"; "ZW"; "HP" |]

let gen_mnemonic (rng : unit -> int) (prefix : string) : string =
  let a = syllables_.(rng () mod 16) in
  let b = syllables_.(rng () mod 16) in
  Printf.sprintf "%s_%s%s" prefix a b

(* ============================================================================
   ML parameter overrides (vectis_synth --gf-poly & friends).
   Some v pins a formal-model constant after clamping/snapping; None keeps the
   per-build random draw. These shape the synthesized spec only — tier-1 C
   codegen never depends on them, so ML values cannot break emitted binaries.
   ============================================================================ *)
type synth_params = {
  gf_poly     : int option;
  rol_const   : int option;
  imm_bits    : int option;
  hash_bits   : int option;
  stack_depth : int option;
  state_regs  : int option;
  key_bits    : int option;
  lcg_mult    : int option;
  lcg_delta   : int64 option;
  page_shift  : int option;
  wipe_passes : int option;
  jit_regs    : int option;
}

let default_params = {
  gf_poly = None; rol_const = None; imm_bits = None; hash_bits = None;
  stack_depth = None; state_regs = None; key_bits = None; lcg_mult = None;
  lcg_delta = None; page_shift = None; wipe_passes = None; jit_regs = None;
}

let clamp v lo hi = max lo (min hi v)

(* Snap to the nearest member of a known-good pool. *)
let snap pool v =
  match pool with
  | [] -> v
  | x :: xs ->
      List.fold_left (fun best candidate ->
        if abs (candidate - v) < abs (best - v) then candidate else best
      ) x xs

(* Dataset-known irreducible GF(2^8) polys (sail_dataset_gen.GF_POLYS). *)
let gf_poly_pool = [ 0x1B; 0x1D; 0x4D; 0x8D; 0xA3; 0xC5 ]


(* ============================================================================
   Format A: R-type 32-bit ISA with unique mnemonic names and GF constants
   ============================================================================ *)

let render_visa_sail
    ~(isa_name : string)
    ~(tier : int)
    ~(op_vadd_vv : int)
    ~(op_vsub_vv : int)
    ~(op_vmul_vv : int)
    ~(op_vxor_vv : int)
    ~(op_vand_vv : int)
    ~(op_vor_vv : int)
    ~(op_vsll_vv : int)
    ~(op_vsrl_vv : int)
    ~(op_vli_vi : int)
    ~(op_vmv_vv : int)
    ~(op_vle8_v : int)
    ~(op_vret_v : int)
    ~(op_vbge_vv : int)
    ~(op_vj : int)
    ~(op_vjit_vv : int)
    ~(vd_shift : int)
    ~(vs1_shift : int)
    ~(vs2_shift : int)
    ~(params : synth_params)
    ~(rng : unit -> int) : string =
  let imm_bits  = match params.imm_bits with
    | Some v -> snap [ 12; 14; 16 ] v
    | None -> [| 12; 14; 16 |].(rng () mod 3)
  in
  let gf_poly   = match params.gf_poly with
    | Some v -> snap gf_poly_pool v
    | None -> [| 0x1B; 0x1D; 0x4D; 0x8D; 0xA3 |].(rng () mod 5)
  in
  let rol_const = match params.rol_const with
    | Some v -> clamp v 1 15
    | None -> 1 + rng () mod 15
  in
  let mv_xor_mask = 0xDEAD0000 lxor (op_vmv_vv lsl 16) in
  let n_add = gen_mnemonic rng "V" in let n_sub = gen_mnemonic rng "V" in
  let n_mul = gen_mnemonic rng "V" in let n_xor = gen_mnemonic rng "V" in
  let n_and = gen_mnemonic rng "V" in let n_or  = gen_mnemonic rng "V" in
  let n_sll = gen_mnemonic rng "V" in let n_srl = gen_mnemonic rng "V" in
  let n_li  = gen_mnemonic rng "I" in let n_mv  = gen_mnemonic rng "M" in
  let n_ld  = gen_mnemonic rng "L" in let n_ret = gen_mnemonic rng "R" in
  let n_bge = gen_mnemonic rng "B" in let n_jmp = gen_mnemonic rng "J" in
  let n_jit = gen_mnemonic rng "Z" in
  let s = Buffer.create 2048 in
  Buffer.add_string s (Printf.sprintf
    "(* Sail ISA: %s  tier=%d  imm%d  GF_poly=0x%02X  ROL=%d\n\
     *  Generated by Vectis Polymorphic ISA Synthesizer *)\n\
     default Order dec\n\
     $include <prelude.sail>\n\
     type regidx_%s = bits(5)\n\
     type imm_%s    = bits(%d)\n\
     register %s_R  : vector(16, dec, bits(32))\n\
     register %s_PC : bits(32)\n"
    isa_name tier imm_bits gf_poly rol_const
    isa_name isa_name imm_bits
    isa_name isa_name);
  Buffer.add_string s (Printf.sprintf "union %s_ast = {\n" isa_name);
  let union_arms = [
    (n_add, Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
    (n_sub, Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
    (n_mul, Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
    (n_xor, Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
    (n_and, Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
    (n_or,  Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
    (n_sll, Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
    (n_srl, Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
    (n_li,  Printf.sprintf "(regidx_%s, imm_%s)" isa_name isa_name);
    (n_mv,  Printf.sprintf "(regidx_%s, regidx_%s)" isa_name isa_name);
    (n_ld,  Printf.sprintf "(regidx_%s, regidx_%s)" isa_name isa_name);
    (n_ret, Printf.sprintf "(regidx_%s)" isa_name);
    (n_bge, Printf.sprintf "(regidx_%s, regidx_%s)" isa_name isa_name);
    (n_jmp, "(bits(32))");
    (n_jit, Printf.sprintf "(regidx_%s, regidx_%s, regidx_%s)" isa_name isa_name isa_name);
  ] in
  List.iter (fun (nm, ty) ->
    Buffer.add_string s (Printf.sprintf "    %s : %s,\n" nm ty)
  ) union_arms;
  Buffer.add_string s "}\n";
  Buffer.add_string s (Printf.sprintf
    "val %s_decode : bits(32) -> option(%s_ast)\n\
     function %s_decode(inst) = {\n\
     \    let f6  : bits(6) = inst[31..26];\n\
     \    let vs2 : bits(5) = inst[%d..%d];\n\
     \    let vs1 : bits(5) = inst[%d..%d];\n\
     \    let vd  : bits(5) = inst[%d..%d];\n\
     \    let imm : bits(%d) = inst[%d..0];\n\
     \    match f6 {\n"
    isa_name isa_name isa_name
    (vs2_shift + 4) vs2_shift (vs1_shift + 4) vs1_shift
    (vd_shift + 4) vd_shift imm_bits (imm_bits - 1));
  let decode_arms = [
    (op_vadd_vv, n_add, "vd, vs1, vs2");
    (op_vsub_vv, n_sub, "vd, vs1, vs2");
    (op_vmul_vv, n_mul, "vd, vs1, vs2");
    (op_vxor_vv, n_xor, "vd, vs1, vs2");
    (op_vand_vv, n_and, "vd, vs1, vs2");
    (op_vor_vv,  n_or,  "vd, vs1, vs2");
    (op_vsll_vv, n_sll, "vd, vs1, vs2");
    (op_vsrl_vv, n_srl, "vd, vs1, vs2");
    (op_vli_vi,  n_li,  "vd, imm");
    (op_vmv_vv,  n_mv,  "vd, vs1");
    (op_vle8_v,  n_ld,  "vd, vs2");
    (op_vret_v,  n_ret, "vd");
    (op_vbge_vv, n_bge, "vs1, vs2");
    (op_vj,      n_jmp, "inst");
    (op_vjit_vv, n_jit, "vd, vs1, vs2");
  ] in
  List.iter (fun (opc, nm, args) ->
    Buffer.add_string s (Printf.sprintf "        %d => Some(%s(%s)),\n" opc nm args)
  ) decode_arms;
  Buffer.add_string s "        _ => None()\n    }\n}\n";
  Buffer.add_string s (Printf.sprintf
    "val %s_gfmul : (bits(8), bits(8)) -> bits(8)\n\
     function %s_gfmul(a, b) = {\n\
     \    let p1 = if a[0] == bitzero then 0x00 else b;\n\
     \    let b2 = (b << 1) ^ (if b[7] == bitone then 0x%02X else 0x00);\n\
     \    p1 ^ (if a[1] == bitzero then 0x00 else b2)\n}\n"
    isa_name isa_name gf_poly);
  Buffer.add_string s (Printf.sprintf
    "val %s_execute : %s_ast -> unit\nfunction %s_execute(op) = {\n    match op {\n"
    isa_name isa_name isa_name);
  let exec_arms = [
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = %s_R[vs1] + %s_R[vs2]" n_add isa_name isa_name isa_name;
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = %s_R[vs1] - %s_R[vs2]" n_sub isa_name isa_name isa_name;
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = %s_R[vs1] * %s_R[vs2]" n_mul isa_name isa_name isa_name;
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = %s_R[vs1] ^ %s_R[vs2]" n_xor isa_name isa_name isa_name;
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = %s_R[vs1] & %s_R[vs2]" n_and isa_name isa_name isa_name;
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = %s_R[vs1] | %s_R[vs2]" n_or  isa_name isa_name isa_name;
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = %s_R[vs1] << unsigned(%s_R[vs2])" n_sll isa_name isa_name isa_name;
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = %s_R[vs1] >> unsigned(%s_R[vs2])" n_srl isa_name isa_name isa_name;
    Printf.sprintf "%s(vd, imm) => %s_R[vd] = EXTZ(imm) ^ (EXTZ(imm) << %d)" n_li  isa_name rol_const;
    Printf.sprintf "%s(vd, vs1) => %s_R[vd] = %s_R[vs1] ^ 0x%08X" n_mv  isa_name isa_name mv_xor_mask;
    Printf.sprintf "%s(vd, _vs2) => { () }" n_ld;
    Printf.sprintf "%s(vd) => { () }" n_ret;
    Printf.sprintf "%s(vs1, vs2) => { () }" n_bge;
    Printf.sprintf "%s(tgt) => { %s_PC = tgt }" n_jmp isa_name;
    Printf.sprintf "%s(vd, vs1, vs2) => %s_R[vd] = ((%s_R[vs1] ^ %s_R[vs2]) * 3) + 42" n_jit isa_name isa_name isa_name;
  ] in
  List.iter (fun arm ->
    Buffer.add_string s (Printf.sprintf "        %s,\n" arm)
  ) exec_arms;
  Buffer.add_string s "    }\n}\n";
  Buffer.contents s


(* ============================================================================
   Format B: 2-tier Stack VM — unique inner/outer AST, hash width, stack depth
   ============================================================================ *)

let render_nested_vm_sail
    ~(vm_name : string)
    ~(params : synth_params)
    ~(rng : unit -> int) : string =
  let hash_bits   = match params.hash_bits with
    | Some v -> snap [ 32; 48; 64 ] v
    | None -> [| 32; 48; 64 |].(rng () mod 3)
  in
  let stack_depth = match params.stack_depth with
    | Some v -> clamp v 4 16
    | None -> 4 + rng () mod 13
  in
  let state_regs  = match params.state_regs with
    | Some v -> clamp v 4 12
    | None -> 4 + rng () mod 9
  in
  let n_init   = gen_mnemonic rng "OX" in
  let n_disp   = gen_mnemonic rng "OX" in
  let n_mutk   = gen_mnemonic rng "OX" in
  let n_halt   = gen_mnemonic rng "OX" in
  let n_lda    = gen_mnemonic rng "IX" in
  let n_ldc    = gen_mnemonic rng "IX" in
  let n_iadd   = gen_mnemonic rng "IX" in
  let n_isub   = gen_mnemonic rng "IX" in
  let n_ixor   = gen_mnemonic rng "IX" in
  let n_imul   = gen_mnemonic rng "IX" in
  let n_iret   = gen_mnemonic rng "IX" in
  let s = Buffer.create 2048 in
  Buffer.add_string s (Printf.sprintf
    "(* Sail ISA: %s (2-Tier Nested Stack VM)\n\
     *  hash_bits=%d  stack_depth=%d  state_regs=%d\n\
     *  Generated by Vectis Polymorphic ISA Synthesizer *)\n\
     default Order dec\n\
     $include <prelude.sail>\n\
     type %s_hash = bits(%d)\n\
     type %s_byte = bits(8)\n\
     type %s_ridx = bits(3)\n"
    vm_name hash_bits stack_depth state_regs
    vm_name hash_bits  vm_name  vm_name);
  Buffer.add_string s (Printf.sprintf
    "register %s_OuterPC : bits(32)\n\
     register %s_InnerPC : bits(32)\n\
     register %s_OuterH  : %s_hash\n\
     register %s_InnerR  : vector(%d, dec, bits(32))\n\
     register %s_Stack   : vector(%d, dec, bits(32))\n\
     register %s_SP      : bits(8)\n"
    vm_name vm_name vm_name vm_name vm_name state_regs vm_name stack_depth vm_name);
  Buffer.add_string s (Printf.sprintf "union %s_outer_ast = {\n" vm_name);
  List.iter (fun (nm, ty) -> Buffer.add_string s (Printf.sprintf "    %s : %s,\n" nm ty)) [
    (n_init, "(unit)"); (n_disp, "(unit)");
    (n_mutk, Printf.sprintf "(%s_byte)" vm_name); (n_halt, "(unit)");
  ];
  Buffer.add_string s "}\n";
  Buffer.add_string s (Printf.sprintf "union %s_inner_ast = {\n" vm_name);
  List.iter (fun (nm, ty) -> Buffer.add_string s (Printf.sprintf "    %s : %s,\n" nm ty)) [
    (n_lda,  Printf.sprintf "(%s_ridx)" vm_name);
    (n_ldc,  Printf.sprintf "(%s_ridx, %s_byte)" vm_name vm_name);
    (n_iadd, Printf.sprintf "(%s_ridx, %s_ridx, %s_ridx)" vm_name vm_name vm_name);
    (n_isub, Printf.sprintf "(%s_ridx, %s_ridx, %s_ridx)" vm_name vm_name vm_name);
    (n_ixor, Printf.sprintf "(%s_ridx, %s_ridx, %s_ridx)" vm_name vm_name vm_name);
    (n_imul, Printf.sprintf "(%s_ridx, %s_ridx, %s_ridx)" vm_name vm_name vm_name);
    (n_iret, Printf.sprintf "(%s_ridx)" vm_name);
  ];
  Buffer.add_string s "}\n";
  Buffer.add_string s (Printf.sprintf
    "val %s_outer_execute : %s_outer_ast -> unit\n\
     function %s_outer_execute(op) = {\n    match op {\n" vm_name vm_name vm_name);
  Buffer.add_string s (Printf.sprintf
    "        %s => { %s_InnerPC = EXTZ(0x00); %s_SP = 0x00 },\n" n_init vm_name vm_name);
  Buffer.add_string s (Printf.sprintf "        %s => { () },\n" n_disp);
  Buffer.add_string s (Printf.sprintf
    "        %s(k) => { %s_OuterH = EXTZ(k) ^ %s_OuterH[%d..0] @ %s_OuterH[%d..%d] },\n"
    n_mutk vm_name vm_name (hash_bits - 1) vm_name (hash_bits - 8) (hash_bits - 8));
  Buffer.add_string s (Printf.sprintf "        %s => { () }\n    }\n}\n" n_halt);
  Buffer.add_string s (Printf.sprintf
    "val %s_inner_execute : %s_inner_ast -> unit\n\
     function %s_inner_execute(op) = {\n    match op {\n" vm_name vm_name vm_name);
  List.iter (fun arm -> Buffer.add_string s (Printf.sprintf "        %s,\n" arm)) [
    Printf.sprintf "%s(rd) => %s_InnerR[rd] = EXTZ(0x00)" n_lda vm_name;
    Printf.sprintf "%s(rd, imm) => %s_InnerR[rd] = EXTZ(imm) ^ EXTZ(%s_OuterH[7..0])" n_ldc vm_name vm_name;
    Printf.sprintf "%s(rd, r1, r2) => %s_InnerR[rd] = %s_InnerR[r1] + %s_InnerR[r2]" n_iadd vm_name vm_name vm_name;
    Printf.sprintf "%s(rd, r1, r2) => %s_InnerR[rd] = %s_InnerR[r1] - %s_InnerR[r2]" n_isub vm_name vm_name vm_name;
    Printf.sprintf "%s(rd, r1, r2) => %s_InnerR[rd] = %s_InnerR[r1] ^ %s_InnerR[r2]" n_ixor vm_name vm_name vm_name;
    Printf.sprintf "%s(rd, r1, r2) => %s_InnerR[rd] = %s_InnerR[r1] * %s_InnerR[r2]" n_imul vm_name vm_name vm_name;
    Printf.sprintf "%s(rs) => { () }" n_iret;
  ];
  Buffer.add_string s "    }\n}\n";
  Buffer.contents s


(* ============================================================================
   Format C: Rolling-key VM — unique GF/LCG chain, op names, state reg count
   ============================================================================ *)

let render_rolling_vkey_sail
    ~(vm_name : string)
    ~(tier : int)
    ~(lcg_mult : int)
    ~(lcg_delta : int64)
    ~(params : synth_params)
    ~(rng : unit -> int) : string =
  let state_regs = match params.state_regs with
    | Some v -> clamp v 4 8
    | None -> 4 + rng () mod 5
  in
  let key_bits   = match params.key_bits with
    | Some v -> snap [ 32; 48; 64 ] v
    | None -> [| 32; 48; 64 |].(rng () mod 3)
  in
  let gf_poly    = match params.gf_poly with
    | Some v -> snap gf_poly_pool v
    | None -> [| 0x1B; 0x1D; 0x4D; 0xA3; 0xC5 |].(rng () mod 5)
  in
  let n_xk   = gen_mnemonic rng "RK" in
  let n_add  = gen_mnemonic rng "RK" in
  let n_mul  = gen_mnemonic rng "RK" in
  let n_rot  = gen_mnemonic rng "RK" in
  let n_fold = gen_mnemonic rng "RK" in
  let n_halt = gen_mnemonic rng "RK" in
  let s = Buffer.create 2048 in

  Buffer.add_string s (Printf.sprintf
    "(* Sail ISA: %s (Rolling VKey VM Tier %d)\n\
     *  key_bits=%d  state_regs=%d  GF_poly=0x%02X  LCG: mult=%d delta=0x%LX\n\
     *  Generated by Vectis Polymorphic ISA Synthesizer *)\n\
     default Order dec\n\
     $include <prelude.sail>\n\
     type %s_kridx = bits(2)\n\
     register %s_VKey     : bits(%d)\n\
     register %s_State    : vector(%d, dec, bits(32))\n\
     register %s_ChainAcc : bits(64)\n\
     register %s_Round    : bits(8)\n"
    vm_name tier key_bits state_regs gf_poly lcg_mult lcg_delta
    vm_name  vm_name key_bits  vm_name state_regs  vm_name  vm_name);
  Buffer.add_string s (Printf.sprintf
    "val %s_evolve_key : bits(32) -> unit\n\
     function %s_evolve_key(data) = {\n\
     \    let s1 = (%s_VKey[31..0] * 0x%08X);\n\
     \    let s2 = s1 ^ (data + 0x%LX);\n\
     \    let fold = s2[31..0] ^ s2[15..0] @ s2[31..16];\n\
     \    %s_VKey = EXTZ(fold);\n\
     \    %s_ChainAcc = %s_ChainAcc ^ EXTZ(%s_VKey[31..0])\n}\n"
    vm_name vm_name vm_name lcg_mult lcg_delta vm_name vm_name vm_name vm_name);
  Buffer.add_string s (Printf.sprintf
    "val %s_gf_reduce : bits(8) -> bits(8)\n\
     function %s_gf_reduce(b) = {\n\
     \    if b[7] == bitone then (b << 1) ^ 0x%02X else b << 1\n}\n"
    vm_name vm_name gf_poly);
  Buffer.add_string s (Printf.sprintf "union %s_rolling_ast = {\n" vm_name);
  let kridx = Printf.sprintf "%s_kridx" vm_name in
  List.iter (fun (nm, ty) -> Buffer.add_string s (Printf.sprintf "    %s : %s,\n" nm ty)) [
    (n_xk,   Printf.sprintf "(%s, bits(32))" kridx);
    (n_add,  Printf.sprintf "(%s, bits(32))" kridx);
    (n_mul,  Printf.sprintf "(%s, bits(32))" kridx);
    (n_rot,  Printf.sprintf "(%s, bits(8))"  kridx);
    (n_fold, Printf.sprintf "(%s)" kridx);
    (n_halt, "(unit)");
  ];
  Buffer.add_string s "}\n";
  Buffer.add_string s (Printf.sprintf
    "val %s_execute : %s_rolling_ast -> unit\nfunction %s_execute(op) = {\n    match op {\n"
    vm_name vm_name vm_name);
  List.iter (fun arm -> Buffer.add_string s (Printf.sprintf "        %s,\n" arm)) [
    Printf.sprintf "%s(rd, imm) => {\n            %s_State[rd] = %s_State[rd] ^ imm ^ %s_VKey[31..0];\n            %s_evolve_key(imm)\n        }" n_xk vm_name vm_name vm_name vm_name;
    Printf.sprintf "%s(rd, imm) => {\n            %s_State[rd] = %s_State[rd] + imm;\n            %s_evolve_key(%s_State[rd])\n        }" n_add vm_name vm_name vm_name vm_name;
    Printf.sprintf "%s(rd, imm) => {\n            %s_State[rd] = %s_State[rd] * imm;\n            %s_evolve_key(%s_State[rd])\n        }" n_mul vm_name vm_name vm_name vm_name;
    Printf.sprintf "%s(rd, sh) => {\n            let v = %s_State[rd];\n            %s_State[rd] = (v << unsigned(sh)) | (v >> (32 - unsigned(sh)));\n            %s_evolve_key(%s_State[rd])\n        }" n_rot vm_name vm_name vm_name vm_name;
    Printf.sprintf "%s(rd) => {\n            %s_State[rd] = EXTZ(%s_ChainAcc[31..0]) ^ %s_VKey[31..0]\n        }" n_fold vm_name vm_name vm_name;
    Printf.sprintf "%s => { %s_Round = %s_Round + 0x01 }" n_halt vm_name vm_name;
  ];
  Buffer.add_string s "    }\n}\n";
  Buffer.contents s

(* ============================================================================
   Format D: Ephemeral JIT VM — unique page size, wipe passes, FSM enum, guard
   ============================================================================ *)

let render_ephemeral_jit_sail
    ~(vm_name : string)
    ~(tier : int)
    ~(params : synth_params)
    ~(rng : unit -> int) : string =
  let page_shift  = match params.page_shift with
    | Some v -> clamp v 12 15
    | None -> 12 + rng () mod 4
  in
  let wipe_passes = match params.wipe_passes with
    | Some v -> clamp v 1 6
    | None -> 2 + rng () mod 5
  in
  let jit_regs    = match params.jit_regs with
    | Some v -> clamp v 4 7
    | None -> 4 + rng () mod 4
  in
  let guard_magic = 0xDEAD0000 lxor (rng () land 0xFFFF) in
  let n_alloc  = gen_mnemonic rng "EP" in
  let n_map    = gen_mnemonic rng "EP" in
  let n_dec    = gen_mnemonic rng "EP" in
  let n_exec   = gen_mnemonic rng "EP" in
  let n_commit = gen_mnemonic rng "EP" in
  let n_wipe   = gen_mnemonic rng "EP" in
  let s = Buffer.create 2048 in
  Buffer.add_string s (Printf.sprintf
    "(* Sail ISA: %s (Ephemeral JIT VM Tier %d)\n\
     *  page=2^%d  wipe_passes=%d  jit_regs=%d  guard=0x%08X\n\
     *  Generated by Vectis Polymorphic ISA Synthesizer *)\n\
     default Order dec\n\
     $include <prelude.sail>\n\
     type %s_paddr = bits(32)\n\
     type %s_jridx = bits(3)\n"
    vm_name tier page_shift wipe_passes jit_regs guard_magic
    vm_name vm_name);
  Buffer.add_string s (Printf.sprintf
    "enum %s_jstate = { JIT_%s_IDLE, JIT_%s_ALLOC, JIT_%s_MAP, JIT_%s_DECRYPTED, JIT_%s_EXEC, JIT_%s_WIPED }\n"
    vm_name vm_name vm_name vm_name vm_name vm_name vm_name);
  Buffer.add_string s (Printf.sprintf
    "register %s_JitSt   : %s_jstate\n\
     register %s_PageB   : %s_paddr\n\
     register %s_Guard   : bits(32)\n\
     register %s_JitRegs : vector(%d, dec, bits(32))\n\
     register %s_Result  : bits(32)\n\
     register %s_Wipes   : bits(8)\n"
    vm_name vm_name  vm_name vm_name  vm_name  vm_name jit_regs  vm_name  vm_name);
  Buffer.add_string s (Printf.sprintf "union %s_eph_ast = {\n" vm_name);
  List.iter (fun (nm, ty) -> Buffer.add_string s (Printf.sprintf "    %s : %s,\n" nm ty)) [
    (n_alloc,  "(bits(32))");   (n_map, "(bits(32), bits(8))");
    (n_dec,    "(bits(8))");    (n_exec, "(bits(32))");
    (n_commit, "(unit)");       (n_wipe, "(unit)");
  ];
  Buffer.add_string s "}\n";
  Buffer.add_string s (Printf.sprintf
    "val %s_execute : %s_eph_ast -> unit\nfunction %s_execute(op) = {\n    match op {\n"
    vm_name vm_name vm_name);
  List.iter (fun arm -> Buffer.add_string s (Printf.sprintf "        %s,\n" arm)) [
    Printf.sprintf "%s(sz) => {\n            %s_JitSt = JIT_%s_ALLOC;\n            %s_PageB = sz & (0x%08X - 1);\n            %s_Guard = 0x%08X\n        }" n_alloc vm_name vm_name vm_name (1 lsl page_shift) vm_name guard_magic;
    Printf.sprintf "%s(base, key) => {\n            %s_JitSt = JIT_%s_MAP;\n            %s_PageB = base ^ EXTZ(key)\n        }" n_map vm_name vm_name vm_name;
    Printf.sprintf "%s(key) => {\n            %s_JitSt = JIT_%s_DECRYPTED;\n            %s_Guard = %s_Guard ^ EXTZ(key)\n        }" n_dec vm_name vm_name vm_name vm_name;
    Printf.sprintf "%s(inp) => {\n            %s_JitSt  = JIT_%s_EXEC;\n            %s_Result = if inp != 0x00000000 then 0x00000001 else 0x00000000\n        }" n_exec vm_name vm_name vm_name;
    Printf.sprintf "%s => {\n            %s_JitSt = JIT_%s_WIPED;\n            %s_Wipes = %s_Wipes + 0x%02X\n        }" n_commit vm_name vm_name vm_name vm_name wipe_passes;
    Printf.sprintf "%s => {\n            %s_JitSt  = JIT_%s_IDLE;\n            %s_Guard  = 0x00000000;\n            %s_Result = 0x00000000\n        }" n_wipe vm_name vm_name vm_name vm_name;
  ];
  Buffer.add_string s "    }\n}\n";
  Buffer.contents s
