/* Generated by Goblint-CIL v. 2.1.1 */
/* print_CIL_Input is false */


static volatile int __ocasorry_runtime_initialized = 0;

__attribute__((constructor(101)))
static void __ocasorry_early_pre_main_stager(void) {
    if (!__ocasorry_runtime_initialized) {
        __ocasorry_runtime_initialized = 1;
#ifdef __APPLE__
        /* Early anti-debug and environment verification */
#endif
    }
}


#include <dlfcn.h>
#include <stdint.h>
#include <string.h>

/* Hash-only resolver: no plaintext symbol name ever leaves the binary in call sites.
   The resolver scans a static candidate table keyed by CRC32, resolving purely by hash. */
static uint32_t __ocasorry_calc_crc32(const char *s) {
    uint32_t crc = 0xFFFFFFFF;
    while (*s) {
        crc ^= (uint32_t)(unsigned char)(*s++);
        for (int i = 0; i < 8; i++) {
            crc = (crc >> 1) ^ ((crc & 1) ? 0xEDB88320 : 0);
        }
    }
    return ~crc;
}

static void *__ocasorry_resolve_symbol_hash(uint32_t target_hash) {
    /* Candidate symbol names stored as XOR-obfuscated byte arrays (key=0xA5).
       No plaintext strings appear in __cstring / __data sections.
       Sentinel 0xA5 = (0x00 ^ 0xA5) marks end of each name. */
    static const unsigned char __c0[] = {0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5}; /* printf */
    static const unsigned char __c1[] = {0xd5,0xd0,0xd1,0xd6,0xA5};           /* puts */
    static const unsigned char __c2[] = {0xc0,0xdd,0xcc,0xd1,0xA5};           /* exit */
    static const unsigned char __c3[] = {0xc8,0xc4,0xc9,0xc9,0xca,0xc6,0xA5};/* malloc */
    static const unsigned char __c4[] = {0xc3,0xd7,0xc0,0xc0,0xA5};          /* free */
    static const unsigned char __c5[] = {0xc8,0xc0,0xc8,0xd6,0xc0,0xd1,0xA5};/* memset */
    static const unsigned char __c6[] = {0xc8,0xc0,0xc8,0xc6,0xd5,0xdc,0xA5};/* memcpy */
    static const unsigned char __c7[] = {0xd6,0xd1,0xd7,0xc9,0xc0,0xcb,0xA5};/* strlen */
    static const unsigned char __c8[] = {0xc3,0xca,0xd5,0xc0,0xcb,0xA5};     /* fopen */
    static const unsigned char __c9[] = {0xd6,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};       /* sprintf */
    static const unsigned char __ca[] = {0xd6,0xcb,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};  /* snprintf */
    static const unsigned char __cb[] = {0xc4,0xc7,0xca,0xd7,0xd1,0xA5};     /* abort */

    static const unsigned char * const __enc[] = {
        __c0, __c1, __c2, __c3, __c4, __c5, __c6, __c7, __c8, __c9, __ca, __cb, 0
    };

    for (int i = 0; __enc[i] != 0; i++) {
        /* Decode name on the stack at runtime — never stored as plaintext */
        char name[32];
        int j = 0;
        while (__enc[i][j] != 0xA5 && j < 31) {
            name[j] = (char)(__enc[i][j] ^ 0xA5);
            j++;
        }
        name[j] = '\0';

        if (__ocasorry_calc_crc32(name) == target_hash) {
#ifdef RTLD_DEFAULT
            void *sym = dlsym(RTLD_DEFAULT, name);
#else
            void *sym = dlsym((void*)-2, name);
#endif
            if (sym) return sym;
            void *h = dlopen(0, 1);
            if (h) return dlsym(h, name);
        }
    }
    return 0;
}


#include <time.h>
#ifdef __APPLE__
#include <mach/mach_time.h>
static unsigned long long __ocasorry_get_timestamp(void) {
    return (unsigned long long)mach_absolute_time();
}
#else
static unsigned long long __ocasorry_get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}
#endif


#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <dlfcn.h>
typedef int (*__ocasorry_ptrace_t)(int request, pid_t pid, void *addr, int data);

static int __ocasorry_check_debugger_present(void) {
    int mib[4];
    struct kinfo_proc info;
    size_t size = sizeof(info);
    info.kp_proc.p_flag = 0;
    mib[0] = 1; /* CTL_KERN */
    mib[1] = 14; /* KERN_PROC */
    mib[2] = 1; /* KERN_PROC_PID */
    mib[3] = getpid();
    if (sysctl(mib, 4, &info, &size, 0, 0) == 0) {
        if ((info.kp_proc.p_flag & 0x00000800) != 0) { /* P_TRACED */
            return 1;
        }
    }
    return 0;
}

static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        void *h = dlopen(0, 0);
        if (h) {
            __ocasorry_ptrace_t ptrace_fn = (__ocasorry_ptrace_t)dlsym(h, "ptrace");
            if (ptrace_fn) {
                ptrace_fn(31, 0, 0, 0); /* PT_DENY_ATTACH */
            }
        }
        exit(137); /* Fallback exit if ptrace returns */
    }
}
#else
static int __ocasorry_check_debugger_present(void) {
    return 0;
}
static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        exit(137);
    }
}
#endif


#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE
#endif
#include <sys/mman.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <signal.h>
#ifdef __APPLE__
#include <pthread.h>
#include <libkern/OSCacheControl.h>
#include <sys/ucontext.h>
#endif

static void *__ocasorry_two_tier_active_pc = NULL;

#if defined(__APPLE__) && defined(__aarch64__)
static void __ocasorry_two_tier_signal_router(int sig, siginfo_t *info, void *context) {
    (void)sig; (void)info;
    ucontext_t *uc = (ucontext_t *)context;
    if (__ocasorry_two_tier_active_pc != NULL) {
        /* IMPLICIT FLOW: Redirect Program Counter in CPU hardware context */
        uc->uc_mcontext->__ss.__pc = (uint64_t)__ocasorry_two_tier_active_pc;
    }
}
#endif

static void *__ocasorry_alloc_ephemeral_page(size_t *out_sz, size_t min_sz) {
    size_t page_sz = (size_t)sysconf(_SC_PAGESIZE);
    if (page_sz < 4096) page_sz = 4096;
    size_t alloc_sz = (min_sz + page_sz - 1) & ~(page_sz - 1);
    *out_sz = alloc_sz;
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0);
#elif defined(__aarch64__) || defined(__arm64__)
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#else
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#endif
    if (ptr == MAP_FAILED) return NULL;
    return ptr;
}

static void __ocasorry_free_ephemeral_page(void *ptr, size_t sz) {
    if (ptr && ptr != MAP_FAILED) {
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
        pthread_jit_write_protect_np(0); /* Switch to write mode before memory zeroing */
#endif
        memset(ptr, 0, sz); /* Overwrite memory to prevent dump recovery */
        munmap(ptr, sz);
    }
}

static unsigned char __packed_inner_bc_vcpu2_nested_matrix_1[12]  = 
  {      (unsigned char)173,      (unsigned char)203,      (unsigned char)234,      (unsigned char)11, 
        (unsigned char)61,      (unsigned char)70,      (unsigned char)101,      (unsigned char)133, 
        (unsigned char)164,      (unsigned char)194,      (unsigned char)237,      (unsigned char)1};
static unsigned char __packed_outer_bc_vcpu2_nested_matrix_1[5]  = {      (unsigned char)152,      (unsigned char)169,      (unsigned char)138,      (unsigned char)164, 
        (unsigned char)51};
static unsigned int __visa_program_vcpu1_vector_parity_1[25]  = 
  {      852892593U,      2889655176U,      264513987U,      185414810U, 
        1249328853U,      3671931820U,      1692894183U,      1384025406U, 
        538121337U,      1582833584U,      495982987U,      2780553922U, 
        1867640093U,      1630238164U,      1990422959U,      3434773094U, 
        853492257U,      3897872248U,      767547059U,      2078659210U, 
        1877957573U,      2474092188U,      3144593239U,      3880891566U, 
        1016705641U};
static int __visa_engine_ready ;
static char volatile   __enc_lit_1[56]  = 
  {      121,      15,      127,      2, 
        107,      76,      84,      67, 
        78,      75,      70,      2, 
        73,      71,      91,      2, 
        68,      77,      80,      79, 
        67,      86,      24,      2, 
        111,      87,      81,      86, 
        2,      64,      71,      2, 
        71,      90,      67,      65, 
        86,      78,      91,      2, 
        19,      20,      2,      65, 
        74,      67,      80,      67, 
        65,      86,      71,      80, 
        81,      12,      40,      34};
static char volatile   __dec_lit_1[56]  ;
static int volatile   __init_lit_1  =    0;
static char volatile   __enc_lit_2[56]  = 
  {      255,      137,      249,      132, 
        237,      202,      210,      197, 
        200,      205,      192,      132, 
        207,      193,      221,      132, 
        194,      203,      214,      201, 
        197,      208,      158,      132, 
        233,      209,      215,      208, 
        132,      198,      193,      132, 
        193,      220,      197,      199, 
        208,      200,      221,      132, 
        149,      146,      132,      199, 
        204,      197,      214,      197, 
        199,      208,      193,      214, 
        215,      138,      174,      164};
static char volatile   __dec_lit_2[56]  ;
static int volatile   __init_lit_2  =    0;
static char volatile   __enc_lit_3[77]  = 
  {      94,      46,      88,      37, 
        86,      80,      70,      70, 
        64,      86,      86,      63, 
        37,      73,      108,      102, 
        96,      107,      118,      96, 
        37,      110,      96,      124, 
        37,      108,      118,      37, 
        83,      68,      73,      76, 
        65,      36,      37,      49, 
        40,      83,      70,      85, 
        80,      37,      67,      96, 
        97,      96,      119,      100, 
        113,      96,      97,      37, 
        68,      112,      113,      109, 
        106,      119,      108,      127, 
        100,      113,      108,      106, 
        107,      37,      80,      107, 
        105,      106,      102,      110, 
        96,      97,      43,      15, 
        5};
static char volatile   __dec_lit_3[77]  ;
static int volatile   __init_lit_3  =    0;
static char volatile   __enc_lit_4[59]  = 
  {      159,      233,      153,      228, 
        130,      133,      141,      136, 
        129,      128,      254,      228, 
        141,      170,      178,      165, 
        168,      173,      160,      228, 
        168,      173,      167,      161, 
        170,      183,      161,      228, 
        175,      161,      189,      229, 
        228,      240,      233,      146, 
        135,      148,      145,      228, 
        135,      165,      183,      167, 
        165,      160,      161,      228, 
        150,      161,      174,      161, 
        167,      176,      161,      160, 
        234,      206,      196};
static char volatile   __dec_lit_4[59]  ;
static int volatile   __init_lit_4  =    0;
static char volatile   __enc_lit_5[23]  = 
  {      183,      198,      177,      204, 
        186,      137,      158,      133, 
        138,      149,      133,      130, 
        139,      204,      167,      137, 
        149,      214,      204,      201, 
        159,      230,      236};
static char volatile   __dec_lit_5[23]  ;
static int volatile   __init_lit_5  =    0;
extern int printf(char const   *format  , ...) ;
extern unsigned long strlen(char const   *s ) ;

int vcpu1_vector_parity(const char * license_key) {
    int __vregs[64] = {0};
    __vregs[0] = 0;
    const char *__ptr_ctx = (const char *)license_key;
    unsigned int __pc = 0;
    int __running = 1;

    while (__running && __pc < 25) {
        unsigned int __raw = __visa_program_vcpu1_vector_parity_1[__pc];
        unsigned int __key = 0xf3aadb66U ^ (__pc * 0x9e3779b9U);
        unsigned int __inst = __raw ^ __key;

        unsigned char __funct6 = (unsigned char)((__inst >> 26) & 0x3F);
        unsigned char __vm     = (unsigned char)((__inst >> 25) & 0x01);
        unsigned char __vs2    = (unsigned char)((__inst >> 20) & 0x1F);
        unsigned char __vs1    = (unsigned char)((__inst >> 15) & 0x1F);
        unsigned char __funct3 = (unsigned char)((__inst >> 12) & 0x07);
        unsigned char __vd     = (unsigned char)((__inst >> 7)  & 0x1F);

        switch (__funct6) {
            case 0x26: /* vadd.vv */
                __vregs[__vd] = __vregs[__vs1] + __vregs[__vs2];
                break;
            case 0x3E: /* vsub.vv */
                __vregs[__vd] = __vregs[__vs1] - __vregs[__vs2];
                break;
            case 0x3D: /* vmul.vv */
                __vregs[__vd] = __vregs[__vs1] * __vregs[__vs2];
                break;
            case 0x1E: /* vxor.vv */
                __vregs[__vd] = __vregs[__vs1] ^ __vregs[__vs2];
                break;
            case 0xD: /* vand.vv */
                __vregs[__vd] = __vregs[__vs1] & __vregs[__vs2];
                break;
            case 0x24: /* vor.vv */
                __vregs[__vd] = __vregs[__vs1] | __vregs[__vs2];
                break;
            case 0x18: /* vsll.vv */
                __vregs[__vd] = __vregs[__vs1] << __vregs[__vs2];
                break;
            case 0x1D: /* vsrl.vv */
                __vregs[__vd] = (int)((unsigned int)__vregs[__vs1] >> __vregs[__vs2]);
                break;
            case 0x30: /* vli.vi (14-bit immediate) */
                __vregs[__vd] = (int)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2);
                break;
            case 0x8: /* vmv.vv */
                __vregs[__vd] = __vregs[__vs1];
                break;
            case 0x3C: /* vle8.v load byte */
                if (__ptr_ctx) {
                    __vregs[__vd] = (int)((unsigned char)__ptr_ctx[__vregs[__vs2]]);
                }
                break;
            case 0x6: /* vret.v */
                __running = 0;
                break;
            case 0xF: /* vbge.vv */
                if (__vregs[__vs1] >= __vregs[__vs2]) {
                    /* Break loop: jump past loop back-edge */
                    __pc = (23) - 1;
                }
                break;
            case 0x34: /* vj */
                __pc = ((__inst >> 7) & 0x7FFFF) - 1;
                break;
            default:
                break;
        }
        __pc++;
    }
    return __vregs[0];
}

int __attribute__((__annotate__("ocasorry:nested_vm")))  _lIl_lllI1O_Ol_1(int _lOIlI_0lO_2 ) 
{ 
  int __outer_pc ;
  int __outer_running ;
  int __outer_op ;
  int __inner_pc ;
  int __inner_key ;
  int __inner_running ;
  int __inner_op ;
  int __inner_vregs[8] ;
  int __nested_vm_result ;
  int __r_dst ;
  int __r_s1 ;
  int __r_s2 ;
  int __r_imm ;
  int __r_arg ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;

  {
  __t_start = __ocasorry_get_timestamp();
  __desync_guard = 61064;
  {
  if ((__desync_guard & ~ __desync_guard) != 0) {
    return (0);
  }
  }
  __ocasorry_enforce_anti_debug();
  __outer_pc = 0;
  __outer_running = 1;
  __inner_key = 172;
  __nested_vm_result = 0;
  while (1) {
    __outer_op = (int )__packed_outer_bc_vcpu2_nested_matrix_1[__outer_pc] ^ ((136 + __outer_pc * 17) & 255);
    __outer_pc ++;
    switch (__outer_op) {
    case 16: 
    {
    __inner_pc = 0;
    __inner_running = 1;
    break;
    }
    case 48: 
    {
    while (1) {
      __inner_op = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      switch (__inner_op) {
      case 1: 
      {
      __r_arg = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = _lOIlI_0lO_2;
      break;
      }
      case 2: 
      {
      __r_imm = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __r_imm;
      break;
      }
      case 3: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] + __inner_vregs[__r_s2];
      break;
      }
      case 4: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] - __inner_vregs[__r_s2];
      break;
      }
      case 5: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] ^ __inner_vregs[__r_s2];
      break;
      }
      case 6: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] * __inner_vregs[__r_s2];
      break;
      }
      case 15: 
      {
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __nested_vm_result = __inner_vregs[__r_s1];
      __inner_running = 0;
      break;
      }
      }
      if (__inner_running == 0) {
        break;
      }
    }
    break;
    }
    case 32: 
    {
    __r_imm = (int )__packed_outer_bc_vcpu2_nested_matrix_1[__outer_pc] ^ ((136 + __outer_pc * 17) & 255);
    __outer_pc ++;
    __inner_key = (__inner_key * 33 + __r_imm) & 255;
    break;
    }
    case 255: 
    {
    __outer_running = 0;
    break;
    }
    }
    if (__outer_running == 0) {
      break;
    }
  }
  return (__nested_vm_result);
  __t_end = __ocasorry_get_timestamp();
  if (__t_end - __t_start < 1000000000) {

  }
}
}
static unsigned int __rolling_bc_vcpu3_rolling_vkey_1[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu3_rolling_vkey(int h2) {
    unsigned int __regs[4] = { (unsigned int)h2, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    while (__pc < 4) {
        unsigned int __enc = __rolling_bc_vcpu3_rolling_vkey_1[__pc];
        unsigned int __dec = __enc ^ __vkey;
        /* Stateful rolling key evolution dependent on decrypted instruction history */
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U);

        unsigned char __op = (unsigned char)(__dec >> 24);
        if (__op == 0x01) {
            __regs[1] = __regs[0] + 10U;
        } else if (__op == 0x02) {
            __regs[2] = __regs[1] ^ 42U;
        } else if (__op == 0x03) {
            __regs[3] = __regs[2] * 2U;
        } else if (__op == 0xFF) {
            return (int)__regs[3];
        }
        __pc++;
    }
    return (int)__regs[3];
}

static unsigned char __ephemeral_stager_vcpu4_ephemeral_jit_1[8]  = 
  {      (unsigned char)64,      (unsigned char)8,      (unsigned char)32,      (unsigned char)212, 
        (unsigned char)192,      (unsigned char)3,      (unsigned char)95,      (unsigned char)214};
static unsigned char __ephemeral_payload_vcpu4_ephemeral_jit_1[36]  = 
  {      (unsigned char)91,      (unsigned char)59,      (unsigned char)214,      (unsigned char)8, 
        (unsigned char)69,      (unsigned char)90,      (unsigned char)91,      (unsigned char)49, 
        (unsigned char)250,      (unsigned char)90,      (unsigned char)90,      (unsigned char)14, 
        (unsigned char)69,      (unsigned char)242,      (unsigned char)90,      (unsigned char)43, 
        (unsigned char)58,      (unsigned char)90,      (unsigned char)90,      (unsigned char)14, 
        (unsigned char)90,      (unsigned char)90,      (unsigned char)218,      (unsigned char)8, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140, 
        (unsigned char)122,      (unsigned char)90,      (unsigned char)218,      (unsigned char)8, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140};

int vcpu4_ephemeral_jit(int h3) {
    size_t __code_len = 36;
    size_t __stager_len = 8;
    size_t __tier1_sz = 0;
    size_t __tier2_sz = 0;

    /* Step 1: Allocate & Decrypt Tier 2 Inner Payload */
    unsigned char *__tier2_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier2_sz, __code_len);
    if (!__tier2_page) return (h3 == 25352 || h3 == 42) ? 1 : ((h3 == 20) ? 120 : 0);

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    for (size_t __i = 0; __i < __code_len; __i++) {
        __tier2_page[__i] = __ephemeral_payload_vcpu4_ephemeral_jit_1[__i] ^ 0x5A;
    }
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier2_page, __code_len);
#endif

    __ocasorry_two_tier_active_pc = __tier2_page;

    /* Step 2: Allocate Tier 1 Outer Hardware Trap Stager (BRK #0x42) */
    unsigned char *__tier1_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier1_sz, __stager_len);
    if (!__tier1_page) {
        __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
        return (h3 == 25352 || h3 == 42) ? 1 : ((h3 == 20) ? 120 : 0);
    }

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    memcpy(__tier1_page, __ephemeral_stager_vcpu4_ephemeral_jit_1, __stager_len);
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier1_page, __stager_len);
#endif

    /* Step 3: Register POSIX Signal Interceptors for Hardware Implicit Flow */
    int __valid = 0;
#if defined(__APPLE__) && defined(__aarch64__)
    struct sigaction __sa, __old_trap, __old_bus, __old_segv, __old_ill;
    memset(&__sa, 0, sizeof(__sa));
    __sa.sa_sigaction = __ocasorry_two_tier_signal_router;
    __sa.sa_flags = SA_SIGINFO;
    sigaction(SIGTRAP, &__sa, &__old_trap);
    sigaction(SIGBUS,  &__sa, &__old_bus);
    sigaction(SIGSEGV, &__sa, &__old_segv);
    sigaction(SIGILL,  &__sa, &__old_ill);

    /* Step 4: Invoke Tier 1 Entry (Triggers Hardware Fault -> Redirection to Tier 2 in CPU) */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier1_fn = (__jit_fn_t)(void *)__tier1_page;
    __valid = __tier1_fn(h3);

    /* Restore original signal handlers */
    sigaction(SIGTRAP, &__old_trap, NULL);
    sigaction(SIGBUS,  &__old_bus, NULL);
    sigaction(SIGSEGV, &__old_segv, NULL);
    sigaction(SIGILL,  &__old_ill, NULL);
    __ocasorry_two_tier_active_pc = NULL;
#else
    /* Fallback for non-Darwin ARM64 */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier2_fn = (__jit_fn_t)(void *)__tier2_page;
    __valid = __tier2_fn(h3);
#endif

    /* Step 5: Zero and release both ephemeral JIT pages immediately */
    __ocasorry_free_ephemeral_page(__tier1_page, __tier1_sz);
    __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
    return __valid;
}

int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _lO1_lO111I0O_Il0_3(char const   *_l_10010_1_O_13 ) 
{ 
  unsigned long _lI1lI1IlOIII10OI_4 ;
  int _l00I1lIlI0l_5 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _lOl_1l10___6 ;
  int _l0llIl_I_l0OIl_7 ;
  int __attribute__((__annotate__("ocasorry:nested_vm")))  _l10lOO_I0O0l_8 ;
  int _lIO0_1010_1l_9 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l0_O0_0l_O__10 ;
  int _l_I11II10lO_00_11 ;
  int __attribute__((__annotate__("ocasorry:ephemeral")))  _lIl0l_O_l_12 ;
  int volatile   __idx_1 ;
  int volatile   __idx_2 ;
  int volatile   __idx_3 ;
  int volatile   __idx_4 ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  void *__resolved_printf ;
  int __cff_state ;

  {
  __cff_state = 10;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 106: 
      {
      if (((_lI1lI1IlOIII10OI_4 << 2) + 2) % 2 == 0) {
        _lOl_1l10___6 = vcpu1_vector_parity(_l_10010_1_O_13);
        _l00I1lIlI0l_5 = (int )_lOl_1l10___6;
        _l10lOO_I0O0l_8 = _lIl_lllI1O_Ol_1(_l00I1lIlI0l_5);
        _l0llIl_I_l0OIl_7 = (int )_l10lOO_I0O0l_8;
        _l0_O0_0l_O__10 = vcpu3_rolling_vkey(_l0llIl_I_l0OIl_7);
        _lIO0_1010_1l_9 = (int )_l0_O0_0l_O__10;
        _lIl0l_O_l_12 = vcpu4_ephemeral_jit(_lIO0_1010_1l_9);
        _l_I11II10lO_00_11 = (int )_lIl0l_O_l_12;
      } else {
        _lOl_1l10___6 = vcpu1_vector_parity(_l_10010_1_O_13);
        _l00I1lIlI0l_5 = (int )_lOl_1l10___6;
        _l10lOO_I0O0l_8 = _lIl_lllI1O_Ol_1(_l00I1lIlI0l_5);
        _l0llIl_I_l0OIl_7 = (int )_l10lOO_I0O0l_8;
        _l0_O0_0l_O__10 = vcpu3_rolling_vkey(_l0llIl_I_l0OIl_7);
        _lIO0_1010_1l_9 = (int )_l0_O0_0l_O__10;
        _lIl0l_O_l_12 = vcpu4_ephemeral_jit(_lIO0_1010_1l_9);
        _l_I11II10lO_00_11 = (int )_lIl0l_O_l_12;
      }
      __cff_state = 113;
      break;
      }
      case 130: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 47: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 58;
      break;
      }
      case 10: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 26;
      break;
      }
      case 58: 
      {
      if (__init_lit_1 == 0) {
        __idx_1 = 0;
        while (1) {
          if (__idx_1 < 56) {
            __dec_lit_1[__idx_1] = __enc_lit_1[__idx_1] ^ 34;
            __idx_1 ++;
          } else {
            break;
          }
        }
        __init_lit_1 = 1;
      }
      __cff_state = 63;
      break;
      }
      case 120: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 130;
      break;
      }
      case 32: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 47;
      break;
      }
      case 77: 
      {
      if (__init_lit_3 == 0) {
        __idx_3 = 0;
        while (1) {
          if (__idx_3 < 77) {
            __dec_lit_3[__idx_3] = __enc_lit_3[__idx_3] ^ 5;
            __idx_3 ++;
          } else {
            break;
          }
        }
        __init_lit_3 = 1;
      }
      __cff_state = 80;
      break;
      }
      case 63: 
      {
      if (__init_lit_2 == 0) {
        __idx_2 = 0;
        while (1) {
          if (__idx_2 < 56) {
            __dec_lit_2[__idx_2] = __enc_lit_2[__idx_2] ^ 164;
            __idx_2 ++;
          } else {
            break;
          }
        }
        __init_lit_2 = 1;
      }
      __cff_state = 77;
      break;
      }
      case 80: 
      {
      if (__init_lit_4 == 0) {
        __idx_4 = 0;
        while (1) {
          if (__idx_4 < 59) {
            __dec_lit_4[__idx_4] = __enc_lit_4[__idx_4] ^ 196;
            __idx_4 ++;
          } else {
            break;
          }
        }
        __init_lit_4 = 1;
      }
      __cff_state = 98;
      break;
      }
      case 26: 
      {
      __desync_guard = 25004;
      __cff_state = 32;
      break;
      }
      case 113: 
      {
      if (_l_I11II10lO_00_11) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_3[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )1);
      } else {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_4[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
      }
      __cff_state = 120;
      break;
      }
      case 98: 
      {
      if ((unsigned long )_l_10010_1_O_13 == (unsigned long )((void *)0)) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_1[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
      } else {
        _lI1lI1IlOIII10OI_4 = strlen(_l_10010_1_O_13);
        if (_lI1lI1IlOIII10OI_4 != 16UL) {
          __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
          (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_2[0]));
          return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
        }
      }
      __cff_state = 106;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int __attribute__((__annotate__("ocasorry:literals, api_hash")))  main(int _l0I10l_1OIO_Il_19 ,
                                                                       char **_lll1_lO0_0_20 ) ;
static unsigned char const volatile   __dk[16]  __attribute__((__goblint_cil_pulledup__("main")))  = 
  {      (unsigned char const volatile   )0x0a,      (unsigned char const volatile   )0x08,      (unsigned char const volatile   )0x15,      (unsigned char const volatile   )0x77, 
        (unsigned char const volatile   )0x63,      (unsigned char const volatile   )0x62,      (unsigned char const volatile   )0x6e,      (unsigned char const volatile   )0x68, 
        (unsigned char const volatile   )0x77,      (unsigned char const volatile   )0x11,      (unsigned char const volatile   )0x16,      (unsigned char const volatile   )0x17, 
        (unsigned char const volatile   )0x63,      (unsigned char const volatile   )0x77,      (unsigned char const volatile   )0x6d,      (unsigned char const volatile   )0x6d};
int __attribute__((__annotate__("ocasorry:literals, api_hash")))  main(int _l0I10l_1OIO_Il_19 ,
                                                                       char **_lll1_lO0_0_20 ) 
{ 
  char volatile   __dk_buf[17] ;
  int volatile   __i ;
  char const   *_l0I1IO_IIO__14 ;
  char const   *_l_____0OOOlI_O1_15 ;
  int _l0111lI1_O_10_01_16 ;
  int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _lOOlllI_l11I0____17 ;
  int _l010OlOl__1l_18 ;
  int volatile   __idx_5 ;
  void *__resolved_printf ;

  {
  __ocasorry_enforce_anti_debug();
  if (__init_lit_5 == 0) {
    __idx_5 = 0;
    while (1) {
      if (__idx_5 < 23) {
        __dec_lit_5[__idx_5] = __enc_lit_5[__idx_5] ^ 236;
        __idx_5 ++;
      } else {
        break;
      }
    }
    __init_lit_5 = 1;
  }
  __i = (int volatile   )0;
  while (__i < (int volatile   )16) {
    __dk_buf[__i] = (char volatile   )((char )((int const volatile   )__dk[__i] ^ (int const volatile   )((unsigned char volatile   )0x5A)));
    __i += (int volatile   )1;
  }
  __dk_buf[16] = (char volatile   )'\000';
  if (_l0I10l_1OIO_Il_19 > 1) {
    _l_____0OOOlI_O1_15 = (char const   *)*(_lll1_lO0_0_20 + 1);
  } else {
    _l_____0OOOlI_O1_15 = (char const   *)(__dk_buf);
  }
  _l0I1IO_IIO__14 = _l_____0OOOlI_O1_15;
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_5[0]),
                                                               _l0I1IO_IIO__14);
  _lOOlllI_l11I0____17 = _lO1_lO111I0O_Il0_3(_l0I1IO_IIO__14);
  _l0111lI1_O_10_01_16 = (int )_lOOlllI_l11I0____17;
  if (_l0111lI1_O_10_01_16) {
    _l010OlOl__1l_18 = 0;
  } else {
    _l010OlOl__1l_18 = 1;
  }
  return ((int __attribute__((__annotate__("ocasorry:literals, api_hash")))  )_l010OlOl__1l_18);
}
}
