/* Generated by Goblint-CIL v. 2.1.1 */
/* print_CIL_Input is false */


static volatile int __ocasorry_runtime_initialized = 0;

__attribute__((constructor(101)))
static void __ocasorry_early_pre_main_stager(void) {
    if (!__ocasorry_runtime_initialized) {
        __ocasorry_runtime_initialized = 1;
#ifdef __APPLE__
        /* Early anti-debug and environment verification */
#endif
    }
}


#include <dlfcn.h>
#include <stdint.h>
#include <string.h>

/* Hash-only resolver: no plaintext symbol name ever leaves the binary in call sites.
   The resolver scans a static candidate table keyed by CRC32, resolving purely by hash. */
static uint32_t __ocasorry_calc_crc32(const char *s) {
    uint32_t crc = 0xFFFFFFFF;
    while (*s) {
        crc ^= (uint32_t)(unsigned char)(*s++);
        for (int i = 0; i < 8; i++) {
            crc = (crc >> 1) ^ ((crc & 1) ? 0xEDB88320 : 0);
        }
    }
    return ~crc;
}

static void *__ocasorry_resolve_symbol_hash(uint32_t target_hash) {
    /* Candidate symbol names stored as XOR-obfuscated byte arrays (key=0xA5).
       No plaintext strings appear in __cstring / __data sections.
       Sentinel 0xA5 = (0x00 ^ 0xA5) marks end of each name. */
    static const unsigned char __c0[] = {0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5}; /* printf */
    static const unsigned char __c1[] = {0xd5,0xd0,0xd1,0xd6,0xA5};           /* puts */
    static const unsigned char __c2[] = {0xc0,0xdd,0xcc,0xd1,0xA5};           /* exit */
    static const unsigned char __c3[] = {0xc8,0xc4,0xc9,0xc9,0xca,0xc6,0xA5};/* malloc */
    static const unsigned char __c4[] = {0xc3,0xd7,0xc0,0xc0,0xA5};          /* free */
    static const unsigned char __c5[] = {0xc8,0xc0,0xc8,0xd6,0xc0,0xd1,0xA5};/* memset */
    static const unsigned char __c6[] = {0xc8,0xc0,0xc8,0xc6,0xd5,0xdc,0xA5};/* memcpy */
    static const unsigned char __c7[] = {0xd6,0xd1,0xd7,0xc9,0xc0,0xcb,0xA5};/* strlen */
    static const unsigned char __c8[] = {0xc3,0xca,0xd5,0xc0,0xcb,0xA5};     /* fopen */
    static const unsigned char __c9[] = {0xd6,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};       /* sprintf */
    static const unsigned char __ca[] = {0xd6,0xcb,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};  /* snprintf */
    static const unsigned char __cb[] = {0xc4,0xc7,0xca,0xd7,0xd1,0xA5};     /* abort */

    static const unsigned char * const __enc[] = {
        __c0, __c1, __c2, __c3, __c4, __c5, __c6, __c7, __c8, __c9, __ca, __cb, 0
    };

    for (int i = 0; __enc[i] != 0; i++) {
        /* Decode name on the stack at runtime — never stored as plaintext */
        char name[32];
        int j = 0;
        while (__enc[i][j] != 0xA5 && j < 31) {
            name[j] = (char)(__enc[i][j] ^ 0xA5);
            j++;
        }
        name[j] = '\0';

        if (__ocasorry_calc_crc32(name) == target_hash) {
#ifdef RTLD_DEFAULT
            void *sym = dlsym(RTLD_DEFAULT, name);
#else
            void *sym = dlsym((void*)-2, name);
#endif
            if (sym) return sym;
            void *h = dlopen(0, 1);
            if (h) return dlsym(h, name);
        }
    }
    return 0;
}


#include <time.h>
#ifdef __APPLE__
#include <mach/mach_time.h>
static unsigned long long __ocasorry_get_timestamp(void) {
    return (unsigned long long)mach_absolute_time();
}
#else
static unsigned long long __ocasorry_get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}
#endif


#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <dlfcn.h>
typedef int (*__ocasorry_ptrace_t)(int request, pid_t pid, void *addr, int data);

static int __ocasorry_check_debugger_present(void) {
    int mib[4];
    struct kinfo_proc info;
    size_t size = sizeof(info);
    info.kp_proc.p_flag = 0;
    mib[0] = 1; /* CTL_KERN */
    mib[1] = 14; /* KERN_PROC */
    mib[2] = 1; /* KERN_PROC_PID */
    mib[3] = getpid();
    if (sysctl(mib, 4, &info, &size, 0, 0) == 0) {
        if ((info.kp_proc.p_flag & 0x00000800) != 0) { /* P_TRACED */
            return 1;
        }
    }
    return 0;
}

static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        void *h = dlopen(0, 0);
        if (h) {
            __ocasorry_ptrace_t ptrace_fn = (__ocasorry_ptrace_t)dlsym(h, "ptrace");
            if (ptrace_fn) {
                ptrace_fn(31, 0, 0, 0); /* PT_DENY_ATTACH */
            }
        }
        exit(137); /* Fallback exit if ptrace returns */
    }
}
#else
static int __ocasorry_check_debugger_present(void) {
    return 0;
}
static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        exit(137);
    }
}
#endif


#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE
#endif
#include <sys/mman.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <signal.h>
#ifdef __APPLE__
#include <pthread.h>
#include <libkern/OSCacheControl.h>
#include <sys/ucontext.h>
#endif

static void *__ocasorry_two_tier_active_pc = NULL;

#if defined(__APPLE__) && defined(__aarch64__)
static void __ocasorry_two_tier_signal_router(int sig, siginfo_t *info, void *context) {
    (void)sig; (void)info;
    ucontext_t *uc = (ucontext_t *)context;
    if (__ocasorry_two_tier_active_pc != NULL) {
        /* IMPLICIT FLOW: Redirect Program Counter in CPU hardware context */
        uc->uc_mcontext->__ss.__pc = (uint64_t)__ocasorry_two_tier_active_pc;
    }
}
#endif

static void *__ocasorry_alloc_ephemeral_page(size_t *out_sz, size_t min_sz) {
    size_t page_sz = (size_t)sysconf(_SC_PAGESIZE);
    if (page_sz < 4096) page_sz = 4096;
    size_t alloc_sz = (min_sz + page_sz - 1) & ~(page_sz - 1);
    *out_sz = alloc_sz;
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0);
#elif defined(__aarch64__) || defined(__arm64__)
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#else
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#endif
    if (ptr == MAP_FAILED) return NULL;
    return ptr;
}

static void __ocasorry_free_ephemeral_page(void *ptr, size_t sz) {
    if (ptr && ptr != MAP_FAILED) {
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
        pthread_jit_write_protect_np(0); /* Switch to write mode before memory zeroing */
#endif
        memset(ptr, 0, sz); /* Overwrite memory to prevent dump recovery */
        munmap(ptr, sz);
    }
}

static unsigned char __packed_inner_bc_vcpu2_nested_matrix_1[12]  = 
  {      (unsigned char)185,      (unsigned char)215,      (unsigned char)246,      (unsigned char)23, 
        (unsigned char)33,      (unsigned char)82,      (unsigned char)113,      (unsigned char)145, 
        (unsigned char)176,      (unsigned char)206,      (unsigned char)225,      (unsigned char)13};
static unsigned char __packed_outer_bc_vcpu2_nested_matrix_1[5]  = {      (unsigned char)104,      (unsigned char)185,      (unsigned char)186,      (unsigned char)180, 
        (unsigned char)67};
static unsigned int __visa_program_vcpu1_vector_parity_1[48]  = 
  {      4255839026U,      3504292579U,      1668850048U,      2893286833U, 
        3981272286U,      4042085119U,      1903273900U,      2377279437U, 
        514387962U,      1660536091U,      2706288696U,      2170816745U, 
        43382902U,      453666471U,      515679172U,      3899762149U, 
        2856643346U,      3812218931U,      2202154720U,      3202418561U, 
        753497646U,      1380665823U,      2066299388U,      4200021677U, 
        1929601866U,      2719057899U,      1634281624U,      2139953593U, 
        248009302U,      2311340407U,      618379028U,      3473803333U, 
        2993813602U,      4068831891U,      3273498928U,      3686437841U, 
        1506700814U,      475486511U,      795235804U,      619349501U, 
        1235187482U,      1942046923U,      2888874856U,      4180324233U, 
        1154442278U,      2281590983U,      1550298484U,      2937461525U};
static int __visa_engine_ready ;
static char volatile   __enc_lit_1[56]  = 
  {      88,      46,      94,      35, 
        74,      109,      117,      98, 
        111,      106,      103,      35, 
        104,      102,      122,      35, 
        101,      108,      113,      110, 
        98,      119,      57,      35, 
        78,      118,      112,      119, 
        35,      97,      102,      35, 
        102,      123,      98,      96, 
        119,      111,      122,      35, 
        50,      53,      35,      96, 
        107,      98,      113,      98, 
        96,      119,      102,      113, 
        112,      45,      9,      3};
static char volatile   __dec_lit_1[56]  ;
static int volatile   __init_lit_1  =    0;
static char volatile   __enc_lit_2[56]  = 
  {      113,      7,      119,      10, 
        99,      68,      92,      75, 
        70,      67,      78,      10, 
        65,      79,      83,      10, 
        76,      69,      88,      71, 
        75,      94,      16,      10, 
        103,      95,      89,      94, 
        10,      72,      79,      10, 
        79,      82,      75,      73, 
        94,      70,      83,      10, 
        27,      28,      10,      73, 
        66,      75,      88,      75, 
        73,      94,      79,      88, 
        89,      4,      32,      42};
static char volatile   __dec_lit_2[56]  ;
static int volatile   __init_lit_2  =    0;
static char volatile   __enc_lit_3[77]  = 
  {      251,      139,      253,      128, 
        243,      245,      227,      227, 
        229,      243,      243,      154, 
        128,      236,      201,      195, 
        197,      206,      211,      197, 
        128,      203,      197,      217, 
        128,      201,      211,      128, 
        246,      225,      236,      233, 
        228,      129,      128,      148, 
        141,      246,      227,      240, 
        245,      128,      230,      197, 
        196,      197,      210,      193, 
        212,      197,      196,      128, 
        225,      213,      212,      200, 
        207,      210,      201,      218, 
        193,      212,      201,      207, 
        206,      128,      245,      206, 
        204,      207,      195,      203, 
        197,      196,      142,      170, 
        160};
static char volatile   __dec_lit_3[77]  ;
static int volatile   __init_lit_3  =    0;
static char volatile   __enc_lit_4[59]  = 
  {      143,      249,      137,      244, 
        146,      149,      157,      152, 
        145,      144,      238,      244, 
        157,      186,      162,      181, 
        184,      189,      176,      244, 
        184,      189,      183,      177, 
        186,      167,      177,      244, 
        191,      177,      173,      245, 
        244,      224,      249,      130, 
        151,      132,      129,      244, 
        151,      181,      167,      183, 
        181,      176,      177,      244, 
        134,      177,      190,      177, 
        183,      160,      177,      176, 
        250,      222,      212};
static char volatile   __dec_lit_4[59]  ;
static int volatile   __init_lit_4  =    0;
static char volatile   __enc_lit_5[23]  = 
  {      204,      189,      202,      183, 
        193,      242,      229,      254, 
        241,      238,      254,      249, 
        240,      183,      220,      242, 
        238,      173,      183,      178, 
        228,      157,      151};
static char volatile   __dec_lit_5[23]  ;
static int volatile   __init_lit_5  =    0;
extern int printf(char const   *format  , ...) ;
extern unsigned long strlen(char const   *s ) ;

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

__attribute__((visibility("default")))
int vcpu1_vector_parity(const char * license_key) {
    unsigned long long __vregs[64];
    #define __VREG_ROT(r) (((unsigned int)(r) + 61U) & 0x3FU)
    #define __VREG_MASK(r) (0x67662c361ec3ULL + ((unsigned long long)__VREG_ROT(r) * 0x9e3779b97f4a7c15ULL))
    #define __VREG_GET(r) (__vregs[__VREG_ROT(r)] ^ __VREG_MASK(r))
    #define __VREG_SET(r, val) do { __vregs[__VREG_ROT(r)] = ((unsigned long long)(val)) ^ __VREG_MASK(r); } while(0)

    for (int __i = 0; __i < 64; __i++) {
        __vregs[__i] = (0x67662c361ec3ULL + ((unsigned long long)__i * 0x9e3779b97f4a7c15ULL));
    }

    /* Vector 2: Dual Shadow Stack (VSP_data + VSP_ctrl) */
    unsigned long long __vstack_data[64] = {0};
    unsigned long long __vstack_ctrl[32] = {0};
    unsigned int __vsp_d = 0;
    unsigned int __vsp_c = 0;
    unsigned long long __vm_state_acc = 0x9E3779B97F4A7C15ULL;

    /* Vector 8: Ephemeral Self-Scrubbing Bytecode Scratchpad */
    unsigned int __vbc_live[48];
    memcpy(__vbc_live, __visa_program_vcpu1_vector_parity_1, sizeof(__vbc_live));

    const char *__ptr_ctx = (const char *)license_key;
    const unsigned long long __cfi_canary = 0x67662c361ec3ULL ^ ((uintptr_t)__ptr_ctx * 0x9E3779B97F4A7C15ULL);

    /* Push CFI Canary into Shadow Control Stack */
    __vstack_ctrl[__vsp_c++] = __cfi_canary ^ 0x409ac756b5b4c6abULL;

    __VREG_SET(2, (unsigned long long)(uintptr_t)license_key);
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x15] = &&__h_vadd,
        [0x2C] = &&__h_vsub,
        [0x30] = &&__h_vmul,
        [0x5] = &&__h_vxor,
        [0x16] = &&__h_vand,
        [0x3F] = &&__h_vor,
        [0x2F] = &&__h_vsll,
        [0x2B] = &&__h_vsrl,
        [0x3C] = &&__h_vli,
        [0xC] = &&__h_vmv,
        [0x35] = &&__h_vle8,
        [0x27] = &&__h_vse8,
        [0x3A] = &&__h_vret,
        [0x19] = &&__h_vbge,
        [0x29] = &&__h_vj,
        /* Vector 9: Polymorphic Multi-Alias Handler Entries */
        [0x2] = &&__h_vadd_alt1,
        [0x33] = &&__h_vadd_alt2,
        [0x0] = &&__h_vsub_alt1,
        [0x10] = &&__h_vsub_alt2,
        [0x23] = &&__h_vxor_alt1,
        [0x3D] = &&__h_vxor_alt2,
        [0x37] = &&__h_vand_alt1,
        [0x8] = &&__h_vor_alt1,
        [0x1C] = &&__h_vmul_alt1,
        [0x26] = &&__h_vmv_alt1,
        [0x36] = &&__h_vli_alt1
    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 48) goto __h_vret; \
        unsigned int __slot = ((__pc * 5U) + 43U) % 48U; \
        __raw = __vbc_live[__slot]; \
        __key = 0x8566e5eU ^ (__pc * 0x45d9f3bU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        __vm_state_acc = (__vm_state_acc ^ (__vd + __funct6)) * 0x517CC1B727220A95ULL; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA ADD: (a ^ b) + ((a & b) << 1) */
    __VREG_SET(__vd, (__a ^ __b) + ((__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vadd_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Alt1 MBA ADD: (a | b) + (a & b) */
    __VREG_SET(__vd, (__a | __b) + (__a & __b));
    __VISA_DISPATCH();
}

__h_vadd_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Alt2 MBA ADD: (2 * (a | b)) - (a ^ b) */
    __VREG_SET(__vd, ((__a | __b) << 1) - (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vsub: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA SUB: (a ^ b) - ((~a & b) << 1) */
    __VREG_SET(__vd, (__a ^ __b) - ((~__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vsub_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Alt1 MBA SUB: (a & ~b) - (~a & b) */
    __VREG_SET(__vd, (__a & ~__b) - (~__a & __b));
    __VISA_DISPATCH();
}

__h_vsub_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Alt2 MBA SUB: (a | ~b) - ~b - (a & b) */
    __VREG_SET(__vd, (__a | ~__b) - ~__b - (__a & __b));
    __VISA_DISPATCH();
}

__h_vmul: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (unsigned long long)(__a * __b));
    __VISA_DISPATCH();
}

__h_vmul_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (unsigned long long)((__a ^ 0) * (__b ^ 0)));
    __VISA_DISPATCH();
}

__h_vxor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA XOR: (a | b) - (a & b) */
    __VREG_SET(__vd, (__a | __b) - (__a & __b));
    __VISA_DISPATCH();
}

__h_vxor_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Alt1 MBA XOR: (~a & b) + (a & ~b) */
    __VREG_SET(__vd, (~__a & __b) + (__a & ~__b));
    __VISA_DISPATCH();
}

__h_vxor_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Alt2 MBA XOR: (a + b) - ((a & b) << 1) */
    __VREG_SET(__vd, (__a + __b) - ((__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vand: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA AND: (a | b) - (a ^ b) */
    __VREG_SET(__vd, (__a | __b) - (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vand_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Alt1 MBA AND: (a + b) - (a | b) */
    __VREG_SET(__vd, (__a + __b) - (__a | __b));
    __VISA_DISPATCH();
}

__h_vor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA OR: (a & b) + (a ^ b) */
    __VREG_SET(__vd, (__a & __b) + (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vor_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Alt1 MBA OR: (a + b) - (a & b) */
    __VREG_SET(__vd, (__a + __b) - (__a & __b));
    __VISA_DISPATCH();
}

__h_vsll: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, __a << __sh);
    __VISA_DISPATCH();
}

__h_vsrl: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, (unsigned long long)(__a >> __sh));
    __VISA_DISPATCH();
}

__h_vli:
    __VREG_SET(__vd, (unsigned long long)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();

__h_vli_alt1:
    __VREG_SET(__vd, (unsigned long long)((((__vm << 3) | __funct3) << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();

__h_vmv:
    __VREG_SET(__vd, __VREG_GET(__vs1));
    __VISA_DISPATCH();

__h_vmv_alt1:
    __VREG_SET(__vd, __VREG_GET(__vs1) ^ 0);
    __VISA_DISPATCH();

__h_vle8:
    if (__ptr_ctx) {
        __VREG_SET(__vd, (unsigned long long)((const unsigned char *)__ptr_ctx)[__VREG_GET(__vs2)]);
    }
    __VISA_DISPATCH();

__h_vse8:
    if (__vsp_d < 63) {
        __vstack_data[__vsp_d++] = __VREG_GET(__vs1);
    }
    __VISA_DISPATCH();

__h_vbge:
    if (__VREG_GET(__vs1) >= __VREG_GET(__vs2)) {
        __pc = (46);
    }
    __VISA_DISPATCH();

__h_vj:
    __pc = ((__inst >> 7) & 0x7FFFF);
    __VISA_DISPATCH();

__h_default:
    __VISA_DISPATCH();

__h_vret: ;
    /* Verify Shadow Control Stack CFI Canary */
    if (__vsp_c == 0 || ((__vstack_ctrl[--__vsp_c] ^ 0x409ac756b5b4c6abULL) != __cfi_canary)) {
        __builtin_trap();
    }
    unsigned long long __res_val = __VREG_GET(0);
    __builtin_memset(__vregs, 0, sizeof(__vregs));
    __builtin_memset(__vbc_live, 0, sizeof(__vbc_live));
    __builtin_memset(__vstack_data, 0, sizeof(__vstack_data));
    __builtin_memset(__vstack_ctrl, 0, sizeof(__vstack_ctrl));
    return (int)__res_val;
}

int __attribute__((__annotate__("ocasorry:nested_vm")))  _l0O__0O__I__II_1(int _lOII0l_O0l1_2 ) 
{ 
  int __outer_pc ;
  int __outer_running ;
  int __outer_op ;
  int __inner_pc ;
  int __inner_key ;
  int __inner_running ;
  int __inner_op ;
  int __inner_vregs[8] ;
  int __nested_vm_result ;
  int __r_dst ;
  int __r_s1 ;
  int __r_s2 ;
  int __r_imm ;
  int __r_arg ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;

  {
  __t_start = __ocasorry_get_timestamp();
  __desync_guard = 55385;
  {
  if ((__desync_guard & ~ __desync_guard) != 0) {
    return (0);
  }
  }
  __ocasorry_enforce_anti_debug();
  __outer_pc = 0;
  __outer_running = 1;
  __inner_key = 184;
  __nested_vm_result = 0;
  while (1) {
    __outer_op = (int )__packed_outer_bc_vcpu2_nested_matrix_1[__outer_pc] ^ ((120 + __outer_pc * 17) & 255);
    __outer_pc ++;
    switch (__outer_op) {
    case 16: 
    {
    __inner_pc = 0;
    __inner_running = 1;
    break;
    }
    case 48: 
    {
    while (1) {
      __inner_op = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      switch (__inner_op) {
      case 1: 
      {
      __r_arg = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = _lOII0l_O0l1_2;
      break;
      }
      case 2: 
      {
      __r_imm = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __r_imm;
      break;
      }
      case 3: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] + __inner_vregs[__r_s2];
      break;
      }
      case 4: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] - __inner_vregs[__r_s2];
      break;
      }
      case 5: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] ^ __inner_vregs[__r_s2];
      break;
      }
      case 6: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] * __inner_vregs[__r_s2];
      break;
      }
      case 15: 
      {
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __nested_vm_result = __inner_vregs[__r_s1];
      __inner_running = 0;
      break;
      }
      }
      if (__inner_running == 0) {
        break;
      }
    }
    break;
    }
    case 32: 
    {
    __r_imm = (int )__packed_outer_bc_vcpu2_nested_matrix_1[__outer_pc] ^ ((120 + __outer_pc * 17) & 255);
    __outer_pc ++;
    __inner_key = (__inner_key * 33 + __r_imm) & 255;
    break;
    }
    case 255: 
    {
    __outer_running = 0;
    break;
    }
    }
    if (__outer_running == 0) {
      break;
    }
  }
  return (__nested_vm_result);
  __t_end = __ocasorry_get_timestamp();
  if (__t_end - __t_start < 1000000000) {

  }
}
}
static unsigned int __rolling_bc_vcpu3_rolling_vkey_1[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu3_rolling_vkey(int h2) {
    unsigned int __regs[4] = { (unsigned int)h2, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu3_rolling_vkey_1[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt: ;
    int __ret_val = (int)__regs[3];
    __builtin_memset(__regs, 0, sizeof(__regs));
    return __ret_val;
}

static unsigned char __ephemeral_stager_vcpu4_ephemeral_jit_1[8]  = 
  {      (unsigned char)64,      (unsigned char)8,      (unsigned char)32,      (unsigned char)212, 
        (unsigned char)192,      (unsigned char)3,      (unsigned char)95,      (unsigned char)214};
static unsigned char __ephemeral_payload_vcpu4_ephemeral_jit_1[36]  = 
  {      (unsigned char)91,      (unsigned char)59,      (unsigned char)214,      (unsigned char)8, 
        (unsigned char)69,      (unsigned char)90,      (unsigned char)91,      (unsigned char)49, 
        (unsigned char)250,      (unsigned char)90,      (unsigned char)90,      (unsigned char)14, 
        (unsigned char)69,      (unsigned char)242,      (unsigned char)90,      (unsigned char)43, 
        (unsigned char)58,      (unsigned char)90,      (unsigned char)90,      (unsigned char)14, 
        (unsigned char)90,      (unsigned char)90,      (unsigned char)218,      (unsigned char)8, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140, 
        (unsigned char)122,      (unsigned char)90,      (unsigned char)218,      (unsigned char)8, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140};

int vcpu4_ephemeral_jit(int h3) {
    size_t __code_len = 36;
    size_t __stager_len = 8;
    size_t __tier1_sz = 0;
    size_t __tier2_sz = 0;

    /* Step 1: Allocate & Decrypt Tier 2 Inner Payload */
    unsigned char *__tier2_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier2_sz, __code_len);
    if (!__tier2_page) return (h3 == 25352 || h3 == 42) ? 1 : ((h3 == 20) ? 120 : 0);

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    for (size_t __i = 0; __i < __code_len; __i++) {
        __tier2_page[__i] = __ephemeral_payload_vcpu4_ephemeral_jit_1[__i] ^ 0x5A;
    }
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier2_page, __code_len);
#endif

    __ocasorry_two_tier_active_pc = __tier2_page;

    /* Step 2: Allocate Tier 1 Outer Hardware Trap Stager (BRK #0x42) */
    unsigned char *__tier1_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier1_sz, __stager_len);
    if (!__tier1_page) {
        __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
        return (h3 == 25352 || h3 == 42) ? 1 : ((h3 == 20) ? 120 : 0);
    }

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    memcpy(__tier1_page, __ephemeral_stager_vcpu4_ephemeral_jit_1, __stager_len);
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier1_page, __stager_len);
#endif

    /* Step 3: Register POSIX Signal Interceptors for Hardware Implicit Flow */
    int __valid = 0;
#if defined(__APPLE__) && defined(__aarch64__)
    struct sigaction __sa, __old_trap, __old_bus, __old_segv, __old_ill;
    memset(&__sa, 0, sizeof(__sa));
    __sa.sa_sigaction = __ocasorry_two_tier_signal_router;
    __sa.sa_flags = SA_SIGINFO;
    sigaction(SIGTRAP, &__sa, &__old_trap);
    sigaction(SIGBUS,  &__sa, &__old_bus);
    sigaction(SIGSEGV, &__sa, &__old_segv);
    sigaction(SIGILL,  &__sa, &__old_ill);

    /* Step 4: Invoke Tier 1 Entry (Triggers Hardware Fault -> Redirection to Tier 2 in CPU) */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier1_fn = (__jit_fn_t)(void *)__tier1_page;
    __valid = __tier1_fn(h3);

    /* Restore original signal handlers */
    sigaction(SIGTRAP, &__old_trap, NULL);
    sigaction(SIGBUS,  &__old_bus, NULL);
    sigaction(SIGSEGV, &__old_segv, NULL);
    sigaction(SIGILL,  &__old_ill, NULL);
    __ocasorry_two_tier_active_pc = NULL;
#else
    /* Fallback for non-Darwin ARM64 */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier2_fn = (__jit_fn_t)(void *)__tier2_page;
    __valid = __tier2_fn(h3);
#endif

    /* Step 5: Zero and release both ephemeral JIT pages immediately */
    __ocasorry_free_ephemeral_page(__tier1_page, __tier1_sz);
    __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
    return __valid;
}

int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _lIlI1l01__3(char const   *_llIl0I_1O1_13 ) 
{ 
  unsigned long _l0l_I_I1lO_OIOII_4 ;
  int _l0_00II110I0_0___5 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _l0111_1_lO1O__1_6 ;
  int _lO_OOIO_IO0l_7 ;
  int __attribute__((__annotate__("ocasorry:nested_vm")))  _ll0_1I0I_l00IOl_8 ;
  int _l__1_O0I1l_11O1l_9 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l111_O11O0OO_10 ;
  int _l0IlOI0_l__II_11 ;
  int __attribute__((__annotate__("ocasorry:ephemeral")))  _lII__0_0I_100II_12 ;
  int volatile   __idx_1 ;
  int volatile   __idx_2 ;
  int volatile   __idx_3 ;
  int volatile   __idx_4 ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  void *__resolved_printf ;
  int __cff_state ;

  {
  __cff_state = 11;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 96: 
      {
      if ((unsigned long )_llIl0I_1O1_13 == (unsigned long )((void *)0)) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_1[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
      } else {
        _l0l_I_I1lO_OIOII_4 = strlen(_llIl0I_1O1_13);
        if (_l0l_I_I1lO_OIOII_4 != 16UL) {
          __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
          (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_2[0]));
          return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
        }
      }
      __cff_state = 104;
      break;
      }
      case 126: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 134;
      break;
      }
      case 11: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 20;
      break;
      }
      case 87: 
      {
      if (__init_lit_4 == 0) {
        __idx_4 = 0;
        while (1) {
          if (__idx_4 < 59) {
            __dec_lit_4[__idx_4] = __enc_lit_4[__idx_4] ^ 212;
            __idx_4 ++;
          } else {
            break;
          }
        }
        __init_lit_4 = 1;
      }
      __cff_state = 96;
      break;
      }
      case 118: 
      {
      if (_l0IlOI0_l__II_11) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_3[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )1);
      } else {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_4[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
      }
      __cff_state = 126;
      break;
      }
      case 72: 
      {
      if (__init_lit_3 == 0) {
        __idx_3 = 0;
        while (1) {
          if (__idx_3 < 77) {
            __dec_lit_3[__idx_3] = __enc_lit_3[__idx_3] ^ 160;
            __idx_3 ++;
          } else {
            break;
          }
        }
        __init_lit_3 = 1;
      }
      __cff_state = 87;
      break;
      }
      case 20: 
      {
      __desync_guard = 35295;
      __cff_state = 33;
      break;
      }
      case 104: 
      {
      if ((_l0l_I_I1lO_OIOII_4 | 1) % 2 != 0) {
        _l0111_1_lO1O__1_6 = vcpu1_vector_parity(_llIl0I_1O1_13);
        _l0_00II110I0_0___5 = (int )_l0111_1_lO1O__1_6;
        _ll0_1I0I_l00IOl_8 = _l0O__0O__I__II_1(_l0_00II110I0_0___5);
        _lO_OOIO_IO0l_7 = (int )_ll0_1I0I_l00IOl_8;
        _l111_O11O0OO_10 = vcpu3_rolling_vkey(_lO_OOIO_IO0l_7);
        _l__1_O0I1l_11O1l_9 = (int )_l111_O11O0OO_10;
        _lII__0_0I_100II_12 = vcpu4_ephemeral_jit(_l__1_O0I1l_11O1l_9);
        _l0IlOI0_l__II_11 = (int )_lII__0_0I_100II_12;
      } else {
        _l0111_1_lO1O__1_6 = vcpu1_vector_parity(_llIl0I_1O1_13);
        _l0_00II110I0_0___5 = (int )_l0111_1_lO1O__1_6;
        _ll0_1I0I_l00IOl_8 = _l0O__0O__I__II_1(_l0_00II110I0_0___5);
        _lO_OOIO_IO0l_7 = (int )_ll0_1I0I_l00IOl_8;
        _l111_O11O0OO_10 = vcpu3_rolling_vkey(_lO_OOIO_IO0l_7);
        _l__1_O0I1l_11O1l_9 = (int )_l111_O11O0OO_10;
        _lII__0_0I_100II_12 = vcpu4_ephemeral_jit(_l__1_O0I1l_11O1l_9);
        _l0IlOI0_l__II_11 = (int )_lII__0_0I_100II_12;
      }
      __cff_state = 118;
      break;
      }
      case 134: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 33: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 41;
      break;
      }
      case 41: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 50;
      break;
      }
      case 63: 
      {
      if (__init_lit_2 == 0) {
        __idx_2 = 0;
        while (1) {
          if (__idx_2 < 56) {
            __dec_lit_2[__idx_2] = __enc_lit_2[__idx_2] ^ 42;
            __idx_2 ++;
          } else {
            break;
          }
        }
        __init_lit_2 = 1;
      }
      __cff_state = 72;
      break;
      }
      case 50: 
      {
      if (__init_lit_1 == 0) {
        __idx_1 = 0;
        while (1) {
          if (__idx_1 < 56) {
            __dec_lit_1[__idx_1] = __enc_lit_1[__idx_1] ^ 3;
            __idx_1 ++;
          } else {
            break;
          }
        }
        __init_lit_1 = 1;
      }
      __cff_state = 63;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int __attribute__((__annotate__("ocasorry:literals, api_hash")))  main(int _lOII__l110___IO_19 ,
                                                                       char **_l1O0IlIOI_20 ) ;
static unsigned char const volatile   __dk[16]  __attribute__((__goblint_cil_pulledup__("main")))  = 
  {      (unsigned char const volatile   )0x0a,      (unsigned char const volatile   )0x08,      (unsigned char const volatile   )0x15,      (unsigned char const volatile   )0x77, 
        (unsigned char const volatile   )0x63,      (unsigned char const volatile   )0x62,      (unsigned char const volatile   )0x6e,      (unsigned char const volatile   )0x68, 
        (unsigned char const volatile   )0x77,      (unsigned char const volatile   )0x11,      (unsigned char const volatile   )0x16,      (unsigned char const volatile   )0x17, 
        (unsigned char const volatile   )0x63,      (unsigned char const volatile   )0x77,      (unsigned char const volatile   )0x6d,      (unsigned char const volatile   )0x6d};
int __attribute__((__annotate__("ocasorry:literals, api_hash")))  main(int _lOII__l110___IO_19 ,
                                                                       char **_l1O0IlIOI_20 ) 
{ 
  char volatile   __dk_buf[17] ;
  int volatile   __i ;
  char const   *_l_lO0l0I1_14 ;
  char const   *_l_1l_0ll0lI_15 ;
  int _l1_OlOO100_II_16 ;
  int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _l____000O_17 ;
  int _lIOI___O0_18 ;
  int volatile   __idx_5 ;
  void *__resolved_printf ;

  {
  __ocasorry_enforce_anti_debug();
  if (__init_lit_5 == 0) {
    __idx_5 = 0;
    while (1) {
      if (__idx_5 < 23) {
        __dec_lit_5[__idx_5] = __enc_lit_5[__idx_5] ^ 151;
        __idx_5 ++;
      } else {
        break;
      }
    }
    __init_lit_5 = 1;
  }
  __i = (int volatile   )0;
  while (__i < (int volatile   )16) {
    __dk_buf[__i] = (char volatile   )((char )((int const volatile   )__dk[__i] ^ (int const volatile   )((unsigned char volatile   )0x5A)));
    __i += (int volatile   )1;
  }
  __dk_buf[16] = (char volatile   )'\000';
  if (_lOII__l110___IO_19 > 1) {
    _l_1l_0ll0lI_15 = (char const   *)*(_l1O0IlIOI_20 + 1);
  } else {
    _l_1l_0ll0lI_15 = (char const   *)(__dk_buf);
  }
  _l_lO0l0I1_14 = _l_1l_0ll0lI_15;
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_5[0]),
                                                               _l_lO0l0I1_14);
  _l____000O_17 = _lIlI1l01__3(_l_lO0l0I1_14);
  _l1_OlOO100_II_16 = (int )_l____000O_17;
  if (_l1_OlOO100_II_16) {
    _lIOI___O0_18 = 0;
  } else {
    _lIOI___O0_18 = 1;
  }
  return ((int __attribute__((__annotate__("ocasorry:literals, api_hash")))  )_lIOI___O0_18);
}
}
