/* Generated by Goblint-CIL v. 2.0.9 */
/* print_CIL_Input is false */

static unsigned int __visa_program_verify_license_key_1[4]  = {      33554647U,      2518663511U,      773947479U,      1644175447U};
static int __visa_engine_ready ;
static char __enc_lit_1[56]  = 
  {      149,      227,      147,      238, 
        135,      160,      184,      175, 
        162,      167,      170,      238, 
        165,      171,      183,      238, 
        168,      161,      188,      163, 
        175,      186,      244,      238, 
        131,      187,      189,      186, 
        238,      172,      171,      238, 
        171,      182,      175,      173, 
        186,      162,      183,      238, 
        255,      248,      238,      173, 
        166,      175,      188,      175, 
        173,      186,      171,      188, 
        189,      224,      196,      206};
static char __dec_lit_1[56]  ;
static int __init_lit_1  =    0;
static char __enc_lit_2[56]  = 
  {      192,      182,      198,      187, 
        210,      245,      237,      250, 
        247,      242,      255,      187, 
        240,      254,      226,      187, 
        253,      244,      233,      246, 
        250,      239,      161,      187, 
        214,      238,      232,      239, 
        187,      249,      254,      187, 
        254,      227,      250,      248, 
        239,      247,      226,      187, 
        170,      173,      187,      248, 
        243,      250,      233,      250, 
        248,      239,      254,      233, 
        232,      181,      145,      155};
static char __dec_lit_2[56]  ;
static int __init_lit_2  =    0;
static char __enc_lit_3[66]  = 
  {      107,      27,      109,      16, 
        99,      101,      115,      115, 
        117,      99,      99,      10, 
        16,      124,      89,      83, 
        85,      94,      67,      85, 
        16,      91,      85,      73, 
        16,      89,      67,      16, 
        102,      113,      124,      121, 
        116,      17,      16,      101, 
        94,      92,      95,      83, 
        91,      89,      94,      87, 
        16,      64,      66,      85, 
        93,      89,      69,      93, 
        16,      86,      85,      81, 
        68,      69,      66,      85, 
        67,      30,      30,      30, 
        58,      48};
static char __dec_lit_3[66]  ;
static int __init_lit_3  =    0;
static char __enc_lit_4[49]  = 
  {      198,      176,      192,      189, 
        219,      220,      212,      209, 
        216,      217,      167,      189, 
        212,      243,      235,      252, 
        241,      244,      249,      189, 
        241,      244,      254,      248, 
        243,      238,      248,      189, 
        246,      248,      228,      188, 
        189,      220,      254,      254, 
        248,      238,      238,      189, 
        249,      248,      243,      244, 
        248,      249,      179,      151, 
        157};
static char __dec_lit_4[49]  ;
static int __init_lit_4  =    0;
static char __enc_lit_5[17]  = 
  {      215,      213,      200,      170, 
        190,      191,      179,      181, 
        170,      204,      203,      202, 
        190,      170,      176,      176, 
        135};
static char __dec_lit_5[17]  ;
static int __init_lit_5  =    0;
static char __enc_lit_6[23]  = 
  {      85,      36,      83,      46, 
        88,      107,      124,      103, 
        104,      119,      103,      96, 
        105,      46,      69,      107, 
        119,      52,      46,      43, 
        125,      4,      14};
static char __dec_lit_6[23]  ;
static int __init_lit_6  =    0;
#line 7 "examples/01_license_keygen.c"
extern int printf(char const   *format  , ...) ;
#line 8
extern unsigned long strlen(char const   *s ) ;
#line 11 "examples/01_license_keygen.c"
int verify_license_key(char const   *license_key ) 
{ 
  unsigned long tmp ;
  int __loop_jitter ;
  int __loop_phase ;
  int __idx_1 ;
  int __idx_2 ;
  int __idx_3 ;
  int __idx_4 ;
  int accumulator_s1 ;
  int accumulator_s2 ;
  int parity_s1 ;
  int parity_s2 ;
  int i_s1 ;
  int i_s2 ;
  int ch_s1 ;
  int ch_s2 ;
  int expected_hash_s1 ;
  int expected_hash_s2 ;
  int __split_tmp_accumulator_24407 ;
  int __split_tmp_parity_36858 ;
  int __split_tmp_i_22013 ;
  int __split_tmp_ch_56189 ;
  int __split_tmp_accumulator_34772 ;
  int __split_tmp_parity_45277 ;
  int __split_tmp_i_63018 ;
  int __split_tmp_ch_28118 ;
  int __split_tmp_accumulator_17541 ;
  int __split_tmp_parity_57408 ;
  int __split_tmp_i_43911 ;
  int __split_tmp_expected_hash_42537 ;
  int __dyn_junk ;
  int __indirect_state ;
  int __vcpu_v0 ;
  int __vcpu_v1 ;
  int __vcpu_v2 ;
  int __vcpu_pc ;
  int __vcpu_acc ;
  int __vcpu_parity ;
  int __vcpu_i ;
  int __vcpu_ch ;
  int __cff_state ;

  {
  __cff_state = 14;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 63: 
      {
      if (__vcpu_acc == 12687) {
        __vcpu_v0 = 1;
      } else {
        __vcpu_v0 = 0;
      }
      __cff_state = 73;
      break;
      }
      case 28: 
      {
      __vcpu_acc = 4919;
      __cff_state = 32;
      break;
      }
      case 32: 
      {
      __vcpu_parity = 90;
      __cff_state = 47;
      break;
      }
      case 73: 
      return (__vcpu_v0);
      case 58: 
      {
      while (! (__vcpu_i >= 16)) {
        __vcpu_ch = (int )((unsigned char )*((char *)license_key + __vcpu_i));
        __vcpu_acc = (__vcpu_acc + __vcpu_ch * (__vcpu_i + 1)) ^ __vcpu_parity;
        __vcpu_parity = (__vcpu_parity + __vcpu_ch) & 255;
        __vcpu_i ++;
      }
      __cff_state = 63;
      break;
      }
      case 47: 
      {
      __vcpu_i = 0;
      __cff_state = 58;
      break;
      }
      case 14: 
      {
      __vcpu_pc = 0;
      __cff_state = 28;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
#line 37 "examples/01_license_keygen.c"
int main(int argc , char **argv ) 
{ 
  char const   *key ;
  char *tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int __idx_5 ;
  int __idx_6 ;
  int res_s1 ;
  int res_s2 ;
  int __split_tmp_res_5080 ;
  int __cff_state ;

  {
  __cff_state = 12;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 34: 
      {
#line 38
      if (argc > 1) {
#line 38
        tmp = *(argv + 1);
      } else {
#line 38
        tmp = & __dec_lit_5[0];
      }
      __cff_state = 45;
      break;
      }
      case 66: 
#line 41
      return (tmp___1);
      case 21: 
      {
      if (__init_lit_6 == 0) {
        __idx_6 = 0;
        while (1) {
          if (__idx_6 < 23) {
            __dec_lit_6[__idx_6] = (char )(2348240763U * (14259U * (unsigned int )((__enc_lit_6[__idx_6] & ~ 14) | (~ __enc_lit_6[__idx_6] & 14)) + 232508253U) - 840394927U);
            __idx_6 = (int )((unsigned int )(1373481501U * (26677U * (unsigned int )((2042226703U * (((1775U * (unsigned int )__idx_6 + 17261U) + (1775U * (unsigned int )1 + 17261U)) - 17261U) & ~ 2078522211U) - (~ (2042226703U * (((1775U * (unsigned int )__idx_6 + 17261U) + (1775U * (unsigned int )1 + 17261U)) - 17261U)) & 2078522211U)) + 135677588U) - 1999128260U));
          } else {
            break;
          }
        }
        __init_lit_6 = 1;
      }
      __cff_state = 34;
      break;
      }
      case 12: 
      {
      if (__init_lit_5 == 0) {
        __idx_5 = 0;
        while (1) {
          if (__idx_5 < 17) {
            __dec_lit_5[__idx_5] = (char )(1997861171U * (29179U * (unsigned int )((__enc_lit_5[__idx_5] | 135) - (__enc_lit_5[__idx_5] & 135)) + 268578282U) - 2582671262U);
            __idx_5 = (int )((unsigned int )(2403635557U * (14445U * (unsigned int )((2380032403U * (((7323U * (unsigned int )__idx_5 + 28948U) + (7323U * (unsigned int )1 + 28948U)) - 28948U) ^ 1607606908U) - ((~ (2380032403U * (((7323U * (unsigned int )__idx_5 + 28948U) + (7323U * (unsigned int )1 + 28948U)) - 28948U)) & 1607606908U) << 1)) + 190449928U) - 1472403496U));
          } else {
            break;
          }
        }
        __init_lit_5 = 1;
      }
      __cff_state = 21;
      break;
      }
      case 45: 
      {
#line 38
      key = (char const   *)tmp;
#line 39
      printf((char const   *)(& __dec_lit_6[0]), key);
#line 40
      tmp___0 = verify_license_key(key);
#line 40
      __split_tmp_res_5080 = tmp___0;
#line 40
      res_s1 = (int )(3305638253U * (26725U * (unsigned int )((__split_tmp_res_5080 & ~ (__split_tmp_res_5080 >> 1)) - (~ __split_tmp_res_5080 & (__split_tmp_res_5080 >> 1))) + 662710790U) - 1094457998U);
#line 40
      res_s2 = __split_tmp_res_5080 >> 1;
      __cff_state = 51;
      break;
      }
      case 51: 
      {
#line 41
      if ((int )((unsigned int )(3009999497U * (9145U * (unsigned int )((1358835807U * (((11167U * (unsigned int )res_s1 + 25025U) + (11167U * (unsigned int )res_s2 + 25025U)) - 25025U) ^ 1609987743U) - ((~ (1358835807U * (((11167U * (unsigned int )res_s1 + 25025U) + (11167U * (unsigned int )res_s2 + 25025U)) - 25025U)) & 1609987743U) << 1)) + 958680216U) - 1251257688U))) {
#line 41
        tmp___1 = 0;
      } else {
#line 41
        tmp___1 = 1;
      }
      __cff_state = 66;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
