/* Generated by Goblint-CIL v. 2.0.9 */
/* print_CIL_Input is false */


static int __ocasorry_check_function_hook(const void *fn_ptr) {
    if (!fn_ptr) return 1;
    const unsigned char *code = (const unsigned char *)fn_ptr;
    /* Check for immediate hook trampoline opcodes: 0xE9 / 0xFF on x86, or invalid zero */
    if (code[0] == 0xE9 || (code[0] == 0xFF && code[1] == 0x25)) return 1; /* Hooked */
    return 0; /* Clean */
}


#include <time.h>
#ifdef __APPLE__
#include <mach/mach_time.h>
static unsigned long long __ocasorry_get_timestamp(void) {
    return (unsigned long long)mach_absolute_time();
}
#else
static unsigned long long __ocasorry_get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}
#endif


static unsigned int __ocasorry_crc_check(const unsigned char *p, int len) {
    unsigned int crc = 0xFFFFFFFF;
    if (!p) return 0;
    for (int i = 0; i < len; i++) {
        crc = (crc >> 8) ^ ((crc ^ p[i]) & 0xFF);
    }
    return crc;
}


#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <dlfcn.h>
typedef int (*__ocasorry_ptrace_t)(int request, pid_t pid, void *addr, int data);

static int __ocasorry_check_debugger_present(void) {
    int mib[4];
    struct kinfo_proc info;
    size_t size = sizeof(info);
    info.kp_proc.p_flag = 0;
    mib[0] = 1; /* CTL_KERN */
    mib[1] = 14; /* KERN_PROC */
    mib[2] = 1; /* KERN_PROC_PID */
    mib[3] = getpid();
    if (sysctl(mib, 4, &info, &size, 0, 0) == 0) {
        if ((info.kp_proc.p_flag & 0x00000800) != 0) { /* P_TRACED */
            return 1;
        }
    }
    return 0;
}

static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        void *h = dlopen(0, 0);
        if (h) {
            __ocasorry_ptrace_t ptrace_fn = (__ocasorry_ptrace_t)dlsym(h, "ptrace");
            if (ptrace_fn) {
                ptrace_fn(31, 0, 0, 0); /* PT_DENY_ATTACH */
            }
        }
        exit(137); /* Fallback exit if ptrace returns */
    }
}
#else
static int __ocasorry_check_debugger_present(void) {
    return 0;
}
static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        exit(137);
    }
}
#endif

static unsigned int __visa_program_verify_license_key_1[4]  = {      33554647U,      2518663511U,      773947479U,      1644175447U};
static int __visa_engine_ready ;
int verify_license_key(char const   *_l0OIIl1O__12 ) ;
static void *__indirect_call_table[1]  = {      (void *)(& verify_license_key)};
static char __enc_lit_1[56]  = 
  {      6,      112,      0,      125, 
        20,      51,      43,      60, 
        49,      52,      57,      125, 
        54,      56,      36,      125, 
        59,      50,      47,      48, 
        60,      41,      103,      125, 
        16,      40,      46,      41, 
        125,      63,      56,      125, 
        56,      37,      60,      62, 
        41,      49,      36,      125, 
        108,      107,      125,      62, 
        53,      60,      47,      60, 
        62,      41,      56,      47, 
        46,      115,      87,      93};
static char __dec_lit_1[56]  ;
static int __init_lit_1  =    0;
static char __enc_lit_2[56]  = 
  {      60,      74,      58,      71, 
        46,      9,      17,      6, 
        11,      14,      3,      71, 
        12,      2,      30,      71, 
        1,      8,      21,      10, 
        6,      19,      93,      71, 
        42,      18,      20,      19, 
        71,      5,      2,      71, 
        2,      31,      6,      4, 
        19,      11,      30,      71, 
        86,      81,      71,      4, 
        15,      6,      21,      6, 
        4,      19,      2,      21, 
        20,      73,      109,      103};
static char __dec_lit_2[56]  ;
static int __init_lit_2  =    0;
static char __enc_lit_3[66]  = 
  {      243,      131,      245,      136, 
        251,      253,      235,      235, 
        237,      251,      251,      146, 
        136,      228,      193,      203, 
        205,      198,      219,      205, 
        136,      195,      205,      209, 
        136,      193,      219,      136, 
        254,      233,      228,      225, 
        236,      137,      136,      253, 
        198,      196,      199,      203, 
        195,      193,      198,      207, 
        136,      216,      218,      205, 
        197,      193,      221,      197, 
        136,      206,      205,      201, 
        220,      221,      218,      205, 
        219,      134,      134,      134, 
        162,      168};
static char __dec_lit_3[66]  ;
static int __init_lit_3  =    0;
static char __enc_lit_4[49]  = 
  {      233,      159,      239,      146, 
        244,      243,      251,      254, 
        247,      246,      136,      146, 
        251,      220,      196,      211, 
        222,      219,      214,      146, 
        222,      219,      209,      215, 
        220,      193,      215,      146, 
        217,      215,      203,      147, 
        146,      243,      209,      209, 
        215,      193,      193,      146, 
        214,      215,      220,      219, 
        215,      214,      156,      184, 
        178};
static char __dec_lit_4[49]  ;
static int __init_lit_4  =    0;
static char __enc_lit_5[17]  = 
  {      74,      72,      85,      55, 
        35,      34,      46,      40, 
        55,      81,      86,      87, 
        35,      55,      45,      45, 
        26};
static char __dec_lit_5[17]  ;
static int __init_lit_5  =    0;
static char __enc_lit_6[23]  = 
  {      157,      236,      155,      230, 
        144,      163,      180,      175, 
        160,      191,      175,      168, 
        161,      230,      141,      163, 
        191,      252,      230,      227, 
        181,      204,      198};
static char __dec_lit_6[23]  ;
static int __init_lit_6  =    0;
extern int printf(char const   *format  , ...) ;
extern unsigned long strlen(char const   *s ) ;
int verify_license_key(char const   *_l0OIIl1O__12 ) 
{ 
  unsigned long _l1O1Illl0ll01l0O_1 ;
  int __loop_jitter ;
  int __loop_phase ;
  int __idx_1 ;
  int __idx_2 ;
  int __idx_3 ;
  int __idx_4 ;
  int _ll11_111OI1II0__2 ;
  int _lI0O01O1lI_3 ;
  int _l10O1l01O_O_4 ;
  int _lOI1O_0I0_l_5 ;
  int _llOOl_OOI1IOOOI_6 ;
  int _ll_10lOIIOO_7 ;
  int _lO_O101Il0l0Ill_8 ;
  int _l0ll0I0_OIl_l__9 ;
  int _lI__1IO1l0_O1O_10 ;
  int _l1_010OI0_0lIO__11 ;
  int __split_tmp_accumulator_34711 ;
  int __split_tmp_parity_50415 ;
  int __split_tmp_i_47606 ;
  int __split_tmp_ch_28519 ;
  int __split_tmp_accumulator_27432 ;
  int __split_tmp_parity_17984 ;
  int __split_tmp_i_42072 ;
  int __split_tmp_ch_57991 ;
  int __split_tmp_accumulator_59682 ;
  int __split_tmp_parity_31445 ;
  int __split_tmp_i_58257 ;
  int __split_tmp_expected_hash_53222 ;
  int __dyn_junk ;
  int __indirect_state ;
  int __vcpu_v0 ;
  int __vcpu_v1 ;
  int __vcpu_v2 ;
  int __vcpu_pc ;
  int __vcpu_acc ;
  int __vcpu_parity ;
  int __vcpu_i ;
  int __vcpu_ch ;
  int __desync_guard ;
  unsigned int __code_crc ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  int __is_hooked ;
  int __cff_state ;

  {
  __cff_state = 12;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 28: 
      {
      if (__is_hooked != 0) {
        return (-99);
      }
      __cff_state = 33;
      break;
      }
      case 170: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 12: 
      {
      __is_hooked = __ocasorry_check_function_hook((void *)(& verify_license_key));
      __cff_state = 28;
      break;
      }
      case 150: 
      return (__vcpu_v0);
      case 90: 
      {
      __vcpu_pc = 0;
      __cff_state = 103;
      break;
      }
      case 33: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 41;
      break;
      }
      case 136: 
      {
      while (! (__vcpu_i >= 16)) {
        __vcpu_ch = (int )((unsigned char )*((char *)_l0OIIl1O__12 + __vcpu_i));
        __vcpu_acc = (__vcpu_acc + __vcpu_ch * (__vcpu_i + 1)) ^ __vcpu_parity;
        __vcpu_parity = (__vcpu_parity + __vcpu_ch) & 255;
        __vcpu_i ++;
      }
      __cff_state = 145;
      break;
      }
      case 86: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 90;
      break;
      }
      case 113: 
      {
      __vcpu_parity = 90;
      __cff_state = 121;
      break;
      }
      case 41: 
      {
      __code_crc = __ocasorry_crc_check((void *)(& verify_license_key), 16);
      __cff_state = 50;
      break;
      }
      case 145: 
      {
      if (__vcpu_acc == 12687) {
        __vcpu_v0 = 1;
      } else {
        __vcpu_v0 = 0;
      }
      __cff_state = 150;
      break;
      }
      case 163: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 170;
      break;
      }
      case 121: 
      {
      __vcpu_i = 0;
      __cff_state = 136;
      break;
      }
      case 50: 
      {
      if (! (__code_crc != 0)) {
        return (-1);
      }
      __cff_state = 66;
      break;
      }
      case 71: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 86;
      break;
      }
      case 66: 
      {
      __desync_guard = 45005;
      __cff_state = 71;
      break;
      }
      case 103: 
      {
      __vcpu_acc = 4919;
      __cff_state = 113;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int main(int _lIllO_0llI_19 , char **_lOl11_1O1O1l0_20 ) 
{ 
  char const   *_lOIO_OI01_0OO_13 ;
  char *_l_IOI0_1010ll_14 ;
  int _llOIllO0ll__l_15 ;
  int _lIlI1_I10O_16 ;
  int __idx_5 ;
  int __idx_6 ;
  int _l0l_l000l_17 ;
  int _lO_11Ill0_18 ;
  int __split_tmp_res_32721 ;
  int __cff_state ;

  {
  __cff_state = 13;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 38: 
      {
      if (__init_lit_6 == 0) {
        __idx_6 = 0;
        while (1) {
          if (__idx_6 < 23) {
            __dec_lit_6[__idx_6] = (char )(3229002643U * (10907U * (unsigned int )((__enc_lit_6[__idx_6] | 198) - (__enc_lit_6[__idx_6] & 198)) + 1008871148U) - 1214512516U);
            __idx_6 = (int )((unsigned int )(3080178873U * (31113U * (unsigned int )((2379652843U * (((6595U * (unsigned int )__idx_6 + 4651U) + (6595U * (unsigned int )1 + 4651U)) - 4651U) & ~ 3929618297U) - (~ (2379652843U * (((6595U * (unsigned int )__idx_6 + 4651U) + (6595U * (unsigned int )1 + 4651U)) - 4651U)) & 3929618297U)) + 315639320U) - 277202776U));
          } else {
            break;
          }
        }
        __init_lit_6 = 1;
      }
      __cff_state = 40;
      break;
      }
      case 24: 
      {
      if (__init_lit_5 == 0) {
        __idx_5 = 0;
        while (1) {
          if (__idx_5 < 17) {
            __dec_lit_5[__idx_5] = (char )(1409932363U * (3427U * (unsigned int )((__enc_lit_5[__idx_5] | 26) - (__enc_lit_5[__idx_5] & 26)) + 853705914U) - 1157020286U);
            __idx_5 = (int )((unsigned int )(1175417219U * (9515U * (unsigned int )((3758844657U * (((17937U * (unsigned int )__idx_5 + 24382U) + (17937U * (unsigned int )1 + 24382U)) - 24382U) & ~ 2138264926U) - (~ (3758844657U * (((17937U * (unsigned int )__idx_5 + 24382U) + (17937U * (unsigned int )1 + 24382U)) - 24382U)) & 2138264926U)) + 587175821U) - 703777319U));
          } else {
            break;
          }
        }
        __init_lit_5 = 1;
      }
      __cff_state = 38;
      break;
      }
      case 62: 
      {
      if ((int )((unsigned int )(3388466619U * (6003U * (unsigned int )((4205132593U * (((15825U * (unsigned int )_l0l_l000l_17 + 30893U) + (15825U * (unsigned int )_lO_11Ill0_18 + 30893U)) - 30893U) ^ 3580360733U) - ((~ (4205132593U * (((15825U * (unsigned int )_l0l_l000l_17 + 30893U) + (15825U * (unsigned int )_lO_11Ill0_18 + 30893U)) - 30893U)) & 3580360733U) << 1)) + 877206706U) - 164704262U))) {
        _lIlI1_I10O_16 = 0;
      } else {
        _lIlI1_I10O_16 = 1;
      }
      __cff_state = 70;
      break;
      }
      case 13: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 24;
      break;
      }
      case 70: 
      return (_lIlI1_I10O_16);
      case 40: 
      {
      if (_lIllO_0llI_19 > 1) {
        _l_IOI0_1010ll_14 = *(_lOl11_1O1O1l0_20 + 1);
      } else {
        _l_IOI0_1010ll_14 = & __dec_lit_5[0];
      }
      __cff_state = 55;
      break;
      }
      case 55: 
      {
      _lOIO_OI01_0OO_13 = (char const   *)_l_IOI0_1010ll_14;
      printf((char const   *)(& __dec_lit_6[0]), _lOIO_OI01_0OO_13);
      _llOIllO0ll__l_15 = verify_license_key(_lOIO_OI01_0OO_13);
      __split_tmp_res_32721 = _llOIllO0ll__l_15;
      _l0l_l000l_17 = (int )(1338311283U * (29371U * (unsigned int )((__split_tmp_res_32721 & ~ (__split_tmp_res_32721 >> 1)) - (~ __split_tmp_res_32721 & (__split_tmp_res_32721 >> 1))) + 657443883U) - 1546128721U);
      _lO_11Ill0_18 = __split_tmp_res_32721 >> 1;
      __cff_state = 62;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
