/* Generated by Goblint-CIL v. 2.1.1 */
/* print_CIL_Input is false */


static volatile int __ocasorry_runtime_initialized = 0;

__attribute__((constructor(101)))
static void __ocasorry_early_pre_main_stager(void) {
    if (!__ocasorry_runtime_initialized) {
        __ocasorry_runtime_initialized = 1;
#ifdef __APPLE__
        /* Early anti-debug and environment verification */
#endif
    }
}


#include <dlfcn.h>
#include <stdint.h>
#include <string.h>

/* Hash-only resolver: no plaintext symbol name ever leaves the binary in call sites.
   The resolver scans a static candidate table keyed by CRC32, resolving purely by hash. */
static uint32_t __ocasorry_calc_crc32(const char *s) {
    uint32_t crc = 0xFFFFFFFF;
    while (*s) {
        crc ^= (uint32_t)(unsigned char)(*s++);
        for (int i = 0; i < 8; i++) {
            crc = (crc >> 1) ^ ((crc & 1) ? 0xEDB88320 : 0);
        }
    }
    return ~crc;
}

static void *__ocasorry_resolve_symbol_hash(uint32_t target_hash) {
    /* Candidate symbol names stored as XOR-obfuscated byte arrays (key=0xA5).
       No plaintext strings appear in __cstring / __data sections.
       Sentinel 0xA5 = (0x00 ^ 0xA5) marks end of each name. */
    static const unsigned char __c0[] = {0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5}; /* printf */
    static const unsigned char __c1[] = {0xd5,0xd0,0xd1,0xd6,0xA5};           /* puts */
    static const unsigned char __c2[] = {0xc0,0xdd,0xcc,0xd1,0xA5};           /* exit */
    static const unsigned char __c3[] = {0xc8,0xc4,0xc9,0xc9,0xca,0xc6,0xA5};/* malloc */
    static const unsigned char __c4[] = {0xc3,0xd7,0xc0,0xc0,0xA5};          /* free */
    static const unsigned char __c5[] = {0xc8,0xc0,0xc8,0xd6,0xc0,0xd1,0xA5};/* memset */
    static const unsigned char __c6[] = {0xc8,0xc0,0xc8,0xc6,0xd5,0xdc,0xA5};/* memcpy */
    static const unsigned char __c7[] = {0xd6,0xd1,0xd7,0xc9,0xc0,0xcb,0xA5};/* strlen */
    static const unsigned char __c8[] = {0xc3,0xca,0xd5,0xc0,0xcb,0xA5};     /* fopen */
    static const unsigned char __c9[] = {0xd6,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};       /* sprintf */
    static const unsigned char __ca[] = {0xd6,0xcb,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};  /* snprintf */
    static const unsigned char __cb[] = {0xc4,0xc7,0xca,0xd7,0xd1,0xA5};     /* abort */

    static const unsigned char * const __enc[] = {
        __c0, __c1, __c2, __c3, __c4, __c5, __c6, __c7, __c8, __c9, __ca, __cb, 0
    };

    for (int i = 0; __enc[i] != 0; i++) {
        /* Decode name on the stack at runtime — never stored as plaintext */
        char name[32];
        int j = 0;
        while (__enc[i][j] != 0xA5 && j < 31) {
            name[j] = (char)(__enc[i][j] ^ 0xA5);
            j++;
        }
        name[j] = '\0';

        if (__ocasorry_calc_crc32(name) == target_hash) {
#ifdef RTLD_DEFAULT
            void *sym = dlsym(RTLD_DEFAULT, name);
#else
            void *sym = dlsym((void*)-2, name);
#endif
            if (sym) return sym;
            void *h = dlopen(0, 1);
            if (h) return dlsym(h, name);
        }
    }
    return 0;
}


#include <time.h>
#ifdef __APPLE__
#include <mach/mach_time.h>
static unsigned long long __ocasorry_get_timestamp(void) {
    return (unsigned long long)mach_absolute_time();
}
#else
static unsigned long long __ocasorry_get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}
#endif


#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <dlfcn.h>
typedef int (*__ocasorry_ptrace_t)(int request, pid_t pid, void *addr, int data);

static int __ocasorry_check_debugger_present(void) {
    int mib[4];
    struct kinfo_proc info;
    size_t size = sizeof(info);
    info.kp_proc.p_flag = 0;
    mib[0] = 1; /* CTL_KERN */
    mib[1] = 14; /* KERN_PROC */
    mib[2] = 1; /* KERN_PROC_PID */
    mib[3] = getpid();
    if (sysctl(mib, 4, &info, &size, 0, 0) == 0) {
        if ((info.kp_proc.p_flag & 0x00000800) != 0) { /* P_TRACED */
            return 1;
        }
    }
    return 0;
}

static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        void *h = dlopen(0, 0);
        if (h) {
            __ocasorry_ptrace_t ptrace_fn = (__ocasorry_ptrace_t)dlsym(h, "ptrace");
            if (ptrace_fn) {
                ptrace_fn(31, 0, 0, 0); /* PT_DENY_ATTACH */
            }
        }
        exit(137); /* Fallback exit if ptrace returns */
    }
}
#else
static int __ocasorry_check_debugger_present(void) {
    return 0;
}
static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        exit(137);
    }
}
#endif


#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE
#endif
#include <sys/mman.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <signal.h>
#ifdef __APPLE__
#include <pthread.h>
#include <libkern/OSCacheControl.h>
#include <sys/ucontext.h>
#endif

static void *__ocasorry_two_tier_active_pc = NULL;

#if defined(__APPLE__) && defined(__aarch64__)
static void __ocasorry_two_tier_signal_router(int sig, siginfo_t *info, void *context) {
    (void)sig; (void)info;
    ucontext_t *uc = (ucontext_t *)context;
    if (__ocasorry_two_tier_active_pc != NULL) {
        /* IMPLICIT FLOW: Redirect Program Counter in CPU hardware context */
        uc->uc_mcontext->__ss.__pc = (uint64_t)__ocasorry_two_tier_active_pc;
    }
}
#endif

static void *__ocasorry_alloc_ephemeral_page(size_t *out_sz, size_t min_sz) {
    size_t page_sz = (size_t)sysconf(_SC_PAGESIZE);
    if (page_sz < 4096) page_sz = 4096;
    size_t alloc_sz = (min_sz + page_sz - 1) & ~(page_sz - 1);
    *out_sz = alloc_sz;
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0);
#elif defined(__aarch64__) || defined(__arm64__)
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#else
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#endif
    if (ptr == MAP_FAILED) return NULL;
    return ptr;
}

static void __ocasorry_free_ephemeral_page(void *ptr, size_t sz) {
    if (ptr && ptr != MAP_FAILED) {
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
        pthread_jit_write_protect_np(0); /* Switch to write mode before memory zeroing */
#endif
        memset(ptr, 0, sz); /* Overwrite memory to prevent dump recovery */
        munmap(ptr, sz);
    }
}

static unsigned char __packed_inner_bc_vcpu2_nested_matrix_1[12]  = 
  {      (unsigned char)188,      (unsigned char)220,      (unsigned char)251,      (unsigned char)24, 
        (unsigned char)44,      (unsigned char)89,      (unsigned char)116,      (unsigned char)150, 
        (unsigned char)181,      (unsigned char)213,      (unsigned char)252,      (unsigned char)18};
static unsigned char __packed_outer_bc_vcpu2_nested_matrix_1[5]  = {      (unsigned char)128,      (unsigned char)145,      (unsigned char)146,      (unsigned char)220, 
        (unsigned char)43};
static unsigned int __visa_program_vcpu1_vector_parity_1[50]  = 
  {      1868978013U,      1313553520U,      771474183U,      3351810906U, 
        2078453737U,      3291561020U,      3803729619U,      3371971046U, 
        2733122485U,      2473365576U,      188244511U,      463234354U, 
        2960823233U,      3823695508U,      481453611U,      3842053502U, 
        1880112653U,      1082344096U,      2063013239U,      3700834058U, 
        3201679577U,      3500479724U,      2225356419U,      620151126U, 
        4008187237U,      1489681976U,      2117812943U,      4201157730U, 
        2453356081U,      4030284484U,      3794769179U,      342801966U, 
        3596567293U,      2625378064U,      2582527911U,      2880225658U, 
        764647049U,      3484630492U,      1716535539U,      601986694U, 
        596655701U,      1740652904U,      2033653311U,      2602024274U, 
        2001192673U,      1431605172U,      1051262667U,      4237767198U, 
        1161435053U,      3540663488U};
static int __visa_engine_ready ;
static char volatile   __enc_lit_1[56]  = 
  {      110,      24,      104,      21, 
        124,      91,      67,      84, 
        89,      92,      81,      21, 
        94,      80,      76,      21, 
        83,      90,      71,      88, 
        84,      65,      15,      21, 
        120,      64,      70,      65, 
        21,      87,      80,      21, 
        80,      77,      84,      86, 
        65,      89,      76,      21, 
        4,      3,      21,      86, 
        93,      84,      71,      84, 
        86,      65,      80,      71, 
        70,      27,      63,      53};
static char volatile   __dec_lit_1[56]  ;
static int volatile   __init_lit_1  =    0;
static char volatile   __enc_lit_2[56]  = 
  {      195,      181,      197,      184, 
        209,      246,      238,      249, 
        244,      241,      252,      184, 
        243,      253,      225,      184, 
        254,      247,      234,      245, 
        249,      236,      162,      184, 
        213,      237,      235,      236, 
        184,      250,      253,      184, 
        253,      224,      249,      251, 
        236,      244,      225,      184, 
        169,      174,      184,      251, 
        240,      249,      234,      249, 
        251,      236,      253,      234, 
        235,      182,      146,      152};
static char volatile   __dec_lit_2[56]  ;
static int volatile   __init_lit_2  =    0;
static char volatile   __enc_lit_3[77]  = 
  {      123,      11,      125,      0, 
        115,      117,      99,      99, 
        101,      115,      115,      26, 
        0,      108,      73,      67, 
        69,      78,      83,      69, 
        0,      75,      69,      89, 
        0,      73,      83,      0, 
        118,      97,      108,      105, 
        100,      1,      0,      20, 
        13,      118,      99,      112, 
        117,      0,      102,      69, 
        68,      69,      82,      65, 
        84,      69,      68,      0, 
        97,      85,      84,      72, 
        79,      82,      73,      90, 
        65,      84,      73,      79, 
        78,      0,      117,      78, 
        76,      79,      67,      75, 
        69,      68,      14,      42, 
        32};
static char volatile   __dec_lit_3[77]  ;
static int volatile   __init_lit_3  =    0;
static char volatile   __enc_lit_4[59]  = 
  {      70,      48,      64,      61, 
        91,      92,      84,      81, 
        88,      89,      39,      61, 
        84,      115,      107,      124, 
        113,      116,      121,      61, 
        113,      116,      126,      120, 
        115,      110,      120,      61, 
        118,      120,      100,      60, 
        61,      41,      48,      75, 
        94,      77,      72,      61, 
        94,      124,      110,      126, 
        124,      121,      120,      61, 
        79,      120,      119,      120, 
        126,      105,      120,      121, 
        51,      23,      29};
static char volatile   __dec_lit_4[59]  ;
static int volatile   __init_lit_4  =    0;
static char volatile   __enc_lit_5[23]  = 
  {      242,      131,      244,      137, 
        255,      204,      219,      192, 
        207,      208,      192,      199, 
        206,      137,      226,      204, 
        208,      147,      137,      140, 
        218,      163,      169};
static char volatile   __dec_lit_5[23]  ;
static int volatile   __init_lit_5  =    0;
extern int printf(char const   *format  , ...) ;
extern unsigned long strlen(char const   *s ) ;

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

__attribute__((visibility("default")))
int vcpu1_vector_parity(const char * license_key) {
    unsigned long long __vregs[64];
    #define __VREG_MASK(r) (0xf055a8546212ULL + ((unsigned long long)(r) * 0x517cc1b727220a95ULL))
    #define __VREG_GET(r) (__vregs[(r)] ^ __VREG_MASK(r))
    #define __VREG_SET(r, val) do { __vregs[(r)] = ((unsigned long long)(val)) ^ __VREG_MASK(r); } while(0)

    for (int __i = 0; __i < 64; __i++) {
        __vregs[__i] = __VREG_MASK(__i);
    }

    /* Vector 2: Dual Shadow Stack (VSP_data + VSP_ctrl) */
    unsigned long long __vstack_data[64] = {0};
    unsigned long long __vstack_ctrl[32] = {0};
    unsigned int __vsp_d = 0;
    unsigned int __vsp_c = 0;

    const char *__ptr_ctx = (const char *)license_key;
    const unsigned long long __cfi_canary = 0xf055a8546212ULL ^ ((uintptr_t)__ptr_ctx * 0x9E3779B97F4A7C15ULL);

    /* Push CFI Canary into Shadow Control Stack */
    __vstack_ctrl[__vsp_c++] = __cfi_canary ^ 0x8fd17f58eddcb02bULL;

    __VREG_SET(0, (unsigned long long)(uintptr_t)license_key);
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0xB] = &&__h_vadd,
        [0x3E] = &&__h_vsub,
        [0x31] = &&__h_vmul,
        [0x2] = &&__h_vxor,
        [0x3] = &&__h_vand,
        [0x3B] = &&__h_vor,
        [0x8] = &&__h_vsll,
        [0x30] = &&__h_vsrl,
        [0x1A] = &&__h_vli,
        [0x7] = &&__h_vmv,
        [0x17] = &&__h_vle8,
        [0x11] = &&__h_vse8,
        [0x2A] = &&__h_vret,
        [0x1] = &&__h_vbge,
        [0x29] = &&__h_vj
    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 50) goto __h_vret; \
        __raw = __visa_program_vcpu1_vector_parity_1[__pc]; \
        __key = 0x61a97d6U ^ (__pc * 0x21f0aaadU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd:
    __VREG_SET(__vd, __VREG_GET(__vs1) + __VREG_GET(__vs2));
    __VISA_DISPATCH();

__h_vsub:
    __VREG_SET(__vd, __VREG_GET(__vs1) - __VREG_GET(__vs2));
    __VISA_DISPATCH();

__h_vmul:
    __VREG_SET(__vd, __VREG_GET(__vs1) * __VREG_GET(__vs2));
    __VISA_DISPATCH();

__h_vxor:
    __VREG_SET(__vd, __VREG_GET(__vs1) ^ __VREG_GET(__vs2));
    __VISA_DISPATCH();

__h_vand:
    __VREG_SET(__vd, __VREG_GET(__vs1) & __VREG_GET(__vs2));
    __VISA_DISPATCH();

__h_vor:
    __VREG_SET(__vd, __VREG_GET(__vs1) | __VREG_GET(__vs2));
    __VISA_DISPATCH();

__h_vsll:
    __VREG_SET(__vd, __VREG_GET(__vs1) << __VREG_GET(__vs2));
    __VISA_DISPATCH();

__h_vsrl:
    __VREG_SET(__vd, (unsigned long long)(__VREG_GET(__vs1) >> __VREG_GET(__vs2)));
    __VISA_DISPATCH();

__h_vli:
    __VREG_SET(__vd, (unsigned long long)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();

__h_vmv:
    __VREG_SET(__vd, __VREG_GET(__vs1));
    __VISA_DISPATCH();

__h_vle8:
    if (__ptr_ctx) {
        __VREG_SET(__vd, (unsigned long long)((const unsigned char *)__ptr_ctx)[__VREG_GET(__vs2)]);
    }
    __VISA_DISPATCH();

__h_vse8:
    if (__vsp_d < 63) {
        __vstack_data[__vsp_d++] = __VREG_GET(__vs1);
    }
    __VISA_DISPATCH();

__h_vbge:
    if (__VREG_GET(__vs1) >= __VREG_GET(__vs2)) {
        __pc = (48);
    }
    __VISA_DISPATCH();

__h_vj:
    __pc = ((__inst >> 7) & 0x7FFFF);
    __VISA_DISPATCH();

__h_default:
    __VISA_DISPATCH();

__h_vret: ;
    /* Verify Shadow Control Stack CFI Canary */
    if (__vsp_c == 0 || ((__vstack_ctrl[--__vsp_c] ^ 0x8fd17f58eddcb02bULL) != __cfi_canary)) {
        __builtin_trap();
    }
    unsigned long long __res_val = __VREG_GET(0);
    __builtin_memset(__vregs, 0, sizeof(__vregs));
    __builtin_memset(__vstack_data, 0, sizeof(__vstack_data));
    __builtin_memset(__vstack_ctrl, 0, sizeof(__vstack_ctrl));
    return (int)__res_val;
}

int __attribute__((__annotate__("ocasorry:nested_vm")))  _llI_II1lO_1(int _l0lI__O0IlO10IlO_2 ) 
{ 
  int __outer_pc ;
  int __outer_running ;
  int __outer_op ;
  int __inner_pc ;
  int __inner_key ;
  int __inner_running ;
  int __inner_op ;
  int __inner_vregs[8] ;
  int __nested_vm_result ;
  int __r_dst ;
  int __r_s1 ;
  int __r_s2 ;
  int __r_imm ;
  int __r_arg ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;

  {
  __t_start = __ocasorry_get_timestamp();
  __desync_guard = 54444;
  {
  if ((__desync_guard & ~ __desync_guard) != 0) {
    return (0);
  }
  }
  __ocasorry_enforce_anti_debug();
  __outer_pc = 0;
  __outer_running = 1;
  __inner_key = 189;
  __nested_vm_result = 0;
  while (1) {
    __outer_op = (int )__packed_outer_bc_vcpu2_nested_matrix_1[__outer_pc] ^ ((144 + __outer_pc * 17) & 255);
    __outer_pc ++;
    switch (__outer_op) {
    case 16: 
    {
    __inner_pc = 0;
    __inner_running = 1;
    break;
    }
    case 48: 
    {
    while (1) {
      __inner_op = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      switch (__inner_op) {
      case 1: 
      {
      __r_arg = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = _l0lI__O0IlO10IlO_2;
      break;
      }
      case 2: 
      {
      __r_imm = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __r_imm;
      break;
      }
      case 3: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] + __inner_vregs[__r_s2];
      break;
      }
      case 4: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] - __inner_vregs[__r_s2];
      break;
      }
      case 5: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] ^ __inner_vregs[__r_s2];
      break;
      }
      case 6: 
      {
      __r_dst = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __r_s2 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __inner_vregs[__r_dst] = __inner_vregs[__r_s1] * __inner_vregs[__r_s2];
      break;
      }
      case 15: 
      {
      __r_s1 = (int )__packed_inner_bc_vcpu2_nested_matrix_1[__inner_pc] ^ ((__inner_key + __inner_pc * 31) & 255);
      __inner_pc ++;
      __nested_vm_result = __inner_vregs[__r_s1];
      __inner_running = 0;
      break;
      }
      }
      if (__inner_running == 0) {
        break;
      }
    }
    break;
    }
    case 32: 
    {
    __r_imm = (int )__packed_outer_bc_vcpu2_nested_matrix_1[__outer_pc] ^ ((144 + __outer_pc * 17) & 255);
    __outer_pc ++;
    __inner_key = (__inner_key * 33 + __r_imm) & 255;
    break;
    }
    case 255: 
    {
    __outer_running = 0;
    break;
    }
    }
    if (__outer_running == 0) {
      break;
    }
  }
  return (__nested_vm_result);
  __t_end = __ocasorry_get_timestamp();
  if (__t_end - __t_start < 1000000000) {

  }
}
}
static unsigned int __rolling_bc_vcpu3_rolling_vkey_1[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu3_rolling_vkey(int h2) {
    unsigned int __regs[4] = { (unsigned int)h2, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu3_rolling_vkey_1[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt: ;
    int __ret_val = (int)__regs[3];
    __builtin_memset(__regs, 0, sizeof(__regs));
    return __ret_val;
}

static unsigned char __ephemeral_stager_vcpu4_ephemeral_jit_1[8]  = 
  {      (unsigned char)64,      (unsigned char)8,      (unsigned char)32,      (unsigned char)212, 
        (unsigned char)192,      (unsigned char)3,      (unsigned char)95,      (unsigned char)214};
static unsigned char __ephemeral_payload_vcpu4_ephemeral_jit_1[36]  = 
  {      (unsigned char)91,      (unsigned char)59,      (unsigned char)214,      (unsigned char)8, 
        (unsigned char)69,      (unsigned char)90,      (unsigned char)91,      (unsigned char)49, 
        (unsigned char)250,      (unsigned char)90,      (unsigned char)90,      (unsigned char)14, 
        (unsigned char)69,      (unsigned char)242,      (unsigned char)90,      (unsigned char)43, 
        (unsigned char)58,      (unsigned char)90,      (unsigned char)90,      (unsigned char)14, 
        (unsigned char)90,      (unsigned char)90,      (unsigned char)218,      (unsigned char)8, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140, 
        (unsigned char)122,      (unsigned char)90,      (unsigned char)218,      (unsigned char)8, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140};

int vcpu4_ephemeral_jit(int h3) {
    size_t __code_len = 36;
    size_t __stager_len = 8;
    size_t __tier1_sz = 0;
    size_t __tier2_sz = 0;

    /* Step 1: Allocate & Decrypt Tier 2 Inner Payload */
    unsigned char *__tier2_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier2_sz, __code_len);
    if (!__tier2_page) return (h3 == 25352 || h3 == 42) ? 1 : ((h3 == 20) ? 120 : 0);

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    for (size_t __i = 0; __i < __code_len; __i++) {
        __tier2_page[__i] = __ephemeral_payload_vcpu4_ephemeral_jit_1[__i] ^ 0x5A;
    }
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier2_page, __code_len);
#endif

    __ocasorry_two_tier_active_pc = __tier2_page;

    /* Step 2: Allocate Tier 1 Outer Hardware Trap Stager (BRK #0x42) */
    unsigned char *__tier1_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier1_sz, __stager_len);
    if (!__tier1_page) {
        __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
        return (h3 == 25352 || h3 == 42) ? 1 : ((h3 == 20) ? 120 : 0);
    }

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    memcpy(__tier1_page, __ephemeral_stager_vcpu4_ephemeral_jit_1, __stager_len);
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier1_page, __stager_len);
#endif

    /* Step 3: Register POSIX Signal Interceptors for Hardware Implicit Flow */
    int __valid = 0;
#if defined(__APPLE__) && defined(__aarch64__)
    struct sigaction __sa, __old_trap, __old_bus, __old_segv, __old_ill;
    memset(&__sa, 0, sizeof(__sa));
    __sa.sa_sigaction = __ocasorry_two_tier_signal_router;
    __sa.sa_flags = SA_SIGINFO;
    sigaction(SIGTRAP, &__sa, &__old_trap);
    sigaction(SIGBUS,  &__sa, &__old_bus);
    sigaction(SIGSEGV, &__sa, &__old_segv);
    sigaction(SIGILL,  &__sa, &__old_ill);

    /* Step 4: Invoke Tier 1 Entry (Triggers Hardware Fault -> Redirection to Tier 2 in CPU) */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier1_fn = (__jit_fn_t)(void *)__tier1_page;
    __valid = __tier1_fn(h3);

    /* Restore original signal handlers */
    sigaction(SIGTRAP, &__old_trap, NULL);
    sigaction(SIGBUS,  &__old_bus, NULL);
    sigaction(SIGSEGV, &__old_segv, NULL);
    sigaction(SIGILL,  &__old_ill, NULL);
    __ocasorry_two_tier_active_pc = NULL;
#else
    /* Fallback for non-Darwin ARM64 */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier2_fn = (__jit_fn_t)(void *)__tier2_page;
    __valid = __tier2_fn(h3);
#endif

    /* Step 5: Zero and release both ephemeral JIT pages immediately */
    __ocasorry_free_ephemeral_page(__tier1_page, __tier1_sz);
    __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
    return __valid;
}

int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _l_0l0_IOl_lll___3(char const   *_l1lI01I____O01O_13 ) 
{ 
  unsigned long _lIlOlO1IIl_4 ;
  int _lI_Ol1OI1_5 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _l0_IO1OOO_6 ;
  int _ll0__1lI_O_0_7 ;
  int __attribute__((__annotate__("ocasorry:nested_vm")))  _l10ll_I_llIl_8 ;
  int _l0l_01_lO11I_9 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l0II_1I0Il_10 ;
  int _l0I10_0O000_l11I_11 ;
  int __attribute__((__annotate__("ocasorry:ephemeral")))  _l1_1l1O_1100__12 ;
  int volatile   __idx_1 ;
  int volatile   __idx_2 ;
  int volatile   __idx_3 ;
  int volatile   __idx_4 ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  void *__resolved_printf ;
  int __cff_state ;

  {
  __cff_state = 14;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 14: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 21;
      break;
      }
      case 74: 
      {
      if (__init_lit_3 == 0) {
        __idx_3 = 0;
        while (1) {
          if (__idx_3 < 77) {
            __dec_lit_3[__idx_3] = __enc_lit_3[__idx_3] ^ 32;
            __idx_3 ++;
          } else {
            break;
          }
        }
        __init_lit_3 = 1;
      }
      __cff_state = 82;
      break;
      }
      case 32: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 47;
      break;
      }
      case 138: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 120: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 138;
      break;
      }
      case 62: 
      {
      if (__init_lit_2 == 0) {
        __idx_2 = 0;
        while (1) {
          if (__idx_2 < 56) {
            __dec_lit_2[__idx_2] = __enc_lit_2[__idx_2] ^ 152;
            __idx_2 ++;
          } else {
            break;
          }
        }
        __init_lit_2 = 1;
      }
      __cff_state = 74;
      break;
      }
      case 21: 
      {
      __desync_guard = 50505;
      __cff_state = 32;
      break;
      }
      case 110: 
      {
      if (_l0I10_0O000_l11I_11) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_3[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )1);
      } else {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_4[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
      }
      __cff_state = 120;
      break;
      }
      case 47: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 58;
      break;
      }
      case 98: 
      {
      if ((unsigned long )_l1lI01I____O01O_13 == (unsigned long )((void *)0)) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_1[0]));
        return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
      } else {
        _lIlOlO1IIl_4 = strlen(_l1lI01I____O01O_13);
        if (_lIlOlO1IIl_4 != 16UL) {
          __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
          (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_2[0]));
          return ((int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0);
        }
      }
      __cff_state = 106;
      break;
      }
      case 82: 
      {
      if (__init_lit_4 == 0) {
        __idx_4 = 0;
        while (1) {
          if (__idx_4 < 59) {
            __dec_lit_4[__idx_4] = __enc_lit_4[__idx_4] ^ 29;
            __idx_4 ++;
          } else {
            break;
          }
        }
        __init_lit_4 = 1;
      }
      __cff_state = 98;
      break;
      }
      case 58: 
      {
      if (__init_lit_1 == 0) {
        __idx_1 = 0;
        while (1) {
          if (__idx_1 < 56) {
            __dec_lit_1[__idx_1] = __enc_lit_1[__idx_1] ^ 53;
            __idx_1 ++;
          } else {
            break;
          }
        }
        __init_lit_1 = 1;
      }
      __cff_state = 62;
      break;
      }
      case 106: 
      {
      if ((_lIlOlO1IIl_4 | 1) % 2 != 0) {
        _l0_IO1OOO_6 = vcpu1_vector_parity(_l1lI01I____O01O_13);
        _lI_Ol1OI1_5 = (int )_l0_IO1OOO_6;
        _l10ll_I_llIl_8 = _llI_II1lO_1(_lI_Ol1OI1_5);
        _ll0__1lI_O_0_7 = (int )_l10ll_I_llIl_8;
        _l0II_1I0Il_10 = vcpu3_rolling_vkey(_ll0__1lI_O_0_7);
        _l0l_01_lO11I_9 = (int )_l0II_1I0Il_10;
        _l1_1l1O_1100__12 = vcpu4_ephemeral_jit(_l0l_01_lO11I_9);
        _l0I10_0O000_l11I_11 = (int )_l1_1l1O_1100__12;
      } else {
        _l0_IO1OOO_6 = vcpu1_vector_parity(_l1lI01I____O01O_13);
        _lI_Ol1OI1_5 = (int )_l0_IO1OOO_6;
        _l10ll_I_llIl_8 = _llI_II1lO_1(_lI_Ol1OI1_5);
        _ll0__1lI_O_0_7 = (int )_l10ll_I_llIl_8;
        _l0II_1I0Il_10 = vcpu3_rolling_vkey(_ll0__1lI_O_0_7);
        _l0l_01_lO11I_9 = (int )_l0II_1I0Il_10;
        _l1_1l1O_1100__12 = vcpu4_ephemeral_jit(_l0l_01_lO11I_9);
        _l0I10_0O000_l11I_11 = (int )_l1_1l1O_1100__12;
      }
      __cff_state = 110;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int __attribute__((__annotate__("ocasorry:literals, api_hash")))  main(int _l1___O0_1_1_O_19 ,
                                                                       char **_l1Ol0l_O_1Ol0_0I_20 ) ;
static unsigned char const volatile   __dk[16]  __attribute__((__goblint_cil_pulledup__("main")))  = 
  {      (unsigned char const volatile   )0x0a,      (unsigned char const volatile   )0x08,      (unsigned char const volatile   )0x15,      (unsigned char const volatile   )0x77, 
        (unsigned char const volatile   )0x63,      (unsigned char const volatile   )0x62,      (unsigned char const volatile   )0x6e,      (unsigned char const volatile   )0x68, 
        (unsigned char const volatile   )0x77,      (unsigned char const volatile   )0x11,      (unsigned char const volatile   )0x16,      (unsigned char const volatile   )0x17, 
        (unsigned char const volatile   )0x63,      (unsigned char const volatile   )0x77,      (unsigned char const volatile   )0x6d,      (unsigned char const volatile   )0x6d};
int __attribute__((__annotate__("ocasorry:literals, api_hash")))  main(int _l1___O0_1_1_O_19 ,
                                                                       char **_l1Ol0l_O_1Ol0_0I_20 ) 
{ 
  char volatile   __dk_buf[17] ;
  int volatile   __i ;
  char const   *_llIOO_lOlI__14 ;
  char const   *_l00lI_010ll_15 ;
  int _lOl01___ll0_16 ;
  int __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _l_1_01I0__O0Ol1O_17 ;
  int _l1OO__I_1_1_18 ;
  int volatile   __idx_5 ;
  void *__resolved_printf ;

  {
  __ocasorry_enforce_anti_debug();
  if (__init_lit_5 == 0) {
    __idx_5 = 0;
    while (1) {
      if (__idx_5 < 23) {
        __dec_lit_5[__idx_5] = __enc_lit_5[__idx_5] ^ 169;
        __idx_5 ++;
      } else {
        break;
      }
    }
    __init_lit_5 = 1;
  }
  __i = (int volatile   )0;
  while (__i < (int volatile   )16) {
    __dk_buf[__i] = (char volatile   )((char )((int const volatile   )__dk[__i] ^ (int const volatile   )((unsigned char volatile   )0x5A)));
    __i += (int volatile   )1;
  }
  __dk_buf[16] = (char volatile   )'\000';
  if (_l1___O0_1_1_O_19 > 1) {
    _l00lI_010ll_15 = (char const   *)*(_l1Ol0l_O_1Ol0_0I_20 + 1);
  } else {
    _l00lI_010ll_15 = (char const   *)(__dk_buf);
  }
  _llIOO_lOlI__14 = _l00lI_010ll_15;
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_5[0]),
                                                               _llIOO_lOlI__14);
  _l_1_01I0__O0Ol1O_17 = _l_0l0_IOl_lll___3(_llIOO_lOlI__14);
  _lOl01___ll0_16 = (int )_l_1_01I0__O0Ol1O_17;
  if (_lOl01___ll0_16) {
    _l1OO__I_1_1_18 = 0;
  } else {
    _l1OO__I_1_1_18 = 1;
  }
  return ((int __attribute__((__annotate__("ocasorry:literals, api_hash")))  )_l1OO__I_1_1_18);
}
}
