/* Generated by Goblint-CIL v. 2.0.9 */
/* print_CIL_Input is false */


static volatile int __ocasorry_runtime_initialized = 0;

__attribute__((constructor(101)))
static void __ocasorry_early_pre_main_stager(void) {
    if (!__ocasorry_runtime_initialized) {
        __ocasorry_runtime_initialized = 1;
#ifdef __APPLE__
        /* Early anti-debug and environment verification */
#endif
    }
}


#include <dlfcn.h>
#include <stdint.h>
#include <string.h>

static uint32_t __ocasorry_calc_crc32(const char *s) {
    uint32_t crc = 0xFFFFFFFF;
    while (*s) {
        crc ^= (uint32_t)(unsigned char)(*s++);
        for (int i = 0; i < 8; i++) {
            crc = (crc >> 1) ^ ((crc & 1) ? 0xEDB88320 : 0);
        }
    }
    return ~crc;
}

static void *__ocasorry_resolve_symbol_hash(uint32_t target_hash, const char *name) {
    void *h = dlopen(0, RTLD_LAZY);
    if (!h) return 0;
    if (name && __ocasorry_calc_crc32(name) == target_hash) {
        return dlsym(h, name);
    }
    return 0;
}


static int __ocasorry_check_function_hook(const void *fn_ptr) {
    if (!fn_ptr) return 1;
    const unsigned char *code = (const unsigned char *)fn_ptr;
    /* Check for immediate hook trampoline opcodes: 0xE9 / 0xFF on x86, or invalid zero */
    if (code[0] == 0xE9 || (code[0] == 0xFF && code[1] == 0x25)) return 1; /* Hooked */
    return 0; /* Clean */
}


#include <time.h>
#ifdef __APPLE__
#include <mach/mach_time.h>
static unsigned long long __ocasorry_get_timestamp(void) {
    return (unsigned long long)mach_absolute_time();
}
#else
static unsigned long long __ocasorry_get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}
#endif


static unsigned int __ocasorry_crc_check(const unsigned char *p, int len) {
    unsigned int crc = 0xFFFFFFFF;
    if (!p) return 0;
    for (int i = 0; i < len; i++) {
        crc = (crc >> 8) ^ ((crc ^ p[i]) & 0xFF);
    }
    return crc;
}


#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <dlfcn.h>
typedef int (*__ocasorry_ptrace_t)(int request, pid_t pid, void *addr, int data);

static int __ocasorry_check_debugger_present(void) {
    int mib[4];
    struct kinfo_proc info;
    size_t size = sizeof(info);
    info.kp_proc.p_flag = 0;
    mib[0] = 1; /* CTL_KERN */
    mib[1] = 14; /* KERN_PROC */
    mib[2] = 1; /* KERN_PROC_PID */
    mib[3] = getpid();
    if (sysctl(mib, 4, &info, &size, 0, 0) == 0) {
        if ((info.kp_proc.p_flag & 0x00000800) != 0) { /* P_TRACED */
            return 1;
        }
    }
    return 0;
}

static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        void *h = dlopen(0, 0);
        if (h) {
            __ocasorry_ptrace_t ptrace_fn = (__ocasorry_ptrace_t)dlsym(h, "ptrace");
            if (ptrace_fn) {
                ptrace_fn(31, 0, 0, 0); /* PT_DENY_ATTACH */
            }
        }
        exit(137); /* Fallback exit if ptrace returns */
    }
}
#else
static int __ocasorry_check_debugger_present(void) {
    return 0;
}
static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        exit(137);
    }
}
#endif

static unsigned int __visa_program_verify_license_key_5[4]  = {      33554647U,      2518663511U,      773947479U,      1644175447U};
static unsigned int __visa_program_vcpu4_ephemeral_jit_4[3]  = {      34603351U,      2518777943U,      772616279U};
static unsigned int __visa_program_vcpu3_rolling_vkey_3[3]  = {      34603351U,      2518777943U,      772616279U};
static unsigned int __visa_program_vcpu2_nested_matrix_2[3]  = {      34603351U,      2518777943U,      772616279U};
static unsigned int __visa_program_vcpu1_vector_parity_1[4]  = {      33554647U,      2518663511U,      773947479U,      1644175447U};
static int __visa_engine_ready ;
int vcpu1_vector_parity(char const   *_lI_O1llIlO1__9 ) ;
int vcpu2_nested_matrix(int _lI1___00110I0Il1_10 ) ;
int vcpu3_rolling_vkey(int _l_l11Il1Oll_11 ) ;
int vcpu4_ephemeral_jit(int _l10l1101O1l_13 ) ;
int verify_license_key(char const   *_l_OO1lI0_l_11_27 ) ;
static void *__indirect_call_table[5]  = {      (void *)(& vcpu1_vector_parity),      (void *)(& vcpu2_nested_matrix),      (void *)(& vcpu3_rolling_vkey),      (void *)(& vcpu4_ephemeral_jit), 
        (void *)(& verify_license_key)};
static char __enc_lit_1[56]  = 
  {      132,      242,      130,      255, 
        150,      177,      169,      190, 
        179,      182,      187,      255, 
        180,      186,      166,      255, 
        185,      176,      173,      178, 
        190,      171,      229,      255, 
        146,      170,      172,      171, 
        255,      189,      186,      255, 
        186,      167,      190,      188, 
        171,      179,      166,      255, 
        238,      233,      255,      188, 
        183,      190,      173,      190, 
        188,      171,      186,      173, 
        172,      241,      213,      223};
static char __dec_lit_1[56]  ;
static int __init_lit_1  =    0;
static char __enc_lit_2[56]  = 
  {      68,      50,      66,      63, 
        86,      113,      105,      126, 
        115,      118,      123,      63, 
        116,      122,      102,      63, 
        121,      112,      109,      114, 
        126,      107,      37,      63, 
        82,      106,      108,      107, 
        63,      125,      122,      63, 
        122,      103,      126,      124, 
        107,      115,      102,      63, 
        46,      41,      63,      124, 
        119,      126,      109,      126, 
        124,      107,      122,      109, 
        108,      49,      21,      31};
static char __dec_lit_2[56]  ;
static int __init_lit_2  =    0;
static char __enc_lit_3[77]  = 
  {      126,      14,      120,      5, 
        118,      112,      102,      102, 
        96,      118,      118,      31, 
        5,      105,      76,      70, 
        64,      75,      86,      64, 
        5,      78,      64,      92, 
        5,      76,      86,      5, 
        115,      100,      105,      108, 
        97,      4,      5,      17, 
        8,      115,      102,      117, 
        112,      5,      99,      64, 
        65,      64,      87,      68, 
        81,      64,      65,      5, 
        100,      80,      81,      77, 
        74,      87,      76,      95, 
        68,      81,      76,      74, 
        75,      5,      112,      75, 
        73,      74,      70,      78, 
        64,      65,      11,      47, 
        37};
static char __dec_lit_3[77]  ;
static int __init_lit_3  =    0;
static char __enc_lit_4[59]  = 
  {      49,      71,      55,      74, 
        44,      43,      35,      38, 
        47,      46,      80,      74, 
        35,      4,      28,      11, 
        6,      3,      14,      74, 
        6,      3,      9,      15, 
        4,      25,      15,      74, 
        1,      15,      19,      75, 
        74,      94,      71,      60, 
        41,      58,      63,      74, 
        41,      11,      25,      9, 
        11,      14,      15,      74, 
        56,      15,      0,      15, 
        9,      30,      15,      14, 
        68,      96,      106};
static char __dec_lit_4[59]  ;
static int __init_lit_4  =    0;
static char __enc_lit_5[17]  = 
  {      130,      128,      157,      255, 
        235,      234,      230,      224, 
        255,      153,      158,      159, 
        235,      255,      229,      229, 
        210};
static char __dec_lit_5[17]  ;
static int __init_lit_5  =    0;
static char __enc_lit_6[23]  = 
  {      172,      221,      170,      215, 
        161,      146,      133,      158, 
        145,      142,      158,      153, 
        144,      215,      188,      146, 
        142,      205,      215,      210, 
        132,      253,      247};
static char __dec_lit_6[23]  ;
static int __init_lit_6  =    0;
extern int printf(char const   *format  , ...) ;
extern unsigned long strlen(char const   *s ) ;
int vcpu1_vector_parity(char const   *_lI_O1llIlO1__9 ) 
{ 
  int __loop_jitter ;
  int __loop_phase ;
  int _l1__0l01_I0_1 ;
  int _l0_0I00Il1_2 ;
  int _lI1O1_0O___l_3 ;
  int _lOI00110_I1_O0O_4 ;
  int _l11000O111O1l_5 ;
  int _l11ll10Il__6 ;
  int _lI0II_IO1ll0_Ill_7 ;
  int _lO1OIl_O0OOO_8 ;
  int __split_tmp_acc_1803 ;
  int __split_tmp_parity_34912 ;
  int __split_tmp_i_63311 ;
  int __split_tmp_ch_30994 ;
  int __split_tmp_acc_55742 ;
  int __split_tmp_parity_44424 ;
  int __split_tmp_i_31897 ;
  int __split_tmp_ch_57169 ;
  int __split_tmp_acc_61857 ;
  int __split_tmp_parity_48545 ;
  int __split_tmp_i_8418 ;
  int __dyn_junk ;
  int __indirect_state ;
  int __vcpu_v0 ;
  int __vcpu_v1 ;
  int __vcpu_v2 ;
  int __vcpu_pc ;
  int __vcpu_acc ;
  int __vcpu_parity ;
  int __vcpu_i ;
  int __vcpu_ch ;
  int __desync_guard ;
  unsigned int __code_crc ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  int __is_hooked ;
  int __cff_state ;

  {
  __cff_state = 16;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 136: 
      {
      while (! (__vcpu_i >= 16)) {
        __vcpu_ch = (int )((unsigned char )*((char *)_lI_O1llIlO1__9 + __vcpu_i));
        __vcpu_acc = (__vcpu_acc + __vcpu_ch * (__vcpu_i + 1)) ^ __vcpu_parity;
        __vcpu_parity = (__vcpu_parity + __vcpu_ch) & 255;
        __vcpu_i ++;
      }
      __cff_state = 144;
      break;
      }
      case 34: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 40;
      break;
      }
      case 120: 
      {
      __vcpu_i = 0;
      __cff_state = 136;
      break;
      }
      case 118: 
      {
      __vcpu_parity = 90;
      __cff_state = 120;
      break;
      }
      case 16: 
      {
      __is_hooked = __ocasorry_check_function_hook((void *)(& vcpu1_vector_parity));
      __cff_state = 28;
      break;
      }
      case 100: 
      {
      __vcpu_acc = 4919;
      __cff_state = 118;
      break;
      }
      case 144: 
      {
      if (__vcpu_acc == 12687) {
        __vcpu_v0 = 1;
      } else {
        __vcpu_v0 = 0;
      }
      __cff_state = 152;
      break;
      }
      case 40: 
      {
      __code_crc = __ocasorry_crc_check((void *)(& vcpu1_vector_parity), 16);
      __cff_state = 56;
      break;
      }
      case 80: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 92;
      break;
      }
      case 162: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 170;
      break;
      }
      case 92: 
      {
      __vcpu_pc = 0;
      __cff_state = 100;
      break;
      }
      case 28: 
      {
      if (__is_hooked != 0) {
        return (-99);
      }
      __cff_state = 34;
      break;
      }
      case 170: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 77: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 80;
      break;
      }
      case 56: 
      {
      if (! (__code_crc != 0)) {
        return (-1);
      }
      __cff_state = 68;
      break;
      }
      case 68: 
      {
      __desync_guard = 8125;
      __cff_state = 77;
      break;
      }
      case 152: 
      return (__vcpu_v0);
      }
    } else {
      break;
    }
  }
}
}
int vcpu2_nested_matrix(int _lI1___00110I0Il1_10 ) 
{ 
  int __dyn_junk ;
  int __indirect_state ;
  int __vcpu_v0 ;
  int __vcpu_v1 ;
  int __vcpu_v2 ;
  int __vcpu_pc ;
  int __vcpu_acc ;
  int __vcpu_parity ;
  int __vcpu_i ;
  int __vcpu_ch ;
  int __desync_guard ;
  unsigned int __code_crc ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  int __is_hooked ;
  int __cff_state ;

  {
  __cff_state = 15;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 152: 
      return (__vcpu_v0);
      case 117: 
      {
      __vcpu_v1 = 20;
      __cff_state = 125;
      break;
      }
      case 88: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 94;
      break;
      }
      case 94: 
      {
      __vcpu_pc = 0;
      __cff_state = 101;
      break;
      }
      case 142: 
      {
      __vcpu_v0 ^= 90;
      __cff_state = 152;
      break;
      }
      case 15: 
      {
      __is_hooked = __ocasorry_check_function_hook((void *)(& vcpu2_nested_matrix));
      __cff_state = 28;
      break;
      }
      case 57: 
      {
      if (! (__code_crc != 0)) {
        return (-1);
      }
      __cff_state = 64;
      break;
      }
      case 101: 
      {
      __vcpu_v0 = _lI1___00110I0Il1_10;
      __cff_state = 117;
      break;
      }
      case 35: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 47;
      break;
      }
      case 28: 
      {
      if (__is_hooked != 0) {
        return (-99);
      }
      __cff_state = 35;
      break;
      }
      case 64: 
      {
      __desync_guard = 24580;
      __cff_state = 78;
      break;
      }
      case 176: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 138: 
      {
      __vcpu_v0 = __vcpu_v2 * 3;
      __cff_state = 142;
      break;
      }
      case 78: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 88;
      break;
      }
      case 125: 
      {
      __vcpu_v2 = __vcpu_v0 + __vcpu_v1;
      __cff_state = 138;
      break;
      }
      case 47: 
      {
      __code_crc = __ocasorry_crc_check((void *)(& vcpu2_nested_matrix), 16);
      __cff_state = 57;
      break;
      }
      case 163: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 176;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int vcpu3_rolling_vkey(int _l_l11Il1Oll_11 ) 
{ 
  int __dyn_junk ;
  int __indirect_state ;
  int __vcpu_v0 ;
  int __vcpu_v1 ;
  int __vcpu_v2 ;
  int __vcpu_pc ;
  int __vcpu_acc ;
  int __vcpu_parity ;
  int __vcpu_i ;
  int __vcpu_ch ;
  int __desync_guard ;
  unsigned int __code_crc ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  int __is_hooked ;
  int __cff_state ;

  {
  __cff_state = 12;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 87: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 98;
      break;
      }
      case 162: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 175;
      break;
      }
      case 61: 
      {
      __desync_guard = 57061;
      __cff_state = 70;
      break;
      }
      case 157: 
      return (__vcpu_v0);
      case 52: 
      {
      if (! (__code_crc != 0)) {
        return (-1);
      }
      __cff_state = 61;
      break;
      }
      case 27: 
      {
      if (__is_hooked != 0) {
        return (-99);
      }
      __cff_state = 36;
      break;
      }
      case 98: 
      {
      __vcpu_pc = 0;
      __cff_state = 106;
      break;
      }
      case 141: 
      {
      __vcpu_v0 ^= 90;
      __cff_state = 157;
      break;
      }
      case 106: 
      {
      __vcpu_v0 = _l_l11Il1Oll_11;
      __cff_state = 111;
      break;
      }
      case 36: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 43;
      break;
      }
      case 12: 
      {
      __is_hooked = __ocasorry_check_function_hook((void *)(& vcpu3_rolling_vkey));
      __cff_state = 27;
      break;
      }
      case 131: 
      {
      __vcpu_v0 = __vcpu_v2 * 3;
      __cff_state = 141;
      break;
      }
      case 127: 
      {
      __vcpu_v2 = __vcpu_v0 + __vcpu_v1;
      __cff_state = 131;
      break;
      }
      case 175: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 43: 
      {
      __code_crc = __ocasorry_crc_check((void *)(& vcpu3_rolling_vkey), 16);
      __cff_state = 52;
      break;
      }
      case 70: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 87;
      break;
      }
      case 111: 
      {
      __vcpu_v1 = 20;
      __cff_state = 127;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int vcpu4_ephemeral_jit(int _l10l1101O1l_13 ) 
{ 
  int _l1IllO1OI1I1IOO_12 ;
  int __dyn_junk ;
  int __indirect_state ;
  int __vcpu_v0 ;
  int __vcpu_v1 ;
  int __vcpu_v2 ;
  int __vcpu_pc ;
  int __vcpu_acc ;
  int __vcpu_parity ;
  int __vcpu_i ;
  int __vcpu_ch ;
  int __desync_guard ;
  unsigned int __code_crc ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  int __is_hooked ;
  int __cff_state ;

  {
  __cff_state = 15;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 134: 
      {
      __vcpu_v0 = __vcpu_v2 * 3;
      __cff_state = 144;
      break;
      }
      case 168: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 178;
      break;
      }
      case 91: 
      {
      __vcpu_pc = 0;
      __cff_state = 101;
      break;
      }
      case 75: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 88;
      break;
      }
      case 15: 
      {
      __is_hooked = __ocasorry_check_function_hook((void *)(& vcpu4_ephemeral_jit));
      __cff_state = 23;
      break;
      }
      case 124: 
      {
      __vcpu_v2 = __vcpu_v0 + __vcpu_v1;
      __cff_state = 134;
      break;
      }
      case 34: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 46;
      break;
      }
      case 88: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 91;
      break;
      }
      case 144: 
      {
      __vcpu_v0 ^= 90;
      __cff_state = 150;
      break;
      }
      case 63: 
      {
      __desync_guard = 49207;
      __cff_state = 75;
      break;
      }
      case 23: 
      {
      if (__is_hooked != 0) {
        return (-99);
      }
      __cff_state = 34;
      break;
      }
      case 150: 
      return (__vcpu_v0);
      case 113: 
      {
      __vcpu_v1 = 20;
      __cff_state = 124;
      break;
      }
      case 178: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 46: 
      {
      __code_crc = __ocasorry_crc_check((void *)(& vcpu4_ephemeral_jit), 16);
      __cff_state = 50;
      break;
      }
      case 50: 
      {
      if (! (__code_crc != 0)) {
        return (-1);
      }
      __cff_state = 63;
      break;
      }
      case 101: 
      {
      __vcpu_v0 = _l10l1101O1l_13;
      __cff_state = 113;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int verify_license_key(char const   *_l_OO1lI0_l_11_27 ) 
{ 
  unsigned long _l11lO10IIOO1I_14 ;
  int _l11_111_0__15 ;
  int _l_11l_Ol1_16 ;
  int _ll10_lIll1O1_17 ;
  int _l0I1l0ll_1l_18 ;
  int __idx_1 ;
  int __idx_2 ;
  int __idx_3 ;
  int __idx_4 ;
  int _l1OI0l1_llllI_1_19 ;
  int _lOl_l0I_011l0_20 ;
  int _l11lOOO11__0O_21 ;
  int _l1100O11__22 ;
  int _lII1I_11OOOl0l_23 ;
  int _l_0Oll0l1OIOI_24 ;
  int _l1l_1_1l__25 ;
  int _l11IO0_III1l_I1I_26 ;
  int __split_tmp_h1_10351 ;
  int __split_tmp_h2_17294 ;
  int __split_tmp_h3_16168 ;
  int __split_tmp_is_valid_60564 ;
  int __dyn_junk ;
  int __indirect_state ;
  int __vcpu_v0 ;
  int __vcpu_v1 ;
  int __vcpu_v2 ;
  int __vcpu_pc ;
  int __vcpu_acc ;
  int __vcpu_parity ;
  int __vcpu_i ;
  int __vcpu_ch ;
  int __desync_guard ;
  unsigned int __code_crc ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  int __is_hooked ;
  int __cff_state ;

  {
  __cff_state = 18;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 160: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 176;
      break;
      }
      case 110: 
      {
      __vcpu_parity = 90;
      __cff_state = 124;
      break;
      }
      case 137: 
      {
      while (! (__vcpu_i >= 16)) {
        __vcpu_ch = (int )((unsigned char )*((char *)_l_OO1lI0_l_11_27 + __vcpu_i));
        __vcpu_acc = (__vcpu_acc + __vcpu_ch * (__vcpu_i + 1)) ^ __vcpu_parity;
        __vcpu_parity = (__vcpu_parity + __vcpu_ch) & 255;
        __vcpu_i ++;
      }
      __cff_state = 144;
      break;
      }
      case 18: 
      {
      __is_hooked = __ocasorry_check_function_hook((void *)(& verify_license_key));
      __cff_state = 21;
      break;
      }
      case 45: 
      {
      __code_crc = __ocasorry_crc_check((void *)(& verify_license_key), 16);
      __cff_state = 50;
      break;
      }
      case 152: 
      return (__vcpu_v0);
      case 107: 
      {
      __vcpu_acc = 4919;
      __cff_state = 110;
      break;
      }
      case 21: 
      {
      if (__is_hooked != 0) {
        return (-99);
      }
      __cff_state = 31;
      break;
      }
      case 176: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 124: 
      {
      __vcpu_i = 0;
      __cff_state = 137;
      break;
      }
      case 31: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 45;
      break;
      }
      case 97: 
      {
      __vcpu_pc = 0;
      __cff_state = 107;
      break;
      }
      case 144: 
      {
      if (__vcpu_acc == 12687) {
        __vcpu_v0 = 1;
      } else {
        __vcpu_v0 = 0;
      }
      __cff_state = 152;
      break;
      }
      case 88: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 97;
      break;
      }
      case 61: 
      {
      __desync_guard = 21661;
      __cff_state = 78;
      break;
      }
      case 78: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 88;
      break;
      }
      case 50: 
      {
      if (! (__code_crc != 0)) {
        return (-1);
      }
      __cff_state = 61;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int main(int _l_l_OI_Ol__0OO_I_34 , char **_llO_1Il100_35 ) 
{ 
  char const   *_lllI0O_1O11Il0_28 ;
  char *_lII00Il0110l_29 ;
  int _lO1lI1OO10_0IO1_30 ;
  int _ll___I0IO_31 ;
  int __idx_5 ;
  int __idx_6 ;
  int _l0_0I__l_Il_32 ;
  int _l00OI1llIlI1lI1O_33 ;
  int __split_tmp_res_34645 ;
  int __cff_state ;

  {
  __cff_state = 15;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 33: 
      {
      if (__init_lit_6 == 0) {
        __idx_6 = 0;
        while (1) {
          if (__idx_6 < 23) {
            __dec_lit_6[__idx_6] = (char )(2340086219U * (15331U * (unsigned int )((__enc_lit_6[__idx_6] & ~ 247) | (~ __enc_lit_6[__idx_6] & 247)) + 237904995U) - 3837779329U);
            __idx_6 = (int )((unsigned int )(3977052061U * (32437U * (unsigned int )((3255464521U * (((8185U * (unsigned int )__idx_6 + 6347U) + (8185U * (unsigned int )1 + 6347U)) - 6347U) ^ 3640621027U) - ((~ (3255464521U * (((8185U * (unsigned int )__idx_6 + 6347U) + (8185U * (unsigned int )1 + 6347U)) - 6347U)) & 3640621027U) << 1)) + 645737343U) - 3859492323U));
          } else {
            break;
          }
        }
        __init_lit_6 = 1;
      }
      __cff_state = 48;
      break;
      }
      case 74: 
      return (_ll___I0IO_31);
      case 55: 
      {
      _lllI0O_1O11Il0_28 = (char const   *)_lII00Il0110l_29;
      printf((char const   *)(& __dec_lit_6[0]), _lllI0O_1O11Il0_28);
      _lO1lI1OO10_0IO1_30 = verify_license_key(_lllI0O_1O11Il0_28);
      __split_tmp_res_34645 = _lO1lI1OO10_0IO1_30;
      _l0_0I__l_Il_32 = (int )(894645815U * (24455U * (unsigned int )((__split_tmp_res_34645 & ~ (__split_tmp_res_34645 >> 1)) - (~ __split_tmp_res_34645 & (__split_tmp_res_34645 >> 1))) + 487452703U) - 1941053609U);
      _l00OI1llIlI1lI1O_33 = __split_tmp_res_34645 >> 1;
      __cff_state = 61;
      break;
      }
      case 61: 
      {
      if ((int )((unsigned int )(592181419U * (16899U * (unsigned int )((2000807291U * (((12723U * (unsigned int )_l0_0I__l_Il_32 + 3201U) + (12723U * (unsigned int )_l00OI1llIlI1lI1O_33 + 3201U)) - 3201U) ^ 787900155U) - ((~ (2000807291U * (((12723U * (unsigned int )_l0_0I__l_Il_32 + 3201U) + (12723U * (unsigned int )_l00OI1llIlI1lI1O_33 + 3201U)) - 3201U)) & 787900155U) << 1)) + 389774148U) - 2366715500U))) {
        _ll___I0IO_31 = 0;
      } else {
        _ll___I0IO_31 = 1;
      }
      __cff_state = 74;
      break;
      }
      case 48: 
      {
      if (_l_l_OI_Ol__0OO_I_34 > 1) {
        _lII00Il0110l_29 = *(_llO_1Il100_35 + 1);
      } else {
        _lII00Il0110l_29 = & __dec_lit_5[0];
      }
      __cff_state = 55;
      break;
      }
      case 15: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 23;
      break;
      }
      case 23: 
      {
      if (__init_lit_5 == 0) {
        __idx_5 = 0;
        while (1) {
          if (__idx_5 < 17) {
            __dec_lit_5[__idx_5] = (char )(315772021U * (9181U * (unsigned int )((__enc_lit_5[__idx_5] | 210) - (__enc_lit_5[__idx_5] & 210)) + 178218706U) - 1235506682U);
            __idx_5 = (int )((unsigned int )(2474055889U * (16433U * (unsigned int )((2413768213U * (((12605U * (unsigned int )__idx_5 + 16740U) + (12605U * (unsigned int )1 + 16740U)) - 16740U) & ~ 3722532148U) - (~ (2413768213U * (((12605U * (unsigned int )__idx_5 + 16740U) + (12605U * (unsigned int )1 + 16740U)) - 16740U)) & 3722532148U)) + 434041557U) - 902510565U));
          } else {
            break;
          }
        }
        __init_lit_5 = 1;
      }
      __cff_state = 33;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
