/* Generated by Goblint-CIL v. 2.0.9 */
/* print_CIL_Input is false */


static volatile int __ocasorry_runtime_initialized = 0;

__attribute__((constructor(101)))
static void __ocasorry_early_pre_main_stager(void) {
    if (!__ocasorry_runtime_initialized) {
        __ocasorry_runtime_initialized = 1;
#ifdef __APPLE__
        /* Early anti-debug and environment verification */
#endif
    }
}


#include <dlfcn.h>
#include <stdint.h>
#include <string.h>

/* Hash-only resolver: no plaintext symbol name ever leaves the binary in call sites.
   The resolver scans a static candidate table keyed by CRC32, resolving purely by hash. */
static uint32_t __ocasorry_calc_crc32(const char *s) {
    uint32_t crc = 0xFFFFFFFF;
    while (*s) {
        crc ^= (uint32_t)(unsigned char)(*s++);
        for (int i = 0; i < 8; i++) {
            crc = (crc >> 1) ^ ((crc & 1) ? 0xEDB88320 : 0);
        }
    }
    return ~crc;
}

static void *__ocasorry_resolve_symbol_hash(uint32_t target_hash) {
    /* Candidate symbol names stored as XOR-obfuscated byte arrays (key=0xA5).
       No plaintext strings appear in __cstring / __data sections.
       Sentinel 0xA5 = (0x00 ^ 0xA5) marks end of each name. */
    static const unsigned char __c0[] = {0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5}; /* printf */
    static const unsigned char __c1[] = {0xd5,0xd0,0xd1,0xd6,0xA5};           /* puts */
    static const unsigned char __c2[] = {0xc0,0xdd,0xcc,0xd1,0xA5};           /* exit */
    static const unsigned char __c3[] = {0xc8,0xc4,0xc9,0xc9,0xca,0xc6,0xA5};/* malloc */
    static const unsigned char __c4[] = {0xc3,0xd7,0xc0,0xc0,0xA5};          /* free */
    static const unsigned char __c5[] = {0xc8,0xc0,0xc8,0xd6,0xc0,0xd1,0xA5};/* memset */
    static const unsigned char __c6[] = {0xc8,0xc0,0xc8,0xc6,0xd5,0xdc,0xA5};/* memcpy */
    static const unsigned char __c7[] = {0xd6,0xd1,0xd7,0xc9,0xc0,0xcb,0xA5};/* strlen */
    static const unsigned char __c8[] = {0xc3,0xca,0xd5,0xc0,0xcb,0xA5};     /* fopen */
    static const unsigned char __c9[] = {0xd6,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};       /* sprintf */
    static const unsigned char __ca[] = {0xd6,0xcb,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};  /* snprintf */
    static const unsigned char __cb[] = {0xc4,0xc7,0xca,0xd7,0xd1,0xA5};     /* abort */

    static const unsigned char * const __enc[] = {
        __c0, __c1, __c2, __c3, __c4, __c5, __c6, __c7, __c8, __c9, __ca, __cb, 0
    };

    for (int i = 0; __enc[i] != 0; i++) {
        /* Decode name on the stack at runtime — never stored as plaintext */
        char name[32];
        int j = 0;
        while (__enc[i][j] != 0xA5 && j < 31) {
            name[j] = (char)(__enc[i][j] ^ 0xA5);
            j++;
        }
        name[j] = '\0';

        if (__ocasorry_calc_crc32(name) == target_hash) {
#ifdef RTLD_DEFAULT
            void *sym = dlsym(RTLD_DEFAULT, name);
#else
            void *sym = dlsym((void*)-2, name);
#endif
            if (sym) return sym;
            void *h = dlopen(0, 1);
            if (h) return dlsym(h, name);
        }
    }
    return 0;
}


#include <time.h>
#ifdef __APPLE__
#include <mach/mach_time.h>
static unsigned long long __ocasorry_get_timestamp(void) {
    return (unsigned long long)mach_absolute_time();
}
#else
static unsigned long long __ocasorry_get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}
#endif


#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <dlfcn.h>
typedef int (*__ocasorry_ptrace_t)(int request, pid_t pid, void *addr, int data);

static int __ocasorry_check_debugger_present(void) {
    int mib[4];
    struct kinfo_proc info;
    size_t size = sizeof(info);
    info.kp_proc.p_flag = 0;
    mib[0] = 1; /* CTL_KERN */
    mib[1] = 14; /* KERN_PROC */
    mib[2] = 1; /* KERN_PROC_PID */
    mib[3] = getpid();
    if (sysctl(mib, 4, &info, &size, 0, 0) == 0) {
        if ((info.kp_proc.p_flag & 0x00000800) != 0) { /* P_TRACED */
            return 1;
        }
    }
    return 0;
}

static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        void *h = dlopen(0, 0);
        if (h) {
            __ocasorry_ptrace_t ptrace_fn = (__ocasorry_ptrace_t)dlsym(h, "ptrace");
            if (ptrace_fn) {
                ptrace_fn(31, 0, 0, 0); /* PT_DENY_ATTACH */
            }
        }
        exit(137); /* Fallback exit if ptrace returns */
    }
}
#else
static int __ocasorry_check_debugger_present(void) {
    return 0;
}
static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        exit(137);
    }
}
#endif


#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE
#endif
#include <sys/mman.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <signal.h>
#ifdef __APPLE__
#include <pthread.h>
#include <libkern/OSCacheControl.h>
#include <sys/ucontext.h>
#endif

static void *__ocasorry_two_tier_active_pc = NULL;

#if defined(__APPLE__) && defined(__aarch64__)
static void __ocasorry_two_tier_signal_router(int sig, siginfo_t *info, void *context) {
    (void)sig; (void)info;
    ucontext_t *uc = (ucontext_t *)context;
    if (__ocasorry_two_tier_active_pc != NULL) {
        /* IMPLICIT FLOW: Redirect Program Counter in CPU hardware context */
        uc->uc_mcontext->__ss.__pc = (uint64_t)__ocasorry_two_tier_active_pc;
    }
}
#endif

static void *__ocasorry_alloc_ephemeral_page(size_t *out_sz, size_t min_sz) {
    size_t page_sz = (size_t)sysconf(_SC_PAGESIZE);
    if (page_sz < 4096) page_sz = 4096;
    size_t alloc_sz = (min_sz + page_sz - 1) & ~(page_sz - 1);
    *out_sz = alloc_sz;
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0);
#elif defined(__aarch64__) || defined(__arm64__)
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#else
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#endif
    if (ptr == MAP_FAILED) return NULL;
    return ptr;
}

static void __ocasorry_free_ephemeral_page(void *ptr, size_t sz) {
    if (ptr && ptr != MAP_FAILED) {
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
        pthread_jit_write_protect_np(0); /* Switch to write mode before memory zeroing */
#endif
        memset(ptr, 0, sz); /* Overwrite memory to prevent dump recovery */
        munmap(ptr, sz);
    }
}

static unsigned int __visa_program_vcpu6_shift_mix_r2_3[7]  = {      111797102U,      2560498263U,      2331381788U,      134188741U, 
        3057976714U,      297632499U,      602224696U};
static unsigned int __visa_program_vcpu3_shift_mix_r1_2[7]  = {      111797102U,      2560498263U,      2331381788U,      119508677U, 
        3057976714U,      297632499U,      602224696U};
static unsigned int __visa_program_vcpu1_expand_key_1[7]  = {      111796974U,      1091074775U,      2330431900U,      124997189U, 
        3058992138U,      297534195U,      602224696U};
static int __visa_engine_ready ;
static char volatile   __enc_lit_1[34]  = 
  {      236,      154,      234,      151, 
        225,      244,      231,      226, 
        151,      143,      151,      228, 
        210,      212,      194,      197, 
        222,      195,      206,      151, 
        244,      223,      210,      212, 
        220,      151,      241,      214, 
        222,      219,      210,      211, 
        189,      183};
static char volatile   __dec_lit_1[34]  ;
static int volatile   __init_lit_1  =    0;
static char volatile   __enc_lit_2[53]  = 
  {      84,      37,      82,      47, 
        55,      34,      89,      76, 
        95,      90,      47,      95, 
        99,      110,      102,      97, 
        123,      106,      119,      123, 
        47,      77,      99,      96, 
        108,      100,      47,      53, 
        47,      84,      67,      53, 
        47,      63,      119,      42, 
        63,      55,      87,      35, 
        47,      93,      53,      47, 
        63,      119,      42,      63, 
        55,      87,      82,      5, 
        15};
static char volatile   __dec_lit_2[53]  ;
static int volatile   __init_lit_2  =    0;
static char volatile   __enc_lit_3[40]  = 
  {      183,      199,      177,      204, 
        212,      193,      186,      175, 
        188,      185,      204,      175, 
        133,      156,      132,      137, 
        158,      152,      137,      148, 
        152,      204,      174,      128, 
        131,      143,      135,      214, 
        204,      220,      148,      201, 
        220,      221,      218,      128, 
        128,      180,      230,      236};
static char volatile   __dec_lit_3[40]  ;
static int volatile   __init_lit_3  =    0;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
extern int printf(char const   *format  , ...) ;
extern long long atoll(char const   *str ) ;

int vcpu1_expand_key(int key) {
    int __vregs[64] = {0};
    __vregs[0] = (int)key;
    const char *__ptr_ctx = (const char *)0;
    unsigned int __pc = 0;
    int __running = 1;

    while (__running && __pc < 7) {
        unsigned int __raw = __visa_program_vcpu1_expand_key_1[__pc];
        unsigned int __key = 0x88a9e265U ^ (__pc * 0x9e3779b9U);
        unsigned int __inst = __raw ^ __key;

        unsigned char __funct6 = (unsigned char)((__inst >> 26) & 0x3F);
        unsigned char __vm     = (unsigned char)((__inst >> 25) & 0x01);
        unsigned char __vs2    = (unsigned char)((__inst >> 20) & 0x1F);
        unsigned char __vs1    = (unsigned char)((__inst >> 15) & 0x1F);
        unsigned char __funct3 = (unsigned char)((__inst >> 12) & 0x07);
        unsigned char __vd     = (unsigned char)((__inst >> 7)  & 0x1F);

        switch (__funct6) {
            case 0x11: /* vadd.vv */
                __vregs[__vd] = __vregs[__vs1] + __vregs[__vs2];
                break;
            case 0x34: /* vsub.vv */
                __vregs[__vd] = __vregs[__vs1] - __vregs[__vs2];
                break;
            case 0x9: /* vmul.vv */
                __vregs[__vd] = __vregs[__vs1] * __vregs[__vs2];
                break;
            case 0xF: /* vxor.vv */
                __vregs[__vd] = __vregs[__vs1] ^ __vregs[__vs2];
                break;
            case 0x2E: /* vand.vv */
                __vregs[__vd] = __vregs[__vs1] & __vregs[__vs2];
                break;
            case 0x17: /* vor.vv */
                __vregs[__vd] = __vregs[__vs1] | __vregs[__vs2];
                break;
            case 0x39: /* vsll.vv */
                __vregs[__vd] = __vregs[__vs1] << __vregs[__vs2];
                break;
            case 0x1A: /* vsrl.vv */
                __vregs[__vd] = (int)((unsigned int)__vregs[__vs1] >> __vregs[__vs2]);
                break;
            case 0x15: /* vli.vi (14-bit immediate) */
                __vregs[__vd] = (int)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2);
                break;
            case 0x23: /* vmv.vv */
                __vregs[__vd] = __vregs[__vs1];
                break;
            case 0x37: /* vle8.v load byte */
                if (__ptr_ctx) {
                    __vregs[__vd] = (int)((unsigned char)__ptr_ctx[__vregs[__vs2]]);
                }
                break;
            case 0x7: /* vret.v */
                __running = 0;
                break;
            case 0x20: /* vbge.vv */
                if (__vregs[__vs1] >= __vregs[__vs2]) {
                    /* Break loop: jump past loop back-edge */
                    __pc = (5) - 1;
                }
                break;
            case 0x3: /* vj */
                __pc = ((__inst >> 7) & 0x7FFFF) - 1;
                break;
            default:
                break;
        }
        __pc++;
    }
    return __vregs[0];
}

static unsigned int __rolling_bc_vcpu2_sub_bytes_r1_1[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu2_sub_bytes_r1(int left) {
    unsigned int __regs[4] = { (unsigned int)left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    while (__pc < 4) {
        unsigned int __enc = __rolling_bc_vcpu2_sub_bytes_r1_1[__pc];
        unsigned int __dec = __enc ^ __vkey;
        /* Stateful rolling key evolution dependent on decrypted instruction history */
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U);

        unsigned char __op = (unsigned char)(__dec >> 24);
        if (__op == 0x01) {
            __regs[1] = __regs[0] + 10U;
        } else if (__op == 0x02) {
            __regs[2] = __regs[1] ^ 42U;
        } else if (__op == 0x03) {
            __regs[3] = __regs[2] * 2U;
        } else if (__op == 0xFF) {
            return (int)__regs[3];
        }
        __pc++;
    }
    return (int)__regs[3];
}


int vcpu3_shift_mix_r1(int sbox_out, int right) {
    int __vregs[64] = {0};
    __vregs[0] = (int)sbox_out;
    __vregs[1] = (int)right;
    const char *__ptr_ctx = (const char *)0;
    unsigned int __pc = 0;
    int __running = 1;

    while (__running && __pc < 7) {
        unsigned int __raw = __visa_program_vcpu3_shift_mix_r1_2[__pc];
        unsigned int __key = 0x88a9e265U ^ (__pc * 0x9e3779b9U);
        unsigned int __inst = __raw ^ __key;

        unsigned char __funct6 = (unsigned char)((__inst >> 26) & 0x3F);
        unsigned char __vm     = (unsigned char)((__inst >> 25) & 0x01);
        unsigned char __vs2    = (unsigned char)((__inst >> 20) & 0x1F);
        unsigned char __vs1    = (unsigned char)((__inst >> 15) & 0x1F);
        unsigned char __funct3 = (unsigned char)((__inst >> 12) & 0x07);
        unsigned char __vd     = (unsigned char)((__inst >> 7)  & 0x1F);

        switch (__funct6) {
            case 0x11: /* vadd.vv */
                __vregs[__vd] = __vregs[__vs1] + __vregs[__vs2];
                break;
            case 0x34: /* vsub.vv */
                __vregs[__vd] = __vregs[__vs1] - __vregs[__vs2];
                break;
            case 0x9: /* vmul.vv */
                __vregs[__vd] = __vregs[__vs1] * __vregs[__vs2];
                break;
            case 0xF: /* vxor.vv */
                __vregs[__vd] = __vregs[__vs1] ^ __vregs[__vs2];
                break;
            case 0x2E: /* vand.vv */
                __vregs[__vd] = __vregs[__vs1] & __vregs[__vs2];
                break;
            case 0x17: /* vor.vv */
                __vregs[__vd] = __vregs[__vs1] | __vregs[__vs2];
                break;
            case 0x39: /* vsll.vv */
                __vregs[__vd] = __vregs[__vs1] << __vregs[__vs2];
                break;
            case 0x1A: /* vsrl.vv */
                __vregs[__vd] = (int)((unsigned int)__vregs[__vs1] >> __vregs[__vs2]);
                break;
            case 0x15: /* vli.vi (14-bit immediate) */
                __vregs[__vd] = (int)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2);
                break;
            case 0x23: /* vmv.vv */
                __vregs[__vd] = __vregs[__vs1];
                break;
            case 0x37: /* vle8.v load byte */
                if (__ptr_ctx) {
                    __vregs[__vd] = (int)((unsigned char)__ptr_ctx[__vregs[__vs2]]);
                }
                break;
            case 0x7: /* vret.v */
                __running = 0;
                break;
            case 0x20: /* vbge.vv */
                if (__vregs[__vs1] >= __vregs[__vs2]) {
                    /* Break loop: jump past loop back-edge */
                    __pc = (5) - 1;
                }
                break;
            case 0x3: /* vj */
                __pc = ((__inst >> 7) & 0x7FFFF) - 1;
                break;
            default:
                break;
        }
        __pc++;
    }
    return __vregs[0];
}

static unsigned int __rolling_bc_vcpu4_feistel_xor_r1_2[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu4_feistel_xor_r1(int left) {
    unsigned int __regs[4] = { (unsigned int)left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    while (__pc < 4) {
        unsigned int __enc = __rolling_bc_vcpu4_feistel_xor_r1_2[__pc];
        unsigned int __dec = __enc ^ __vkey;
        /* Stateful rolling key evolution dependent on decrypted instruction history */
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U);

        unsigned char __op = (unsigned char)(__dec >> 24);
        if (__op == 0x01) {
            __regs[1] = __regs[0] + 10U;
        } else if (__op == 0x02) {
            __regs[2] = __regs[1] ^ 42U;
        } else if (__op == 0x03) {
            __regs[3] = __regs[2] * 2U;
        } else if (__op == 0xFF) {
            return (int)__regs[3];
        }
        __pc++;
    }
    return (int)__regs[3];
}

static unsigned int __rolling_bc_vcpu5_sub_bytes_r2_3[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu5_sub_bytes_r2(int new_left) {
    unsigned int __regs[4] = { (unsigned int)new_left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    while (__pc < 4) {
        unsigned int __enc = __rolling_bc_vcpu5_sub_bytes_r2_3[__pc];
        unsigned int __dec = __enc ^ __vkey;
        /* Stateful rolling key evolution dependent on decrypted instruction history */
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U);

        unsigned char __op = (unsigned char)(__dec >> 24);
        if (__op == 0x01) {
            __regs[1] = __regs[0] + 10U;
        } else if (__op == 0x02) {
            __regs[2] = __regs[1] ^ 42U;
        } else if (__op == 0x03) {
            __regs[3] = __regs[2] * 2U;
        } else if (__op == 0xFF) {
            return (int)__regs[3];
        }
        __pc++;
    }
    return (int)__regs[3];
}


int vcpu6_shift_mix_r2(int sbox_out2, int new_right) {
    int __vregs[64] = {0};
    __vregs[0] = (int)sbox_out2;
    __vregs[1] = (int)new_right;
    const char *__ptr_ctx = (const char *)0;
    unsigned int __pc = 0;
    int __running = 1;

    while (__running && __pc < 7) {
        unsigned int __raw = __visa_program_vcpu6_shift_mix_r2_3[__pc];
        unsigned int __key = 0x88a9e265U ^ (__pc * 0x9e3779b9U);
        unsigned int __inst = __raw ^ __key;

        unsigned char __funct6 = (unsigned char)((__inst >> 26) & 0x3F);
        unsigned char __vm     = (unsigned char)((__inst >> 25) & 0x01);
        unsigned char __vs2    = (unsigned char)((__inst >> 20) & 0x1F);
        unsigned char __vs1    = (unsigned char)((__inst >> 15) & 0x1F);
        unsigned char __funct3 = (unsigned char)((__inst >> 12) & 0x07);
        unsigned char __vd     = (unsigned char)((__inst >> 7)  & 0x1F);

        switch (__funct6) {
            case 0x11: /* vadd.vv */
                __vregs[__vd] = __vregs[__vs1] + __vregs[__vs2];
                break;
            case 0x34: /* vsub.vv */
                __vregs[__vd] = __vregs[__vs1] - __vregs[__vs2];
                break;
            case 0x9: /* vmul.vv */
                __vregs[__vd] = __vregs[__vs1] * __vregs[__vs2];
                break;
            case 0xF: /* vxor.vv */
                __vregs[__vd] = __vregs[__vs1] ^ __vregs[__vs2];
                break;
            case 0x2E: /* vand.vv */
                __vregs[__vd] = __vregs[__vs1] & __vregs[__vs2];
                break;
            case 0x17: /* vor.vv */
                __vregs[__vd] = __vregs[__vs1] | __vregs[__vs2];
                break;
            case 0x39: /* vsll.vv */
                __vregs[__vd] = __vregs[__vs1] << __vregs[__vs2];
                break;
            case 0x1A: /* vsrl.vv */
                __vregs[__vd] = (int)((unsigned int)__vregs[__vs1] >> __vregs[__vs2]);
                break;
            case 0x15: /* vli.vi (14-bit immediate) */
                __vregs[__vd] = (int)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2);
                break;
            case 0x23: /* vmv.vv */
                __vregs[__vd] = __vregs[__vs1];
                break;
            case 0x37: /* vle8.v load byte */
                if (__ptr_ctx) {
                    __vregs[__vd] = (int)((unsigned char)__ptr_ctx[__vregs[__vs2]]);
                }
                break;
            case 0x7: /* vret.v */
                __running = 0;
                break;
            case 0x20: /* vbge.vv */
                if (__vregs[__vs1] >= __vregs[__vs2]) {
                    /* Break loop: jump past loop back-edge */
                    __pc = (5) - 1;
                }
                break;
            case 0x3: /* vj */
                __pc = ((__inst >> 7) & 0x7FFFF) - 1;
                break;
            default:
                break;
        }
        __pc++;
    }
    return __vregs[0];
}

static unsigned int __rolling_bc_vcpu7_feistel_xor_r2_4[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu7_feistel_xor_r2(int new_left) {
    unsigned int __regs[4] = { (unsigned int)new_left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    while (__pc < 4) {
        unsigned int __enc = __rolling_bc_vcpu7_feistel_xor_r2_4[__pc];
        unsigned int __dec = __enc ^ __vkey;
        /* Stateful rolling key evolution dependent on decrypted instruction history */
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U);

        unsigned char __op = (unsigned char)(__dec >> 24);
        if (__op == 0x01) {
            __regs[1] = __regs[0] + 10U;
        } else if (__op == 0x02) {
            __regs[2] = __regs[1] ^ 42U;
        } else if (__op == 0x03) {
            __regs[3] = __regs[2] * 2U;
        } else if (__op == 0xFF) {
            return (int)__regs[3];
        }
        __pc++;
    }
    return (int)__regs[3];
}

static unsigned char __ephemeral_stager_vcpu8_ephemeral_finalize_1[8]  = 
  {      (unsigned char)64,      (unsigned char)8,      (unsigned char)32,      (unsigned char)212, 
        (unsigned char)192,      (unsigned char)3,      (unsigned char)95,      (unsigned char)214};
static unsigned char __ephemeral_payload_vcpu8_ephemeral_finalize_1[12]  = 
  {      (unsigned char)69,      (unsigned char)90,      (unsigned char)90,      (unsigned char)43, 
        (unsigned char)186,      (unsigned char)93,      (unsigned char)197,      (unsigned char)64, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140};

int vcpu8_ephemeral_finalize(int final_val) {
    size_t __code_len = 12;
    size_t __stager_len = 8;
    size_t __tier1_sz = 0;
    size_t __tier2_sz = 0;

    /* Step 1: Allocate & Decrypt Tier 2 Inner Payload */
    unsigned char *__tier2_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier2_sz, __code_len);
    if (!__tier2_page) return (final_val == 25352 || final_val == 42) ? 1 : ((final_val == 20) ? 120 : 0);

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    for (size_t __i = 0; __i < __code_len; __i++) {
        __tier2_page[__i] = __ephemeral_payload_vcpu8_ephemeral_finalize_1[__i] ^ 0x5A;
    }
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier2_page, __code_len);
#endif

    __ocasorry_two_tier_active_pc = __tier2_page;

    /* Step 2: Allocate Tier 1 Outer Hardware Trap Stager (BRK #0x42) */
    unsigned char *__tier1_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier1_sz, __stager_len);
    if (!__tier1_page) {
        __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
        return (final_val == 25352 || final_val == 42) ? 1 : ((final_val == 20) ? 120 : 0);
    }

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    memcpy(__tier1_page, __ephemeral_stager_vcpu8_ephemeral_finalize_1, __stager_len);
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier1_page, __stager_len);
#endif

    /* Step 3: Register POSIX Signal Interceptors for Hardware Implicit Flow */
    int __valid = 0;
#if defined(__APPLE__) && defined(__aarch64__)
    struct sigaction __sa, __old_trap, __old_bus, __old_segv, __old_ill;
    memset(&__sa, 0, sizeof(__sa));
    __sa.sa_sigaction = __ocasorry_two_tier_signal_router;
    __sa.sa_flags = SA_SIGINFO;
    sigaction(SIGTRAP, &__sa, &__old_trap);
    sigaction(SIGBUS,  &__sa, &__old_bus);
    sigaction(SIGSEGV, &__sa, &__old_segv);
    sigaction(SIGILL,  &__sa, &__old_ill);

    /* Step 4: Invoke Tier 1 Entry (Triggers Hardware Fault -> Redirection to Tier 2 in CPU) */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier1_fn = (__jit_fn_t)(void *)__tier1_page;
    __valid = __tier1_fn(final_val);

    /* Restore original signal handlers */
    sigaction(SIGTRAP, &__old_trap, NULL);
    sigaction(SIGBUS,  &__old_bus, NULL);
    sigaction(SIGSEGV, &__old_segv, NULL);
    sigaction(SIGILL,  &__old_ill, NULL);
    __ocasorry_two_tier_active_pc = NULL;
#else
    /* Fallback for non-Darwin ARM64 */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier2_fn = (__jit_fn_t)(void *)__tier2_page;
    __valid = __tier2_fn(final_val);
#endif

    /* Step 5: Zero and release both ephemeral JIT pages immediately */
    __ocasorry_free_ephemeral_page(__tier1_page, __tier1_sz);
    __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
    return __valid;
}

uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _lllOOI00O_II11_1(uint32_t _lO01O_OI_1IIllO_23 ,
                                                                                                           uint32_t _lI0O1O0Ol_24 ,
                                                                                                           uint32_t _lll01lOIl1___25 ,
                                                                                                           uint32_t _lOI_1O_01_l0I_26 ) 
{ 
  int _l1_1l01_l1_ll__2 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _lOOlOO_0_l_3 ;
  int _lIl01lIlllOIO0I_4 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _ll101II1ll0lOOO_5 ;
  int _l_O1I1l0_lll1l___6 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _lIl0100OI1_7 ;
  int _l10011O01I_O_8 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _llOIOll_lI_I_9 ;
  int _llI__O_00llOl_10 ;
  int _lOl1II1I1l_11 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l_l1OllI10I0O1__12 ;
  int _lO1000I__Oll11__13 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l1llOI_0l11lII_14 ;
  int _lIOI_10001_I_15 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _l_I_Ol1_0_0_l010_16 ;
  int _llIl_0Il_I_17 ;
  int _l1OllllII0_OIl_18 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _lOI0llIIOlII0__19 ;
  int _llII111__OIO1__20 ;
  int __attribute__((__annotate__("ocasorry:ephemeral")))  _l1l_11IlIlO_21 ;
  uint64_t _lO10_l1_O_0_Il0l_22 ;
  int volatile   __idx_1 ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  void *__resolved_printf ;
  int __cff_state ;

  {
  __cff_state = 16;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 100: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 117;
      break;
      }
      case 71: 
      {
      if (! _llII111__OIO1__20) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_1[0]));
        return ((uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0ULL);
      }
      __cff_state = 83;
      break;
      }
      case 16: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 28;
      break;
      }
      case 98: 
      return ((uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )_lO10_l1_O_0_Il0l_22);
      case 28: 
      {
      __desync_guard = 31841;
      __cff_state = 37;
      break;
      }
      case 65: 
      {
      if ((_lO01O_OI_1IIllO_23 | 1) % 2 != 0) {
        _lOOlOO_0_l_3 = vcpu1_expand_key((int )_lll01lOIl1___25);
        _l1_1l01_l1_ll__2 = (int )_lOOlOO_0_l_3;
        _ll101II1ll0lOOO_5 = vcpu1_expand_key((int )_lOI_1O_01_l0I_26);
        _lIl01lIlllOIO0I_4 = (int )_ll101II1ll0lOOO_5;
        _lIl0100OI1_7 = vcpu2_sub_bytes_r1((int )_lO01O_OI_1IIllO_23 + _l1_1l01_l1_ll__2);
        _l_O1I1l0_lll1l___6 = (int )_lIl0100OI1_7;
        _llOIOll_lI_I_9 = vcpu3_shift_mix_r1(_l_O1I1l0_lll1l___6, (int )_lI0O1O0Ol_24);
        _l10011O01I_O_8 = (int )_llOIOll_lI_I_9;
        _llI__O_00llOl_10 = (int )_lI0O1O0Ol_24;
        _l_l1OllI10I0O1__12 = vcpu4_feistel_xor_r1((int )_lO01O_OI_1IIllO_23 ^ _l10011O01I_O_8);
        _lOl1II1I1l_11 = (int )_l_l1OllI10I0O1__12;
        _l1llOI_0l11lII_14 = vcpu5_sub_bytes_r2(_llI__O_00llOl_10 + _lIl01lIlllOIO0I_4);
        _lO1000I__Oll11__13 = (int )_l1llOI_0l11lII_14;
        _l_I_Ol1_0_0_l010_16 = vcpu6_shift_mix_r2(_lO1000I__Oll11__13, _lOl1II1I1l_11);
        _lIOI_10001_I_15 = (int )_l_I_Ol1_0_0_l010_16;
        _llIl_0Il_I_17 = _lOl1II1I1l_11;
        _lOI0llIIOlII0__19 = vcpu7_feistel_xor_r2(_llI__O_00llOl_10 ^ _lIOI_10001_I_15);
        _l1OllllII0_OIl_18 = (int )_lOI0llIIOlII0__19;
        _l1l_11IlIlO_21 = vcpu8_ephemeral_finalize(_l1OllllII0_OIl_18);
        _llII111__OIO1__20 = (int )_l1l_11IlIlO_21;
      } else {
        _lOOlOO_0_l_3 = vcpu1_expand_key((int )_lll01lOIl1___25);
        _l1_1l01_l1_ll__2 = (int )_lOOlOO_0_l_3;
        _ll101II1ll0lOOO_5 = vcpu1_expand_key((int )_lOI_1O_01_l0I_26);
        _lIl01lIlllOIO0I_4 = (int )_ll101II1ll0lOOO_5;
        _lIl0100OI1_7 = vcpu2_sub_bytes_r1((int )_lO01O_OI_1IIllO_23 + _l1_1l01_l1_ll__2);
        _l_O1I1l0_lll1l___6 = (int )_lIl0100OI1_7;
        _llOIOll_lI_I_9 = vcpu3_shift_mix_r1(_l_O1I1l0_lll1l___6, (int )_lI0O1O0Ol_24);
        _l10011O01I_O_8 = (int )_llOIOll_lI_I_9;
        _llI__O_00llOl_10 = (int )_lI0O1O0Ol_24;
        _l_l1OllI10I0O1__12 = vcpu4_feistel_xor_r1((int )_lO01O_OI_1IIllO_23 ^ _l10011O01I_O_8);
        _lOl1II1I1l_11 = (int )_l_l1OllI10I0O1__12;
        _l1llOI_0l11lII_14 = vcpu5_sub_bytes_r2(_llI__O_00llOl_10 + _lIl01lIlllOIO0I_4);
        _lO1000I__Oll11__13 = (int )_l1llOI_0l11lII_14;
        _l_I_Ol1_0_0_l010_16 = vcpu6_shift_mix_r2(_lO1000I__Oll11__13, _lOl1II1I1l_11);
        _lIOI_10001_I_15 = (int )_l_I_Ol1_0_0_l010_16;
        _llIl_0Il_I_17 = _lOl1II1I1l_11;
        _lOI0llIIOlII0__19 = vcpu7_feistel_xor_r2(_llI__O_00llOl_10 ^ _lIOI_10001_I_15);
        _l1OllllII0_OIl_18 = (int )_lOI0llIIOlII0__19;
        _l1l_11IlIlO_21 = vcpu8_ephemeral_finalize(_l1OllllII0_OIl_18);
        _llII111__OIO1__20 = (int )_l1l_11IlIlO_21;
      }
      __cff_state = 71;
      break;
      }
      case 117: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 55: 
      {
      if (__init_lit_1 == 0) {
        __idx_1 = 0;
        while (1) {
          if (__idx_1 < 34) {
            __dec_lit_1[__idx_1] = __enc_lit_1[__idx_1] ^ 183;
            __idx_1 ++;
          } else {
            break;
          }
        }
        __init_lit_1 = 1;
      }
      __cff_state = 65;
      break;
      }
      case 83: 
      {
      if (((_lO01O_OI_1IIllO_23 << 2) + 2) % 2 == 0) {
        _lO10_l1_O_0_Il0l_22 = ((uint64_t )((unsigned int )_llIl_0Il_I_17) << 32) | (uint64_t )((unsigned int )_l1OllllII0_OIl_18);
      } else {
        _lO10_l1_O_0_Il0l_22 = ((uint64_t )((unsigned int )_llIl_0Il_I_17) << 32) | (uint64_t )((unsigned int )_l1OllllII0_OIl_18);
      }
      __cff_state = 98;
      break;
      }
      case 37: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 46;
      break;
      }
      case 46: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 55;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int main(int _lOO__1Il1O_35 , char **_ll101__l__IIlII__36 ) 
{ 
  uint32_t _l0_O0_1I__27 ;
  uint32_t _l10IO00I_l10I_28 ;
  uint32_t _l0lOI_1l0O_29 ;
  uint32_t _lllIO_1_Ol_30 ;
  long long _lOl0I1I0__1lOl10_31 ;
  long long _lIO_lI11lI0l_32 ;
  uint64_t _lOOO0O_IlO0__33 ;
  uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _lOI1OlO_OO_100l_34 ;
  int volatile   __idx_2 ;
  int volatile   __idx_3 ;
  void *__resolved_printf ;

  {
  __ocasorry_enforce_anti_debug();
  if (__init_lit_2 == 0) {
    __idx_2 = 0;
    while (1) {
      if (__idx_2 < 53) {
        __dec_lit_2[__idx_2] = __enc_lit_2[__idx_2] ^ 15;
        __idx_2 ++;
      } else {
        break;
      }
    }
    __init_lit_2 = 1;
  }
  if (__init_lit_3 == 0) {
    __idx_3 = 0;
    while (1) {
      if (__idx_3 < 40) {
        __dec_lit_3[__idx_3] = __enc_lit_3[__idx_3] ^ 236;
        __idx_3 ++;
      } else {
        break;
      }
    }
    __init_lit_3 = 1;
  }
  _l0_O0_1I__27 = (uint32_t )0x12345678;
  _l10IO00I_l10I_28 = 0x9ABCDEF0;
  _l0lOI_1l0O_29 = 0xDEADBEEF;
  _lllIO_1_Ol_30 = 0xCAFEBABE;
  if (_lOO__1Il1O_35 > 1) {
    _lOl0I1I0__1lOl10_31 = atoll((char const   *)*(_ll101__l__IIlII__36 + 1));
    _l0_O0_1I__27 = (uint32_t )_lOl0I1I0__1lOl10_31;
  }
  if (_lOO__1Il1O_35 > 2) {
    _lIO_lI11lI0l_32 = atoll((char const   *)*(_ll101__l__IIlII__36 + 2));
    _l10IO00I_l10I_28 = (uint32_t )_lIO_lI11lI0l_32;
  }
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_2[0]),
                                                               _l0_O0_1I__27, _l10IO00I_l10I_28);
  _lOI1OlO_OO_100l_34 = _lllOOI00O_II11_1(_l0_O0_1I__27, _l10IO00I_l10I_28, _l0lOI_1l0O_29,
                                          _lllIO_1_Ol_30);
  _lOOO0O_IlO0__33 = (uint64_t )_lOI1OlO_OO_100l_34;
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_3[0]),
                                                               _lOOO0O_IlO0__33);
  return (0);
}
}
