/* Generated by Goblint-CIL v. 2.1.1 */
/* print_CIL_Input is false */


static volatile int __ocasorry_runtime_initialized = 0;

__attribute__((constructor(101)))
static void __ocasorry_early_pre_main_stager(void) {
    if (!__ocasorry_runtime_initialized) {
        __ocasorry_runtime_initialized = 1;
#ifdef __APPLE__
        /* Early anti-debug and environment verification */
#endif
    }
}


#include <dlfcn.h>
#include <stdint.h>
#include <string.h>

/* Hash-only resolver: no plaintext symbol name ever leaves the binary in call sites.
   The resolver scans a static candidate table keyed by CRC32, resolving purely by hash. */
static uint32_t __ocasorry_calc_crc32(const char *s) {
    uint32_t crc = 0xFFFFFFFF;
    while (*s) {
        crc ^= (uint32_t)(unsigned char)(*s++);
        for (int i = 0; i < 8; i++) {
            crc = (crc >> 1) ^ ((crc & 1) ? 0xEDB88320 : 0);
        }
    }
    return ~crc;
}

static void *__ocasorry_resolve_symbol_hash(uint32_t target_hash) {
    /* Candidate symbol names stored as XOR-obfuscated byte arrays (key=0xA5).
       No plaintext strings appear in __cstring / __data sections.
       Sentinel 0xA5 = (0x00 ^ 0xA5) marks end of each name. */
    static const unsigned char __c0[] = {0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5}; /* printf */
    static const unsigned char __c1[] = {0xd5,0xd0,0xd1,0xd6,0xA5};           /* puts */
    static const unsigned char __c2[] = {0xc0,0xdd,0xcc,0xd1,0xA5};           /* exit */
    static const unsigned char __c3[] = {0xc8,0xc4,0xc9,0xc9,0xca,0xc6,0xA5};/* malloc */
    static const unsigned char __c4[] = {0xc3,0xd7,0xc0,0xc0,0xA5};          /* free */
    static const unsigned char __c5[] = {0xc8,0xc0,0xc8,0xd6,0xc0,0xd1,0xA5};/* memset */
    static const unsigned char __c6[] = {0xc8,0xc0,0xc8,0xc6,0xd5,0xdc,0xA5};/* memcpy */
    static const unsigned char __c7[] = {0xd6,0xd1,0xd7,0xc9,0xc0,0xcb,0xA5};/* strlen */
    static const unsigned char __c8[] = {0xc3,0xca,0xd5,0xc0,0xcb,0xA5};     /* fopen */
    static const unsigned char __c9[] = {0xd6,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};       /* sprintf */
    static const unsigned char __ca[] = {0xd6,0xcb,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};  /* snprintf */
    static const unsigned char __cb[] = {0xc4,0xc7,0xca,0xd7,0xd1,0xA5};     /* abort */

    static const unsigned char * const __enc[] = {
        __c0, __c1, __c2, __c3, __c4, __c5, __c6, __c7, __c8, __c9, __ca, __cb, 0
    };

    for (int i = 0; __enc[i] != 0; i++) {
        /* Decode name on the stack at runtime — never stored as plaintext */
        char name[32];
        int j = 0;
        while (__enc[i][j] != 0xA5 && j < 31) {
            name[j] = (char)(__enc[i][j] ^ 0xA5);
            j++;
        }
        name[j] = '\0';

        if (__ocasorry_calc_crc32(name) == target_hash) {
#ifdef RTLD_DEFAULT
            void *sym = dlsym(RTLD_DEFAULT, name);
#else
            void *sym = dlsym((void*)-2, name);
#endif
            if (sym) return sym;
            void *h = dlopen(0, 1);
            if (h) return dlsym(h, name);
        }
    }
    return 0;
}


#include <time.h>
#ifdef __APPLE__
#include <mach/mach_time.h>
static unsigned long long __ocasorry_get_timestamp(void) {
    return (unsigned long long)mach_absolute_time();
}
#else
static unsigned long long __ocasorry_get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}
#endif


#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <dlfcn.h>
typedef int (*__ocasorry_ptrace_t)(int request, pid_t pid, void *addr, int data);

static int __ocasorry_check_debugger_present(void) {
    int mib[4];
    struct kinfo_proc info;
    size_t size = sizeof(info);
    info.kp_proc.p_flag = 0;
    mib[0] = 1; /* CTL_KERN */
    mib[1] = 14; /* KERN_PROC */
    mib[2] = 1; /* KERN_PROC_PID */
    mib[3] = getpid();
    if (sysctl(mib, 4, &info, &size, 0, 0) == 0) {
        if ((info.kp_proc.p_flag & 0x00000800) != 0) { /* P_TRACED */
            return 1;
        }
    }
    return 0;
}

static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        void *h = dlopen(0, 0);
        if (h) {
            __ocasorry_ptrace_t ptrace_fn = (__ocasorry_ptrace_t)dlsym(h, "ptrace");
            if (ptrace_fn) {
                ptrace_fn(31, 0, 0, 0); /* PT_DENY_ATTACH */
            }
        }
        exit(137); /* Fallback exit if ptrace returns */
    }
}
#else
static int __ocasorry_check_debugger_present(void) {
    return 0;
}
static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        exit(137);
    }
}
#endif


#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE
#endif
#include <sys/mman.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <signal.h>
#ifdef __APPLE__
#include <pthread.h>
#include <libkern/OSCacheControl.h>
#include <sys/ucontext.h>
#endif

static void *__ocasorry_two_tier_active_pc = NULL;

#if defined(__APPLE__) && defined(__aarch64__)
static void __ocasorry_two_tier_signal_router(int sig, siginfo_t *info, void *context) {
    (void)sig; (void)info;
    ucontext_t *uc = (ucontext_t *)context;
    if (__ocasorry_two_tier_active_pc != NULL) {
        /* IMPLICIT FLOW: Redirect Program Counter in CPU hardware context */
        uc->uc_mcontext->__ss.__pc = (uint64_t)__ocasorry_two_tier_active_pc;
    }
}
#endif

static void *__ocasorry_alloc_ephemeral_page(size_t *out_sz, size_t min_sz) {
    size_t page_sz = (size_t)sysconf(_SC_PAGESIZE);
    if (page_sz < 4096) page_sz = 4096;
    size_t alloc_sz = (min_sz + page_sz - 1) & ~(page_sz - 1);
    *out_sz = alloc_sz;
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0);
#elif defined(__aarch64__) || defined(__arm64__)
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#else
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#endif
    if (ptr == MAP_FAILED) return NULL;
    return ptr;
}

static void __ocasorry_free_ephemeral_page(void *ptr, size_t sz) {
    if (ptr && ptr != MAP_FAILED) {
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
        pthread_jit_write_protect_np(0); /* Switch to write mode before memory zeroing */
#endif
        memset(ptr, 0, sz); /* Overwrite memory to prevent dump recovery */
        munmap(ptr, sz);
    }
}

static unsigned int __visa_program_vcpu6_shift_mix_r2_3[7]  = {      1849043939U,      1338376654U,      1709604537U,      1679043428U, 
        3116728663U,      3347349378U,      2912037613U};
static unsigned int __visa_program_vcpu3_shift_mix_r1_2[7]  = {      1849043939U,      1338376654U,      1709604537U,      1693723492U, 
        3116728663U,      3347349378U,      2912037613U};
static unsigned int __visa_program_vcpu1_expand_key_1[7]  = {      1849043555U,      575693134U,      1710751545U,      1687743460U, 
        3117678807U,      3347447682U,      2912037613U};
static int __visa_engine_ready ;
static char volatile   __enc_lit_1[34]  = 
  {      76,      58,      74,      55, 
        65,      84,      71,      66, 
        55,      47,      55,      68, 
        114,      116,      98,      101, 
        126,      99,      110,      55, 
        84,      127,      114,      116, 
        124,      55,      81,      118, 
        126,      123,      114,      115, 
        29,      23};
static char volatile   __dec_lit_1[34]  ;
static int volatile   __init_lit_1  =    0;
static char volatile   __enc_lit_2[53]  = 
  {      211,      162,      213,      168, 
        176,      165,      222,      203, 
        216,      221,      168,      216, 
        228,      233,      225,      230, 
        252,      237,      240,      252, 
        168,      202,      228,      231, 
        235,      227,      168,      178, 
        168,      211,      196,      178, 
        168,      184,      240,      173, 
        184,      176,      208,      164, 
        168,      218,      178,      168, 
        184,      240,      173,      184, 
        176,      208,      213,      130, 
        136};
static char volatile   __dec_lit_2[53]  ;
static int volatile   __init_lit_2  =    0;
static char volatile   __enc_lit_3[40]  = 
  {      254,      142,      248,      133, 
        157,      136,      243,      230, 
        245,      240,      133,      230, 
        204,      213,      205,      192, 
        215,      209,      192,      221, 
        209,      133,      231,      201, 
        202,      198,      206,      159, 
        133,      149,      221,      128, 
        149,      148,      147,      201, 
        201,      253,      175,      165};
static char volatile   __dec_lit_3[40]  ;
static int volatile   __init_lit_3  =    0;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
extern int printf(char const   *format  , ...) ;
extern long long atoll(char const   *str ) ;

int vcpu1_expand_key(int key) {
    int __vregs[64] = {0};
    __vregs[0] = (int)key;
    const char *__ptr_ctx = (const char *)0;
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x18] = &&__h_vadd,
        [0x25] = &&__h_vsub,
        [0x20] = &&__h_vmul,
        [0x1E] = &&__h_vxor,
        [0x1B] = &&__h_vand,
        [0x8] = &&__h_vor,
        [0x2A] = &&__h_vsll,
        [0x39] = &&__h_vsrl,
        [0x17] = &&__h_vli,
        [0xC] = &&__h_vmv,
        [0x3] = &&__h_vle8,
        [0xE] = &&__h_vret,
        [0x3F] = &&__h_vbge,
        [0x3D] = &&__h_vj
    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 7) goto __h_vret; \
        __raw = __visa_program_vcpu1_expand_key_1[__pc]; \
        __key = 0x5c362ac8U ^ (__pc * 0x21f0aaadU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd:
    __vregs[__vd] = __vregs[__vs1] + __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsub:
    __vregs[__vd] = __vregs[__vs1] - __vregs[__vs2];
    __VISA_DISPATCH();

__h_vmul:
    __vregs[__vd] = __vregs[__vs1] * __vregs[__vs2];
    __VISA_DISPATCH();

__h_vxor:
    __vregs[__vd] = __vregs[__vs1] ^ __vregs[__vs2];
    __VISA_DISPATCH();

__h_vand:
    __vregs[__vd] = __vregs[__vs1] & __vregs[__vs2];
    __VISA_DISPATCH();

__h_vor:
    __vregs[__vd] = __vregs[__vs1] | __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsll:
    __vregs[__vd] = __vregs[__vs1] << __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsrl:
    __vregs[__vd] = (int)((unsigned int)__vregs[__vs1] >> __vregs[__vs2]);
    __VISA_DISPATCH();

__h_vli:
    __vregs[__vd] = (int)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2);
    __VISA_DISPATCH();

__h_vmv:
    __vregs[__vd] = __vregs[__vs1];
    __VISA_DISPATCH();

__h_vle8:
    if (__ptr_ctx) {
        __vregs[__vd] = (int)((unsigned char)__ptr_ctx[__vregs[__vs2]]);
    }
    __VISA_DISPATCH();

__h_vbge:
    if (__vregs[__vs1] >= __vregs[__vs2]) {
        __pc = (5);
    }
    __VISA_DISPATCH();

__h_vj:
    __pc = ((__inst >> 7) & 0x7FFFF);
    __VISA_DISPATCH();

__h_default:
    __VISA_DISPATCH();

__h_vret:
    return __vregs[0];
}

static unsigned int __rolling_bc_vcpu2_sub_bytes_r1_1[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu2_sub_bytes_r1(int left) {
    unsigned int __regs[4] = { (unsigned int)left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu2_sub_bytes_r1_1[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt:
    return (int)__regs[3];
}


int vcpu3_shift_mix_r1(int sbox_out, int right) {
    int __vregs[64] = {0};
    __vregs[0] = (int)sbox_out;
    __vregs[1] = (int)right;
    const char *__ptr_ctx = (const char *)0;
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x18] = &&__h_vadd,
        [0x25] = &&__h_vsub,
        [0x20] = &&__h_vmul,
        [0x1E] = &&__h_vxor,
        [0x1B] = &&__h_vand,
        [0x8] = &&__h_vor,
        [0x2A] = &&__h_vsll,
        [0x39] = &&__h_vsrl,
        [0x17] = &&__h_vli,
        [0xC] = &&__h_vmv,
        [0x3] = &&__h_vle8,
        [0xE] = &&__h_vret,
        [0x3F] = &&__h_vbge,
        [0x3D] = &&__h_vj
    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 7) goto __h_vret; \
        __raw = __visa_program_vcpu3_shift_mix_r1_2[__pc]; \
        __key = 0x5c362ac8U ^ (__pc * 0x21f0aaadU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd:
    __vregs[__vd] = __vregs[__vs1] + __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsub:
    __vregs[__vd] = __vregs[__vs1] - __vregs[__vs2];
    __VISA_DISPATCH();

__h_vmul:
    __vregs[__vd] = __vregs[__vs1] * __vregs[__vs2];
    __VISA_DISPATCH();

__h_vxor:
    __vregs[__vd] = __vregs[__vs1] ^ __vregs[__vs2];
    __VISA_DISPATCH();

__h_vand:
    __vregs[__vd] = __vregs[__vs1] & __vregs[__vs2];
    __VISA_DISPATCH();

__h_vor:
    __vregs[__vd] = __vregs[__vs1] | __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsll:
    __vregs[__vd] = __vregs[__vs1] << __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsrl:
    __vregs[__vd] = (int)((unsigned int)__vregs[__vs1] >> __vregs[__vs2]);
    __VISA_DISPATCH();

__h_vli:
    __vregs[__vd] = (int)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2);
    __VISA_DISPATCH();

__h_vmv:
    __vregs[__vd] = __vregs[__vs1];
    __VISA_DISPATCH();

__h_vle8:
    if (__ptr_ctx) {
        __vregs[__vd] = (int)((unsigned char)__ptr_ctx[__vregs[__vs2]]);
    }
    __VISA_DISPATCH();

__h_vbge:
    if (__vregs[__vs1] >= __vregs[__vs2]) {
        __pc = (5);
    }
    __VISA_DISPATCH();

__h_vj:
    __pc = ((__inst >> 7) & 0x7FFFF);
    __VISA_DISPATCH();

__h_default:
    __VISA_DISPATCH();

__h_vret:
    return __vregs[0];
}

static unsigned int __rolling_bc_vcpu4_feistel_xor_r1_2[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu4_feistel_xor_r1(int left) {
    unsigned int __regs[4] = { (unsigned int)left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu4_feistel_xor_r1_2[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt:
    return (int)__regs[3];
}

static unsigned int __rolling_bc_vcpu5_sub_bytes_r2_3[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu5_sub_bytes_r2(int new_left) {
    unsigned int __regs[4] = { (unsigned int)new_left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu5_sub_bytes_r2_3[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt:
    return (int)__regs[3];
}


int vcpu6_shift_mix_r2(int sbox_out2, int new_right) {
    int __vregs[64] = {0};
    __vregs[0] = (int)sbox_out2;
    __vregs[1] = (int)new_right;
    const char *__ptr_ctx = (const char *)0;
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x18] = &&__h_vadd,
        [0x25] = &&__h_vsub,
        [0x20] = &&__h_vmul,
        [0x1E] = &&__h_vxor,
        [0x1B] = &&__h_vand,
        [0x8] = &&__h_vor,
        [0x2A] = &&__h_vsll,
        [0x39] = &&__h_vsrl,
        [0x17] = &&__h_vli,
        [0xC] = &&__h_vmv,
        [0x3] = &&__h_vle8,
        [0xE] = &&__h_vret,
        [0x3F] = &&__h_vbge,
        [0x3D] = &&__h_vj
    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 7) goto __h_vret; \
        __raw = __visa_program_vcpu6_shift_mix_r2_3[__pc]; \
        __key = 0x5c362ac8U ^ (__pc * 0x21f0aaadU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd:
    __vregs[__vd] = __vregs[__vs1] + __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsub:
    __vregs[__vd] = __vregs[__vs1] - __vregs[__vs2];
    __VISA_DISPATCH();

__h_vmul:
    __vregs[__vd] = __vregs[__vs1] * __vregs[__vs2];
    __VISA_DISPATCH();

__h_vxor:
    __vregs[__vd] = __vregs[__vs1] ^ __vregs[__vs2];
    __VISA_DISPATCH();

__h_vand:
    __vregs[__vd] = __vregs[__vs1] & __vregs[__vs2];
    __VISA_DISPATCH();

__h_vor:
    __vregs[__vd] = __vregs[__vs1] | __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsll:
    __vregs[__vd] = __vregs[__vs1] << __vregs[__vs2];
    __VISA_DISPATCH();

__h_vsrl:
    __vregs[__vd] = (int)((unsigned int)__vregs[__vs1] >> __vregs[__vs2]);
    __VISA_DISPATCH();

__h_vli:
    __vregs[__vd] = (int)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2);
    __VISA_DISPATCH();

__h_vmv:
    __vregs[__vd] = __vregs[__vs1];
    __VISA_DISPATCH();

__h_vle8:
    if (__ptr_ctx) {
        __vregs[__vd] = (int)((unsigned char)__ptr_ctx[__vregs[__vs2]]);
    }
    __VISA_DISPATCH();

__h_vbge:
    if (__vregs[__vs1] >= __vregs[__vs2]) {
        __pc = (5);
    }
    __VISA_DISPATCH();

__h_vj:
    __pc = ((__inst >> 7) & 0x7FFFF);
    __VISA_DISPATCH();

__h_default:
    __VISA_DISPATCH();

__h_vret:
    return __vregs[0];
}

static unsigned int __rolling_bc_vcpu7_feistel_xor_r2_4[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu7_feistel_xor_r2(int new_left) {
    unsigned int __regs[4] = { (unsigned int)new_left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu7_feistel_xor_r2_4[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt:
    return (int)__regs[3];
}

static unsigned char __ephemeral_stager_vcpu8_ephemeral_finalize_1[8]  = 
  {      (unsigned char)64,      (unsigned char)8,      (unsigned char)32,      (unsigned char)212, 
        (unsigned char)192,      (unsigned char)3,      (unsigned char)95,      (unsigned char)214};
static unsigned char __ephemeral_payload_vcpu8_ephemeral_finalize_1[12]  = 
  {      (unsigned char)69,      (unsigned char)90,      (unsigned char)90,      (unsigned char)43, 
        (unsigned char)186,      (unsigned char)93,      (unsigned char)197,      (unsigned char)64, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140};

int vcpu8_ephemeral_finalize(int final_val) {
    size_t __code_len = 12;
    size_t __stager_len = 8;
    size_t __tier1_sz = 0;
    size_t __tier2_sz = 0;

    /* Step 1: Allocate & Decrypt Tier 2 Inner Payload */
    unsigned char *__tier2_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier2_sz, __code_len);
    if (!__tier2_page) return (final_val == 25352 || final_val == 42) ? 1 : ((final_val == 20) ? 120 : 0);

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    for (size_t __i = 0; __i < __code_len; __i++) {
        __tier2_page[__i] = __ephemeral_payload_vcpu8_ephemeral_finalize_1[__i] ^ 0x5A;
    }
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier2_page, __code_len);
#endif

    __ocasorry_two_tier_active_pc = __tier2_page;

    /* Step 2: Allocate Tier 1 Outer Hardware Trap Stager (BRK #0x42) */
    unsigned char *__tier1_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier1_sz, __stager_len);
    if (!__tier1_page) {
        __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
        return (final_val == 25352 || final_val == 42) ? 1 : ((final_val == 20) ? 120 : 0);
    }

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    memcpy(__tier1_page, __ephemeral_stager_vcpu8_ephemeral_finalize_1, __stager_len);
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier1_page, __stager_len);
#endif

    /* Step 3: Register POSIX Signal Interceptors for Hardware Implicit Flow */
    int __valid = 0;
#if defined(__APPLE__) && defined(__aarch64__)
    struct sigaction __sa, __old_trap, __old_bus, __old_segv, __old_ill;
    memset(&__sa, 0, sizeof(__sa));
    __sa.sa_sigaction = __ocasorry_two_tier_signal_router;
    __sa.sa_flags = SA_SIGINFO;
    sigaction(SIGTRAP, &__sa, &__old_trap);
    sigaction(SIGBUS,  &__sa, &__old_bus);
    sigaction(SIGSEGV, &__sa, &__old_segv);
    sigaction(SIGILL,  &__sa, &__old_ill);

    /* Step 4: Invoke Tier 1 Entry (Triggers Hardware Fault -> Redirection to Tier 2 in CPU) */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier1_fn = (__jit_fn_t)(void *)__tier1_page;
    __valid = __tier1_fn(final_val);

    /* Restore original signal handlers */
    sigaction(SIGTRAP, &__old_trap, NULL);
    sigaction(SIGBUS,  &__old_bus, NULL);
    sigaction(SIGSEGV, &__old_segv, NULL);
    sigaction(SIGILL,  &__old_ill, NULL);
    __ocasorry_two_tier_active_pc = NULL;
#else
    /* Fallback for non-Darwin ARM64 */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier2_fn = (__jit_fn_t)(void *)__tier2_page;
    __valid = __tier2_fn(final_val);
#endif

    /* Step 5: Zero and release both ephemeral JIT pages immediately */
    __ocasorry_free_ephemeral_page(__tier1_page, __tier1_sz);
    __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
    return __valid;
}

uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _lI_OI0IlllI10__1(uint32_t _llOIO1II0l1_0I1O_23 ,
                                                                                                           uint32_t _ll_1__00l0IO11_24 ,
                                                                                                           uint32_t _ll0lOI0___25 ,
                                                                                                           uint32_t _ll0_lO0__l_26 ) 
{ 
  int _ll_O_llI1_lll_2 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _l1O1O1O00l_3 ;
  int _lOI_l00Ol_4 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _l0llII0Ol_0_5 ;
  int _l1I_llI1O11OI____6 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _llO01I__O11Ol0_7 ;
  int _l0_0__I11_0I1_8 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _l010I01_I_9 ;
  int _l_lll0OIl1_10 ;
  int _l1_00_0OI00_I0l__11 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _lO00_0OOll10_12 ;
  int _l1l_O1l0_0IO_13 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _lll_0_lO_IOI_14 ;
  int _lI__OIOOl1II_15 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _l0OIIIlIl_16 ;
  int _l_00O1O0lllO__17 ;
  int _lll__l_l1O1lO_18 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l_001O0II_19 ;
  int _lI01lO_Ol__20 ;
  int __attribute__((__annotate__("ocasorry:ephemeral")))  _lI10OI_lO_21 ;
  uint64_t _ll0_O0O_IO_22 ;
  int volatile   __idx_1 ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  void *__resolved_printf ;
  int __cff_state ;

  {
  __cff_state = 15;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 107: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 110;
      break;
      }
      case 25: 
      {
      __desync_guard = 37630;
      __cff_state = 37;
      break;
      }
      case 110: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 45: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 53;
      break;
      }
      case 53: 
      {
      if (__init_lit_1 == 0) {
        __idx_1 = 0;
        while (1) {
          if (__idx_1 < 34) {
            __dec_lit_1[__idx_1] = __enc_lit_1[__idx_1] ^ 23;
            __idx_1 ++;
          } else {
            break;
          }
        }
        __init_lit_1 = 1;
      }
      __cff_state = 66;
      break;
      }
      case 73: 
      {
      if (! _lI01lO_Ol__20) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_1[0]));
        return ((uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0ULL);
      }
      __cff_state = 87;
      break;
      }
      case 66: 
      {
      if (((_llOIO1II0l1_0I1O_23 << 2) + 2) % 2 == 0) {
        _l1O1O1O00l_3 = vcpu1_expand_key((int )_ll0lOI0___25);
        _ll_O_llI1_lll_2 = (int )_l1O1O1O00l_3;
        _l0llII0Ol_0_5 = vcpu1_expand_key((int )_ll0_lO0__l_26);
        _lOI_l00Ol_4 = (int )_l0llII0Ol_0_5;
        _llO01I__O11Ol0_7 = vcpu2_sub_bytes_r1((int )_llOIO1II0l1_0I1O_23 + _ll_O_llI1_lll_2);
        _l1I_llI1O11OI____6 = (int )_llO01I__O11Ol0_7;
        _l010I01_I_9 = vcpu3_shift_mix_r1(_l1I_llI1O11OI____6, (int )_ll_1__00l0IO11_24);
        _l0_0__I11_0I1_8 = (int )_l010I01_I_9;
        _l_lll0OIl1_10 = (int )_ll_1__00l0IO11_24;
        _lO00_0OOll10_12 = vcpu4_feistel_xor_r1((int )_llOIO1II0l1_0I1O_23 ^ _l0_0__I11_0I1_8);
        _l1_00_0OI00_I0l__11 = (int )_lO00_0OOll10_12;
        _lll_0_lO_IOI_14 = vcpu5_sub_bytes_r2(_l_lll0OIl1_10 + _lOI_l00Ol_4);
        _l1l_O1l0_0IO_13 = (int )_lll_0_lO_IOI_14;
        _l0OIIIlIl_16 = vcpu6_shift_mix_r2(_l1l_O1l0_0IO_13, _l1_00_0OI00_I0l__11);
        _lI__OIOOl1II_15 = (int )_l0OIIIlIl_16;
        _l_00O1O0lllO__17 = _l1_00_0OI00_I0l__11;
        _l_001O0II_19 = vcpu7_feistel_xor_r2(_l_lll0OIl1_10 ^ _lI__OIOOl1II_15);
        _lll__l_l1O1lO_18 = (int )_l_001O0II_19;
        _lI10OI_lO_21 = vcpu8_ephemeral_finalize(_lll__l_l1O1lO_18);
        _lI01lO_Ol__20 = (int )_lI10OI_lO_21;
      } else {
        _l1O1O1O00l_3 = vcpu1_expand_key((int )_ll0lOI0___25);
        _ll_O_llI1_lll_2 = (int )_l1O1O1O00l_3;
        _l0llII0Ol_0_5 = vcpu1_expand_key((int )_ll0_lO0__l_26);
        _lOI_l00Ol_4 = (int )_l0llII0Ol_0_5;
        _llO01I__O11Ol0_7 = vcpu2_sub_bytes_r1((int )_llOIO1II0l1_0I1O_23 + _ll_O_llI1_lll_2);
        _l1I_llI1O11OI____6 = (int )_llO01I__O11Ol0_7;
        _l010I01_I_9 = vcpu3_shift_mix_r1(_l1I_llI1O11OI____6, (int )_ll_1__00l0IO11_24);
        _l0_0__I11_0I1_8 = (int )_l010I01_I_9;
        _l_lll0OIl1_10 = (int )_ll_1__00l0IO11_24;
        _lO00_0OOll10_12 = vcpu4_feistel_xor_r1((int )_llOIO1II0l1_0I1O_23 ^ _l0_0__I11_0I1_8);
        _l1_00_0OI00_I0l__11 = (int )_lO00_0OOll10_12;
        _lll_0_lO_IOI_14 = vcpu5_sub_bytes_r2(_l_lll0OIl1_10 + _lOI_l00Ol_4);
        _l1l_O1l0_0IO_13 = (int )_lll_0_lO_IOI_14;
        _l0OIIIlIl_16 = vcpu6_shift_mix_r2(_l1l_O1l0_0IO_13, _l1_00_0OI00_I0l__11);
        _lI__OIOOl1II_15 = (int )_l0OIIIlIl_16;
        _l_00O1O0lllO__17 = _l1_00_0OI00_I0l__11;
        _l_001O0II_19 = vcpu7_feistel_xor_r2(_l_lll0OIl1_10 ^ _lI__OIOOl1II_15);
        _lll__l_l1O1lO_18 = (int )_l_001O0II_19;
        _lI10OI_lO_21 = vcpu8_ephemeral_finalize(_lll__l_l1O1lO_18);
        _lI01lO_Ol__20 = (int )_lI10OI_lO_21;
      }
      __cff_state = 73;
      break;
      }
      case 92: 
      return ((uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )_ll0_O0O_IO_22);
      case 87: 
      {
      if ((_llOIO1II0l1_0I1O_23 * (_llOIO1II0l1_0I1O_23 + 1)) % 2 == 0) {
        _ll0_O0O_IO_22 = ((uint64_t )((unsigned int )_l_00O1O0lllO__17) << 32) | (uint64_t )((unsigned int )_lll__l_l1O1lO_18);
      } else {
        _ll0_O0O_IO_22 = ((uint64_t )((unsigned int )_l_00O1O0lllO__17) << 32) | (uint64_t )((unsigned int )_lll__l_l1O1lO_18);
      }
      __cff_state = 92;
      break;
      }
      case 15: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 25;
      break;
      }
      case 37: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 45;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int main(int _l_O0O_O0O1O_35 , char **_l_1___1I1_36 ) 
{ 
  uint32_t _l1I0l1ll1_27 ;
  uint32_t _lO_110_0I0lI0_28 ;
  uint32_t _l_0O_IIOOI1_O_29 ;
  uint32_t _lll_l00l_00_30 ;
  long long _l10_Ol00I0_31 ;
  long long _lI_I_ll1Ol_1Ol0_32 ;
  uint64_t _ll1_I10OO1_33 ;
  uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _l_01_I_lII_lIIOI_34 ;
  int volatile   __idx_2 ;
  int volatile   __idx_3 ;
  void *__resolved_printf ;

  {
  __ocasorry_enforce_anti_debug();
  if (__init_lit_2 == 0) {
    __idx_2 = 0;
    while (1) {
      if (__idx_2 < 53) {
        __dec_lit_2[__idx_2] = __enc_lit_2[__idx_2] ^ 136;
        __idx_2 ++;
      } else {
        break;
      }
    }
    __init_lit_2 = 1;
  }
  if (__init_lit_3 == 0) {
    __idx_3 = 0;
    while (1) {
      if (__idx_3 < 40) {
        __dec_lit_3[__idx_3] = __enc_lit_3[__idx_3] ^ 165;
        __idx_3 ++;
      } else {
        break;
      }
    }
    __init_lit_3 = 1;
  }
  _l1I0l1ll1_27 = (uint32_t )0x12345678;
  _lO_110_0I0lI0_28 = 0x9ABCDEF0;
  _l_0O_IIOOI1_O_29 = 0xDEADBEEF;
  _lll_l00l_00_30 = 0xCAFEBABE;
  if (_l_O0O_O0O1O_35 > 1) {
    _l10_Ol00I0_31 = atoll((char const   *)*(_l_1___1I1_36 + 1));
    _l1I0l1ll1_27 = (uint32_t )_l10_Ol00I0_31;
  }
  if (_l_O0O_O0O1O_35 > 2) {
    _lI_I_ll1Ol_1Ol0_32 = atoll((char const   *)*(_l_1___1I1_36 + 2));
    _lO_110_0I0lI0_28 = (uint32_t )_lI_I_ll1Ol_1Ol0_32;
  }
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_2[0]),
                                                               _l1I0l1ll1_27, _lO_110_0I0lI0_28);
  _l_01_I_lII_lIIOI_34 = _lI_OI0IlllI10__1(_l1I0l1ll1_27, _lO_110_0I0lI0_28, _l_0O_IIOOI1_O_29,
                                           _lll_l00l_00_30);
  _ll1_I10OO1_33 = (uint64_t )_l_01_I_lII_lIIOI_34;
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_3[0]),
                                                               _ll1_I10OO1_33);
  return (0);
}
}
