/* Generated by Goblint-CIL v. 2.0.9 */
/* print_CIL_Input is false */

static char __enc_lit_1[33]  = 
  {      43,      90,      45,      80, 
        32,      28,      17,      25, 
        30,      4,      21,      8, 
        4,      80,      18,      28, 
        31,      19,      27,      80, 
        74,      80,      64,      8, 
        85,      64,      65,      70, 
        28,      28,      40,      122, 
        112};
static char __dec_lit_1[33]  ;
static int __init_lit_1  =    0;
static char __enc_lit_2[33]  = 
  {      66,      50,      68,      57, 
        90,      112,      105,      113, 
        124,      107,      109,      124, 
        97,      109,      57,      123, 
        117,      118,      122,      114, 
        35,      57,      41,      97, 
        60,      41,      40,      47, 
        117,      117,      65,      19, 
        25};
static char __dec_lit_2[33]  ;
static int __init_lit_2  =    0;
#line 7 "examples/02_aes_sbox_mini.c"
typedef unsigned int uint32_t;
#line 8 "examples/02_aes_sbox_mini.c"
typedef unsigned long long uint64_t;
#line 10
extern int printf(char const   *format  , ...) ;
#line 11
extern unsigned long long atoll(char const   *str ) ;
#line 14 "examples/02_aes_sbox_mini.c"
uint32_t non_linear_round(uint32_t left , uint32_t right , uint32_t round_key ) 
{ 
  uint32_t mixed ;
  uint32_t poly ;
  uint32_t rotated ;
  uint32_t sbox_out ;

  {
  if ((left & ~ left) != 0) {
    left = 22829;
  }
#line 15
  mixed = (unsigned int )((unsigned int )1748265675 * ((unsigned int )10979 * (unsigned int )(((left + round_key) | right) - ((left + round_key) & right)) + (unsigned int )230472419) - (unsigned int )942026753);
#line 16
  poly = (uint32_t )((unsigned int )-1177641125 * ((unsigned int )30931 * (unsigned int )((mixed * 3U ^ ((mixed ^ 0x9E3779B9) - (right & 255U))) + ((mixed * 3U & ((mixed ^ 0x9E3779B9) - (right & 255U))) << 1)) + (unsigned int )57078216) - (unsigned int )1018374680);
#line 17
  rotated = (poly << 7) | (poly >> 25);
#line 18
  sbox_out = (unsigned int )((unsigned int )-2067708189 * ((unsigned int )11979 * (unsigned int )((rotated | ((left | right) + (left & right))) - (rotated & ((left | right) + (left & right)))) + (unsigned int )732661547) - (unsigned int )-1283875551);
#line 19
  return (sbox_out);
}
}
#line 22 "examples/02_aes_sbox_mini.c"
uint64_t feistel_encrypt_block(uint64_t plaintext , uint32_t key1 , uint32_t key2 ) 
{ 
  uint32_t l ;
  uint32_t r ;
  uint32_t f1 ;
  uint32_t tmp ;
  uint32_t new_l ;
  uint32_t new_r ;
  uint32_t f2 ;
  uint32_t tmp___0 ;
  uint32_t final_l ;
  uint32_t final_r ;

  {
  if ((plaintext & ~ plaintext) != 0) {
    plaintext = 28462;
  }
#line 23
  l = (uint32_t )(plaintext >> 32);
#line 24
  r = (uint32_t )(plaintext & 4294967295ULL);
#line 27
  tmp = non_linear_round(l, r, key1);
#line 27
  f1 = tmp;
#line 28
  new_l = r;
#line 29
  new_r = (unsigned int )((unsigned int )643862379 * ((unsigned int )9539 * (unsigned int )((l | f1) - (l & f1)) + (unsigned int )629374076) - (unsigned int )922635220);
#line 32
  tmp___0 = non_linear_round(new_l, new_r, key2);
#line 32
  f2 = tmp___0;
#line 33
  final_l = new_r;
#line 34
  final_r = (unsigned int )((unsigned int )1687699625 * ((unsigned int )25497 * (unsigned int )(((new_l | f2) + (~ new_l & ~ f2)) + 1) + (unsigned int )1004883319) - (unsigned int )1483072399);
#line 36
  return (((uint64_t )final_l << 32) | (uint64_t )final_r);
}
}
#line 39 "examples/02_aes_sbox_mini.c"
int main(int argc , char **argv ) 
{ 
  uint64_t data ;
  uint32_t k1 ;
  uint32_t k2 ;
  unsigned long long tmp ;
  uint64_t ciphertext ;
  uint64_t tmp___0 ;
  int __idx_1 ;
  int __idx_2 ;

  {
  if (__init_lit_1 == 0) {
    __idx_1 = 0;
    while (1) {
      if (__idx_1 < 33) {
        __dec_lit_1[__idx_1] = (char )((unsigned int )-84985181 * ((unsigned int )18699 * (unsigned int )((__enc_lit_1[__idx_1] | 112) - (__enc_lit_1[__idx_1] & 112)) + (unsigned int )388605398) - (unsigned int )-35581118);
        __idx_1 = (int )((unsigned int )-153750341 * ((unsigned int )12403 * (unsigned int )((__idx_1 ^ 1) + ((__idx_1 & 1) << 1)) + (unsigned int )1071857834) - (unsigned int )1846821934);
      } else {
        break;
      }
    }
    __init_lit_1 = 1;
  }
  if (__init_lit_2 == 0) {
    __idx_2 = 0;
    while (1) {
      if (__idx_2 < 33) {
        __dec_lit_2[__idx_2] = (char )((unsigned int )1699196051 * ((unsigned int )20891 * (unsigned int )(((__enc_lit_2[__idx_2] | 25) + (~ __enc_lit_2[__idx_2] & ~ 25)) + 1) + (unsigned int )910738097) - (unsigned int )-491931741);
        __idx_2 = (int )((unsigned int )568106067 * ((unsigned int )2011 * (unsigned int )((__idx_2 | 1) + (__idx_2 & 1)) + (unsigned int )260062387) - (unsigned int )1751433737);
      } else {
        break;
      }
    }
    __init_lit_2 = 1;
  }
#line 40
  data = 0x0123456789ABCDEFULL;
#line 41
  k1 = 0xDEADBEEF;
#line 42
  k2 = 0xCAFEBABE;
#line 44
  if (argc > 1) {
#line 44
    tmp = atoll((char const   *)*(argv + 1));
#line 44
    data = tmp;
  }
#line 46
  printf((char const   *)(& __dec_lit_1[0]), data);
#line 47
  tmp___0 = feistel_encrypt_block(data, k1, k2);
#line 47
  ciphertext = tmp___0;
#line 48
  printf((char const   *)(& __dec_lit_2[0]), ciphertext);
#line 50
  return (0);
}
}
