/* Generated by Goblint-CIL v. 2.1.1 */
/* print_CIL_Input is false */


static volatile int __ocasorry_runtime_initialized = 0;

__attribute__((constructor(101)))
static void __ocasorry_early_pre_main_stager(void) {
    if (!__ocasorry_runtime_initialized) {
        __ocasorry_runtime_initialized = 1;
#ifdef __APPLE__
        /* Early anti-debug and environment verification */
#endif
    }
}


#include <dlfcn.h>
#include <stdint.h>
#include <string.h>

/* Hash-only resolver: no plaintext symbol name ever leaves the binary in call sites.
   The resolver scans a static candidate table keyed by CRC32, resolving purely by hash. */
static uint32_t __ocasorry_calc_crc32(const char *s) {
    uint32_t crc = 0xFFFFFFFF;
    while (*s) {
        crc ^= (uint32_t)(unsigned char)(*s++);
        for (int i = 0; i < 8; i++) {
            crc = (crc >> 1) ^ ((crc & 1) ? 0xEDB88320 : 0);
        }
    }
    return ~crc;
}

static void *__ocasorry_resolve_symbol_hash(uint32_t target_hash) {
    /* Candidate symbol names stored as XOR-obfuscated byte arrays (key=0xA5).
       No plaintext strings appear in __cstring / __data sections.
       Sentinel 0xA5 = (0x00 ^ 0xA5) marks end of each name. */
    static const unsigned char __c0[] = {0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5}; /* printf */
    static const unsigned char __c1[] = {0xd5,0xd0,0xd1,0xd6,0xA5};           /* puts */
    static const unsigned char __c2[] = {0xc0,0xdd,0xcc,0xd1,0xA5};           /* exit */
    static const unsigned char __c3[] = {0xc8,0xc4,0xc9,0xc9,0xca,0xc6,0xA5};/* malloc */
    static const unsigned char __c4[] = {0xc3,0xd7,0xc0,0xc0,0xA5};          /* free */
    static const unsigned char __c5[] = {0xc8,0xc0,0xc8,0xd6,0xc0,0xd1,0xA5};/* memset */
    static const unsigned char __c6[] = {0xc8,0xc0,0xc8,0xc6,0xd5,0xdc,0xA5};/* memcpy */
    static const unsigned char __c7[] = {0xd6,0xd1,0xd7,0xc9,0xc0,0xcb,0xA5};/* strlen */
    static const unsigned char __c8[] = {0xc3,0xca,0xd5,0xc0,0xcb,0xA5};     /* fopen */
    static const unsigned char __c9[] = {0xd6,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};       /* sprintf */
    static const unsigned char __ca[] = {0xd6,0xcb,0xd5,0xd7,0xcc,0xcb,0xd1,0xc3,0xA5};  /* snprintf */
    static const unsigned char __cb[] = {0xc4,0xc7,0xca,0xd7,0xd1,0xA5};     /* abort */

    static const unsigned char * const __enc[] = {
        __c0, __c1, __c2, __c3, __c4, __c5, __c6, __c7, __c8, __c9, __ca, __cb, 0
    };

    for (int i = 0; __enc[i] != 0; i++) {
        /* Decode name on the stack at runtime — never stored as plaintext */
        char name[32];
        int j = 0;
        while (__enc[i][j] != 0xA5 && j < 31) {
            name[j] = (char)(__enc[i][j] ^ 0xA5);
            j++;
        }
        name[j] = '\0';

        if (__ocasorry_calc_crc32(name) == target_hash) {
#ifdef RTLD_DEFAULT
            void *sym = dlsym(RTLD_DEFAULT, name);
#else
            void *sym = dlsym((void*)-2, name);
#endif
            if (sym) return sym;
            void *h = dlopen(0, 1);
            if (h) return dlsym(h, name);
        }
    }
    return 0;
}


#include <time.h>
#ifdef __APPLE__
#include <mach/mach_time.h>
static unsigned long long __ocasorry_get_timestamp(void) {
    return (unsigned long long)mach_absolute_time();
}
#else
static unsigned long long __ocasorry_get_timestamp(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}
#endif


#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

#ifdef __APPLE__
#include <sys/sysctl.h>
#include <dlfcn.h>
typedef int (*__ocasorry_ptrace_t)(int request, pid_t pid, void *addr, int data);

static int __ocasorry_check_debugger_present(void) {
    int mib[4];
    struct kinfo_proc info;
    size_t size = sizeof(info);
    info.kp_proc.p_flag = 0;
    mib[0] = 1; /* CTL_KERN */
    mib[1] = 14; /* KERN_PROC */
    mib[2] = 1; /* KERN_PROC_PID */
    mib[3] = getpid();
    if (sysctl(mib, 4, &info, &size, 0, 0) == 0) {
        if ((info.kp_proc.p_flag & 0x00000800) != 0) { /* P_TRACED */
            return 1;
        }
    }
    return 0;
}

static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        void *h = dlopen(0, 0);
        if (h) {
            __ocasorry_ptrace_t ptrace_fn = (__ocasorry_ptrace_t)dlsym(h, "ptrace");
            if (ptrace_fn) {
                ptrace_fn(31, 0, 0, 0); /* PT_DENY_ATTACH */
            }
        }
        exit(137); /* Fallback exit if ptrace returns */
    }
}
#else
static int __ocasorry_check_debugger_present(void) {
    return 0;
}
static void __ocasorry_enforce_anti_debug(void) {
    if (__ocasorry_check_debugger_present()) {
        exit(137);
    }
}
#endif


#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE
#endif
#include <sys/mman.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <signal.h>
#ifdef __APPLE__
#include <pthread.h>
#include <libkern/OSCacheControl.h>
#include <sys/ucontext.h>
#endif

static void *__ocasorry_two_tier_active_pc = NULL;

#if defined(__APPLE__) && defined(__aarch64__)
static void __ocasorry_two_tier_signal_router(int sig, siginfo_t *info, void *context) {
    (void)sig; (void)info;
    ucontext_t *uc = (ucontext_t *)context;
    if (__ocasorry_two_tier_active_pc != NULL) {
        /* IMPLICIT FLOW: Redirect Program Counter in CPU hardware context */
        uc->uc_mcontext->__ss.__pc = (uint64_t)__ocasorry_two_tier_active_pc;
    }
}
#endif

static void *__ocasorry_alloc_ephemeral_page(size_t *out_sz, size_t min_sz) {
    size_t page_sz = (size_t)sysconf(_SC_PAGESIZE);
    if (page_sz < 4096) page_sz = 4096;
    size_t alloc_sz = (min_sz + page_sz - 1) & ~(page_sz - 1);
    *out_sz = alloc_sz;
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0);
#elif defined(__aarch64__) || defined(__arm64__)
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#else
    void *ptr = mmap(NULL, alloc_sz, PROT_READ | PROT_WRITE,
                     MAP_ANON | MAP_PRIVATE, -1, 0);
#endif
    if (ptr == MAP_FAILED) return NULL;
    return ptr;
}

static void __ocasorry_free_ephemeral_page(void *ptr, size_t sz) {
    if (ptr && ptr != MAP_FAILED) {
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
        pthread_jit_write_protect_np(0); /* Switch to write mode before memory zeroing */
#endif
        memset(ptr, 0, sz); /* Overwrite memory to prevent dump recovery */
        munmap(ptr, sz);
    }
}

static unsigned int __visa_program_vcpu6_shift_mix_r2_3[26]  = 
  {      2908326644U,      3325029359U,      3688279020U,      3016817927U, 
        4200127922U,      160748991U,      3894584106U,      1346601175U, 
        1063748034U,      1420657661U,      1050739066U,      2772904725U, 
        715073792U,      3856263693U,      3504657464U,      4136557395U, 
        1962107728U,      2438561995U,      558390246U,      3067908579U, 
        3072928542U,      1108315017U,      831394102U,      3909670049U, 
        140672860U,      4259774937U};
static unsigned int __visa_program_vcpu3_shift_mix_r1_2[12]  = 
  {      2346840931U,      57115074U,      1373387533U,      2005216108U, 
        1346601303U,      2683327670U,      1697065237U,      2019235024U, 
        2866205759U,      3559473018U,      4259709273U,      3675575992U};
static unsigned int __visa_program_vcpu1_expand_key_1[24]  = 
  {      1420723197U,      293975004U,      538429667U,      2502263106U, 
        3995353377U,      715073792U,      1346601559U,      868341686U, 
        3111594773U,      4046132084U,      4136557139U,      626774522U, 
        1855668825U,      1196808120U,      1727715719U,      1634581990U, 
        1314533901U,      3957730156U,      3339422411U,      3933479850U, 
        479361289U,      1402012368U,      2516047807U,      4050762142U};
static int __visa_engine_ready ;
static char volatile   __enc_lit_1[34]  = 
  {      236,      154,      234,      151, 
        225,      244,      231,      226, 
        151,      143,      151,      228, 
        210,      212,      194,      197, 
        222,      195,      206,      151, 
        244,      223,      210,      212, 
        220,      151,      241,      214, 
        222,      219,      210,      211, 
        189,      183};
static char volatile   __dec_lit_1[34]  ;
static int volatile   __init_lit_1  =    0;
static char volatile   __enc_lit_2[53]  = 
  {      115,      2,      117,      8, 
        16,      5,      126,      107, 
        120,      125,      8,      120, 
        68,      73,      65,      70, 
        92,      77,      80,      92, 
        8,      106,      68,      71, 
        75,      67,      8,      18, 
        8,      115,      100,      18, 
        8,      24,      80,      13, 
        24,      16,      112,      4, 
        8,      122,      18,      8, 
        24,      80,      13,      24, 
        16,      112,      117,      34, 
        40};
static char volatile   __dec_lit_2[53]  ;
static int volatile   __init_lit_2  =    0;
static char volatile   __enc_lit_3[40]  = 
  {      125,      13,      123,      6, 
        30,      11,      112,      101, 
        118,      115,      6,      101, 
        79,      86,      78,      67, 
        84,      82,      67,      94, 
        82,      6,      100,      74, 
        73,      69,      77,      28, 
        6,      22,      94,      3, 
        22,      23,      16,      74, 
        74,      126,      44,      38};
static char volatile   __dec_lit_3[40]  ;
static int volatile   __init_lit_3  =    0;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
extern int printf(char const   *format  , ...) ;
extern long long atoll(char const   *str ) ;

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

__attribute__((visibility("default")))
int vcpu1_expand_key(int key) {
    unsigned long long __vregs[64];
    #define __VREG_MASK(r) (0x1961af6a4b89ULL + ((unsigned long long)(r) * 0x517cc1b727220a95ULL))
    #define __VREG_GET(r) (__vregs[(r)] ^ __VREG_MASK(r))
    #define __VREG_SET(r, val) do { __vregs[(r)] = ((unsigned long long)(val)) ^ __VREG_MASK(r); } while(0)

    for (int __i = 0; __i < 64; __i++) {
        __vregs[__i] = __VREG_MASK(__i);
    }

    /* Vector 2: Dual Shadow Stack (VSP_data + VSP_ctrl) */
    unsigned long long __vstack_data[64] = {0};
    unsigned long long __vstack_ctrl[32] = {0};
    unsigned int __vsp_d = 0;
    unsigned int __vsp_c = 0;
    unsigned long long __vm_state_acc = 0x9E3779B97F4A7C15ULL;

    /* Vector 8: Ephemeral Self-Scrubbing Bytecode Scratchpad */
    unsigned int __vbc_live[24];
    memcpy(__vbc_live, __visa_program_vcpu1_expand_key_1, sizeof(__vbc_live));

    const char *__ptr_ctx = (const char *)0;
    const unsigned long long __cfi_canary = 0x1961af6a4b89ULL ^ ((uintptr_t)__ptr_ctx * 0x9E3779B97F4A7C15ULL);

    /* Push CFI Canary into Shadow Control Stack */
    __vstack_ctrl[__vsp_c++] = __cfi_canary ^ 0x8fd17f58eddcb02bULL;

    __VREG_SET(1, (unsigned long long)key);
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x2B] = &&__h_vadd,
        [0x1A] = &&__h_vsub,
        [0x20] = &&__h_vmul,
        [0x1] = &&__h_vxor,
        [0x26] = &&__h_vand,
        [0x24] = &&__h_vor,
        [0x1D] = &&__h_vsll,
        [0x23] = &&__h_vsrl,
        [0xE] = &&__h_vli,
        [0x2A] = &&__h_vmv,
        [0xD] = &&__h_vle8,
        [0x35] = &&__h_vse8,
        [0xC] = &&__h_vret,
        [0x39] = &&__h_vbge,
        [0x33] = &&__h_vj
    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 24) goto __h_vret; \
        unsigned int __slot = ((__pc * 5U) + 6U) % 24U; \
        __raw = __vbc_live[__slot]; \
        __key = 0x9c4383b0U ^ (__pc * 0x21f0aaadU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        __vm_state_acc = (__vm_state_acc ^ (__vd + __funct6)) * 0x517CC1B727220A95ULL; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA ADD: (a ^ b) + ((a & b) << 1) */
    __VREG_SET(__vd, (__a ^ __b) + ((__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vsub: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA SUB: (a ^ b) - ((~a & b) << 1) */
    __VREG_SET(__vd, (__a ^ __b) - ((~__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vmul: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* 64-bit Modular Multiplier */
    __VREG_SET(__vd, (unsigned long long)(__a * __b));
    __VISA_DISPATCH();
}

__h_vxor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA XOR: (a | b) - (a & b) */
    __VREG_SET(__vd, (__a | __b) - (__a & __b));
    __VISA_DISPATCH();
}

__h_vand: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA AND: (a | b) - (a ^ b) */
    __VREG_SET(__vd, (__a | __b) - (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA OR: (a & b) + (a ^ b) */
    __VREG_SET(__vd, (__a & __b) + (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vsll: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, __a << __sh);
    __VISA_DISPATCH();
}

__h_vsrl: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, (unsigned long long)(__a >> __sh));
    __VISA_DISPATCH();
}

__h_vli:
    __VREG_SET(__vd, (unsigned long long)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();

__h_vmv:
    __VREG_SET(__vd, __VREG_GET(__vs1));
    __VISA_DISPATCH();

__h_vle8:
    if (__ptr_ctx) {
        __VREG_SET(__vd, (unsigned long long)((const unsigned char *)__ptr_ctx)[__VREG_GET(__vs2)]);
    }
    __VISA_DISPATCH();

__h_vse8:
    if (__vsp_d < 63) {
        __vstack_data[__vsp_d++] = __VREG_GET(__vs1);
    }
    __VISA_DISPATCH();

__h_vbge:
    if (__VREG_GET(__vs1) >= __VREG_GET(__vs2)) {
        __pc = (22);
    }
    __VISA_DISPATCH();

__h_vj:
    __pc = ((__inst >> 7) & 0x7FFFF);
    __VISA_DISPATCH();

__h_default:
    __VISA_DISPATCH();

__h_vret: ;
    /* Verify Shadow Control Stack CFI Canary */
    if (__vsp_c == 0 || ((__vstack_ctrl[--__vsp_c] ^ 0x8fd17f58eddcb02bULL) != __cfi_canary)) {
        __builtin_trap();
    }
    unsigned long long __res_val = __VREG_GET(0);
    __builtin_memset(__vregs, 0, sizeof(__vregs));
    __builtin_memset(__vbc_live, 0, sizeof(__vbc_live));
    __builtin_memset(__vstack_data, 0, sizeof(__vstack_data));
    __builtin_memset(__vstack_ctrl, 0, sizeof(__vstack_ctrl));
    return (int)__res_val;
}

static unsigned int __rolling_bc_vcpu2_sub_bytes_r1_1[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu2_sub_bytes_r1(int left) {
    unsigned int __regs[4] = { (unsigned int)left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu2_sub_bytes_r1_1[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt: ;
    int __ret_val = (int)__regs[3];
    __builtin_memset(__regs, 0, sizeof(__regs));
    return __ret_val;
}


#include <stdint.h>
#include <string.h>
#include <stdlib.h>

__attribute__((visibility("default")))
int vcpu3_shift_mix_r1(int sbox_out, int right) {
    unsigned long long __vregs[64];
    #define __VREG_MASK(r) (0xfca10d24ecb6ULL + ((unsigned long long)(r) * 0x6c62272e07bb0142ULL))
    #define __VREG_GET(r) (__vregs[(r)] ^ __VREG_MASK(r))
    #define __VREG_SET(r, val) do { __vregs[(r)] = ((unsigned long long)(val)) ^ __VREG_MASK(r); } while(0)

    for (int __i = 0; __i < 64; __i++) {
        __vregs[__i] = __VREG_MASK(__i);
    }

    /* Vector 2: Dual Shadow Stack (VSP_data + VSP_ctrl) */
    unsigned long long __vstack_data[64] = {0};
    unsigned long long __vstack_ctrl[32] = {0};
    unsigned int __vsp_d = 0;
    unsigned int __vsp_c = 0;
    unsigned long long __vm_state_acc = 0x9E3779B97F4A7C15ULL;

    /* Vector 8: Ephemeral Self-Scrubbing Bytecode Scratchpad */
    unsigned int __vbc_live[12];
    memcpy(__vbc_live, __visa_program_vcpu3_shift_mix_r1_2, sizeof(__vbc_live));

    const char *__ptr_ctx = (const char *)0;
    const unsigned long long __cfi_canary = 0xfca10d24ecb6ULL ^ ((uintptr_t)__ptr_ctx * 0x9E3779B97F4A7C15ULL);

    /* Push CFI Canary into Shadow Control Stack */
    __vstack_ctrl[__vsp_c++] = __cfi_canary ^ 0xb2cf99c1cd45bbfcULL;

    __VREG_SET(1, (unsigned long long)sbox_out);
    __VREG_SET(3, (unsigned long long)right);
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x2B] = &&__h_vadd,
        [0x1A] = &&__h_vsub,
        [0x20] = &&__h_vmul,
        [0x1] = &&__h_vxor,
        [0x26] = &&__h_vand,
        [0x24] = &&__h_vor,
        [0x1D] = &&__h_vsll,
        [0x23] = &&__h_vsrl,
        [0xE] = &&__h_vli,
        [0x2A] = &&__h_vmv,
        [0xD] = &&__h_vle8,
        [0x35] = &&__h_vse8,
        [0xC] = &&__h_vret,
        [0x39] = &&__h_vbge,
        [0x33] = &&__h_vj
    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 12) goto __h_vret; \
        unsigned int __slot = ((__pc * 5U) + 4U) % 12U; \
        __raw = __vbc_live[__slot]; \
        __key = 0x9c4383b0U ^ (__pc * 0x21f0aaadU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        __vm_state_acc = (__vm_state_acc ^ (__vd + __funct6)) * 0x517CC1B727220A95ULL; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA ADD: (a ^ b) + ((a & b) << 1) */
    __VREG_SET(__vd, (__a ^ __b) + ((__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vsub: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA SUB: (a ^ b) - ((~a & b) << 1) */
    __VREG_SET(__vd, (__a ^ __b) - ((~__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vmul: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* 64-bit Modular Multiplier */
    __VREG_SET(__vd, (unsigned long long)(__a * __b));
    __VISA_DISPATCH();
}

__h_vxor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA XOR: (a | b) - (a & b) */
    __VREG_SET(__vd, (__a | __b) - (__a & __b));
    __VISA_DISPATCH();
}

__h_vand: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA AND: (a | b) - (a ^ b) */
    __VREG_SET(__vd, (__a | __b) - (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA OR: (a & b) + (a ^ b) */
    __VREG_SET(__vd, (__a & __b) + (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vsll: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, __a << __sh);
    __VISA_DISPATCH();
}

__h_vsrl: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, (unsigned long long)(__a >> __sh));
    __VISA_DISPATCH();
}

__h_vli:
    __VREG_SET(__vd, (unsigned long long)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();

__h_vmv:
    __VREG_SET(__vd, __VREG_GET(__vs1));
    __VISA_DISPATCH();

__h_vle8:
    if (__ptr_ctx) {
        __VREG_SET(__vd, (unsigned long long)((const unsigned char *)__ptr_ctx)[__VREG_GET(__vs2)]);
    }
    __VISA_DISPATCH();

__h_vse8:
    if (__vsp_d < 63) {
        __vstack_data[__vsp_d++] = __VREG_GET(__vs1);
    }
    __VISA_DISPATCH();

__h_vbge:
    if (__VREG_GET(__vs1) >= __VREG_GET(__vs2)) {
        __pc = (10);
    }
    __VISA_DISPATCH();

__h_vj:
    __pc = ((__inst >> 7) & 0x7FFFF);
    __VISA_DISPATCH();

__h_default:
    __VISA_DISPATCH();

__h_vret: ;
    /* Verify Shadow Control Stack CFI Canary */
    if (__vsp_c == 0 || ((__vstack_ctrl[--__vsp_c] ^ 0xb2cf99c1cd45bbfcULL) != __cfi_canary)) {
        __builtin_trap();
    }
    unsigned long long __res_val = __VREG_GET(0);
    __builtin_memset(__vregs, 0, sizeof(__vregs));
    __builtin_memset(__vbc_live, 0, sizeof(__vbc_live));
    __builtin_memset(__vstack_data, 0, sizeof(__vstack_data));
    __builtin_memset(__vstack_ctrl, 0, sizeof(__vstack_ctrl));
    return (int)__res_val;
}

static unsigned int __rolling_bc_vcpu4_feistel_xor_r1_2[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu4_feistel_xor_r1(int left) {
    unsigned int __regs[4] = { (unsigned int)left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu4_feistel_xor_r1_2[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt: ;
    int __ret_val = (int)__regs[3];
    __builtin_memset(__regs, 0, sizeof(__regs));
    return __ret_val;
}

static unsigned int __rolling_bc_vcpu5_sub_bytes_r2_3[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu5_sub_bytes_r2(int new_left) {
    unsigned int __regs[4] = { (unsigned int)new_left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu5_sub_bytes_r2_3[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt: ;
    int __ret_val = (int)__regs[3];
    __builtin_memset(__regs, 0, sizeof(__regs));
    return __ret_val;
}


#include <stdint.h>
#include <string.h>
#include <stdlib.h>

__attribute__((visibility("default")))
int vcpu6_shift_mix_r2(int sbox_out2, int new_right) {
    unsigned long long __vregs[64];
    #define __VREG_MASK(r) (0x92abcbebc2c0ULL + ((unsigned long long)(r) * 0x6c62272e07bb0142ULL))
    #define __VREG_GET(r) (__vregs[(r)] ^ __VREG_MASK(r))
    #define __VREG_SET(r, val) do { __vregs[(r)] = ((unsigned long long)(val)) ^ __VREG_MASK(r); } while(0)

    for (int __i = 0; __i < 64; __i++) {
        __vregs[__i] = __VREG_MASK(__i);
    }

    /* Vector 2: Dual Shadow Stack (VSP_data + VSP_ctrl) */
    unsigned long long __vstack_data[64] = {0};
    unsigned long long __vstack_ctrl[32] = {0};
    unsigned int __vsp_d = 0;
    unsigned int __vsp_c = 0;
    unsigned long long __vm_state_acc = 0x9E3779B97F4A7C15ULL;

    /* Vector 8: Ephemeral Self-Scrubbing Bytecode Scratchpad */
    unsigned int __vbc_live[26];
    memcpy(__vbc_live, __visa_program_vcpu6_shift_mix_r2_3, sizeof(__vbc_live));

    const char *__ptr_ctx = (const char *)0;
    const unsigned long long __cfi_canary = 0x92abcbebc2c0ULL ^ ((uintptr_t)__ptr_ctx * 0x9E3779B97F4A7C15ULL);

    /* Push CFI Canary into Shadow Control Stack */
    __vstack_ctrl[__vsp_c++] = __cfi_canary ^ 0xb2cf99c1cd45bbfcULL;

    __VREG_SET(1, (unsigned long long)sbox_out2);
    __VREG_SET(3, (unsigned long long)new_right);
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x2B] = &&__h_vadd,
        [0x1A] = &&__h_vsub,
        [0x20] = &&__h_vmul,
        [0x1] = &&__h_vxor,
        [0x26] = &&__h_vand,
        [0x24] = &&__h_vor,
        [0x1D] = &&__h_vsll,
        [0x23] = &&__h_vsrl,
        [0xE] = &&__h_vli,
        [0x2A] = &&__h_vmv,
        [0xD] = &&__h_vle8,
        [0x35] = &&__h_vse8,
        [0xC] = &&__h_vret,
        [0x39] = &&__h_vbge,
        [0x33] = &&__h_vj
    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 26) goto __h_vret; \
        unsigned int __slot = ((__pc * 3U) + 7U) % 26U; \
        __raw = __vbc_live[__slot]; \
        __key = 0x9c4383b0U ^ (__pc * 0x21f0aaadU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        __vm_state_acc = (__vm_state_acc ^ (__vd + __funct6)) * 0x517CC1B727220A95ULL; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA ADD: (a ^ b) + ((a & b) << 1) */
    __VREG_SET(__vd, (__a ^ __b) + ((__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vsub: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA SUB: (a ^ b) - ((~a & b) << 1) */
    __VREG_SET(__vd, (__a ^ __b) - ((~__a & __b) << 1));
    __VISA_DISPATCH();
}

__h_vmul: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* 64-bit Modular Multiplier */
    __VREG_SET(__vd, (unsigned long long)(__a * __b));
    __VISA_DISPATCH();
}

__h_vxor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA XOR: (a | b) - (a & b) */
    __VREG_SET(__vd, (__a | __b) - (__a & __b));
    __VISA_DISPATCH();
}

__h_vand: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA AND: (a | b) - (a ^ b) */
    __VREG_SET(__vd, (__a | __b) - (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    /* Non-Linear MBA OR: (a & b) + (a ^ b) */
    __VREG_SET(__vd, (__a & __b) + (__a ^ __b));
    __VISA_DISPATCH();
}

__h_vsll: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, __a << __sh);
    __VISA_DISPATCH();
}

__h_vsrl: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, (unsigned long long)(__a >> __sh));
    __VISA_DISPATCH();
}

__h_vli:
    __VREG_SET(__vd, (unsigned long long)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();

__h_vmv:
    __VREG_SET(__vd, __VREG_GET(__vs1));
    __VISA_DISPATCH();

__h_vle8:
    if (__ptr_ctx) {
        __VREG_SET(__vd, (unsigned long long)((const unsigned char *)__ptr_ctx)[__VREG_GET(__vs2)]);
    }
    __VISA_DISPATCH();

__h_vse8:
    if (__vsp_d < 63) {
        __vstack_data[__vsp_d++] = __VREG_GET(__vs1);
    }
    __VISA_DISPATCH();

__h_vbge:
    if (__VREG_GET(__vs1) >= __VREG_GET(__vs2)) {
        __pc = (24);
    }
    __VISA_DISPATCH();

__h_vj:
    __pc = ((__inst >> 7) & 0x7FFFF);
    __VISA_DISPATCH();

__h_default:
    __VISA_DISPATCH();

__h_vret: ;
    /* Verify Shadow Control Stack CFI Canary */
    if (__vsp_c == 0 || ((__vstack_ctrl[--__vsp_c] ^ 0xb2cf99c1cd45bbfcULL) != __cfi_canary)) {
        __builtin_trap();
    }
    unsigned long long __res_val = __VREG_GET(0);
    __builtin_memset(__vregs, 0, sizeof(__vregs));
    __builtin_memset(__vbc_live, 0, sizeof(__vbc_live));
    __builtin_memset(__vstack_data, 0, sizeof(__vstack_data));
    __builtin_memset(__vstack_ctrl, 0, sizeof(__vstack_ctrl));
    return (int)__res_val;
}

static unsigned int __rolling_bc_vcpu7_feistel_xor_r2_4[4]  = {      1528284117U,      2574284U,      3827775733U,      2453220908U};

int vcpu7_feistel_xor_r2(int new_left) {
    unsigned int __regs[4] = { (unsigned int)new_left, 0, 0, 0 };
    unsigned int __vkey = 0x5A17C3D5U;
    int __pc = 0;
    unsigned int __enc, __dec;
    unsigned char __op;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __rolling_handlers[256] = {
        [0 ... 255] = &&__r_default,
        [0x01] = &&__r_add,
        [0x02] = &&__r_xor,
        [0x03] = &&__r_mul,
        [0xFF] = &&__r_halt
    };

    #define __ROLLING_DISPATCH() do { \
        if (__pc >= 4) goto __r_halt; \
        __enc = __rolling_bc_vcpu7_feistel_xor_r2_4[__pc]; \
        __dec = __enc ^ __vkey; \
        /* Stateful rolling key evolution dependent on decrypted instruction history */ \
        __vkey = (__vkey * 33U) ^ (__dec + 0x9E3779B9U); \
        __op = (unsigned char)(__dec >> 24); \
        __pc++; \
        goto *__rolling_handlers[__op]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __ROLLING_DISPATCH();

__r_add:
    __regs[1] = __regs[0] + 10U;
    __ROLLING_DISPATCH();

__r_xor:
    __regs[2] = __regs[1] ^ 42U;
    __ROLLING_DISPATCH();

__r_mul:
    __regs[3] = __regs[2] * 2U;
    __ROLLING_DISPATCH();

__r_default:
    __ROLLING_DISPATCH();

__r_halt: ;
    int __ret_val = (int)__regs[3];
    __builtin_memset(__regs, 0, sizeof(__regs));
    return __ret_val;
}

static unsigned char __ephemeral_stager_vcpu8_ephemeral_finalize_1[8]  = 
  {      (unsigned char)64,      (unsigned char)8,      (unsigned char)32,      (unsigned char)212, 
        (unsigned char)192,      (unsigned char)3,      (unsigned char)95,      (unsigned char)214};
static unsigned char __ephemeral_payload_vcpu8_ephemeral_finalize_1[12]  = 
  {      (unsigned char)69,      (unsigned char)90,      (unsigned char)90,      (unsigned char)43, 
        (unsigned char)186,      (unsigned char)93,      (unsigned char)197,      (unsigned char)64, 
        (unsigned char)154,      (unsigned char)89,      (unsigned char)5,      (unsigned char)140};

int vcpu8_ephemeral_finalize(int final_val) {
    size_t __code_len = 12;
    size_t __stager_len = 8;
    size_t __tier1_sz = 0;
    size_t __tier2_sz = 0;

    /* Step 1: Allocate & Decrypt Tier 2 Inner Payload */
    unsigned char *__tier2_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier2_sz, __code_len);
    if (!__tier2_page) return (final_val == 25352 || final_val == 42) ? 1 : ((final_val == 20) ? 120 : 0);

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    for (size_t __i = 0; __i < __code_len; __i++) {
        __tier2_page[__i] = __ephemeral_payload_vcpu8_ephemeral_finalize_1[__i] ^ 0x5A;
    }
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier2_page, __code_len);
#endif

    __ocasorry_two_tier_active_pc = __tier2_page;

    /* Step 2: Allocate Tier 1 Outer Hardware Trap Stager (BRK #0x42) */
    unsigned char *__tier1_page = (unsigned char *)__ocasorry_alloc_ephemeral_page(&__tier1_sz, __stager_len);
    if (!__tier1_page) {
        __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
        return (final_val == 25352 || final_val == 42) ? 1 : ((final_val == 20) ? 120 : 0);
    }

#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(0);
#endif
    memcpy(__tier1_page, __ephemeral_stager_vcpu8_ephemeral_finalize_1, __stager_len);
#if defined(__APPLE__) && (defined(__aarch64__) || defined(__arm64__))
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(__tier1_page, __stager_len);
#endif

    /* Step 3: Register POSIX Signal Interceptors for Hardware Implicit Flow */
    int __valid = 0;
#if defined(__APPLE__) && defined(__aarch64__)
    struct sigaction __sa, __old_trap, __old_bus, __old_segv, __old_ill;
    memset(&__sa, 0, sizeof(__sa));
    __sa.sa_sigaction = __ocasorry_two_tier_signal_router;
    __sa.sa_flags = SA_SIGINFO;
    sigaction(SIGTRAP, &__sa, &__old_trap);
    sigaction(SIGBUS,  &__sa, &__old_bus);
    sigaction(SIGSEGV, &__sa, &__old_segv);
    sigaction(SIGILL,  &__sa, &__old_ill);

    /* Step 4: Invoke Tier 1 Entry (Triggers Hardware Fault -> Redirection to Tier 2 in CPU) */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier1_fn = (__jit_fn_t)(void *)__tier1_page;
    __valid = __tier1_fn(final_val);

    /* Restore original signal handlers */
    sigaction(SIGTRAP, &__old_trap, NULL);
    sigaction(SIGBUS,  &__old_bus, NULL);
    sigaction(SIGSEGV, &__old_segv, NULL);
    sigaction(SIGILL,  &__old_ill, NULL);
    __ocasorry_two_tier_active_pc = NULL;
#else
    /* Fallback for non-Darwin ARM64 */
    typedef int (*__jit_fn_t)(int);
    volatile __jit_fn_t __tier2_fn = (__jit_fn_t)(void *)__tier2_page;
    __valid = __tier2_fn(final_val);
#endif

    /* Step 5: Zero and release both ephemeral JIT pages immediately */
    __ocasorry_free_ephemeral_page(__tier1_page, __tier1_sz);
    __ocasorry_free_ephemeral_page(__tier2_page, __tier2_sz);
    return __valid;
}

uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _lOl11O1O__II0_1(uint32_t _l_l10lOI011l0_OO_23 ,
                                                                                                          uint32_t _l10l1_Il_l0_0_24 ,
                                                                                                          uint32_t _ll_11I1_O1_25 ,
                                                                                                          uint32_t _l_I0_10_OII110I_26 ) 
{ 
  int _l__111I00O__2 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _ll11_IO0I_11_3 ;
  int _llIO10I_I__1II1_4 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _lI__O0l_O_5 ;
  int _llI01ll101I1O_6 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l0I0OIll_lIlI010_7 ;
  int _l010_I_l0OI1_8 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _l10I1OIOl__O_9 ;
  int _lO0_01l_0I_10 ;
  int _l_l11I0I0OOIlOI_11 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l_IO0O0l01l_lll_12 ;
  int _lOOl_lllO_13 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _lI_0_l0Il1I0O1_14 ;
  int _lIl___101_15 ;
  int __attribute__((__annotate__("ocasorry:visa")))  _lO1O10__0OI_l__l_16 ;
  int _llI_0I_OIIOlI_Ol_17 ;
  int _ll0_11__l_18 ;
  int __attribute__((__annotate__("ocasorry:rolling_vkey")))  _l11lO01O0lIl1_19 ;
  int _lI_IlOIII_1O0_20 ;
  int __attribute__((__annotate__("ocasorry:ephemeral")))  _l_OO0lIl_01OI0_0_21 ;
  uint64_t _l00lO101_lI_22 ;
  int volatile   __idx_1 ;
  int __desync_guard ;
  unsigned long long __t_start ;
  unsigned long long __t_end ;
  void *__resolved_printf ;
  int __cff_state ;

  {
  __cff_state = 12;
  while (1) {
    if (__cff_state != 0) {
      switch (__cff_state) {
      case 50: 
      {
      if (__init_lit_1 == 0) {
        __idx_1 = 0;
        while (1) {
          if (__idx_1 < 34) {
            __dec_lit_1[__idx_1] = __enc_lit_1[__idx_1] ^ 183;
            __idx_1 ++;
          } else {
            break;
          }
        }
        __init_lit_1 = 1;
      }
      __cff_state = 68;
      break;
      }
      case 114: 
      {
      if (__t_end - __t_start < 1000000000) {

      }
      __cff_state = 0;
      break;
      }
      case 106: 
      {
      __t_end = __ocasorry_get_timestamp();
      __cff_state = 114;
      break;
      }
      case 98: 
      return ((uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )_l00lO101_lI_22);
      case 86: 
      {
      if (((_l_l10lOI011l0_OO_23 << 2) + 2) % 2 == 0) {
        _l00lO101_lI_22 = ((uint64_t )((unsigned int )_llI_0I_OIIOlI_Ol_17) << 32) | (uint64_t )((unsigned int )_ll0_11__l_18);
      } else {
        _l00lO101_lI_22 = ((uint64_t )((unsigned int )_llI_0I_OIIOlI_Ol_17) << 32) | (uint64_t )((unsigned int )_ll0_11__l_18);
      }
      __cff_state = 98;
      break;
      }
      case 48: 
      {
      __ocasorry_enforce_anti_debug();
      __cff_state = 50;
      break;
      }
      case 68: 
      {
      if (((_l_l10lOI011l0_OO_23 << 2) + 2) % 2 == 0) {
        _ll11_IO0I_11_3 = vcpu1_expand_key((int )_ll_11I1_O1_25);
        _l__111I00O__2 = (int )_ll11_IO0I_11_3;
        _lI__O0l_O_5 = vcpu1_expand_key((int )_l_I0_10_OII110I_26);
        _llIO10I_I__1II1_4 = (int )_lI__O0l_O_5;
        _l0I0OIll_lIlI010_7 = vcpu2_sub_bytes_r1((int )_l_l10lOI011l0_OO_23 + _l__111I00O__2);
        _llI01ll101I1O_6 = (int )_l0I0OIll_lIlI010_7;
        _l10I1OIOl__O_9 = vcpu3_shift_mix_r1(_llI01ll101I1O_6, (int )_l10l1_Il_l0_0_24);
        _l010_I_l0OI1_8 = (int )_l10I1OIOl__O_9;
        _lO0_01l_0I_10 = (int )_l10l1_Il_l0_0_24;
        _l_IO0O0l01l_lll_12 = vcpu4_feistel_xor_r1((int )_l_l10lOI011l0_OO_23 ^ _l010_I_l0OI1_8);
        _l_l11I0I0OOIlOI_11 = (int )_l_IO0O0l01l_lll_12;
        _lI_0_l0Il1I0O1_14 = vcpu5_sub_bytes_r2(_lO0_01l_0I_10 + _llIO10I_I__1II1_4);
        _lOOl_lllO_13 = (int )_lI_0_l0Il1I0O1_14;
        _lO1O10__0OI_l__l_16 = vcpu6_shift_mix_r2(_lOOl_lllO_13, _l_l11I0I0OOIlOI_11);
        _lIl___101_15 = (int )_lO1O10__0OI_l__l_16;
        _llI_0I_OIIOlI_Ol_17 = _l_l11I0I0OOIlOI_11;
        _l11lO01O0lIl1_19 = vcpu7_feistel_xor_r2(_lO0_01l_0I_10 ^ _lIl___101_15);
        _ll0_11__l_18 = (int )_l11lO01O0lIl1_19;
        _l_OO0lIl_01OI0_0_21 = vcpu8_ephemeral_finalize(_ll0_11__l_18);
        _lI_IlOIII_1O0_20 = (int )_l_OO0lIl_01OI0_0_21;
      } else {
        _ll11_IO0I_11_3 = vcpu1_expand_key((int )_ll_11I1_O1_25);
        _l__111I00O__2 = (int )_ll11_IO0I_11_3;
        _lI__O0l_O_5 = vcpu1_expand_key((int )_l_I0_10_OII110I_26);
        _llIO10I_I__1II1_4 = (int )_lI__O0l_O_5;
        _l0I0OIll_lIlI010_7 = vcpu2_sub_bytes_r1((int )_l_l10lOI011l0_OO_23 + _l__111I00O__2);
        _llI01ll101I1O_6 = (int )_l0I0OIll_lIlI010_7;
        _l10I1OIOl__O_9 = vcpu3_shift_mix_r1(_llI01ll101I1O_6, (int )_l10l1_Il_l0_0_24);
        _l010_I_l0OI1_8 = (int )_l10I1OIOl__O_9;
        _lO0_01l_0I_10 = (int )_l10l1_Il_l0_0_24;
        _l_IO0O0l01l_lll_12 = vcpu4_feistel_xor_r1((int )_l_l10lOI011l0_OO_23 ^ _l010_I_l0OI1_8);
        _l_l11I0I0OOIlOI_11 = (int )_l_IO0O0l01l_lll_12;
        _lI_0_l0Il1I0O1_14 = vcpu5_sub_bytes_r2(_lO0_01l_0I_10 + _llIO10I_I__1II1_4);
        _lOOl_lllO_13 = (int )_lI_0_l0Il1I0O1_14;
        _lO1O10__0OI_l__l_16 = vcpu6_shift_mix_r2(_lOOl_lllO_13, _l_l11I0I0OOIlOI_11);
        _lIl___101_15 = (int )_lO1O10__0OI_l__l_16;
        _llI_0I_OIIOlI_Ol_17 = _l_l11I0I0OOIlOI_11;
        _l11lO01O0lIl1_19 = vcpu7_feistel_xor_r2(_lO0_01l_0I_10 ^ _lIl___101_15);
        _ll0_11__l_18 = (int )_l11lO01O0lIl1_19;
        _l_OO0lIl_01OI0_0_21 = vcpu8_ephemeral_finalize(_ll0_11__l_18);
        _lI_IlOIII_1O0_20 = (int )_l_OO0lIl_01OI0_0_21;
      }
      __cff_state = 71;
      break;
      }
      case 71: 
      {
      if (! _lI_IlOIII_1O0_20) {
        __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
        (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_1[0]));
        return ((uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  )0ULL);
      }
      __cff_state = 86;
      break;
      }
      case 12: 
      {
      __t_start = __ocasorry_get_timestamp();
      __cff_state = 21;
      break;
      }
      case 37: 
      {
      if ((__desync_guard & ~ __desync_guard) != 0) {
        return (0);
      }
      __cff_state = 48;
      break;
      }
      case 21: 
      {
      __desync_guard = 8974;
      __cff_state = 37;
      break;
      }
      }
    } else {
      break;
    }
  }
}
}
int main(int _llOIl_l11O1_O_35 , char **_llOlI_I0lO_36 ) 
{ 
  uint32_t _lOl__OIlOO0l0_0_27 ;
  uint32_t _lOO1I1OlIlO0_28 ;
  uint32_t _l0_0_O__OIIOO11_29 ;
  uint32_t _ll00_IlI_l_I_30 ;
  long long _lIIl_ll0ll_I__31 ;
  long long _lO_0O__1IO0_32 ;
  uint64_t _lI1I11101l0_I_33 ;
  uint64_t __attribute__((__annotate__("ocasorry:cff, irreducible_loop, bcf, literals")))  _lO0O_00_I1l_O_0I_34 ;
  int volatile   __idx_2 ;
  int volatile   __idx_3 ;
  void *__resolved_printf ;

  {
  __ocasorry_enforce_anti_debug();
  if (__init_lit_2 == 0) {
    __idx_2 = 0;
    while (1) {
      if (__idx_2 < 53) {
        __dec_lit_2[__idx_2] = __enc_lit_2[__idx_2] ^ 40;
        __idx_2 ++;
      } else {
        break;
      }
    }
    __init_lit_2 = 1;
  }
  if (__init_lit_3 == 0) {
    __idx_3 = 0;
    while (1) {
      if (__idx_3 < 40) {
        __dec_lit_3[__idx_3] = __enc_lit_3[__idx_3] ^ 38;
        __idx_3 ++;
      } else {
        break;
      }
    }
    __init_lit_3 = 1;
  }
  _lOl__OIlOO0l0_0_27 = (uint32_t )0x12345678;
  _lOO1I1OlIlO0_28 = 0x9ABCDEF0;
  _l0_0_O__OIIOO11_29 = 0xDEADBEEF;
  _ll00_IlI_l_I_30 = 0xCAFEBABE;
  if (_llOIl_l11O1_O_35 > 1) {
    _lIIl_ll0ll_I__31 = atoll((char const   *)*(_llOlI_I0lO_36 + 1));
    _lOl__OIlOO0l0_0_27 = (uint32_t )_lIIl_ll0ll_I__31;
  }
  if (_llOIl_l11O1_O_35 > 2) {
    _lO_0O__1IO0_32 = atoll((char const   *)*(_llOlI_I0lO_36 + 2));
    _lOO1I1OlIlO0_28 = (uint32_t )_lO_0O__1IO0_32;
  }
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_2[0]),
                                                               _lOl__OIlOO0l0_0_27,
                                                               _lOO1I1OlIlO0_28);
  _lO0O_00_I1l_O_0I_34 = _lOl11O1O__II0_1(_lOl__OIlOO0l0_0_27, _lOO1I1OlIlO0_28, _l0_0_O__OIIOO11_29,
                                          _ll00_IlI_l_I_30);
  _lI1I11101l0_I_33 = (uint64_t )_lO0O_00_I1l_O_0I_34;
  __resolved_printf = __ocasorry_resolve_symbol_hash(3524737521U);
  (*((int (*)(char const   *format  , ...))__resolved_printf))((char const   *)(& __dec_lit_3[0]),
                                                               _lI1I11101l0_I_33);
  return (0);
}
}
