/* Generated by Goblint-CIL v. 2.1.1 */
/* print_CIL_Input is false */

static unsigned int __visa_program_compute_tier2_2[8]  = 
  {      2216883747U,      1785139912U,      599667001U,      921032046U, 
        4139283255U,      1307613028U,      1089128533U,      2914998002U};
static unsigned int __visa_program_compute_tier1_1[8]  = 
  {      50441065U,      2854755202U,      1283621983U,      4187530544U, 
        3122762061U,      1619361638U,      3286375675U,      76188692U};
static int __visa_engine_ready ;

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

__attribute__((visibility("default")))
int compute_tier1(int a, int b) {
static const unsigned char __vm_sbox_0[256] = {
    0x9B, 0x57, 0x02, 0xFF, 0xAA, 0x66, 0xD3, 0x8E, 0x7A, 0x37, 0xE2, 0x5E, 0x0B, 0xC6, 0xB3, 0x6F, 0xDA, 0x97, 0x43, 0x3E, 0xEB, 0xA6, 0x12, 0xCF, 0xBA, 0x76, 0x23, 0x9E, 0x4A, 0x07, 0xF2, 0xAF, 0x1B, 0xD6, 0x83, 0x7F, 0x2A, 0xE7, 0x53, 0x0E, 0xFB, 0xB6, 0x62, 0xDF, 0x8A, 0x46, 0x33, 0xEE, 0x5A, 0x17, 0xC2, 0xBF, 0x6B, 0x26, 0x93, 0x4F, 0x3A, 0xF7, 0xA2, 0x1E, 0xCB, 0x86, 0x72, 0x2F, 0x9A, 0x56, 0x03, 0xFE, 0xAB, 0x67, 0xD2, 0x8F, 0x7B, 0x36, 0xE3, 0x5F, 0x0A, 0xC7, 0xB2, 0x6E, 0xDB, 0x96, 0x42, 0x3F, 0xEA, 0xA7, 0x13, 0xCE, 0xBB, 0x77, 0x22, 0x9F, 0x4B, 0x06, 0xF3, 0xAE, 0x1A, 0xD7, 0x82, 0x7E, 0x2B, 0xE6, 0x52, 0x0F, 0xFA, 0xB7, 0x63, 0xDE, 0x8B, 0x47, 0x32, 0xEF, 0x5B, 0x16, 0xC3, 0xBE, 0x6A, 0x27, 0x92, 0x4E, 0x3B, 0xF6, 0xA3, 0x1F, 0xCA, 0x87, 0x73, 0x2E, 0x9B, 0x57, 0x02, 0xFF, 0xAA, 0x66, 0xD3, 0x8E, 0x7A, 0x37, 0xE2, 0x5E, 0x0B, 0xC6, 0xB3, 0x6F, 0xDA, 0x97, 0x43, 0x3E, 0xEB, 0xA6, 0x12, 0xCF, 0xBA, 0x76, 0x23, 0x9E, 0x4A, 0x07, 0xF2, 0xAF, 0x1B, 0xD6, 0x83, 0x7F, 0x2A, 0xE7, 0x53, 0x0E, 0xFB, 0xB6, 0x62, 0xDF, 0x8A, 0x46, 0x33, 0xEE, 0x5A, 0x17, 0xC2, 0xBF, 0x6B, 0x26, 0x93, 0x4F, 0x3A, 0xF7, 0xA2, 0x1E, 0xCB, 0x86, 0x72, 0x2F, 0x9A, 0x56, 0x03, 0xFE, 0xAB, 0x67, 0xD2, 0x8F, 0x7B, 0x36, 0xE3, 0x5F, 0x0A, 0xC7, 0xB2, 0x6E, 0xDB, 0x96, 0x42, 0x3F, 0xEA, 0xA7, 0x13, 0xCE, 0xBB, 0x77, 0x22, 0x9F, 0x4B, 0x06, 0xF3, 0xAE, 0x1A, 0xD7, 0x82, 0x7E, 0x2B, 0xE6, 0x52, 0x0F, 0xFA, 0xB7, 0x63, 0xDE, 0x8B, 0x47, 0x32, 0xEF, 0x5B, 0x16, 0xC3, 0xBE, 0x6A, 0x27, 0x92, 0x4E, 0x3B, 0xF6, 0xA3, 0x1F, 0xCA, 0x87, 0x73, 0x2E
};

    /* Anti-VTIL / Anti-NoVmp: Overlapping Aliased VCPU Register Matrix */
    union __attribute__((aligned(16))) {
        unsigned char __b[1024];
        unsigned long long __q[128];
    } __vbank;
    #define __VREG_ROT(r) (((unsigned int)(r) + 51U) & 0x3FU)
    #define __VREG_MASK(r) (0x6351ca5ea577ULL + ((unsigned long long)__VREG_ROT(r) * 0x9e3779b97f4a7c15ULL))
    #define __VREG_GET(r) (__vbank.__q[__VREG_ROT(r)] ^ __VREG_MASK(r))
    #define __VREG_SET(r, val) do { __vbank.__q[__VREG_ROT(r)] = ((unsigned long long)(val)) ^ __VREG_MASK(r); } while(0)

    for (int __i = 0; __i < 128; __i++) {
        __vbank.__q[__i] = (0x6351ca5ea577ULL + ((unsigned long long)__i * 0x9e3779b97f4a7c15ULL));
    }

    /* Vector 2: Dual Shadow Stack (VSP_data + VSP_ctrl) */
    unsigned long long __vstack_data[64] = {0};
    unsigned long long __vstack_ctrl[32] = {0};
    unsigned int __vsp_d = 0;
    unsigned int __vsp_c = 0;
    unsigned long long __vm_state_acc = 0x9E3779B97F4A7C15ULL;

    /* Vector 12: Microarchitectural Timer Sampling & Anti-Single-Stepping */
    #if defined(__aarch64__)
    unsigned long long __t_entry;
    __asm__ volatile("mrs %0, cntvct_el0" : "=r"(__t_entry));
    #elif defined(__x86_64__)
    unsigned int __t_lo, __t_hi;
    __asm__ volatile("rdtsc" : "=a"(__t_lo), "=d"(__t_hi));
    unsigned long long __t_entry = ((unsigned long long)__t_hi << 32) | __t_lo;
    #else
    unsigned long long __t_entry = 0;
    #endif

    /* Vector 8: Ephemeral Self-Scrubbing Bytecode Scratchpad */
    unsigned int __vbc_live[8];
    memcpy(__vbc_live, __visa_program_compute_tier1_1, sizeof(__vbc_live));

    const unsigned long long __fn_addr_entropy =
        (unsigned long long)(uintptr_t)(0 != 0 ? (const void *)0 : (const void *)&__vbc_live);
    const unsigned long long __vbc_hash_0 = __vbc_live[0] ^ (unsigned long long)__vbc_live[1];
    const unsigned long long __cfi_canary =
        0x6351ca5ea577ULL
        ^ (__fn_addr_entropy * 0x9E3779B97F4A7C15ULL)
        ^ (__vbc_hash_0 * 0x517CC1B727220A95ULL);

    __vstack_ctrl[__vsp_c++] = __cfi_canary ^ 0x409ac756b5b4c6abULL;

    __VREG_SET(1, (unsigned long long)a);
    __VREG_SET(4, (unsigned long long)b);
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x1F] = &&__h_vadd,
        [0x4] = &&__h_vsub,
        [0x29] = &&__h_vmul,
        [0x15] = &&__h_vxor,
        [0x13] = &&__h_vand,
        [0x6] = &&__h_vor,
        [0x34] = &&__h_vsll,
        [0x10] = &&__h_vsrl,
        [0xA] = &&__h_vli,
        [0x26] = &&__h_vmv,
        [0x12] = &&__h_vle8,
        [0x31] = &&__h_vse8,
        [0x2A] = &&__h_vret,
        [0x2B] = &&__h_vbge,
        [0x27] = &&__h_vj,
        /* Polymorphic Multi-Alias Opcode Handlers */
        [0x28] = &&__h_vadd_alt1,
        [0x2D] = &&__h_vadd_alt2,
        [0x17] = &&__h_vsub_alt1,
        [0x1B] = &&__h_vsub_alt2,
        [0xB] = &&__h_vxor_alt1,
        [0x22] = &&__h_vxor_alt2,
        [0xC] = &&__h_vand_alt1,
        [0x1C] = &&__h_vor_alt1,
        [0x30] = &&__h_vmul_alt1,
        [0x35] = &&__h_vmv_alt1,
        [0x3F] = &&__h_vli_alt1,

    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 8) goto __h_vret; \
        unsigned int __slot = ((__pc * 29U) + 5U) % 8U; \
        __raw = __vbc_live[__slot]; \
        __key = 0xFA85FEEDU ^ (__pc * 0x9E3779B9U); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        __vm_state_acc = ((__vm_state_acc * 0x63c63cd93839c9b9ULL) ^ (__vd + __funct6 + (unsigned long long)__pc)) * 0x517CC1B727220A95ULL; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a ^ __b) + ((__a & __b) << 1));
    __VISA_DISPATCH();
}
__h_vadd_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a | __b) + (__a & __b));
    __VISA_DISPATCH();
}
__h_vadd_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, ((__a | __b) << 1) - (__a ^ __b));
    __VISA_DISPATCH();
}
__h_vsub: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a ^ __b) - ((~__a & __b) << 1));
    __VISA_DISPATCH();
}
__h_vsub_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a & ~__b) - (~__a & __b));
    __VISA_DISPATCH();
}
__h_vsub_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a ^ ~__b) + 1ULL + ((__a & ~__b) << 1));
    __VISA_DISPATCH();
}
__h_vmul:
    __VREG_SET(__vd, (unsigned long long)(__VREG_GET(__vs1) * __VREG_GET(__vs2)));
    __VISA_DISPATCH();
__h_vmul_alt1:
    __VREG_SET(__vd, (unsigned long long)((__VREG_GET(__vs1) ^ 0) * (__VREG_GET(__vs2) ^ 0)));
    __VISA_DISPATCH();
__h_vxor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a | __b) - (__a & __b));
    __VISA_DISPATCH();
}
__h_vxor_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (~__a & __b) + (__a & ~__b));
    __VISA_DISPATCH();
}
__h_vxor_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a + __b) - ((__a & __b) << 1));
    __VISA_DISPATCH();
}
__h_vand: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a | __b) - (__a ^ __b));
    __VISA_DISPATCH();
}
__h_vand_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a + __b) - (__a | __b));
    __VISA_DISPATCH();
}
__h_vor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a & __b) + (__a ^ __b));
    __VISA_DISPATCH();
}
__h_vor_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a + __b) - (__a & __b));
    __VISA_DISPATCH();
}
__h_vsll: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, __a << __sh);
    __VISA_DISPATCH();
}
__h_vsrl: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, (unsigned long long)(__a >> __sh));
    __VISA_DISPATCH();
}
__h_vli:
    __VREG_SET(__vd, (unsigned long long)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();
__h_vli_alt1:
    __VREG_SET(__vd, (unsigned long long)((((__vm << 3) | __funct3) << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();
__h_vmv:
    __VREG_SET(__vd, __VREG_GET(__vs1));
    __VISA_DISPATCH();
__h_vmv_alt1:
    __VREG_SET(__vd, __VREG_GET(__vs1) ^ 0);
    __VISA_DISPATCH();
__h_vle8: {
    const unsigned char *__load_base = (const unsigned char *)(uintptr_t)__VREG_GET(__vs1);
    if (__load_base) {
        __VREG_SET(__vd, (unsigned long long)__load_base[__VREG_GET(__vs2)]);
    }
    __VISA_DISPATCH();
}
__h_vse8:
    if (__vsp_d < 63) {
        __vstack_data[__vsp_d++] = __VREG_GET(__vs1);
    }
    __VISA_DISPATCH();
__h_vbge: {
    unsigned int __branch_target = (__inst >> 7) & 0xFFU;
    if (__VREG_GET(__vs1) >= __VREG_GET(__vs2)) {
        __pc = (unsigned int)((__branch_target) + ((__vm_state_acc * (__vm_state_acc + 1ULL)) & 1ULL));
    }
    __VISA_DISPATCH();
}
__h_vj: {
    unsigned int __jump_target = (__inst >> 7) & 0x7FFFFU;
    __pc = (unsigned int)((__jump_target) + ((__vm_state_acc * (__vm_state_acc + 1ULL)) & 1ULL));
    __VISA_DISPATCH();
}
__h_default:
    __builtin_trap();

__h_vret: ;
    /* Verify Shadow Control Stack CFI Canary */
    if (__vsp_c == 0 || ((__vstack_ctrl[--__vsp_c] ^ 0x409ac756b5b4c6abULL) != __cfi_canary)) {
        __builtin_trap();
    }
    /* Vector 12: Microarchitectural Timer Check & Silent State Poisoning */
    #if defined(__aarch64__)
    unsigned long long __t_exit;
    __asm__ volatile("mrs %0, cntvct_el0" : "=r"(__t_exit));
    #elif defined(__x86_64__)
    unsigned int __x_lo, __x_hi;
    __asm__ volatile("rdtsc" : "=a"(__x_lo), "=d"(__x_hi));
    unsigned long long __t_exit = ((unsigned long long)__x_hi << 32) | __x_lo;
    #else
    unsigned long long __t_exit = 0;
    #endif
    unsigned long long __t_delta = (__t_exit > __t_entry) ? (__t_exit - __t_entry) : 0ULL;
    unsigned long long __stepped = (__t_delta > 1000000000ULL) ? 1ULL : 0ULL;
    __vm_state_acc ^= (__stepped * 0x9E3779B97F4A7C15ULL);

    /* Vector 11: Anti-Symbolic Quadratic Invariant & Dataflow Interlock */
    if (((__vm_state_acc * (__vm_state_acc + 1ULL)) & 1ULL) != 0ULL) {
        __builtin_trap();
    }
    unsigned long long __res_val = (__VREG_GET(3) ^ (__stepped * 0xBADF00DULL)) ^ ((__vm_state_acc * (__vm_state_acc + 1ULL)) & 1ULL);
    __builtin_memset(&__vbank, 0, sizeof(__vbank));
    __builtin_memset(__vbc_live, 0, sizeof(__vbc_live));
    __builtin_memset(__vstack_data, 0, sizeof(__vstack_data));
    __builtin_memset(__vstack_ctrl, 0, sizeof(__vstack_ctrl));
    return (int)__res_val;
}
#undef __VREG_ROT
#undef __VREG_MASK
#undef __VREG_GET
#undef __VREG_SET
#undef __VISA_DISPATCH


#include <stdint.h>
#include <string.h>
#include <stdlib.h>

__attribute__((visibility("default")))
int compute_tier2(int x, int y) {
static const unsigned char __vm_sbox_0[256] = {
    0x9B, 0x57, 0x02, 0xFF, 0xAA, 0x66, 0xD3, 0x8E, 0x7A, 0x37, 0xE2, 0x5E, 0x0B, 0xC6, 0xB3, 0x6F, 0xDA, 0x97, 0x43, 0x3E, 0xEB, 0xA6, 0x12, 0xCF, 0xBA, 0x76, 0x23, 0x9E, 0x4A, 0x07, 0xF2, 0xAF, 0x1B, 0xD6, 0x83, 0x7F, 0x2A, 0xE7, 0x53, 0x0E, 0xFB, 0xB6, 0x62, 0xDF, 0x8A, 0x46, 0x33, 0xEE, 0x5A, 0x17, 0xC2, 0xBF, 0x6B, 0x26, 0x93, 0x4F, 0x3A, 0xF7, 0xA2, 0x1E, 0xCB, 0x86, 0x72, 0x2F, 0x9A, 0x56, 0x03, 0xFE, 0xAB, 0x67, 0xD2, 0x8F, 0x7B, 0x36, 0xE3, 0x5F, 0x0A, 0xC7, 0xB2, 0x6E, 0xDB, 0x96, 0x42, 0x3F, 0xEA, 0xA7, 0x13, 0xCE, 0xBB, 0x77, 0x22, 0x9F, 0x4B, 0x06, 0xF3, 0xAE, 0x1A, 0xD7, 0x82, 0x7E, 0x2B, 0xE6, 0x52, 0x0F, 0xFA, 0xB7, 0x63, 0xDE, 0x8B, 0x47, 0x32, 0xEF, 0x5B, 0x16, 0xC3, 0xBE, 0x6A, 0x27, 0x92, 0x4E, 0x3B, 0xF6, 0xA3, 0x1F, 0xCA, 0x87, 0x73, 0x2E, 0x9B, 0x57, 0x02, 0xFF, 0xAA, 0x66, 0xD3, 0x8E, 0x7A, 0x37, 0xE2, 0x5E, 0x0B, 0xC6, 0xB3, 0x6F, 0xDA, 0x97, 0x43, 0x3E, 0xEB, 0xA6, 0x12, 0xCF, 0xBA, 0x76, 0x23, 0x9E, 0x4A, 0x07, 0xF2, 0xAF, 0x1B, 0xD6, 0x83, 0x7F, 0x2A, 0xE7, 0x53, 0x0E, 0xFB, 0xB6, 0x62, 0xDF, 0x8A, 0x46, 0x33, 0xEE, 0x5A, 0x17, 0xC2, 0xBF, 0x6B, 0x26, 0x93, 0x4F, 0x3A, 0xF7, 0xA2, 0x1E, 0xCB, 0x86, 0x72, 0x2F, 0x9A, 0x56, 0x03, 0xFE, 0xAB, 0x67, 0xD2, 0x8F, 0x7B, 0x36, 0xE3, 0x5F, 0x0A, 0xC7, 0xB2, 0x6E, 0xDB, 0x96, 0x42, 0x3F, 0xEA, 0xA7, 0x13, 0xCE, 0xBB, 0x77, 0x22, 0x9F, 0x4B, 0x06, 0xF3, 0xAE, 0x1A, 0xD7, 0x82, 0x7E, 0x2B, 0xE6, 0x52, 0x0F, 0xFA, 0xB7, 0x63, 0xDE, 0x8B, 0x47, 0x32, 0xEF, 0x5B, 0x16, 0xC3, 0xBE, 0x6A, 0x27, 0x92, 0x4E, 0x3B, 0xF6, 0xA3, 0x1F, 0xCA, 0x87, 0x73, 0x2E
};

    /* Anti-VTIL / Anti-NoVmp: Overlapping Aliased VCPU Register Matrix */
    union __attribute__((aligned(16))) {
        unsigned char __b[1024];
        unsigned long long __q[128];
    } __vbank;
    #define __VREG_ROT(r) (((unsigned int)(r) + 44U) & 0x3FU)
    #define __VREG_MASK(r) (0x5e7b3b4ea4ebULL + ((unsigned long long)__VREG_ROT(r) * 0x517cc1b727220a95ULL))
    #define __VREG_GET(r) (__vbank.__q[__VREG_ROT(r)] ^ __VREG_MASK(r))
    #define __VREG_SET(r, val) do { __vbank.__q[__VREG_ROT(r)] = ((unsigned long long)(val)) ^ __VREG_MASK(r); } while(0)

    for (int __i = 0; __i < 128; __i++) {
        __vbank.__q[__i] = (0x5e7b3b4ea4ebULL + ((unsigned long long)__i * 0x517cc1b727220a95ULL));
    }

    /* Vector 2: Dual Shadow Stack (VSP_data + VSP_ctrl) */
    unsigned long long __vstack_data[64] = {0};
    unsigned long long __vstack_ctrl[32] = {0};
    unsigned int __vsp_d = 0;
    unsigned int __vsp_c = 0;
    unsigned long long __vm_state_acc = 0x9E3779B97F4A7C15ULL;

    /* Vector 12: Microarchitectural Timer Sampling & Anti-Single-Stepping */
    #if defined(__aarch64__)
    unsigned long long __t_entry;
    __asm__ volatile("mrs %0, cntvct_el0" : "=r"(__t_entry));
    #elif defined(__x86_64__)
    unsigned int __t_lo, __t_hi;
    __asm__ volatile("rdtsc" : "=a"(__t_lo), "=d"(__t_hi));
    unsigned long long __t_entry = ((unsigned long long)__t_hi << 32) | __t_lo;
    #else
    unsigned long long __t_entry = 0;
    #endif

    /* Vector 8: Ephemeral Self-Scrubbing Bytecode Scratchpad */
    unsigned int __vbc_live[8];
    memcpy(__vbc_live, __visa_program_compute_tier2_2, sizeof(__vbc_live));

    const unsigned long long __fn_addr_entropy =
        (unsigned long long)(uintptr_t)(0 != 0 ? (const void *)0 : (const void *)&__vbc_live);
    const unsigned long long __vbc_hash_0 = __vbc_live[0] ^ (unsigned long long)__vbc_live[1];
    const unsigned long long __cfi_canary =
        0x5e7b3b4ea4ebULL
        ^ (__fn_addr_entropy * 0x9E3779B97F4A7C15ULL)
        ^ (__vbc_hash_0 * 0x517CC1B727220A95ULL);

    __vstack_ctrl[__vsp_c++] = __cfi_canary ^ 0x8fd17f58eddcb02bULL;

    __VREG_SET(5, (unsigned long long)x);
    __VREG_SET(0, (unsigned long long)y);
    unsigned int __pc = 0;
    unsigned int __raw, __key, __inst;
    unsigned char __funct6, __vm, __vs2, __vs1, __funct3, __vd;

    /* Direct Threading Dispatch Table via GNU C Computed Gotos */
    static const void * const __dispatch_table[64] = {
        [0 ... 63] = &&__h_default,
        [0x33] = &&__h_vadd,
        [0x2E] = &&__h_vsub,
        [0x16] = &&__h_vmul,
        [0x30] = &&__h_vxor,
        [0x11] = &&__h_vand,
        [0x4] = &&__h_vor,
        [0x3] = &&__h_vsll,
        [0x32] = &&__h_vsrl,
        [0x1] = &&__h_vli,
        [0x1D] = &&__h_vmv,
        [0x1F] = &&__h_vle8,
        [0x1B] = &&__h_vse8,
        [0x10] = &&__h_vret,
        [0x3E] = &&__h_vbge,
        [0x26] = &&__h_vj,
        /* Polymorphic Multi-Alias Opcode Handlers */
        [0x23] = &&__h_vadd_alt1,
        [0xB] = &&__h_vadd_alt2,
        [0xF] = &&__h_vsub_alt1,
        [0x38] = &&__h_vsub_alt2,
        [0x24] = &&__h_vxor_alt1,
        [0xD] = &&__h_vxor_alt2,
        [0x34] = &&__h_vand_alt1,
        [0x22] = &&__h_vor_alt1,
        [0x36] = &&__h_vmul_alt1,
        [0x2B] = &&__h_vmv_alt1,
        [0x27] = &&__h_vli_alt1,

    };

    #define __VISA_DISPATCH() do { \
        if (__pc >= 8) goto __h_vret; \
        unsigned int __slot = ((__pc * 5U) + 6U) % 8U; \
        __raw = __vbc_live[__slot]; \
        __key = 0x36E849E2U ^ (__pc * 0x45D9F3BU); \
        __inst = __raw ^ __key; \
        __funct6 = (unsigned char)((__inst >> 26) & 0x3F); \
        __vm     = (unsigned char)((__inst >> 25) & 0x01); \
        __vs2    = (unsigned char)((__inst >> 20) & 0x1F); \
        __vs1    = (unsigned char)((__inst >> 15) & 0x1F); \
        __funct3 = (unsigned char)((__inst >> 12) & 0x07); \
        __vd     = (unsigned char)((__inst >> 7)  & 0x1F); \
        __pc++; \
        __vm_state_acc = ((__vm_state_acc * 0x63c63cd93839c9b9ULL) ^ (__vd + __funct6 + (unsigned long long)__pc)) * 0x517CC1B727220A95ULL; \
        goto *__dispatch_table[__funct6 & 0x3F]; \
    } while (0)

    /* Enter Direct Threading pipeline */
    __VISA_DISPATCH();

__h_vadd: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a ^ __b) + ((__a & __b) << 1));
    __VISA_DISPATCH();
}
__h_vadd_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a | __b) + (__a & __b));
    __VISA_DISPATCH();
}
__h_vadd_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, ((__a | __b) << 1) - (__a ^ __b));
    __VISA_DISPATCH();
}
__h_vsub: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a ^ __b) - ((~__a & __b) << 1));
    __VISA_DISPATCH();
}
__h_vsub_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a & ~__b) - (~__a & __b));
    __VISA_DISPATCH();
}
__h_vsub_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a ^ ~__b) + 1ULL + ((__a & ~__b) << 1));
    __VISA_DISPATCH();
}
__h_vmul:
    __VREG_SET(__vd, (unsigned long long)(__VREG_GET(__vs1) * __VREG_GET(__vs2)));
    __VISA_DISPATCH();
__h_vmul_alt1:
    __VREG_SET(__vd, (unsigned long long)((__VREG_GET(__vs1) ^ 0) * (__VREG_GET(__vs2) ^ 0)));
    __VISA_DISPATCH();
__h_vxor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a | __b) - (__a & __b));
    __VISA_DISPATCH();
}
__h_vxor_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (~__a & __b) + (__a & ~__b));
    __VISA_DISPATCH();
}
__h_vxor_alt2: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a + __b) - ((__a & __b) << 1));
    __VISA_DISPATCH();
}
__h_vand: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a | __b) - (__a ^ __b));
    __VISA_DISPATCH();
}
__h_vand_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a + __b) - (__a | __b));
    __VISA_DISPATCH();
}
__h_vor: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a & __b) + (__a ^ __b));
    __VISA_DISPATCH();
}
__h_vor_alt1: {
    unsigned long long __a = __VREG_GET(__vs1), __b = __VREG_GET(__vs2);
    __VREG_SET(__vd, (__a + __b) - (__a & __b));
    __VISA_DISPATCH();
}
__h_vsll: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, __a << __sh);
    __VISA_DISPATCH();
}
__h_vsrl: {
    unsigned long long __a = __VREG_GET(__vs1), __sh = __VREG_GET(__vs2) & 0x3FULL;
    __VREG_SET(__vd, (unsigned long long)(__a >> __sh));
    __VISA_DISPATCH();
}
__h_vli:
    __VREG_SET(__vd, (unsigned long long)((__vm << 13) | (__funct3 << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();
__h_vli_alt1:
    __VREG_SET(__vd, (unsigned long long)((((__vm << 3) | __funct3) << 10) | (__vs1 << 5) | __vs2));
    __VISA_DISPATCH();
__h_vmv:
    __VREG_SET(__vd, __VREG_GET(__vs1));
    __VISA_DISPATCH();
__h_vmv_alt1:
    __VREG_SET(__vd, __VREG_GET(__vs1) ^ 0);
    __VISA_DISPATCH();
__h_vle8: {
    const unsigned char *__load_base = (const unsigned char *)(uintptr_t)__VREG_GET(__vs1);
    if (__load_base) {
        __VREG_SET(__vd, (unsigned long long)__load_base[__VREG_GET(__vs2)]);
    }
    __VISA_DISPATCH();
}
__h_vse8:
    if (__vsp_d < 63) {
        __vstack_data[__vsp_d++] = __VREG_GET(__vs1);
    }
    __VISA_DISPATCH();
__h_vbge: {
    unsigned int __branch_target = (__inst >> 7) & 0xFFU;
    if (__VREG_GET(__vs1) >= __VREG_GET(__vs2)) {
        __pc = (unsigned int)((__branch_target) + ((__vm_state_acc * (__vm_state_acc + 1ULL)) & 1ULL));
    }
    __VISA_DISPATCH();
}
__h_vj: {
    unsigned int __jump_target = (__inst >> 7) & 0x7FFFFU;
    __pc = (unsigned int)((__jump_target) + ((__vm_state_acc * (__vm_state_acc + 1ULL)) & 1ULL));
    __VISA_DISPATCH();
}
__h_default:
    __builtin_trap();

__h_vret: ;
    /* Verify Shadow Control Stack CFI Canary */
    if (__vsp_c == 0 || ((__vstack_ctrl[--__vsp_c] ^ 0x8fd17f58eddcb02bULL) != __cfi_canary)) {
        __builtin_trap();
    }
    /* Vector 12: Microarchitectural Timer Check & Silent State Poisoning */
    #if defined(__aarch64__)
    unsigned long long __t_exit;
    __asm__ volatile("mrs %0, cntvct_el0" : "=r"(__t_exit));
    #elif defined(__x86_64__)
    unsigned int __x_lo, __x_hi;
    __asm__ volatile("rdtsc" : "=a"(__x_lo), "=d"(__x_hi));
    unsigned long long __t_exit = ((unsigned long long)__x_hi << 32) | __x_lo;
    #else
    unsigned long long __t_exit = 0;
    #endif
    unsigned long long __t_delta = (__t_exit > __t_entry) ? (__t_exit - __t_entry) : 0ULL;
    unsigned long long __stepped = (__t_delta > 1000000000ULL) ? 1ULL : 0ULL;
    __vm_state_acc ^= (__stepped * 0x9E3779B97F4A7C15ULL);

    /* Vector 11: Anti-Symbolic Quadratic Invariant & Dataflow Interlock */
    if (((__vm_state_acc * (__vm_state_acc + 1ULL)) & 1ULL) != 0ULL) {
        __builtin_trap();
    }
    unsigned long long __res_val = (__VREG_GET(3) ^ (__stepped * 0xBADF00DULL)) ^ ((__vm_state_acc * (__vm_state_acc + 1ULL)) & 1ULL);
    __builtin_memset(&__vbank, 0, sizeof(__vbank));
    __builtin_memset(__vbc_live, 0, sizeof(__vbc_live));
    __builtin_memset(__vstack_data, 0, sizeof(__vstack_data));
    __builtin_memset(__vstack_ctrl, 0, sizeof(__vstack_ctrl));
    return (int)__res_val;
}
#undef __VREG_ROT
#undef __VREG_MASK
#undef __VREG_GET
#undef __VREG_SET
#undef __VISA_DISPATCH

#line 16 "examples/09_test_multi_isa.c"
extern int ( /* missing proto */  printf)() ;
#line 13 "examples/09_test_multi_isa.c"
int main(void) 
{ 
  int r1 ;
  int __attribute__((__annotate__("ocasorry:visa:VCPU1_Arch")))  tmp ;
  int r2 ;
  int __attribute__((__annotate__("ocasorry:visa:VCPU2_Arch")))  tmp___0 ;

  {
#line 14
  tmp = compute_tier1(10, 20);
#line 14
  r1 = (int )tmp;
#line 15
  tmp___0 = compute_tier2(10, 20);
#line 15
  r2 = (int )tmp___0;
#line 16
  printf("Tier1: %d, Tier2: %d\n", r1, r2);
#line 17
  if (r1 == 49) {
#line 17
    if (r2 == 110) {
#line 18
      printf("MULTI-ISA VERIFIED PASS!\n");
#line 19
      return (0);
    }
  }
#line 21
  return (1);
}
}
