/**
 * Standalone C Source Demonstration:
 * Two-Level JITting (Tier 1 Stager + Tier 2 Encrypted Payload)
 * with Hardware-Level Implicit Flow via Apple Silicon (ARM64) Signal Interception.
 *
 * Generated by Vectis Multi-Target Obfuscator Engine.
 */

#define _DARWIN_C_SOURCE
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <sys/mman.h>
#include <unistd.h>

#ifdef __APPLE__
#include <libkern/OSCacheControl.h>
#include <pthread.h>
#include <sys/ucontext.h>
#endif

/* ========================================================================= */
/* [1] GENERATED JIT PAYLOADS (ARM64 Little-Endian Byte Streams)             */
/* ========================================================================= */

/**
 * Tier 1: Outer JIT Hardware Trap Stager (8 bytes)
 * Disassembly:
 *   brk  #0x42        ; (0xD4200840) -> Triggers hardware SIGTRAP fault
 *   ret               ; (0xD65F03C0)
 */
static const unsigned char g_tier1_stager_code[8] = {
    0x40, 0x08, 0x20, 0xd4,  /* brk #0x42 */
    0xc0, 0x03, 0x5f, 0xd6   /* ret       */
};

/**
 * Dynamic Session Key for Tier 2 Decryption: 0x9F
 */
#define TIER2_SESSION_KEY 0x9F

/**
 * Tier 2: Inner Encrypted Payload (132 bytes)
 * Contains the full protected algorithm: f(x0, x1) = (x0 + x1) ^ 0x5A5A
 * Obfuscated with: Linear MBA + Control Flow Flattening (CFF) + Invariant Opaque Predicates
 * Encrypted via: Byte[i] ^ 0x9F
 */
static const unsigned char g_tier2_encrypted_payload[132] = {
    0x50, 0xe9, 0x1d, 0x4d, 0x9e, 0x9f, 0x9f, 0x8b, 
    0x4f, 0xe9, 0x1d, 0x4d, 0x60, 0x9e, 0x8f, 0x74, 
    0x9f, 0x9e, 0x9f, 0xcb, 0xcf, 0x44, 0x1b, 0x4d, 
    0x60, 0x9e, 0x8f, 0x74, 0x9f, 0x9d, 0x9f, 0xcb, 
    0x6f, 0xa2, 0x18, 0x4d, 0x60, 0x9e, 0x8f, 0x74, 
    0xff, 0x9d, 0x9f, 0xcb, 0x5f, 0x9c, 0xc0, 0x49, 
    0x6e, 0x9c, 0xbf, 0x35, 0x8f, 0x9f, 0x8e, 0x15, 
    0x80, 0x9d, 0x9f, 0x6e, 0x5e, 0x9e, 0x9f, 0xcb, 
    0x8f, 0x9f, 0x9e, 0x35, 0x8f, 0x65, 0xe0, 0x4c, 
    0x8e, 0x9f, 0x9e, 0x55, 0x9f, 0x9d, 0x8e, 0x54, 
    0xdd, 0xd4, 0x14, 0x4d, 0xd0, 0x44, 0x1b, 0x4d, 
    0x73, 0x60, 0x60, 0x88, 0x6f, 0x9c, 0xbd, 0x35, 
    0x8f, 0x9f, 0x8f, 0x15, 0x6e, 0x9c, 0xbf, 0x35, 
    0xae, 0x9d, 0x9d, 0x15, 0x9f, 0x9d, 0x8e, 0x35, 
    0x5f, 0x9c, 0xc0, 0x49, 0x70, 0x21, 0x32, 0x41, 
    0x92, 0x6f, 0x32, 0x25, 0xe7, 0xc9, 0xab, 0x8d, 
    0x5f, 0x9c, 0xc0, 0x49
};

/* ========================================================================= */
/* [2] HARDWARE IMPLICIT FLOW SIGNAL ROUTER                                  */
/* ========================================================================= */

static void *g_active_tier2_pc = NULL;

#if defined(__APPLE__) && defined(__aarch64__)
static void two_tier_hardware_signal_router(int sig, siginfo_t *info, void *context) {
    (void)sig;
    (void)info;
    ucontext_t *uc = (ucontext_t *)context;

    if (g_active_tier2_pc != NULL) {
        /* IMPLICIT FLOW: Overwrite the hardware Program Counter (PC) in CPU context!
         * When the kernel returns from the signal handler, execution resumes directly
         * at the decrypted Tier 2 entry point in hardware, with ZERO branch instructions. */
        uc->uc_mcontext->__ss.__pc = (uint64_t)g_active_tier2_pc;
    }
}
#endif

/* ========================================================================= */
/* [3] TWO-LEVEL JIT EXECUTION ENGINE                                        */
/* ========================================================================= */

typedef int64_t (*jit_entry_fn2_t)(int64_t, int64_t);

int64_t execute_two_tier_obfuscated_fn(int64_t x0, int64_t x1) {
    size_t page_size = (size_t)sysconf(_SC_PAGESIZE);
    size_t tier1_alloc_sz = (sizeof(g_tier1_stager_code) + page_size - 1) & ~(page_size - 1);
    size_t tier2_alloc_sz = (sizeof(g_tier2_encrypted_payload) + page_size - 1) & ~(page_size - 1);

    /* --- STEP 1: Allocate & Decrypt Tier 2 JIT Page --- */
    void *tier2_page = mmap(NULL, tier2_alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                            MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0);
    if (tier2_page == MAP_FAILED) {
        perror("mmap tier2");
        exit(1);
    }

    /* Decrypt on-the-fly into memory */
    unsigned char dec_payload[sizeof(g_tier2_encrypted_payload)];
    for (size_t i = 0; i < sizeof(g_tier2_encrypted_payload); i++) {
        dec_payload[i] = g_tier2_encrypted_payload[i] ^ TIER2_SESSION_KEY;
    }

    pthread_jit_write_protect_np(0); /* Enable write mode */
    memcpy(tier2_page, dec_payload, sizeof(g_tier2_encrypted_payload));
    pthread_jit_write_protect_np(1); /* Enable execute mode (W^X) */
    sys_icache_invalidate(tier2_page, sizeof(g_tier2_encrypted_payload)); /* Flush instruction cache */

    g_active_tier2_pc = tier2_page;

    /* --- STEP 2: Allocate Tier 1 JIT Stager Page --- */
    void *tier1_page = mmap(NULL, tier1_alloc_sz, PROT_READ | PROT_WRITE | PROT_EXEC,
                            MAP_ANON | MAP_PRIVATE | MAP_JIT, -1, 0);
    if (tier1_page == MAP_FAILED) {
        perror("mmap tier1");
        exit(1);
    }

    pthread_jit_write_protect_np(0);
    memcpy(tier1_page, g_tier1_stager_code, sizeof(g_tier1_stager_code));
    pthread_jit_write_protect_np(1);
    sys_icache_invalidate(tier1_page, sizeof(g_tier1_stager_code));

    /* --- STEP 3: Register POSIX Signal Interceptors --- */
    struct sigaction sa, old_sigtrap, old_sigbus, old_sigsegv, old_sigill;
    memset(&sa, 0, sizeof(sa));
#if defined(__APPLE__) && defined(__aarch64__)
    sa.sa_sigaction = two_tier_hardware_signal_router;
    sa.sa_flags = SA_SIGINFO;
#endif
    sigaction(SIGTRAP, &sa, &old_sigtrap);
    sigaction(SIGBUS, &sa, &old_sigbus);
    sigaction(SIGSEGV, &sa, &old_sigsegv);
    sigaction(SIGILL, &sa, &old_sigill);

    /* --- STEP 4: Invoke Tier 1 Entry (Triggers Hardware Fault -> Redirection to Tier 2) --- */
    jit_entry_fn2_t tier1_entry = (jit_entry_fn2_t)tier1_page;
    int64_t result = tier1_entry(x0, x1);

    /* --- STEP 5: Cleanup Handlers & Memory Pages --- */
    sigaction(SIGTRAP, &old_sigtrap, NULL);
    sigaction(SIGBUS, &old_sigbus, NULL);
    sigaction(SIGSEGV, &old_sigsegv, NULL);
    sigaction(SIGILL, &old_sigill, NULL);

    g_active_tier2_pc = NULL;
    munmap(tier1_page, tier1_alloc_sz);
    munmap(tier2_page, tier2_alloc_sz);

    return result;
}

/* ========================================================================= */
/* [4] MAIN DEMONSTRATOR                                                     */
/* ========================================================================= */

int main(int argc, char **argv) {
    int64_t x0 = (argc > 1) ? atoll(argv[1]) : 100LL;
    int64_t x1 = (argc > 2) ? atoll(argv[2]) : 200LL;
    int64_t expected = (x0 + x1) ^ 0x5A5ALL;

    printf("=================================================================\n");
    printf("  Vectis: Two-Level JITting + Hardware Implicit Flow Demo      \n");
    printf("=================================================================\n");
    printf("  Input Arguments: x0 = %lld, x1 = %lld\n", x0, x1);
    printf("  Expected Value : (x0 + x1) ^ 0x5A5A = %lld (0x%llX)\n\n", expected, expected);

    printf("  [Stage 1] Tier 1 Stager executed -> Triggering BRK #0x42 fault...\n");
    printf("  [Stage 2] Signal Handler intercepted -> Modifying CPU context PC...\n");
    printf("  [Stage 3] Tier 2 Decrypted & Executed in hardware directly!\n\n");

    int64_t actual = execute_two_tier_obfuscated_fn(x0, x1);

    printf("  Actual Result  : %lld (0x%llX)\n", actual, actual);
    printf("  Status         : %s\n", (actual == expected) ? "PASSED [OK]" : "FAILED [MISMATCH]");
    printf("=================================================================\n");

    return (actual == expected) ? 0 : 1;
}
