#!/bin/bash
# Auto-generated by sail_params_to_synth.py
# params: tools/sail_optimal_params.json

/Volumes/External/Code/ocasorry/_build/default/bin/vectis_synth.exe --vcpu-tier visa --output-dir examples/ml_optimized --gf-poly 0x8d --rol-const 5 --imm-bits 16
/Volumes/External/Code/ocasorry/_build/default/bin/vectis_synth.exe --vcpu-tier nested_vm --output-dir examples/ml_optimized --hash-bits 48 --stack-depth 8 --state-regs 5
/Volumes/External/Code/ocasorry/_build/default/bin/vectis_synth.exe --vcpu-tier rolling_vkey --output-dir examples/ml_optimized --key-bits 48 --state-regs 4 --gf-poly 0x4d --lcg-mult 31
/Volumes/External/Code/ocasorry/_build/default/bin/vectis_synth.exe --vcpu-tier ephemeral_jit --output-dir examples/ml_optimized --page-shift 14 --wipe-passes 4 --jit-regs 4
