#!/bin/bash
# Auto-generated by sail_params_to_synth.py
# params: /Volumes/External/Code/ocasorry/tools/sail_optimal_params.json

/Volumes/External/Code/ocasorry/_build/default/bin/vectis_synth.exe --vcpu visa --output-dir examples/ml_optimized --name ML_Opt_VISA_Arch --seed 175
/Volumes/External/Code/ocasorry/_build/default/bin/vectis_synth.exe --vcpu nested_vm --output-dir examples/ml_optimized --name ML_Opt_NESTED_Arch --seed 9039
/Volumes/External/Code/ocasorry/_build/default/bin/vectis_synth.exe --vcpu rolling_vkey --output-dir examples/ml_optimized --name ML_Opt_ROLLING_Arch --seed 8581
/Volumes/External/Code/ocasorry/_build/default/bin/vectis_synth.exe --vcpu ephemeral --output-dir examples/ml_optimized --name ML_Opt_EPHEMERAL_Arch --seed 8800
