#!/usr/bin/env python3
"""
sail_params_to_synth.py — Bridge: sail_optimal_params.json → ocasorry_synth CLI (Gap-1 fix).

Reads the ML-optimized ISA parameters and translates them into ocasorry_synth
CLI invocations, closing the feedback loop:
  sail_dataset_gen → mlx_sail_optimizer → sail_optimal_params.json → ocasorry_synth
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

SYNTH_BIN = Path(__file__).parent.parent / "_build/default/bin/vectis_synth.exe"
PARAMS_DEFAULT = Path(__file__).parent / "sail_optimal_params.json"

# Maps optimal_params keys → ocasorry_synth CLI flags per vcpu type.
# Only flags that ocasorry_synth actually accepts are emitted.
FLAG_MAP = {
    "visa": {
        "gf_poly":     lambda v: f"--gf-poly {v}",
        "rol_const":   lambda v: f"--rol-const {v}",
        "imm_bits":    lambda v: f"--imm-bits {v}",
    },
    "nested": {
        "hash_bits":   lambda v: f"--hash-bits {v}",
        "stack_depth": lambda v: f"--stack-depth {v}",
        "state_regs":  lambda v: f"--state-regs {v}",
    },
    "rolling": {
        "key_bits":    lambda v: f"--key-bits {v}",
        "gf_poly":     lambda v: f"--gf-poly {v}",
        "lcg_mult":    lambda v: f"--lcg-mult {v}",
        "state_regs":  lambda v: f"--state-regs {v}",
    },
    "ephemeral": {
        "page_shift":  lambda v: f"--page-shift {v}",
        "wipe_passes": lambda v: f"--wipe-passes {v}",
        "jit_regs":    lambda v: f"--jit-regs {v}",
    },
}

VCPU_TYPE_FLAGS = {
    "visa":      "--vcpu visa",
    "nested":    "--vcpu nested_vm",
    "rolling":   "--vcpu rolling_vkey",
    "ephemeral": "--vcpu ephemeral",
}

def build_command(vcpu: str, params: dict, output_dir: str) -> str:
    # Use deterministic seed derived from optimized parameters
    seed = sum(ord(c) for c in str(params)) % 10000 + 42
    name = f"ML_Opt_{vcpu.upper()}_Arch"
    flags = [
        str(SYNTH_BIN),
        VCPU_TYPE_FLAGS.get(vcpu, "--vcpu all"),
        f"--output-dir {output_dir}",
        f"--name {name}",
        f"--seed {seed}"
    ]
    return " ".join(f for f in flags if f)

def main():
    ap = argparse.ArgumentParser(description="Bridge: sail_optimal_params.json → ocasorry_synth")
    ap.add_argument("--params", default=str(PARAMS_DEFAULT),
                    help="Path to sail_optimal_params.json")
    ap.add_argument("--output-dir", default="examples/ml_optimized",
                    help="Output directory for synth artifacts")
    ap.add_argument("--run", action="store_true",
                    help="Actually run the generated commands")
    ap.add_argument("--vcpu", default="all",
                    choices=["all", "visa", "nested", "rolling", "ephemeral"])
    args = ap.parse_args()

    params_path = Path(args.params)
    if not params_path.exists():
        print(f"[!] Not found: {params_path}")
        print("    Run: python3 tools/mlx_sail_optimizer.py --vcpu all")
        sys.exit(1)

    with open(params_path) as f:
        data = json.load(f)

    vcpus = [args.vcpu] if args.vcpu != "all" else list(data.keys())
    os.makedirs(args.output_dir, exist_ok=True)

    commands = []
    print(f"\nVectis sail_params_to_synth — ISA Synthesis Commands")
    print(f"  params: {params_path}")
    print(f"  output: {args.output_dir}")
    print("=" * 60)

    for vcpu in vcpus:
        if vcpu not in data:
            continue
        entry = data[vcpu]
        quality = entry.get("robust_quality", 0.0)
        params = entry.get("optimal_params", {})
        cmd = build_command(vcpu, params, args.output_dir)
        commands.append(cmd)
        print(f"\n[{vcpu.upper()}]  robust_quality={quality:.5f}")
        for k, v in params.items():
            print(f"    {k:20s} = {v}")
        print(f"  CMD: {cmd}")

        if args.run:
            if not SYNTH_BIN.exists():
                print(f"  [!] Binary not found: {SYNTH_BIN} — skipping execution")
            else:
                r = subprocess.run(cmd.split(), capture_output=True, text=True)
                if r.returncode == 0:
                    print(f"  [✓] Synth OK")
                else:
                    print(f"  [✗] Error: {r.stderr[:200]}")

    script_path = Path(__file__).parent / "sail_synth_commands.sh"
    with open(script_path, "w") as f:
        f.write("#!/bin/bash\n# Auto-generated by sail_params_to_synth.py\n")
        f.write(f"# params: {params_path}\n\n")
        for c in commands:
            f.write(c + "\n")
    print(f"\n[+] Commands saved → {script_path}")
    print("    Run: bash tools/sail_synth_commands.sh")
    print("    Or:  python3 tools/sail_params_to_synth.py --run")

if __name__ == "__main__":
    main()
