#!/usr/bin/env python3
"""
tools/visa_synthesizer.py - Formal Multi-VCPU & Sail Architecture Synthesizer
Synthesizes randomized formal Sail-compatible ISA specifications and JSON schemas for OcaSorry.

Supports:
  - 4-Tier Federated Architecture: VCPU 1 (visa), VCPU 2 (nested_vm), VCPU 3 (rolling_vkey), VCPU 4 (ephemeral)
  - 8-Tier Cryptographic Architecture (without nested_vm): 8 distinct VCPUs cascading across rounds
"""

import sys
import os
import json
import random
import argparse

# ==============================================================================
# VCPU 1: random_vISA (32-bit Vector ISA)
# ==============================================================================
def generate_random_visa(seed=None, name=None, tier=1):
    if seed is not None:
        random.seed(seed + tier)
    
    isa_id = random.randint(0x1000, 0xFFFF)
    isa_name = name or f"vISA_Vector_Arch_{isa_id:04X}"
    
    base_opcode = random.choice([0x57, 0x0B, 0x2B, 0x7B, 0x37, 0x67])
    
    funct6_pool = list(range(0, 64))
    random.shuffle(funct6_pool)
    
    opcodes = {
        "vadd_vv": funct6_pool.pop(),
        "vsub_vv": funct6_pool.pop(),
        "vmul_vv": funct6_pool.pop(),
        "vxor_vv": funct6_pool.pop(),
        "vand_vv": funct6_pool.pop(),
        "vor_vv":  funct6_pool.pop(),
        "vsll_vv": funct6_pool.pop(),
        "vsrl_vv": funct6_pool.pop(),
        "vli_vi":  funct6_pool.pop(),
        "vmv_vv":  funct6_pool.pop(),
        "vle8_v":  funct6_pool.pop(),
        "vse8_v":  funct6_pool.pop(),
        "vret_v":  funct6_pool.pop(),
        "vbge_vv": funct6_pool.pop(),
        "vblt_vv": funct6_pool.pop(),
        "vbeq_vv": funct6_pool.pop(),
        "vbne_vv": funct6_pool.pop(),
        "vj":      funct6_pool.pop(),
    }
    
    pack_key = random.randint(0x10000000, 0xFFFFFFFF)
    delta_key = random.choice([0x1000193, 0x9E3779B9, 0x045D9F3B, 0x21F0AAAD])
    
    spec = {
        "vcpu_tier": tier,
        "vcpu_type": "visa",
        "isa_name": isa_name,
        "isa_version": "2.0",
        "word_bits": 32,
        "reg_count": 16,
        "pack_key": pack_key,
        "delta_key": delta_key,
        "layout": {
            "funct6_shift": 26,
            "funct6_mask": 0x3F,
            "vm_shift": 25,
            "vs2_shift": 20,
            "vs1_shift": 15,
            "funct3_shift": 12,
            "vd_shift": 7,
            "opcode_val": base_opcode
        },
        "bitfields": {
            "funct6": {"msb": 31, "lsb": 26, "bits": 6},
            "vm":     {"msb": 25, "lsb": 25, "bits": 1},
            "vs2":    {"msb": 24, "lsb": 20, "bits": 5},
            "vs1":    {"msb": 19, "lsb": 15, "bits": 5},
            "funct3": {"msb": 14, "lsb": 12, "bits": 3},
            "vd":     {"msb": 11, "lsb": 7,  "bits": 5},
            "opcode": {"msb": 6,  "lsb": 0,  "bits": 7}
        },
        "opcodes": opcodes
    }
    return spec

def export_sail_visa(spec):
    op = spec["opcodes"]
    return f"""/* ==============================================================================
 * Sail Architecture Specification: {spec["isa_name"]} (Tier {spec.get("vcpu_tier", 1)})
 * Generated by OcaSorry Dynamic vISA Synthesizer
 * ============================================================================== */

default Order dec
$include <prelude.sail>

type regidx = bits(5)
type imm14  = bits(14)
type imm7   = bits(7)

/* 16 Virtual 32-bit Vector Registers */
register R : vector(16, dec, bits(32))
register PC : bits(32)

/* AST Node Union for Synthesized {spec["isa_name"]} */
union ast = {{
    VADD_VV : (regidx, regidx, regidx),
    VSUB_VV : (regidx, regidx, regidx),
    VMUL_VV : (regidx, regidx, regidx),
    VXOR_VV : (regidx, regidx, regidx),
    VAND_VV : (regidx, regidx, regidx),
    VOR_VV  : (regidx, regidx, regidx),
    VSLL_VV : (regidx, regidx, regidx),
    VSRL_VV : (regidx, regidx, regidx),
    VLI_VI  : (regidx, bits(14)),
    VMV_VV  : (regidx, regidx),
    VLE8_V  : (regidx, regidx),
    VSE8_V  : (regidx, regidx, regidx),
    VRET_V  : (regidx),
    VBGE_VV : (regidx, regidx),
    VJ      : (bits(32))
}}

/* Dynamic Instruction Decoder */
val decode : bits(32) -> option(ast)
function decode(inst) = {{
    let funct6 : bits(6) = inst[31..26];
    let vm     : bits(1) = inst[25..25];
    let vs2    : bits(5) = inst[24..20];
    let vs1    : bits(5) = inst[19..15];
    let funct3 : bits(3) = inst[14..12];
    let vd     : bits(5) = inst[11..7];
    let opcode : bits(7) = inst[6..0];

    let imm14 : bits(14) = vm @ funct3 @ vs1 @ vs2;

    match funct6 {{
        {op["vadd_vv"]} => Some(VADD_VV(vd, vs1, vs2)),
        {op["vsub_vv"]} => Some(VSUB_VV(vd, vs1, vs2)),
        {op["vmul_vv"]} => Some(VMUL_VV(vd, vs1, vs2)),
        {op["vxor_vv"]} => Some(VXOR_VV(vd, vs1, vs2)),
        {op["vand_vv"]} => Some(VAND_VV(vd, vs1, vs2)),
        {op["vor_vv"]}  => Some(VOR_VV(vd, vs1, vs2)),
        {op["vsll_vv"]} => Some(VSLL_VV(vd, vs1, vs2)),
        {op["vsrl_vv"]} => Some(VSRL_VV(vd, vs1, vs2)),
        {op["vli_vi"]}  => Some(VLI_VI(vd, imm14)),
        {op["vmv_vv"]}  => Some(VMV_VV(vd, vs1)),
        {op["vle8_v"]}  => Some(VLE8_V(vd, vs2)),
        {op["vret_v"]}  => Some(VRET_V(vd)),
        {op["vbge_vv"]} => Some(VBGE_VV(vs1, vs2)),
        {op["vj"]}      => Some(VJ(inst)),
        _ => None()
    }}
}}

/* Execution Semantics */
function execute(instruction : ast) -> unit = {{
    match instruction {{
        VADD_VV(vd, vs1, vs2) => R[vd] = R[vs1] + R[vs2],
        VSUB_VV(vd, vs1, vs2) => R[vd] = R[vs1] - R[vs2],
        VMUL_VV(vd, vs1, vs2) => R[vd] = R[vs1] * R[vs2],
        VXOR_VV(vd, vs1, vs2) => R[vd] = R[vs1] ^ R[vs2],
        VAND_VV(vd, vs1, vs2) => R[vd] = R[vs1] & R[vs2],
        VOR_VV(vd, vs1, vs2)  => R[vd] = R[vs1] | R[vs2],
        VSLL_VV(vd, vs1, vs2) => R[vd] = R[vs1] << unsigned(R[vs2]),
        VSRL_VV(vd, vs1, vs2) => R[vd] = R[vs1] >> unsigned(R[vs2]),
        VLI_VI(vd, imm)       => R[vd] = EXTZ(imm),
        VMV_VV(vd, vs1)       => R[vd] = R[vs1],
        VLE8_V(vd, vs2)       => (),
        VSE8_V(vd, vs1, vs2)  => (),
        VRET_V(vd)            => (),
        VBGE_VV(vs1, vs2)     => (),
        VJ(target)            => ()
    }}
}}
"""

# ==============================================================================
# VCPU 2: nested_vm (2-Tier Hierarchical Nested VM)
# ==============================================================================
def generate_nested_vm(seed=None, name=None):
    if seed is not None:
        random.seed(seed)
    
    vm_id = random.randint(0x1000, 0xFFFF)
    vm_name = name or f"NestedVM_2Tier_Arch_{vm_id:04X}"
    
    outer_key = random.randint(0x50, 0xAA)
    inner_key = random.randint(0x80, 0xEE)
    
    spec = {
        "vcpu_tier": 2,
        "vcpu_type": "nested_vm",
        "isa_name": vm_name,
        "isa_version": "2.0",
        "outer_key": outer_key,
        "inner_key": inner_key,
        "outer_opcodes": {
            "op_out_setup": 0x10,
            "op_out_dispatch": 0x30,
            "op_out_mutate_key": 0x20,
            "op_out_halt": 0xFF
        },
        "inner_opcodes": {
            "op_in_load_arg": 0x01,
            "op_in_load_const": 0x02,
            "op_in_add": 0x03,
            "op_in_sub": 0x04,
            "op_in_xor": 0x05,
            "op_in_mul": 0x06,
            "op_in_ret": 0x0F
        }
    }
    return spec

def export_sail_nested_vm(spec):
    return f"""/* ==============================================================================
 * Sail Architecture Specification: {spec["isa_name"]} (2-Tier Nested VM)
 * Generated by OcaSorry Multi-Tier VM Synthesizer
 * ============================================================================== */

default Order dec
$include <prelude.sail>

type byte = bits(8)
type regidx = bits(3)

/* Inner Worker Registers */
register Inner_R : vector(8, dec, bits(32))
register Outer_PC : bits(32)
register Inner_PC : bits(32)

union outer_ast = {{
    OUT_SETUP      : (unit),
    OUT_DISPATCH   : (unit),
    OUT_MUTATE_KEY : (byte),
    OUT_HALT       : (unit)
}}

union inner_ast = {{
    IN_LOAD_ARG   : (regidx),
    IN_LOAD_CONST : (regidx, byte),
    IN_ADD        : (regidx, regidx, regidx),
    IN_SUB        : (regidx, regidx, regidx),
    IN_XOR        : (regidx, regidx, regidx),
    IN_MUL        : (regidx, regidx, regidx),
    IN_RET        : (regidx)
}}

function execute_outer(op : outer_ast) -> unit = {{
    match op {{
        OUT_SETUP      => {{ Inner_PC = EXTZ(0x00) }},
        OUT_DISPATCH   => {{ () }},
        OUT_MUTATE_KEY(k) => {{ () }},
        OUT_HALT       => {{ () }}
    }}
}}

function execute_inner(op : inner_ast) -> unit = {{
    match op {{
        IN_LOAD_ARG(rd)         => Inner_R[rd] = EXTZ(0x00),
        IN_LOAD_CONST(rd, imm)  => Inner_R[rd] = EXTZ(imm),
        IN_ADD(rd, rs1, rs2)    => Inner_R[rd] = Inner_R[rs1] + Inner_R[rs2],
        IN_SUB(rd, rs1, rs2)    => Inner_R[rd] = Inner_R[rs1] - Inner_R[rs2],
        IN_XOR(rd, rs1, rs2)    => Inner_R[rd] = Inner_R[rs1] ^ Inner_R[rs2],
        IN_MUL(rd, rs1, rs2)    => Inner_R[rd] = Inner_R[rs1] * Inner_R[rs2],
        IN_RET(rs)              => ()
    }}
}}
"""

# ==============================================================================
# VCPU 3: rolling_vkey (Stateful History-Dependent Key VM)
# ==============================================================================
def generate_rolling_vkey(seed=None, name=None, tier=3):
    if seed is not None:
        random.seed(seed + tier * 10)
    
    vm_id = random.randint(0x1000, 0xFFFF)
    vm_name = name or f"RollingVKey_Arch_{vm_id:04X}"
    
    vkey_seed = random.randint(0x10000000, 0xFFFFFFFF)
    lcg_mult = random.choice([33, 65, 31, 17])
    lcg_delta = random.choice([0x9E3779B9, 0x85EBCA6B, 0xC2B2AE3D])
    
    spec = {
        "vcpu_tier": tier,
        "vcpu_type": "rolling_vkey",
        "isa_name": vm_name,
        "vkey_seed": vkey_seed,
        "lcg_multiplier": lcg_mult,
        "lcg_delta": lcg_delta,
        "opcodes": {
            "op_add_imm": 0x01,
            "op_xor_imm": 0x02,
            "op_mul_imm": 0x03,
            "op_halt": 0xFF
        }
    }
    return spec

def export_sail_rolling_vkey(spec):
    return f"""/* ==============================================================================
 * Sail Architecture Specification: {spec["isa_name"]} (Rolling Key VM Tier {spec.get("vcpu_tier", 3)})
 * Generated by OcaSorry Stateful Keychain Synthesizer
 * ============================================================================== */

default Order dec
$include <prelude.sail>

register VKey : bits(32)
register State_Regs : vector(4, dec, bits(32))

union rolling_ast = {{
    R_ADD_IMM : (bits(2), bits(32)),
    R_XOR_IMM : (bits(2), bits(32)),
    R_MUL_IMM : (bits(2), bits(32)),
    R_HALT    : (unit)
}}

function evolve_key(decrypted_word : bits(32)) -> unit = {{
    VKey = (VKey * {spec["lcg_multiplier"]}) ^ (decrypted_word + {spec["lcg_delta"]});
}}

function execute_rolling(op : rolling_ast) -> unit = {{
    match op {{
        R_ADD_IMM(rd, imm) => State_Regs[rd] = State_Regs[rd] + imm,
        R_XOR_IMM(rd, imm) => State_Regs[rd] = State_Regs[rd] ^ imm,
        R_MUL_IMM(rd, imm) => State_Regs[rd] = State_Regs[rd] * imm,
        R_HALT             => ()
    }}
}}
"""

# ==============================================================================
# VCPU 4: ephemeral_jit (In-Memory Ephemeral JIT Wiper VM)
# ==============================================================================
def generate_ephemeral_vm(seed=None, name=None, tier=4):
    if seed is not None:
        random.seed(seed + tier * 100)
    
    vm_id = random.randint(0x1000, 0xFFFF)
    vm_name = name or f"Ephemeral_JIT_Arch_{vm_id:04X}"
    
    spec = {
        "vcpu_tier": tier,
        "vcpu_type": "ephemeral_jit",
        "isa_name": vm_name,
        "session_key": random.randint(0x10, 0xFE),
        "page_size": 4096,
        "opcodes": {
            "op_alloc_mmap": 0x10,
            "op_decrypt": 0x20,
            "op_execute": 0x30,
            "op_free_zero": 0x40
        }
    }
    return spec

def export_sail_ephemeral_vm(spec):
    return f"""/* ==============================================================================
 * Sail Architecture Specification: {spec["isa_name"]} (Ephemeral JIT Tier {spec.get("vcpu_tier", 4)})
 * Generated by OcaSorry In-Memory JIT Wiper Synthesizer
 * ============================================================================== */

default Order dec
$include <prelude.sail>

register Page_Allocated : bool
register Page_Zeroed    : bool
register Ephemeral_Result : bits(32)

union ephemeral_ast = {{
    EPH_ALLOC_MMAP : (bits(32)),
    EPH_DECRYPT    : (bits(8)),
    EPH_EXECUTE    : (bits(32)),
    EPH_FREE_ZERO  : (unit)
}}

function execute_ephemeral(op : ephemeral_ast) -> unit = {{
    match op {{
        EPH_ALLOC_MMAP(sz) => {{ Page_Allocated = true; Page_Zeroed = false }},
        EPH_DECRYPT(key)   => {{ () }},
        EPH_EXECUTE(input) => {{ Ephemeral_Result = if input != 0 then EXTZ(0x01) else EXTZ(0x00) }},
        EPH_FREE_ZERO()    => {{ Page_Zeroed = true; Page_Allocated = false }}
    }}
}}
"""

# ==============================================================================
# CLI Entrypoint
# ==============================================================================
def main():
    parser = argparse.ArgumentParser(description="OcaSorry Formal Multi-VCPU Sail & JSON Architecture Synthesizer")
    parser.add_argument("-o", "--output-json", default="visa_spec.json", help="Path to output JSON ISA specification")
    parser.add_argument("-s", "--output-sail", default=None, help="Path to output formal Sail specification (.sail)")
    parser.add_argument("--vcpu", choices=["visa", "nested_vm", "rolling_vkey", "ephemeral", "all", "8vcpu"], default="all",
                        help="Target VCPU tier or architecture mode to synthesize (default: all 4 VCPUs)")
    parser.add_argument("--output-dir", default=None, help="Output directory to write all Sail and JSON specs")
    parser.add_argument("--seed", type=int, default=None, help="Deterministic random seed")
    parser.add_argument("--name", default=None, help="Custom ISA architecture name")
    
    args = parser.parse_args()
    
    out_dir = args.output_dir or os.path.dirname(args.output_json) or "."
    os.makedirs(out_dir, exist_ok=True)
    
    if args.vcpu == "8vcpu":
        # Generate 8 VCPU architectures without nested_vm
        vcpus_8 = [
            ("vcpu1_expand_key", generate_random_visa(args.seed, "vISA_AES_ExpandKey_Arch", tier=1), export_sail_visa),
            ("vcpu2_sub_bytes_r1", generate_rolling_vkey(args.seed, "RollingVKey_AES_SubBytesR1_Arch", tier=2), export_sail_rolling_vkey),
            ("vcpu3_shift_mix_r1", generate_random_visa(args.seed, "vISA_AES_ShiftMixR1_Arch", tier=3), export_sail_visa),
            ("vcpu4_feistel_xor_r1", generate_rolling_vkey(args.seed, "RollingVKey_AES_FeistelR1_Arch", tier=4), export_sail_rolling_vkey),
            ("vcpu5_sub_bytes_r2", generate_rolling_vkey(args.seed, "RollingVKey_AES_SubBytesR2_Arch", tier=5), export_sail_rolling_vkey),
            ("vcpu6_shift_mix_r2", generate_random_visa(args.seed, "vISA_AES_ShiftMixR2_Arch", tier=6), export_sail_visa),
            ("vcpu7_feistel_xor_r2", generate_rolling_vkey(args.seed, "RollingVKey_AES_FeistelR2_Arch", tier=7), export_sail_rolling_vkey),
            ("vcpu8_ephemeral_finalize", generate_ephemeral_vm(args.seed, "Ephemeral_JIT_AES_Finalize_Arch", tier=8), export_sail_ephemeral_vm),
        ]
        for prefix, spec, export_fn in vcpus_8:
            j_path = os.path.join(out_dir, f"{prefix}.json")
            s_path = os.path.join(out_dir, f"{prefix}.sail")
            with open(j_path, "w") as f:
                json.dump(spec, f, indent=2)
            with open(s_path, "w") as f:
                f.write(export_fn(spec))
            print(f"[+] [VCPU {spec.get('vcpu_tier', 1)}] Synthesized {spec['isa_name']} -> {j_path} & {s_path}")
            
    elif args.vcpu == "all" or args.output_dir is not None:
        # Generate 4 VCPU architectures
        vcpus = [
            ("vcpu1_visa", generate_random_visa(args.seed, args.name or "vISA_Vector_Cascade_Arch", tier=1), export_sail_visa),
            ("vcpu2_nested_vm", generate_nested_vm(args.seed, "NestedVM_Hierarchical_Arch"), export_sail_nested_vm),
            ("vcpu3_rolling_vkey", generate_rolling_vkey(args.seed, "RollingVKey_Stateful_Arch", tier=3), export_sail_rolling_vkey),
            ("vcpu4_ephemeral_jit", generate_ephemeral_vm(args.seed, "Ephemeral_JIT_Security_Arch", tier=4), export_sail_ephemeral_vm),
        ]
        
        for prefix, spec, export_fn in vcpus:
            j_path = os.path.join(out_dir, f"{prefix}.json")
            s_path = os.path.join(out_dir, f"{prefix}.sail")
            
            with open(j_path, "w") as f:
                json.dump(spec, f, indent=2)
            with open(s_path, "w") as f:
                f.write(export_fn(spec))
            print(f"[+] [VCPU {spec.get('vcpu_tier', 1)}] Synthesized {spec['isa_name']} -> {j_path} & {s_path}")
            
        if args.output_json and args.output_json != "visa_spec.json":
            v1_spec = vcpus[0][1]
            with open(args.output_json, "w") as f:
                json.dump(v1_spec, f, indent=2)
            sail_p = args.output_sail or args.output_json.replace(".json", ".sail")
            with open(sail_p, "w") as f:
                f.write(export_sail_visa(v1_spec))
    else:
        generators = {
            "visa": (generate_random_visa, export_sail_visa),
            "nested_vm": (generate_nested_vm, export_sail_nested_vm),
            "rolling_vkey": (generate_rolling_vkey, export_sail_rolling_vkey),
            "ephemeral": (generate_ephemeral_vm, export_sail_ephemeral_vm),
        }
        gen_fn, export_fn = generators[args.vcpu]
        spec = gen_fn(seed=args.seed, name=args.name)
        
        with open(args.output_json, "w") as f:
            json.dump(spec, f, indent=2)
        print(f"[+] Synthesized JSON Spec -> {args.output_json} ({spec['isa_name']})")
        
        sail_path = args.output_sail or args.output_json.replace(".json", ".sail")
        if not sail_path.endswith(".sail"):
            sail_path += ".sail"
        with open(sail_path, "w") as f:
            f.write(export_fn(spec))
        print(f"[+] Formal Sail Architecture Spec -> {sail_path}")

if __name__ == "__main__":
    main()
